import { SLANG_DATA, type SlangTerm } from "@/lib/slang-data";

export type ConfidenceLevel = "alta" | "media" | "baixa";
export type ToneLabel = "positivo" | "neutro" | "ironico" | "provocativo" | "sensivel";
export interface ContextAlternative { term: string; meaning: string; reason: string; score: number; }
export interface ContextIntelligence { detectedTerm: SlangTerm | null; confidence: ConfidenceLevel; confidenceScore: number; tone: ToneLabel; intent: string; platform: string | null; ambiguity: boolean; clarificationQuestion: string | null; contextualMeaning: string; alternatives: ContextAlternative[]; }

function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[“”"'`]/g,"").trim();}
function containsExpression(text:string,expression:string){const escaped=normalize(expression).replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return new RegExp(`(^|\\W)${escaped}(?=$|\\W)`,"i").test(normalize(text));}
function matchedCandidates(input:string){return SLANG_DATA.flatMap(term=>[term.term,...(term.variations||[])].map(expression=>({term,expression}))).filter(({expression})=>expression&&containsExpression(input,expression)).sort((a,b)=>b.expression.length-a.expression.length);}
export function detectTermInContext(input:string):SlangTerm|null{return matchedCandidates(input)[0]?.term??null;}
function detectPlatform(input:string,term:SlangTerm|null){const text=normalize(input);if(/tiktok|reels|shorts/.test(text))return"vídeo curto / redes sociais";if(/discord|steam|valorant|lol|fortnite|minecraft|jogo|game|ranked|partida/.test(text))return"games / comunidade gamer";if(/twitter|tweet|x.com|threads/.test(text))return"rede social / conversa pública";if(/whatsapp|grupo|dm|direct|mensagem|mandou|falou/.test(text))return"mensagem / conversa privada";if(term?.category==="gaming"||term?.category==="games")return"games / comunidade gamer";if(term?.category==="redes_sociais"||term?.category==="meme")return"redes sociais / cultura digital";return null;}
function detectTone(term:SlangTerm|null):ToneLabel{if(!term)return"neutro";if(term.riskLevel==="red")return"sensivel";if(["ironia","humor","zoeira"].includes(term.category))return"ironico";if(["provocacao","bullying","insulto_leve"].includes(term.category)||term.riskLevel==="orange")return"provocativo";if(["elogio","flerte","saudacao"].includes(term.category))return"positivo";return"neutro";}
function detectIntent(term:SlangTerm|null,tone:ToneLabel){if(!term)return"Interpretar uma expressão possivelmente nova, local ou escrita de forma alternativa.";if(term.contextNotes?.trim())return term.contextNotes.trim();if(tone==="ironico")return"Humor, ironia ou reforço de cumplicidade social.";if(tone==="provocativo")return"Provocação, julgamento ou disputa de status social.";if(tone==="positivo")return"Aproximação, aprovação ou reforço positivo.";return"Comunicação informal dependente do contexto da conversa.";}
function alternativesFor(input:string,selected:SlangTerm|null):ContextAlternative[]{if(!selected)return[];const exact=matchedCandidates(input).filter(({term})=>term.term!==selected.term);const sameExpression=SLANG_DATA.filter(term=>term.term!==selected.term&&(normalize(term.term)===normalize(selected.term)||term.variations.some(v=>normalize(v)===normalize(selected.term))));const unique=new Map<string,SlangTerm>();[...exact.map(x=>x.term),...sameExpression].forEach(term=>unique.set(term.term,term));return [...unique.values()].slice(0,2).map((term,index)=>({term:term.term,meaning:term.adultTranslation||term.meaning,reason:term.category===selected.category?"mesma expressão em contexto semelhante":"o sentido pode mudar conforme a conversa ou comunidade",score:Number((0.72-index*0.08).toFixed(2))}));}

export function analyzeContext(input:string,fallbackTerm:SlangTerm|null=null):ContextIntelligence{
 const detectedTerm=detectTermInContext(input)??fallbackTerm;const exactInSentence=detectedTerm?containsExpression(input,detectedTerm.term)||detectedTerm.variations.some(v=>containsExpression(input,v)):false;const wordCount=normalize(input).split(/\s+/).filter(Boolean).length;const hasContext=wordCount>=4;const richContext=wordCount>=8;const platform=detectPlatform(input,detectedTerm);const tone=detectTone(detectedTerm);const alternatives=alternativesFor(input,detectedTerm);
 let confidenceScore=detectedTerm?(exactInSentence?0.9:0.66):0.2;if(hasContext&&detectedTerm)confidenceScore+=0.04;if(richContext&&detectedTerm)confidenceScore+=0.03;if(platform&&detectedTerm)confidenceScore+=0.02;if(alternatives.length)confidenceScore-=0.12;confidenceScore=Math.max(0.1,Math.min(0.99,confidenceScore));
 const confidence:ConfidenceLevel=confidenceScore>=0.85?"alta":confidenceScore>=0.55?"media":"baixa";const ambiguity=!detectedTerm||confidence==="baixa"||alternatives.length>0||(!hasContext&&detectedTerm.riskLevel!=="green");
 const clarificationQuestion=ambiguity?(alternatives.length?"Essa expressão pode mudar de sentido. Se você colar a frase inteira, eu digo qual interpretação faz mais sentido aqui.":platform?"Você consegue me mandar a frase inteira em que isso apareceu?":"Isso apareceu em conversa, rede social ou jogo? Cole a frase inteira que eu interpreto melhor."):null;
 const contextualMeaning=detectedTerm?hasContext?`Aqui, “${detectedTerm.term}” provavelmente quer dizer: ${detectedTerm.adultTranslation}`:detectedTerm.adultTranslation:"Não tenho contexto suficiente para afirmar o significado com segurança.";
 return{detectedTerm,confidence,confidenceScore,tone,intent:detectIntent(detectedTerm,tone),platform,ambiguity,clarificationQuestion,contextualMeaning,alternatives};
}
