import type { SlangTerm } from "./slang-data";

export const REGIONAL_SLANG_DATA: SlangTerm[] = [
  {
    term: "tri massa",
    meaning: "Muito legal, ótimo, excelente.",
    adultTranslation: "Muito bom / Excelente.",
    context: "Expressão de elogio bastante comum no Sul do Brasil.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse show foi tri!",
    contextNotes: "Uso positivo e inofensivo, geralmente no Rio Grande do Sul.",
    origin: "Uso popular da região Sul, especialmente no RS.",
    variations: ["tri legal", "tri bom", "tri"],
    popularityStatus: "regional",
    region: "Sul (RS)",
  },
  {
    term: "oxi mainha",
    meaning: "Interjeição de surpresa, espanto ou dúvida.",
    adultTranslation: "Ué / Nossa / Como assim?",
    context: "Interjeição típica em contextos informais no Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Oxente, já acabou a aula?",
    contextNotes: "Expressão tradicional e sem conotação ofensiva.",
    origin: "Expressão histórica da cultura nordestina.",
    variations: ["oxente", "o xente"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "visse",
    meaning: "Partícula para reforçar ou pedir confirmação.",
    adultTranslation: "Entendeu? / Viu? / Certo?",
    context: "Usado no fim da frase em conversas informais no Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Chega cedo amanhã, visse?",
    contextNotes: "Uso coloquial regional, geralmente amigável.",
    origin: "Variação oral de 'viste/viu' na fala regional.",
    variations: ["vixe", "viu"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
];
