// =============================================================================
// Slang Extra 16 — Abreviações populares WhatsApp/Internet e gírias faltantes
// =============================================================================

import type { SlangTerm } from "./slang-data";

export const EXTRA_SLANG_DATA_16: SlangTerm[] = [
  {
    term: "nmrl",
    meaning: "Não me lembro, esqueci.",
    adultTranslation: "Não me lembro / Esqueci.",
    context: "Abreviação usada quando alguém não se recorda de algo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Nmrl o que eu tinha pra fazer hoje.",
    contextNotes: "Abreviação de 'não me lembro'. Inofensivo, muito comum em mensagens de texto entre adolescentes.",
    origin: "Abreviação de 'não me lembro', popularizada no WhatsApp e redes sociais.",
    variations: ["n lembro", "nao me lembro"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cq",
    meaning: "Cuida, se cuida, despedida carinhosa.",
    adultTranslation: "Se cuida / Até logo / Tchau carinhoso.",
    context: "Usado como despedida carinhosa em mensagens.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Cq, amanhã a gente se fala!",
    contextNotes: "Abreviação de 'cuida'. Inofensivo e carinhoso.",
    origin: "Abreviação de 'cuida', popularizada no WhatsApp entre jovens.",
    variations: ["cuida", "cq sempre"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "oq",
    meaning: "O quê, pergunta.",
    adultTranslation: "O quê? / Qual?",
    context: "Abreviação de 'o quê', usada como pergunta.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Oq q vc quer?",
    contextNotes: "Abreviação de 'o quê'. Inofensivo e muito comum em mensagens.",
    origin: "Abreviação de 'o quê', usada massivamente no WhatsApp.",
    variations: ["oque", "o q"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vc",
    meaning: "Você.",
    adultTranslation: "Você.",
    context: "Abreviação de 'você', usada informalmente.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vc vai na festa hoje?",
    contextNotes: "Abreviação de 'você'. Totalmente inofensivo e universal.",
    origin: "Abreviação de 'você', uma das mais antigas e usadas no português digital.",
    variations: ["voce"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pq",
    meaning: "Por quê, porque.",
    adultTranslation: "Por quê? / Porque.",
    context: "Abreviação de 'por quê/porque', usada em perguntas ou explicações.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Pq vc não foi?",
    contextNotes: "Abreviação de 'porque/por quê'. Inofensivo e onipresente.",
    origin: "Abreviação de 'porque', uma das mais comuns no português digital.",
    variations: ["porque", "por q"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "td",
    meaning: "Tudo, todo.",
    adultTranslation: "Tudo / Todo.",
    context: "Abreviação de 'tudo' ou 'todo'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Td bem com vc?",
    contextNotes: "Abreviação de 'tudo'. Inofensivo.",
    origin: "Abreviação de 'tudo', popularizada no WhatsApp.",
    variations: ["tudo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tbm",
    meaning: "Também.",
    adultTranslation: "Também / Igualmente.",
    context: "Abreviação de 'também', usada para concordar.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tbm quero ir!",
    contextNotes: "Abreviação de 'também'. Inofensivo e extremamente comum.",
    origin: "Abreviação de 'também', uma das mais usadas em mensagens.",
    variations: ["tambem", "tb"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tb",
    meaning: "Também.",
    adultTranslation: "Também / Igualmente.",
    context: "Versão curta de 'também'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Eu tb quero!",
    contextNotes: "Abreviação de 'também'. Inofensivo.",
    origin: "Abreviação curta de 'também', popularizada no WhatsApp.",
    variations: ["tambem", "tbm"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ngm",
    meaning: "Ninguém.",
    adultTranslation: "Ninguém.",
    context: "Abreviação de 'ninguém'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ngm me convidou.",
    contextNotes: "Abreviação de 'ninguém'. Inofensivo.",
    origin: "Abreviação de 'ninguém', usada em mensagens rápidas.",
    variations: ["ninguem", "ngm"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "nds",
    meaning: "Não disse, não disseste.",
    adultTranslation: "Não disse / Não falei isso.",
    context: "Abreviação de 'não disse'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Nds nada!",
    contextNotes: "Abreviação de 'não disse'. Inofensivo.",
    origin: "Abreviação de 'não disse', popularizada em mensagens rápidas.",
    variations: ["nao disse", "nd"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "n",
    meaning: "Não, negação.",
    adultTranslation: "Não.",
    context: "Letra 'n' usada como abreviação de 'não'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "N, eu não vou.",
    contextNotes: "Abreviação mínima de 'não'. Inofensivo.",
    origin: "Abreviação de 'não' para respostas rápidas em chat.",
    variations: ["nao", "não"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "s",
    meaning: "Sim, afirmação.",
    adultTranslation: "Sim.",
    context: "Letra 's' usada como abreviação de 'sim'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "S, pode crer.",
    contextNotes: "Abreviação mínima de 'sim'. Inofensivo.",
    origin: "Abreviação de 'sim' para respostas rápidas em chat.",
    variations: ["sim"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "k",
    meaning: "Ok, beleza, combinado.",
    adultTranslation: "OK / Beleza / Combinado.",
    context: "Letra 'k' usada como abreviação de 'ok'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "K, depois a gente se fala.",
    contextNotes: "Abreviação de 'ok'. Pode soar desinteressado dependendo do contexto, mas geralmente é neutro.",
    origin: "Abreviação de 'ok', popularizada em mensagens rápidas.",
    variations: ["ok", "kk"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "kkkk",
    meaning: "Riso, achando graça.",
    adultTranslation: "Hahaha / Risada.",
    context: "Abreviação de risada, quanto mais 'k' mais risada.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Kkkkk morri de rir!",
    contextNotes: "Representação de risada em texto. Inofensivo. 'Kkkkk' é a risada mais brasileira, diferente de 'lol' ou 'haha' de outras culturas.",
    origin: "Onomatopeia de risada brasileira, adaptada para texto. Virou padrão nacional.",
    variations: ["kkk", "kk", "haha", "rs"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vlw",
    meaning: "Valeu, obrigado.",
    adultTranslation: "Valeu / Obrigado / Obrigada.",
    context: "Abreviação de 'valeu', usada como agradecimento rápido.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vlw pela ajuda!",
    contextNotes: "Abreviação de 'valeu'. Inofensivo e muito comum.",
    origin: "Abreviação de 'valeu', popularizada no WhatsApp.",
    variations: ["valeu", "vlww"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mds",
    meaning: "Meu Deus, expressão de espanto ou ênfase.",
    adultTranslation: "Meu Deus! / Nossa! / Caramba!",
    context: "Abreviação de 'meu Deus', usada para expressar surpresa, espanto ou ênfase.",
    category: "expressão",
    riskLevel: "yellow",
    safeExample: "Mds que lindo!",
    contextNotes: "Abreviação de 'meu Deus'. Pode ser positivo (admiração) ou negativo (espanto). Em contextos religiosos pode ser considerado desrespeitoso, mas entre adolescentes é neutro.",
    origin: "Abreviação de 'meu Deus', onipresente em mensagens de adolescentes brasileiros.",
    variations: ["meu deus", "mds"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "aff",
    meaning: "Expressão de irritação, tédio ou impaciência.",
    adultTranslation: "Ai, que chato / Irritação / Tédio.",
    context: "Onomatopeia usada para expressar irritação ou desânimo.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Aff, que prova difícil!",
    contextNotes: "Expressão onomatopeica muito comum. Pode indicar irritação leve ou tédio. Inofensivo.",
    origin: "Onomatopeia popular brasileira, adaptada para texto. Popularizada por adolescentes na internet.",
    variations: ["afff", "affz"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "axo",
    meaning: "Acho, penso, tenho opinião.",
    adultTranslation: "Eu acho / Penso / Na minha opinião.",
    context: "Abreviação de 'acho', usada para expressar opinião.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Axo q vai dar certo.",
    contextNotes: "Abreviação de 'acho'. Inofensivo. Pode soar informal demais para contextos formais.",
    origin: "Abreviação de 'acho', popularizada no WhatsApp entre adolescentes.",
    variations: ["acho"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bjs",
    meaning: "Beijos, carinho.",
    adultTranslation: "Beijos / Abraços.",
    context: "Abreviação de 'beijos', usada como despedida carinhosa.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Bjs, até amanhã!",
    contextNotes: "Abreviação de 'beijos'. Inofensivo e carinhoso.",
    origin: "Abreviação de 'beijos', muito comum entre amigas e casais.",
    variations: ["beijos", "bj"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bj",
    meaning: "Beijo, carinho.",
    adultTranslation: "Beijo / Abraço.",
    context: "Versão curta de 'beijos'.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Bj, te amo!",
    contextNotes: "Abreviação de 'beijo'. Inofensivo.",
    origin: "Abreviação de 'beijo', popularizada no WhatsApp.",
    variations: ["beijo", "bjs"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "abs",
    meaning: "Abraços, despedida carinhosa.",
    adultTranslation: "Abraços / Até logo.",
    context: "Abreviação de 'abraços'.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Abs, até semana que vem!",
    contextNotes: "Abreviação de 'abraços'. Inofensivo.",
    origin: "Abreviação de 'abraços', comum no WhatsApp entre amigos.",
    variations: ["abraços"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tbt",
    meaning: "Throwback Thursday, lembrança do passado. Postar foto antiga nas redes sociais.",
    adultTranslation: "Lembrança / Foto antiga / Nostalgia.",
    context: "Hashtag usada para postar fotos ou lembranças do passado, geralmente às quintas-feiras.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Tbt da viagem do ano passado!",
    contextNotes: "Do inglês 'Throwback Thursday'. Inofensivo e muito popular no Instagram.",
    origin: "Do inglês 'Throwback Thursday', viralizou no Instagram como hashtag semanal para fotos antigas.",
    variations: ["throwback", "#tbt"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "fodase",
    meaning: "Não me importo, que se dane, desdém.",
    adultTranslation: "Não me importa / Que se dane / Indiferença.",
    context: "Expressão de desdém ou desinteresse. Palavrão leve.",
    category: "expressão",
    riskLevel: "orange",
    safeExample: "Fodase o que os outros vão pensar.",
    contextNotes: "Palavra de baixo calão mas extremamente comum. Indica desdém ou desinteresse. Entre adolescentes é usado de forma leve, mas pode ser considerado ofensivo em contextos formais.",
    origin: "Expressão vulgar brasileira que se popularizou na linguagem informal e na internet.",
    variations: ["foda-se", "fds"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fds",
    meaning: "Fodase, não me importo.",
    adultTranslation: "Não me importa / Que se dane.",
    context: "Abreviação de 'fodase'.",
    category: "expressão",
    riskLevel: "orange",
    safeExample: "Fds, vou fazer o que eu quero.",
    contextNotes: "Abreviação de 'fodase'. Palavrão, mas extremamente comum entre jovens. Mesmo nível de risco que a versão completa.",
    origin: "Abreviação de 'fodase' para mensagens de texto.",
    variations: ["fodase", "foda-se"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ctz",
    meaning: "Certeza, certeza absoluta.",
    adultTranslation: "Com certeza / Certeza / Tenho certeza.",
    context: "Abreviação de 'certeza'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ctz que vai dar certo.",
    contextNotes: "Abreviação de 'certeza'. Inofensivo.",
    origin: "Abreviação de 'certeza', popularizada no WhatsApp.",
    variations: ["certeza"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cmrt",
    meaning: "Com a razão, você está certo.",
    adultTranslation: "Você tem razão / Concordo totalmente.",
    context: "Abreviação de 'com a razão'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Cmrt, a prova tava mesmo difícil.",
    contextNotes: "Abreviação de 'com a razão'. Inofensivo.",
    origin: "Abreviação de 'com a razão', popularizada entre adolescentes no Twitter e WhatsApp.",
    variations: ["com a razão", "c razão"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "irl",
    meaning: "In Real Life, na vida real.",
    adultTranslation: "Na vida real / Pessoalmente / Ao vivo.",
    context: "Expressão usada para distinguir algo real do mundo virtual.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vimos no TikTok mas nunca irl.",
    contextNotes: "Do inglês 'In Real Life'. Muito usado para diferenciar interações online de pessoais. Inofensivo.",
    origin: "Do inglês 'In Real Life', popularizado na cultura gamer e de internet.",
    variations: ["in real life"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "idk",
    meaning: "I don't know, não sei.",
    adultTranslation: "Não sei / Sem ideia.",
    context: "Abreviação em inglês para 'não sei'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Idk o que fazer agora.",
    contextNotes: "Do inglês 'I don't know'. Inofensivo e muito comum.",
    origin: "Do inglês 'I don't know', popularizado na internet global.",
    variations: ["i dont know"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "imo",
    meaning: "In my opinion, na minha opinião.",
    adultTranslation: "Na minha opinião / Acho que.",
    context: "Abreviação em inglês para expressar opinião.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Imo esse filme é top.",
    contextNotes: "Do inglês 'In my opinion'. Inofensivo.",
    origin: "Do inglês 'In my opinion', popularizado em fóruns e redes sociais.",
    variations: ["in my opinion"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "ama",
    meaning: "Amanhã, dia seguinte.",
    adultTranslation: "Amanhã.",
    context: "Abreviação de 'amanhã'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ama a gente resolve.",
    contextNotes: "Abreviação de 'amanhã'. Inofensivo.",
    origin: "Abreviação de 'amanhã', usada em mensagens rápidas.",
    variations: ["amanhã"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ontm",
    meaning: "Ontem.",
    adultTranslation: "Ontem.",
    context: "Abreviação de 'ontem'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ontm foi incrível!",
    contextNotes: "Abreviação de 'ontem'. Inofensivo.",
    origin: "Abreviação de 'ontem', popularizada no WhatsApp.",
    variations: ["ontem"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "obg",
    meaning: "Obrigado, obrigada.",
    adultTranslation: "Obrigado / Obrigada.",
    context: "Abreviação de 'obrigado(a)'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Obg pela ajuda!",
    contextNotes: "Abreviação de 'obrigado'. Inofensivo e educado.",
    origin: "Abreviação de 'obrigado', uma das mais antigas e universais.",
    variations: ["obrigado", "obrigada"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "msg",
    meaning: "Mensagem.",
    adultTranslation: "Mensagem.",
    context: "Abreviação de 'mensagem'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me manda uma msg.",
    contextNotes: "Abreviação de 'mensagem'. Inofensivo.",
    origin: "Abreviação de 'mensagem', muito comum em contextos digitais.",
    variations: ["mensagem"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "pdp",
    meaning: "Pode parar de palhaçada / Pau de papo. Expressão de desdém ou alerta.",
    adultTranslation: "Para de palhaçada / Sem graça / Bobagem.",
    context: "Usado para dizer que algo é sem graça ou que alguém deveria parar com algo absurdo.",
    category: "expressão",
    riskLevel: "orange",
    safeExample: "Pdp, para de mentir!",
    contextNotes: "Sigla que pode ter diferentes interpretações dependendo do contexto. Entre adolescentes geralmente significa 'pode parar de palhaçada'. Em contextos mais pesados pode ter conotação sexual.",
    origin: "Sigla popularizada na internet brasileira. O significado varia conforme contexto.",
    variations: ["pode parar de palhaçada"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "toptier",
    meaning: "O melhor, nível máximo, elite.",
    adultTranslation: "O melhor / De primeira / Nível máximo.",
    context: "Usado para descrever algo ou alguém que é excepcional.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Esse jogador é toptier!",
    contextNotes: "Do inglês 'top tier' (nível superior). Inofensivo e elogioso.",
    origin: "Do inglês 'top tier', popularizado no gaming e na internet.",
    variations: ["top tier", "top tier mesmo"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "fyi",
    meaning: "For your information, para sua informação.",
    adultTranslation: "Para sua informação / Sabia que...",
    context: "Abreviação em inglês para compartilhar informação.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Fyi, a prova foi adiada.",
    contextNotes: "Do inglês 'For your information'. Inofensivo.",
    origin: "Do inglês 'For your information', popularizado no meio corporativo e redes sociais.",
    variations: ["for your information"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "rn",
    meaning: "Right now, agora mesmo, neste momento.",
    adultTranslation: "Agora / Neste momento / Agora mesmo.",
    context: "Abreviação em inglês para indicar que algo está acontecendo agora.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tá muito quente rn.",
    contextNotes: "Do inglês 'right now'. Muito comum no Twitter e TikTok.",
    origin: "Do inglês 'right now', popularizado no Twitter e TikTok.",
    variations: ["right now"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "glow up",
    meaning: "Transformação positiva, melhora na aparência ou na vida.",
    adultTranslation: "Transformação positiva / Melhorou muito / Evolução.",
    context: "Usado quando alguém melhorou significativamente em aparência, estilo ou vida.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "O glow up dela foi insano depois do ensino médio!",
    contextNotes: "Do inglês. Termo positivo que celebra transformações. Inofensivo.",
    origin: "Do inglês 'glow up', popularizado no YouTube e TikTok.",
    variations: ["glowup", "deu glow up"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "pick me",
    meaning: "Pessoa que busca aprovação, especialmente de pessoas do sexo oposto, rejeitando o próprio grupo.",
    adultTranslation: "Pessoa que busca aprovação / Puxa-saco.",
    context: "Usado para descrever alguém que tenta se destacar para ganhar aprovação, geralmente rejeitando pessoas do próprio grupo.",
    category: "ironia",
    riskLevel: "orange",
    safeExample: "Ela é tão pick me, sempre falando que 'não é como as outras meninas'.",
    contextNotes: "Do inglês. Termo pode ser usado de forma pejorativa para criticar comportamento de busca por aprovação. Pode causar desconforto.",
    origin: "Do inglês 'pick me', viralizou no TikTok como crítica comportamental.",
    variations: ["pick me girl", "pick me boy"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "bait",
    meaning: "Isca, postagem feita para gerar engajamento ou reação.",
    adultTranslation: "Isca / Provocação / Postagem para likes.",
    context: "Conteúdo feito intencionalmente para gerar polêmica ou engajamento.",
    category: "redes_sociais",
    riskLevel: "yellow",
    safeExample: "Esse tweet é puro bait.",
    contextNotes: "Do inglês. Identificar 'bait' é uma habilidade de alfabetização digital importante.",
    origin: "Do inglês 'bait', termo da cultura de internet e pesca.",
    variations: ["clickbait", "baited"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "vibe check",
    meaning: "Avaliar a energia/atmosfera de uma pessoa ou situação.",
    adultTranslation: "Avaliar o clima / Testar a energia de alguém.",
    context: "Usado para avaliar se a energia de alguém é positiva ou negativa.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Fiz vibe check e o pessoal tá de boa.",
    contextNotes: "Expressão usada para ler o ambiente. Inofensivo.",
    origin: "Tendência do TikTok, popularizada nos anos 2020.",
    variations: ["vibe"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "goat",
    meaning: "Greatest of All Time, o melhor de todos os tempos.",
    adultTranslation: "O melhor de todos os tempos / Lendário.",
    context: "Usado para descrever alguém que é excepcional em sua área.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "O Neymar é o goat do futebol brasileiro!",
    contextNotes: "Do inglês 'Greatest of All Time'. Inofensivo e elogioso.",
    origin: "Do inglês 'GOAT', popularizado no esporte e cultura pop.",
    variations: ["g.o.a.t."],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "cringe",
    meaning: "Vergonha alheia, constrangimento, algo embaraçoso.",
    adultTranslation: "Vergonha alheia / Constrangimento / Embaraçoso.",
    context: "Usado para descrever algo que causa vergonha ou desconforto.",
    category: "ironia",
    riskLevel: "yellow",
    safeExample: "Que cringe aquele vídeo antigo!",
    contextNotes: "Do inglês. Muito usado para julgar conteúdo de forma irônica. Pode ser usado de forma cruel se direcionado a pessoas.",
    origin: "Do inglês 'cringe', popularizado pelo YouTube e TikTok.",
    variations: ["cringou", "muito cringe"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "vém",
    meaning: "Vem, venha cá, vem comigo.",
    adultTranslation: "Vem cá / Vem / Vamos.",
    context: "Abreviação informal de 'vem' ou 'você vem'.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Vém jogar com a gente!",
    contextNotes: "Forma informal de 'vem'. Inofensivo e comum.",
    origin: "Redução informal de 'vem', popularizada na fala e mensagens de jovens.",
    variations: ["vem", "vem cá"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "moio",
    meaning: "Muito bom, excelente, impressionante.",
    adultTranslation: "Muito bom / Impressionante / Legal demais.",
    context: "Termo de elogio, especialmente no funk e cultura periférica.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Essa música é moio demais!",
    contextNotes: "Termo muito usado na cultura funk e periférica. Inofensivo e elogioso.",
    origin: "Termo popularizado pelo funk brasileiro e cultura periférica nos anos 2010.",
    variations: ["moia"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "calabreso",
    meaning: "Encrenqueiro, mala, pessoa chata ou problemática.",
    adultTranslation: "Encrenqueiro / Chato / Problemático.",
    context: "Usado para descrever alguém que causa confusão ou é chato.",
    category: "provocacao",
    riskLevel: "yellow",
    safeExample: "O colega novo é calabreso.",
    contextNotes: "Termo popularizado por Davi Britto no BBB 24. Pode ser usado de forma leve entre amigos ou como provocação. O tom de voz define se é brincadeira ou ofensa.",
    origin: "Popularizado por Davi Britto no BBB 24 (2024), ganhou o país rapidamente.",
    variations: ["calabresa"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "biscoiteiro",
    meaning: "Pessoa que fica com muita gente ao mesmo tempo, envolvida em vários relacionamentos.",
    adultTranslation: "Mantenha de várias pessoas / Fica com todo mundo.",
    context: "Usado para descrever quem tem múltiplos parceiros românticos simultaneamente.",
    category: "relacionamento",
    riskLevel: "yellow",
    safeExample: "Ele é biscoiteiro, fica com metade da escola.",
    contextNotes: "Termo que pode ser usado de forma leve ou como crítica, dependendo do contexto. Refere-se à infidelidade emocional ou romântica.",
    origin: "Expressão popularizada na cultura jovem e funk brasileiro. 'Biscoito fino' em sentido inverso.",
    variations: ["biscoitar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "btf",
    meaning: "Bota pra fuder, expressão de intensidade ou violência.",
    adultTranslation: "Fazer algo com intensidade / Elogio máximo (depende do contexto).",
    context: "Pode ser usado como elogio (arrasar) ou como ameaça (destruir). Contexto é crucial.",
    category: "expressão",
    riskLevel: "orange",
    safeExample: "Esse cara btf na dança!",
    contextNotes: "Sigla de 'bota pra fuder'. Pode ser elogio (quando alguém é muito bom em algo) ou expressão agressiva (dependendo do tom e contexto). Importante orientar que a expressão tem origem vulgar mas entre jovens perdeu parte do peso.",
    origin: "Sigla popularizada no funk e cultura periférica. Significado varia muito com o contexto.",
    variations: ["bota pra foder"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mlk",
    meaning: "Moleque, cara, garoto.",
    adultTranslation: "Cara / Garoto / Moleque.",
    context: "Termo para se referir a um cara, geralmente amigo.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "E aí mlk, tudo certo?",
    contextNotes: "Abreviação de 'moleque'. Inofensivo e muito comum entre homens jovens.",
    origin: "Abreviação de 'moleque', popularizada no funk e cultura periférica.",
    variations: ["moleque", "mlkk"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cabuloso",
    meaning: "Muito bom, impressionante, excelente.",
    adultTranslation: "Muito bom / Impressionante / Excelente.",
    context: "Termo de elogio máximo.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Esse carro é cabuloso!",
    contextNotes: "Termo muito positivo. Totalmente inofensivo.",
    origin: "Termo de origem incerta, popularizado na cultura popular brasileira. Fortemente associado ao funk.",
    variations: ["cabuloso demais", "cabulosa"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "miga",
    meaning: "Amiga, companheira.",
    adultTranslation: "Amiga / Colega / Parceira.",
    context: "Diminutivo afetivo de amiga.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Oi miga, tudo bem?",
    contextNotes: "Diminutivo carinhoso de 'amiga'. Inofensivo.",
    origin: "Diminutivo de 'amiga', muito popular entre jovens e mulheres.",
    variations: ["amiga", "miguinha"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cria",
    meaning: "Cara, amigo, pessoa (do 'crioulo').",
    adultTranslation: "Cara / Amigo / Pessoa.",
    context: "Termo para se referir a alguém, geralmente amigo.",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "E aí cria, bora?",
    contextNotes: "Termo muito usado na cultura funk e periférica como vocativo. Originalmente derivado de 'crioulo', foi ressignificado como termo de camaradagem entre amigos. Inofensivo no contexto jovem.",
    origin: "Derivado de 'crioulo', ressignificado como termo de amizade na cultura funk e hip-hop.",
    variations: ["cria dó", "criação"],
    popularityStatus: "ativo",
    region: "RJ",
  },
  {
    term: "gata",
    meaning: "Mulher bonita, garota atraente.",
    adultTranslation: "Garota bonita / Mulher atraente.",
    context: "Termo para se referir a uma mulher bonita.",
    category: "elogio",
    riskLevel: "yellow",
    safeExample: "Aquela gata é muito bonita.",
    contextNotes: "Termo que pode ser elogio ou objetificação, dependendo do contexto e de quem usa. Quando usado de forma respeitosa entre jovens, é geralmente um elogio à aparência.",
    origin: "Diminutivo de 'gato', usado na cultura popular e funk como referência a beleza feminina.",
    variations: ["gato", "gatona"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "seloko",
    meaning: "É sério, é verdade, pode confiar.",
    adultTranslation: "É sério / É verdade / Pode confiar.",
    context: "Expressão de afirmação e confiança.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Seloko, o professor passou a matéria toda!",
    contextNotes: "Termo popularizado na cultura funk e internet. Indica que algo é verdadeiro ou confiável.",
    origin: "Possivelmente derivação de 'é sério' ou termo de origem no funk. Popularizado nacionalmente.",
    variations: ["é seloko", "seloko mesmo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "crisp",
    meaning: "Impressionante, excepcional, muito bom.",
    adultTranslation: "Impressionante / Excepcional / Muito bom.",
    context: "Termo de elogio máximo.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Essa play é crisp!",
    contextNotes: "Termo muito elogioso. Totalmente positivo.",
    origin: "Possivelmente do inglês 'crisp' (definido/impecável) ou variação de 'crack'. Popularizado na internet brasileira.",
    variations: ["crispou"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pode crer",
    meaning: "Pode acreditar, é verdade, confia.",
    adultTranslation: "Pode acreditar / É verdade / Confia.",
    context: "Expressão de afirmação forte, pedindo confiança.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "O show foi insano, pode crer!",
    contextNotes: "Expressão muito comum na cultura jovem. Inofensivo.",
    origin: "Expressão popular brasileira, muito usada na cultura urbana e funk.",
    variations: ["pode crer mesmo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "brabo",
    meaning: "Com raiva, irritado; ou muito bom/forte (depende do contexto).",
    adultTranslation: "Com raiva / Irritado — ou — Muito bom / Forte.",
    context: "Pode significar irritação ou ser elogio. Contexto é crucial.",
    category: "expressão",
    riskLevel: "yellow",
    safeExample: "Tô brabo com essa situação. / Esse jogador é brabo!",
    contextNotes: "Termo ambíguo: pode ser negativo (raiva) ou positivo (elogio). O contexto da frase define o significado.",
    origin: "Termo antigo na cultura brasileira, popularizado no funk e esporte.",
    variations: ["braba", "brabíssimo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
];
