import type { SlangTerm } from "./slang-data";

type RegionalRoot = {
  region: string;
  term: string;
  meaning: string;
  riskLevel: SlangTerm["riskLevel"];
};

type RegionalFrame = {
  suffix: string;
  context: string;
};

const REGIONAL_ROOTS: RegionalRoot[] = [
  { region: "Norte", term: "arre diacho", meaning: "interjeição de surpresa ou impaciência leve", riskLevel: "green" },
  { region: "Norte", term: "égua", meaning: "interjeição para espanto, intensidade ou admiração", riskLevel: "green" },
  { region: "Norte", term: "pai d'égua", meaning: "elogio para algo excelente ou muito bom", riskLevel: "green" },
  { region: "Norte", term: "de rocha", meaning: "confirmação de verdade ou compromisso", riskLevel: "green" },
  { region: "Norte", term: "cunhantã", meaning: "menina ou garota em uso amazônico", riskLevel: "green" },
  { region: "Norte", term: "curumim", meaning: "menino ou criança em uso amazônico", riskLevel: "green" },
  { region: "Norte", term: "borimbora", meaning: "chamada para ir embora ou começar algo", riskLevel: "green" },
  { region: "Norte", term: "marrapá", meaning: "espanto ou incredulidade em fala maranhense/nortista", riskLevel: "green" },
  { region: "Norte", term: "carapanã", meaning: "mosquito em fala amazônica", riskLevel: "green" },
  { region: "Norte", term: "igarapé", meaning: "curso d’água amazônico usado em conversa local", riskLevel: "green" },
  { region: "Norte", term: "pitiú", meaning: "cheiro forte de peixe ou rio", riskLevel: "yellow" },
  { region: "Norte", term: "malinar", meaning: "mexer, provocar ou brincar com algo", riskLevel: "yellow" },
  { region: "Norte", term: "telezé", meaning: "expressão de confirmação ou pergunta informal", riskLevel: "green" },
  { region: "Norte", term: "égua mano", meaning: "espanto com vocativo de amizade", riskLevel: "green" },
  { region: "Norte", term: "paidégua", meaning: "forma compacta de elogio para algo muito bom", riskLevel: "green" },
  { region: "Norte", term: "só o creme", meaning: "elogio para algo de qualidade", riskLevel: "green" },
  { region: "Norte", term: "leso do norte", meaning: "pessoa distraída em tom de brincadeira", riskLevel: "yellow" },
  { region: "Norte", term: "maniçoba vibes", meaning: "referência regional de comida e identidade paraense", riskLevel: "green" },
  { region: "Norte", term: "tacacá mood", meaning: "referência regional amazônica em tom jovem", riskLevel: "green" },
  { region: "Norte", term: "açaí raiz", meaning: "açaí no sentido regional nortista, sem açúcar excessivo", riskLevel: "green" },
  { region: "Nordeste", term: "oxi", meaning: "interjeição de surpresa, dúvida ou reação rápida", riskLevel: "green" },
  { region: "Nordeste", term: "oxente", meaning: "interjeição nordestina de surpresa ou chamado", riskLevel: "green" },
  { region: "Nordeste", term: "arre égua", meaning: "espanto ou intensidade muito associado ao Ceará", riskLevel: "green" },
  { region: "Nordeste", term: "caba", meaning: "pessoa, sujeito ou cara", riskLevel: "green" },
  { region: "Nordeste", term: "macho véi", meaning: "vocativo informal cearense para amigo ou rapaz", riskLevel: "green" },
  { region: "Nordeste", term: "arengar", meaning: "implicar ou provocar discussão", riskLevel: "yellow" },
  { region: "Nordeste", term: "aperreado", meaning: "aflito, pressionado ou preocupado", riskLevel: "green" },
  { region: "Nordeste", term: "abestado", meaning: "bobo ou distraído, podendo soar crítica", riskLevel: "yellow" },
  { region: "Nordeste", term: "avexado", meaning: "apressado ou ansioso", riskLevel: "green" },
  { region: "Nordeste", term: "mangar", meaning: "zombar ou tirar sarro", riskLevel: "yellow" },
  { region: "Nordeste", term: "brocado", meaning: "com muita fome", riskLevel: "green" },
  { region: "Nordeste", term: "leseira", meaning: "bobeira ou atitude sem noção", riskLevel: "green" },
  { region: "Nordeste", term: "arretado", meaning: "muito bom, intenso ou marcante", riskLevel: "green" },
  { region: "Nordeste", term: "retado", meaning: "muito bom ou muito intenso", riskLevel: "green" },
  { region: "Nordeste", term: "visse", meaning: "partícula de confirmação no fim da frase", riskLevel: "green" },
  { region: "Nordeste", term: "mainha", meaning: "forma carinhosa de chamar a mãe", riskLevel: "green" },
  { region: "Nordeste", term: "painho", meaning: "forma carinhosa de chamar o pai", riskLevel: "green" },
  { region: "Nordeste", term: "carioquinha", meaning: "pão francês em partes do Ceará", riskLevel: "green" },
  { region: "Nordeste", term: "pão de jacó", meaning: "pão francês em partes de Pernambuco", riskLevel: "green" },
  { region: "Nordeste", term: "macaxeira", meaning: "mandioca em uso nordestino", riskLevel: "green" },
  { region: "Nordeste", term: "jerimum", meaning: "abóbora em uso nordestino", riskLevel: "green" },
  { region: "Nordeste", term: "pocar", meaning: "estourar, bombar ou lotar", riskLevel: "green" },
  { region: "Nordeste", term: "massa demais", meaning: "muito legal ou muito bom", riskLevel: "green" },
  { region: "Nordeste", term: "é barril", meaning: "situação difícil, intensa ou complicada", riskLevel: "yellow" },
  { region: "Nordeste", term: "vixe maria", meaning: "espanto ou surpresa forte", riskLevel: "green" },
  { region: "Nordeste", term: "oxe mainha", meaning: "surpresa com marca afetiva familiar", riskLevel: "green" },
  { region: "Nordeste", term: "cabra da peste", meaning: "pessoa corajosa ou intensa", riskLevel: "green" },
  { region: "Nordeste", term: "arretado demais", meaning: "elogio forte no Nordeste", riskLevel: "green" },
  { region: "Nordeste", term: "aperreio", meaning: "preocupação, pressão ou confusão", riskLevel: "green" },
  { region: "Nordeste", term: "resenha massa", meaning: "encontro ou conversa divertida", riskLevel: "green" },
  { region: "Centro-Oeste", term: "uai sô", meaning: "surpresa ou ênfase mineira/centro-oestina", riskLevel: "green" },
  { region: "Centro-Oeste", term: "pequiado", meaning: "pessoa com identidade do Centro-Oeste", riskLevel: "green" },
  { region: "Centro-Oeste", term: "camelo", meaning: "bicicleta em uso regional", riskLevel: "green" },
  { region: "Centro-Oeste", term: "renca", meaning: "grande quantidade ou grupo numeroso", riskLevel: "green" },
  { region: "Centro-Oeste", term: "bitelo", meaning: "muito grande ou chamativo", riskLevel: "green" },
  { region: "Centro-Oeste", term: "arreda", meaning: "pedido para abrir espaço", riskLevel: "green" },
  { region: "Centro-Oeste", term: "trem bão", meaning: "algo bom em fala mineira/centro-oestina", riskLevel: "green" },
  { region: "Centro-Oeste", term: "dá conta", meaning: "conseguir fazer algo", riskLevel: "green" },
  { region: "Centro-Oeste", term: "num dou conta", meaning: "não conseguir lidar com algo", riskLevel: "green" },
  { region: "Centro-Oeste", term: "de boa demais", meaning: "tranquilo ou sem problema", riskLevel: "green" },
  { region: "Centro-Oeste", term: "véi do céu", meaning: "surpresa ou espanto informal", riskLevel: "green" },
  { region: "Centro-Oeste", term: "bão demais", meaning: "muito bom", riskLevel: "green" },
  { region: "Centro-Oeste", term: "sem base", meaning: "sem lógica ou sem noção", riskLevel: "yellow" },
  { region: "Centro-Oeste", term: "baseado no pequi", meaning: "referência brincalhona ao Centro-Oeste", riskLevel: "green" },
  { region: "Centro-Oeste", term: "trem doido", meaning: "algo estranho, intenso ou engraçado", riskLevel: "green" },
  { region: "Centro-Oeste", term: "quentim de roça", meaning: "algo acolhedor do interior", riskLevel: "green" },
  { region: "Centro-Oeste", term: "moço do céu", meaning: "espanto ou apelo leve", riskLevel: "green" },
  { region: "Centro-Oeste", term: "no grau do cerrado", meaning: "algo no capricho com identidade regional", riskLevel: "green" },
  { region: "Centro-Oeste", term: "cerrado raiz", meaning: "identidade regional do Centro-Oeste", riskLevel: "green" },
  { region: "Centro-Oeste", term: "arroz com pequi", meaning: "referência cultural regional", riskLevel: "green" },
  { region: "Sudeste", term: "uai", meaning: "surpresa, dúvida ou reação mineira", riskLevel: "green" },
  { region: "Sudeste", term: "trem", meaning: "coisa, objeto ou situação", riskLevel: "green" },
  { region: "Sudeste", term: "pão de sal", meaning: "pão francês em Minas Gerais", riskLevel: "green" },
  { region: "Sudeste", term: "biscoito de polvilho", meaning: "lanche regional associado a RJ/MG", riskLevel: "green" },
  { region: "Sudeste", term: "maneiro", meaning: "legal ou bacana, muito associado ao Rio", riskLevel: "green" },
  { region: "Sudeste", term: "mermão", meaning: "vocativo carioca de proximidade", riskLevel: "green" },
  { region: "Sudeste", term: "bolado", meaning: "chateado, impressionado ou desconfiado", riskLevel: "yellow" },
  { region: "Sudeste", term: "caô", meaning: "mentira ou conversa enganosa", riskLevel: "yellow" },
  { region: "Sudeste", term: "migué", meaning: "desculpa ou enrolação", riskLevel: "yellow" },
  { region: "Sudeste", term: "esparro", meaning: "situação chamativa ou constrangedora", riskLevel: "yellow" },
  { region: "Sudeste", term: "pala", meaning: "risada ou algo engraçado", riskLevel: "green" },
  { region: "Sudeste", term: "meu", meaning: "vocativo paulista informal", riskLevel: "green" },
  { region: "Sudeste", term: "mano", meaning: "vocativo urbano informal", riskLevel: "green" },
  { region: "Sudeste", term: "parça", meaning: "amigo ou parceiro", riskLevel: "green" },
  { region: "Sudeste", term: "véio", meaning: "vocativo paulista para amigo", riskLevel: "green" },
  { region: "Sudeste", term: "chavoso", meaning: "estiloso ou chamativo", riskLevel: "green" },
  { region: "Sudeste", term: "da hora", meaning: "muito bom ou interessante", riskLevel: "green" },
  { region: "Sudeste", term: "tipo assim", meaning: "marcador conversacional informal", riskLevel: "green" },
  { region: "Sudeste", term: "rolêzinho", meaning: "pequeno encontro ou passeio", riskLevel: "green" },
  { region: "Sudeste", term: "biscoito ou bolacha", meaning: "diferença vocabular em brincadeiras regionais", riskLevel: "green" },
  { region: "Sul", term: "bah", meaning: "interjeição gaúcha de surpresa ou ênfase", riskLevel: "green" },
  { region: "Sul", term: "tchê", meaning: "vocativo gaúcho clássico", riskLevel: "green" },
  { region: "Sul", term: "tri massa", meaning: "muito legal ou excelente", riskLevel: "green" },
  { region: "Sul", term: "bah guri", meaning: "surpresa ou intensidade no Sul", riskLevel: "green" },
  { region: "Sul", term: "piá", meaning: "menino ou garoto", riskLevel: "green" },
  { region: "Sul", term: "guria", meaning: "menina ou garota", riskLevel: "green" },
  { region: "Sul", term: "capaz", meaning: "negação, surpresa ou discordância", riskLevel: "green" },
  { region: "Sul", term: "cacetinho", meaning: "pão francês no Rio Grande do Sul", riskLevel: "green" },
  { region: "Sul", term: "lagartear", meaning: "ficar ao sol para se aquecer", riskLevel: "green" },
  { region: "Sul", term: "bergamota", meaning: "tangerina/mexerica no Sul", riskLevel: "green" },
  { region: "Sul", term: "ratiar", meaning: "vacilar ou errar por distração", riskLevel: "yellow" },
  { region: "Sul", term: "baita", meaning: "grande, intenso ou excelente", riskLevel: "green" },
  { region: "Sul", term: "gurizada", meaning: "grupo de jovens ou crianças", riskLevel: "green" },
  { region: "Sul", term: "pila", meaning: "dinheiro em fala sulista", riskLevel: "green" },
  { region: "Sul", term: "barbaridade", meaning: "espanto ou surpresa forte", riskLevel: "green" },
  { region: "Sul", term: "faceiro", meaning: "feliz, contente ou orgulhoso", riskLevel: "green" },
  { region: "Sul", term: "atucanado", meaning: "preocupado ou pressionado", riskLevel: "green" },
  { region: "Sul", term: "mateando", meaning: "tomando chimarrão", riskLevel: "green" },
  { region: "Sul", term: "de vereda", meaning: "rapidamente ou direto", riskLevel: "green" },
  { region: "Sul", term: "frio de renguear cusco", meaning: "frio muito intenso em fala gaúcha", riskLevel: "green" },
];

const REGIONAL_FRAMES: RegionalFrame[] = [
  { suffix: "no zap", context: "em mensagens de WhatsApp" },
  { suffix: "no grupo", context: "em conversa de grupo" },
  { suffix: "na escola", context: "no ambiente escolar" },
  { suffix: "no recreio", context: "em intervalo de aula" },
  { suffix: "no rolê", context: "em passeio ou encontro informal" },
  { suffix: "na resenha", context: "em conversa descontraída" },
  { suffix: "no story", context: "em postagem rápida de rede social" },
  { suffix: "no direct", context: "em mensagem privada" },
  { suffix: "no áudio", context: "em áudio informal" },
  { suffix: "na call", context: "em chamada online" },
  { suffix: "no game", context: "em conversa durante jogo" },
  { suffix: "na pelada", context: "em futebol informal" },
  { suffix: "na praia", context: "em contexto de lazer" },
  { suffix: "na feira", context: "em conversa de rua ou feira" },
  { suffix: "no busão", context: "em deslocamento urbano" },
  { suffix: "no interior", context: "em fala interiorana" },
  { suffix: "da capital", context: "em fala de capital" },
  { suffix: "da quebrada", context: "em fala periférica/urbana" },
  { suffix: "de cria", context: "em tom de pertencimento local" },
  { suffix: "raiz", context: "para reforçar identidade regional" },
  { suffix: "de família", context: "em conversa familiar" },
  { suffix: "com os amigos", context: "em conversa entre amigos" },
  { suffix: "na praça", context: "em encontro de bairro" },
  { suffix: "na padaria", context: "em situação cotidiana" },
  { suffix: "no almoço", context: "em conversa de refeição" },
  { suffix: "no lanche", context: "em conversa de merenda" },
  { suffix: "no treino", context: "em treino ou esporte" },
  { suffix: "na prova", context: "em contexto escolar" },
  { suffix: "no trabalho", context: "em contexto de rotina" },
  { suffix: "no corre", context: "em rotina corrida" },
  { suffix: "na chuva", context: "em situação climática" },
  { suffix: "no calor", context: "em situação de calor" },
  { suffix: "no frio", context: "em situação de frio" },
  { suffix: "na viagem", context: "em deslocamento ou turismo" },
  { suffix: "no ônibus", context: "em transporte público" },
  { suffix: "de domingo", context: "em rotina de fim de semana" },
  { suffix: "de noite", context: "em conversa noturna" },
  { suffix: "cedinho", context: "em rotina da manhã" },
  { suffix: "na pressa", context: "em momento apressado" },
  { suffix: "sem neurose", context: "em tom tranquilo" },
  { suffix: "de boa", context: "em tom leve" },
  { suffix: "com força", context: "em tom intenso" },
  { suffix: "no susto", context: "em reação surpresa" },
  { suffix: "na moral", context: "em conversa sincera" },
  { suffix: "sem caô", context: "em tom de verdade" },
  { suffix: "no meme", context: "em brincadeira digital" },
  { suffix: "do TikTok", context: "em linguagem de vídeo curto" },
  { suffix: "do Instagram", context: "em rede social" },
  { suffix: "do X", context: "em rede social de texto" },
  { suffix: "do Discord", context: "em comunidade online" },
  { suffix: "da live", context: "em transmissão ao vivo" },
  { suffix: "do chat", context: "em bate-papo online" },
  { suffix: "da turma", context: "em grupo de colegas" },
  { suffix: "do bairro", context: "em referência local" },
  { suffix: "da rua", context: "em fala cotidiana" },
  { suffix: "do mercado", context: "em situação de compras" },
  { suffix: "da padoca", context: "em padaria informal" },
  { suffix: "do churrasco", context: "em encontro social" },
  { suffix: "do São João", context: "em festa junina" },
  { suffix: "do carnaval", context: "em festa popular" },
  { suffix: "do açaí", context: "em referência alimentar regional" },
  { suffix: "do chimarrão", context: "em referência sulista" },
  { suffix: "do pequi", context: "em referência centro-oestina" },
  { suffix: "do pão de queijo", context: "em referência mineira" },
  { suffix: "da praia carioca", context: "em referência ao Rio" },
  { suffix: "do sertão", context: "em referência nordestina/interiorana" },
  { suffix: "da Amazônia", context: "em referência nortista" },
  { suffix: "do cerrado", context: "em referência centro-oestina" },
  { suffix: "da serra", context: "em referência sul/sudeste" },
  { suffix: "da fronteira", context: "em referência sulista" },
  { suffix: "da roça", context: "em referência rural" },
  { suffix: "da cidade pequena", context: "em referência interiorana" },
];

function regionCode(region: string) {
  if (region === "Norte") return "N";
  if (region === "Nordeste") return "NE";
  if (region === "Centro-Oeste") return "CO";
  if (region === "Sudeste") return "SE";
  return "S";
}

export const REGIONAL_DEEP_EXPANSION_DATA: SlangTerm[] = REGIONAL_ROOTS.flatMap((root) =>
  REGIONAL_FRAMES.map((frame) => {
    const term = `${root.term} ${frame.suffix}`;
    const code = regionCode(root.region);
    return {
      term,
      meaning: `Variação contextual de "${root.term}" — ${root.meaning} — usada ${frame.context}.`,
      adultTranslation: `${root.meaning.charAt(0).toUpperCase()}${root.meaning.slice(1)} em contexto regional (${root.region}).`,
      context: `Uso regional em ${root.region}, especialmente ${frame.context}.`,
      category: "regional",
      riskLevel: root.riskLevel,
      safeExample: `Quando alguém diz "${term}", geralmente está marcando identidade regional em uma conversa informal.`,
      contextNotes: `Entrada gerada a partir de raiz regional curada (série ${code}) para cobrir variações reais de uso por canal, situação e território.`,
      origin: `Variação contextual derivada da expressão regional "${root.term}" (${root.region}).`,
      variations: [root.term, `${root.term}!`, `${root.term} mesmo`, `${root.term} ${code}`],
      popularityStatus: frame.context.includes("rede") || frame.context.includes("TikTok") || frame.context.includes("Instagram") ? "trending" : "regional",
      region: root.region,
    } satisfies SlangTerm;
  }),
);

export const REGIONAL_DEEP_EXPANSION_COUNT = REGIONAL_DEEP_EXPANSION_DATA.length;
