// =============================================================================
// Brazilian Teen Slang Dictionary — Extra Set 10 (Regional Slang Deep Dive)
// =============================================================================

import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_10: SlangTerm[] = [
  // ===========================================================================
  // SÃO PAULO (SP) — Paulistano / Paulista
  // ===========================================================================
  { term: "maninho", meaning: "Irmão, amigo próximo — termo de carinho e confiança entre amigos.", adultTranslation: "Irmão / Amigo próximo / Irmãozinho.", context: "Vocativo muito usado em São Paulo para se referir a um amigo próximo, geralmente do sexo masculino.", category: "saudacao", riskLevel: "green", safeExample: "E aí maninho, bora jogar bola hoje?", contextNotes: "Diminutivo carinhoso de 'irmão'. Extremamente comum em São Paulo entre amigos. Totalmente inofensivo e positivo.", origin: "Gíria paulista, derivação carinhosa de 'irmão', popularizada pela cultura hip-hop e funk de São Paulo.", variations: ["mano", "irmão", "maninhoza"], popularityStatus: "ativo", region: "SP" },
  { term: "truta", meaning: "Amigo, cara, parceiro — muito característico de São Paulo.", adultTranslation: "Amigo / Cara / Parceiro / Irmão.", context: "Vocativo tipicamente paulista para se referir a um amigo ou pessoa de confiança.", category: "saudacao", riskLevel: "green", safeExample: "E aí truta, tudo belezoca?", contextNotes: "Termo extremamente paulista. Pode soar estranho para quem não é de SP, mas é totalmente positivo e carinhoso entre amigos.", origin: "Gíria de origem paulista, possivelmente do universo do skate e hip-hop de São Paulo nos anos 2000.", variations: ["truta boa", "tmjt (tamo junto truta)"], popularityStatus: "ativo", region: "SP" },
  { term: "pae", meaning: "Chefe, amigo, pessoa de respeito — usado na periferia de São Paulo.", adultTranslation: "Chefe / Amigo / Pessoa de respeito.", context: "Vocativo da periferia paulista para tratar amigo com respeito e admiração.", category: "saudacao", riskLevel: "green", safeExample: "E aí pae,beleza?", contextNotes: "Escrito sem acento ('pae' e não 'pai'). Muito usado na periferia de São Paulo como sinal de respeito entre amigos.", origin: "Cultura da periferia paulista, funk e rap de São Paulo.", variations: ["pai", "paizão"], popularityStatus: "ativo", region: "SP" },
  { term: "magina", meaning: "Relaxa, não foi isso, não dá importância — expressão paulista clássica.", adultTranslation: "Relaxa / Não liga / Brincadeira / Não se preocupa.", context: "Expressão usada para acalmar alguém após uma provocação leve ou dizer que algo não foi sério.", category: "expressão", riskLevel: "green", safeExample: "Magina, foi só zoera! Não fica bravo não.", contextNotes: "Expressão cultural de São Paulo, muito usada para desescalar tensões leves entre amigos. Totalmente inofensiva.", origin: "Gíria paulista clássica, de longa tradição na cultura de São Paulo.", variations: ["mágina", "magina aí", "num magina"], popularityStatus: "ativo", region: "SP" },
  { term: "tri", meaning: "Legal, bom, excelente — abreviação de 'tri legal' ou 'trilegal'.", adultTranslation: "Legal / Bom / Excelente / Muito bom.", context: "Adjetivo usado para dizer que algo é bom ou legal. Muito usado por adolescentes paulistas.", category: "elogio", riskLevel: "green", safeExample: "Essa festa foi tri demais!", contextNotes: "Abreviação de 'tri legal' ou 'trilegal'. Extremamente comum entre adolescentes de São Paulo. Totalmente positivo.", origin: "Gíria jovem paulista, abreviação de 'tri legal'.", variations: ["tri legal", "tri demais", "trilegal"], popularityStatus: "ativo", region: "SP" },
  { term: "bicho", meaning: "Interjeição de surpresa ou espanto, muito comum em São Paulo.", adultTranslation: "Nossa! / Caramba! / Interjeição de espanto.", context: "Interjeição tipicamente paulista para expressar surpresa diante de algo.", category: "expressão", riskLevel: "green", safeExample: "Bicho, que prova difícil!", contextNotes: "Interjeição muito comum em SP. Diferente de outros estados onde 'bicho' tem outros significados. Inofensiva.", origin: "Gíria paulista clássica, usada há décadas em São Paulo.", variations: ["bicho!", "ah bicho"], popularityStatus: "ativo", region: "SP" },
  { term: "du", meaning: "Cara, pessoa, indivíduo — adaptação paulista de 'dude' (inglês).", adultTranslation: "Cara / Pessoa / Indivíduo / Mano.", context: "Vocativo usado para se referir a uma pessoa, geralmente amigo. Influência do inglês 'dude'.", category: "saudacao", riskLevel: "green", safeExample: "E aí du, tudo certo?", contextNotes: "Adaptação brasileira de 'dude'. Muito comum entre adolescentes paulistas que consomem cultura americana.", origin: "Do inglês 'dude', adaptado pela cultura jovem paulista com influência de internet e cultura americana.", variations: ["dude", "dudeza"], popularityStatus: "ativo", region: "SP" },
  { term: "mlk", meaning: "Moleque, cara, garoto — abreviação muito usada em São Paulo.", adultTranslation: "Moleque / Cara / Garoto / Rapaz.", context: "Abreviação de 'moleque', usada como vocativo ou para se referir a um cara jovem.", category: "saudacao", riskLevel: "green", safeExample: "Esse mlk é muito engraçado!", contextNotes: "Abreviação de 'moleque'. Extremamente comum em mensagens de texto entre adolescentes paulistas. Inofensiva.", origin: "Abreviação de 'moleque', popularizada por mensagens de texto e WhatsApp em São Paulo.", variations: ["moleque", "mlk demais", "molecada"], popularityStatus: "ativo", region: "SP" },
  { term: "cê tá doido?", meaning: "Você está doido? — expressão de incredulidade ou surpresa paulista.", adultTranslation: "Você está doido? / Você tá bem? / Não acredito.", context: "Expressão usada para demonstrar surpresa ou incredulidade diante de algo absurdo ou inesperado.", category: "expressão", riskLevel: "green", safeExample: "Cê tá doido? Vai pular daí não!", contextNotes: "Forma paulista de dizer 'você está doido?'. Pode ser de preocupação ou espanto. Inofensiva.", origin: "Expressão coloquial paulista, redução de 'você' para 'cê'.", variations: ["cê tá louco?", "tá doido?"], popularityStatus: "ativo", region: "SP" },
  { term: "me respeita", meaning: "Expressão de afirmação e autoconfiança, popularizada pelo funk paulista.", adultTranslation: "Me respeita / Tenha respeito / Sou alguém.", context: "Expressão de autoafirmação muito usada no funk de São Paulo. Pode ser saudação ou afirmação.", category: "expressão", riskLevel: "green", safeExample: "Chegou o bonde, me respeita!", contextNotes: "Expressão do funk paulista que se tornou popular entre adolescentes. Pode soar agressiva para quem não conhece, mas geralmente é usada de forma festiva.", origin: "Cultura funk paulista, popularizada por MCs de São Paulo.", variations: ["respeita", "me respeita irmão"], popularityStatus: "ativo", region: "SP" },
  { term: "tá osso", meaning: "Difícil, complicado, péssimo — quando algo está muito ruim.", adultTranslation: "Difícil / Complicado / Péssimo / Muito ruim.", context: "Expressão para dizer que algo está difícil ou ruim, como uma prova, o trânsito ou uma situação.", category: "expressão", riskLevel: "green", safeExample: "Hoje o trânsito tá osso, não vou chegar a tempo.", contextNotes: "Expressão paulista muito comum. Inofensiva, apenas indica dificuldade.", origin: "Gíria paulista, possivelmente referência a algo 'duro como osso'.", variations: ["tá osso mesmo", "foi osso", "osso"], popularityStatus: "ativo", region: "SP" },
  { term: "baum", meaning: "Bom — forma de escrever a pronúncia paulista de 'bom'.", adultTranslation: "Bom / Legal / Bacana.", context: "Forma de escrever 'bom' como os paulistas pronunciam (com som mais fechado/aberto).", category: "elogio", riskLevel: "green", safeExample: "O filme foi baum demais!", contextNotes: "Representação escrita da pronúncia paulista. Totalmente inofensiva e cultural.", origin: "Pronúncia característica de São Paulo, adaptada para escrita em mensagens de texto.", variations: ["bom", "tá baum"], popularityStatus: "ativo", region: "SP" },
  { term: "véio", meaning: "Amigo, cara, pessoa — pronúncia paulista de 'velho' como vocativo.", adultTranslation: "Amigo / Cara / Parceiro.", context: "Vocativo informal entre amigos em São Paulo, sem relação com idade real da pessoa.", category: "saudacao", riskLevel: "green", safeExample: "E aí véio, bora sair?", contextNotes: "Forma paulista de pronunciar 'velho'. Usado entre amigos como vocativo carinhoso. Nada a ver com idade.", origin: "Gíria paulista, pronúncia característica de 'velho' como vocativo amigável.", variations: ["velho", "vei", "véiozinho"], popularityStatus: "ativo", region: "SP" },
  { term: "rapariga", meaning: "Mulher, menina, garota — uso normal no interior de SP, mas atenção ao contexto nacional.", adultTranslation: "Menina / Mulher / Garota (interior de SP).", context: "No interior de São Paulo, é usado normalmente para se referir a uma mulher jovem. ATENÇÃO: em Portugal e em algumas regiões do Brasil, pode ter conotação pejorativa.", category: "regional", riskLevel: "yellow", safeExample: "Aquela rapariga é muito simpática.", contextNotes: "ORIENTAÇÃO IMPORTANTE: No interior de São Paulo, é um termo normal para 'menina/mulher'. Porém, em Portugal significa 'prostituta'. Se o adolescente usar em contextos online com pessoas de PT, pode gerar confusão. Orientar sobre regionalismo.", origin: "Termo de origem portuguesa, mas que no interior de SP mantém o significado original de 'moça'.", variations: ["rapariga boa", "raparigada"], popularityStatus: "regional", region: "SP (interior)" },
  { term: "vei", meaning: "Amigo, cara — forma abreviada de 'véio/velho' em São Paulo.", adultTranslation: "Amigo / Cara / Irmão.", context: "Abreviação de 'véio', muito usada em mensagens rápidas entre amigos paulistas.", category: "saudacao", riskLevel: "green", safeExample: "Vei, você acreditou nisso?", contextNotes: "Abreviação de 'véio'. Extremamente comum em mensagens de WhatsApp entre adolescentes de SP.", origin: "Abreviação de 'véio', gíria paulista.", variations: ["véio", "velho", "veizinho"], popularityStatus: "ativo", region: "SP" },
  { term: "me chama", meaning: "Me liga, me contata, me procura — expressão paulista para contato.", adultTranslation: "Me liga / Me procura / Me contata.", context: "Expressão usada para pedir que alguém entre em contato, por ligação ou mensagem.", category: "saudacao", riskLevel: "green", safeExample: "Depois me chama pra gente combinar!", contextNotes: "Expressão paulista muito comum. Pode significar ligar, mandar mensagem ou buscar pessoalmente. Inofensiva.", origin: "Expressão coloquial de São Paulo, popularizada pelo hip-hop e funk.", variations: ["me liga", "me procura", "me chama no pv"], popularityStatus: "ativo", region: "SP" },
  { term: "manda ver", meaning: "Vai em frente, faz acontecer, mostra do que é capaz.", adultTranslation: "Vai em frente / Faz acontecer / Manda bala.", context: "Expressão de incentivo e encorajamento, muito usada em São Paulo.", category: "expressão", riskLevel: "green", safeExample: "Manda ver na prova de hoje!", contextNotes: "Expressão muito positiva de incentivo. Totalmente inofensiva e encorajadora.", origin: "Expressão popular brasileira, muito forte em São Paulo.", variations: ["manda bala", "manda", "bora manda ver"], popularityStatus: "ativo", region: "SP" },
  { term: "deicha", meaning: "Deixa — forma de escrever com sotaque paulista (o 'e' aberto vira 'ei').", adultTranslation: "Deixa / Deixe / Não se preocupe.", context: "Forma escrita do sotaque paulista para 'deixa'. Comum em mensagens de adolescentes de SP.", category: "expressão", riskLevel: "green", safeExample: "Deicha que eu resolvo isso.", contextNotes: "Representação do sotaque paulista. O 'e' antes de 'x' é pronunciado como 'ei'. Inofensivo e cultural.", origin: "Sotaque paulista, pronúncia aberta do 'e'.", variations: ["deixa", "deixa eu ver"], popularityStatus: "regional", region: "SP" },
  { term: "pincha", meaning: "Puxa, chama, convida — gíria paulista para chamar alguém.", adultTranslation: "Puxa / Chama / Convida / Vem cá.", context: "Gíria paulista para convidar ou chamar alguém para fazer algo.", category: "saudacao", riskLevel: "green", safeExample: "Pincha o bonde pra gente ir no show!", contextNotes: "Termo regional de São Paulo. Pode soar estranho para quem não é de SP, mas é totalmente positivo.", origin: "Gíria paulista, possivelmente do skate ou cultura de rua de SP.", variations: ["pincha a galera", "pincha os mlk"], popularityStatus: "ativo", region: "SP" },
  { term: "osso", meaning: "Difícil, péssimo, algo muito ruim ou complicado.", adultTranslation: "Péssimo / Difícil / Muito ruim / Complicado.", context: "Adjetivo para algo ruim: prova osso, dia osso, trânsito osso.", category: "expressão", riskLevel: "green", safeExample: "A prova de matemática foi osso!", contextNotes: "Gíria paulista muito comum. Significa algo difícil ou ruim. Inofensiva.", origin: "Gíria paulista, comparação com algo duro como osso.", variations: ["tá osso", "foi osso", "osso demais"], popularityStatus: "ativo", region: "SP" },
  { term: "coragem", meaning: "Ousadia, atitude, destemor — usado como elogio na cultura paulista.", adultTranslation: "Ousadia / Atitude / Coragem / Destemor.", context: "Usado para elogiar alguém que teve atitude ou fez algo corajoso.", category: "elogio", riskLevel: "green", safeExample: "Esse cara tem coragem, bora no mosh!", contextNotes: "No contexto jovem paulista, é um elogio à atitude. Totalmente positivo.", origin: "Cultura urbana de São Paulo, associado a atitude e destemor.", variations: ["tem coragem", "coragem esse mlk"], popularityStatus: "ativo", region: "SP" },

  // ===========================================================================
  // RIO DE JANEIRO (RJ) — Carioca
  // ===========================================================================
  { term: "mermão", meaning: "Meu irmão, amigo muito próximo — marca carioca por excelência.", adultTranslation: "Meu irmão / Amigo muito próximo / Irmão.", context: "Contração de 'meu irmão', vocativo carioca usado entre amigos de muita confiança.", category: "saudacao", riskLevel: "green", safeExample: "E aí mermão, tudo na paz?", contextNotes: "Marca registrada do falar carioca. Indica muita proximidade entre amigos. Totalmente positivo e carinhoso.", origin: "Contração de 'meu irmão', gíria carioca clássica, popularizada pelo funk e cultura do Rio de Janeiro.", variations: ["mano", "irmão", "maninho"], popularityStatus: "ativo", region: "RJ" },
  { term: "irado", meaning: "Incrível, muito bom, fantástico — elogio carioca clássico.", adultTranslation: "Incrível / Fantástico / Muito bom / Excelente.", context: "Adjetivo muito usado no Rio para elogiar algo que é extraordinariamente bom.", category: "elogio", riskLevel: "green", safeExample: "Essa festa foi irada demais!", contextNotes: "Termo carioca extremamente positivo. Usado para descrever algo incrível. Inofensivo e elogioso.", origin: "Gíria carioca, possivelmente derivada de 'irar' (provocar admiração).", variations: ["irado demais", "irada", "muito irado"], popularityStatus: "ativo", region: "RJ" },
  { term: "fera", meaning: "Pessoa incrível, alguém muito bom em algo — elogio carioca.", adultTranslation: "Pessoa incrível / Alguém excelente / Craque.", context: "Elogio para alguém que é muito bom em algo ou que é uma pessoa incrível.", category: "elogio", riskLevel: "green", safeExample: "Você é fera na matemática!", contextNotes: "Termo muito positivo e elogioso. 'Fera' = alguém que domina algo. Inofensivo.", origin: "Gíria carioca, referência a uma 'fera' (animal forte) como metáfora de competência.", variations: ["fera demais", "você é fera", "fera do jogo"], popularityStatus: "ativo", region: "RJ" },
  { term: "nóia", meaning: "Pessoa desconfiada, estranha, ou pessoa que faz muita faniquito.", adultTranslation: "Pessoa desconfiada / Estranha / Ansiosa.", context: "Pode se referir a alguém desconfiado ou ansioso, ou alguém que cria problema por nada.", category: "expressão", riskLevel: "yellow", safeExample: "Para de ser nóia, fica tranquilo!", contextNotes: "Pode ser usado de forma levemente provocativa entre amigos. Observar o tom — se usado de forma agressiva, pode ser desrespeitoso. Geralmente é brincadeira leve.", origin: "Gíria carioca, possivelmente derivada de 'paranoico' ou 'enoia'.", variations: ["nóia da silva", "nóia pra caralho"], popularityStatus: "ativo", region: "RJ" },
  { term: "brisa", meaning: "Fácil, sem problema, moleza — algo muito simples de resolver.", adultTranslation: "Fácil / Sem problema / Moleza / Simples.", context: "Expressão carioca para dizer que algo é muito fácil ou tranquilo.", category: "elogio", riskLevel: "green", safeExample: "Essa prova foi brisa, nem estudei!", contextNotes: "Termo muito positivo. Significa facilidade e tranquilidade. Inofensivo.", origin: "Gíria carioca, metáfora de algo leve como a brisa.", variations: ["brisinha", "foi brisa", "totalmente brisa"], popularityStatus: "ativo", region: "RJ" },
  { term: "zoeira", meaning: "Brincadeira, bagunça divertida — expressão que nasceu no Rio e se espalhou pelo Brasil.", adultTranslation: "Brincadeira / Bagunça divertida / Zoação.", context: "Atitude de brincar, zoar, fazer piada. Pode ser positivo ou negativo dependendo do contexto.", category: "zoeira", riskLevel: "green", safeExample: "Hoje o rolê é só zoeira!", contextNotes: "Expressão carioca que se tornou nacional. Geralmente positiva, mas pode envolver provocação se alvo não estiver confortável.", origin: "Gíria carioca, do verbo 'zoar', popularizada nacionalmente pelo funk e redes sociais.", variations: ["zoar", "zoeiro", "zoeira pura"], popularityStatus: "ativo", region: "RJ" },
  { term: "sec", meaning: "Segurança, olho vivo, ficar atento — gíria carioca de atenção.", adultTranslation: "Olho vivo / Fica atento / Segurança.", context: "Expressão para avisar alguém para ficar atento ou cuidado com algo.", category: "expressão", riskLevel: "green", safeExample: "Fica sec que o professor tá vindo!", contextNotes: "Abreviação de 'segurança'. Muito usada no Rio para dizer 'fica atento'. Inofensiva.", origin: "Gíria carioca, redução de 'segurança'.", variations: ["segurança", "fica sec", "sec na visão"], popularityStatus: "ativo", region: "RJ" },
  { term: "treta", meaning: "Confusão, briga, discussão, drama — originou-se no Rio e se espalhou pelo Brasil.", adultTranslation: "Confusão / Briga / Discussão / Drama.", context: "Pode ser uma briga física, uma discussão ou drama nas redes sociais.", category: "expressão", riskLevel: "yellow", safeExample: "Teve treta no grupo de WhatsApp, não quero nem saber.", contextNotes: "Gíria que nasceu no Rio e se espalhou pelo Brasil. Pode envolver conflito, mas geralmente entre adolescentes significa drama online ou discussão. Observar contexto.", origin: "Gíria carioca, do mundo do funk e cultura urbana do Rio de Janeiro.", variations: ["treta online", "treta na quebrada", "treta de leve"], popularityStatus: "ativo", region: "RJ" },
  { term: "c seam", meaning: "Parece que, parece ser — expressão carioca de comparação ou observação.", adultTranslation: "Parece que / Parece ser / Me parece.", context: "Expressão tipicamente carioca para dizer que algo parece ser de um jeito.", category: "expressão", riskLevel: "green", safeExample: "C seam que vai chover hoje.", contextNotes: "Expressão fonética carioca para 'parece que'. Pode ser difícil de entender para quem não é do Rio. Inofensiva.", origin: "Fonética carioca de 'parece que', pronunciado rápido como 'c seam'.", variations: ["parece que", "parece"], popularityStatus: "ativo", region: "RJ" },
  { term: "sussa", meaning: "Sossegado, tranquilo, sem problemas — expressão carioca de calma.", adultTranslation: "Tranquilo / Calmo / Sem problemas / Sossegado.", context: "Usado para dizer que está tudo bem ou que alguém está calmo.", category: "saudacao", riskLevel: "green", safeExample: "Relaxa, tá tudo sussa.", contextNotes: "Diminutivo de 'sossegado'. Nasceu no Rio e se espalhou pelo Brasil. Totalmente inofensivo e positivo.", origin: "Diminutivo de 'sossegado', gíria carioca que se nacionalizou.", variations: ["sossegado", "sussa total", "tá sussa"], popularityStatus: "ativo", region: "RJ" },
  { term: "pacas", meaning: "Muito, várias vezes, aos montes — intensificador carioca.", adultTranslation: "Muito / Várias vezes / Bastante / Demais.", context: "Intensificador usado para dizer que algo acontece muito ou é em grande quantidade.", category: "expressão", riskLevel: "green", safeExample: "Eu ri pacas com esse meme!", contextNotes: "Expressão muito comum no Rio. 'Dar pacas' = muito. Inofensiva e expressiva.", origin: "Gíria carioca, possivelmente referência a uma 'paca' (animal) que produz muito.", variations: ["dar pacas", "ri pacas", "chorei pacas"], popularityStatus: "ativo", region: "RJ" },
  { term: "da hora", meaning: "Muito legal, excelente, incrível — expressão carioca de elogio.", adultTranslation: "Muito legal / Excelente / Incrível.", context: "Expressão para elogiar algo ou alguém que é muito bom.", category: "elogio", riskLevel: "green", safeExample: "Esse restaurante é da hora!", contextNotes: "Expressão carioca que se tornou nacional. Totalmente positiva e elogiosa.", origin: "Gíria carioca clássica, popularizada por músicas e cultura do Rio.", variations: ["muito da hora", "é da hora mesmo"], popularityStatus: "ativo", region: "RJ" },
  { term: "massinha", meaning: "Legal, tranquilo, bacana — versão carinhosa de 'massa'.", adultTranslation: "Legal / Tranquilo / Bacana / Muito bom.", context: "Versão suavizada de 'massa', usada para dizer que algo é legal ou tranquilo.", category: "elogio", riskLevel: "green", safeExample: "O rolê foi massinha!", contextNotes: "Diminutivo de 'massa'. Termo carioca positivo e carinhoso. Inofensivo.", origin: "Gíria carioca, derivação de 'massa' com sufixo diminutivo.", variations: ["massa", "massinha demais"], popularityStatus: "ativo", region: "RJ" },
  { term: "sinistro", meaning: "Muito bom/incrível (irônico ou genuíno), ou algo assustador — depende do tom.", adultTranslation: "Incrível / Assustador / Absurdo (depende do contexto).", context: "Pode ser elogio irônico ('esse som é sinistro' = muito bom) ou genuíno espanto.", category: "elogio", riskLevel: "yellow", safeExample: "Essa mancada foi sinistro, kkk!", contextNotes: "Uso irônico comum no Rio: 'sinistro' = incrível/absurdo. Observar o contexto — pode ser positivo ou negativo dependendo do tom.", origin: "Gíria carioca com uso irônico, popularizada pelo funk e cultura urbana.", variations: ["sinistro demais", "é sinistro"], popularityStatus: "ativo", region: "RJ" },
  { term: "esquenta", meaning: "Se preocupa, se irrita, fica nervoso — gíria carioca.", adultTranslation: "Se preocupa / Se irrita / Fica nervoso.", context: "Dizer para alguém não se preocupar ou não se irritar com algo.", category: "expressão", riskLevel: "green", safeExample: "Não esquenta, vai dar tudo certo!", contextNotes: "Expressão carioca para acalmar alguém. Geralmente positiva e acolhedora. Inofensiva.", origin: "Gíria carioca, do verbo 'esquentar a cabeça'.", variations: ["não esquenta", "esquenta não", "esquentou a cabeça"], popularityStatus: "ativo", region: "RJ" },
  { term: "gravata", meaning: "Resposta forte, comentário afiado, réplica inteligente — do funk carioca.", adultTranslation: "Resposta forte / Réplica inteligente / Comentário afiado.", context: "Resposta rápida e inteligente, geralmente com humor ou ironia, para desconcertar alguém.", category: "zoeira", riskLevel: "yellow", safeExample: "Ele mandou uma gravata e o outro não soube responder!", contextNotes: "Do funk carioca, significa dar uma resposta irônica ou forte. Pode ser engraçado entre amigos, mas se for agressivo pode machucar.", origin: "Cultura funk carioca, popularizada por MCs do Rio de Janeiro.", variations: ["gravata forte", "dar gravata"], popularityStatus: "ativo", region: "RJ" },
  { term: "bando de", meaning: "Grupo de, monte de — expressão carioca para quantidade.", adultTranslation: "Grupo de / Monte de / Vários.", context: "Expressão para falar de um grupo de pessoas ou coisas.", category: "expressão", riskLevel: "green", safeExample: "Tinha bando de gente na festa!", contextNotes: "Expressão carioca muito comum no dia a dia. Inofensiva.", origin: "Expressão popular do Rio de Janeiro, de uso cotidiano.", variations: ["bando de gente", "bando de gato"], popularityStatus: "ativo", region: "RJ" },
  { term: "trem (RJ)", meaning: "Coisa, negócio, objeto — uso carioca diferente do mineiro.", adultTranslation: "Coisa / Negócio / Objeto / Assunto.", context: "No Rio, 'trem' é usado como pronome genérico para 'coisa' ou 'negócio'.", category: "expressão", riskLevel: "green", safeExample: "Passa aquele trem ali pra mim?", contextNotes: "Uso carioca de 'trem' como 'coisa'. Diferente do mineiro onde é mais genérico ainda. Inofensivo.", origin: "Expressão carioca de longa data, uso de 'trem' como pronome.", variations: ["aquele trem", "o trem"], popularityStatus: "ativo", region: "RJ" },
  { term: "maluco (RJ)", meaning: "Cara, pessoa, sujeito — vocativo carioca para se referir a alguém.", adultTranslation: "Cara / Pessoa / Sujeito / Indivíduo.", context: "Vocativo carioca para se referir a uma pessoa de forma informal.", category: "saudacao", riskLevel: "green", safeExample: "Aquele maluco é muito engraçado!", contextNotes: "No Rio, 'maluco' é usado como 'cara' ou 'sujeito'. Não significa que a pessoa é literalmente doida.", origin: "Gíria carioca clássica, uso como pronome para 'pessoa'.", variations: ["maluco demais", "aquele maluco"], popularityStatus: "ativo", region: "RJ" },
  { term: "quebrada", meaning: "Bairro, periferia, local onde se mora — termo carioca forte.", adultTranslation: "Bairro / Periferia / Vizinhança / Local de moradia.", context: "Refere-se ao bairro ou comunidade onde a pessoa mora, geralmente periferia.", category: "regional", riskLevel: "green", safeExample: "Hoje o role é na quebrada mesmo.", contextNotes: "Termo muito presente no funk carioca. Refere-se ao bairro com carinho e pertencimento. Inofensivo.", origin: "Cultura funk e hip-hop carioca, referência à quebrada (bairro/periferia).", variations: ["minha quebrada", "quebrada tava", "vindo da quebrada"], popularityStatus: "ativo", region: "RJ" },
  { term: "os gringo", meaning: "Os caras, os pessoal, o pessoal — expressão carioca para 'aqueles caras'.", adultTranslation: "Os caras / O pessoal / Aquela galera.", context: "Expressão carioca para se referir a um grupo de pessoas, geralmente de forma vaga.", category: "expressão", riskLevel: "green", safeExample: "Os gringo não veio hoje na aula.", contextNotes: "Expressão carioca curiosa. 'Gringo' aqui não se refere a estrangeiros, mas a 'os caras'. Inofensiva.", origin: "Gíria carioca, uso de 'gringo' como pronome genérico para 'os caras'.", variations: ["os gringo lá", "os gringo tava"], popularityStatus: "ativo", region: "RJ" },

  // ===========================================================================
  // MINAS GERAIS (MG) — Mineiro
  // ===========================================================================
  { term: "uai", meaning: "Interjeição mineira clássica de dúvida, surpresa ou espanto.", adultTranslation: "Nossa? / Como assim? / Pois é? / Espanto.", context: "Marca registrada do falar mineiro. Pode expressar dúvida, surpresa ou simples ênfase.", category: "expressão", riskLevel: "green", safeExample: "Uai, mas você não disse que ia vir?", contextNotes: "Interjeição cultural de Minas Gerais, parte da identidade mineira. Totalmente inofensiva e cultural.", origin: "Expressão tradicional de Minas Gerais, de origem incerta (possivelmente influência indígena ou portuguesa).", variations: ["uai pois", "uai mesmo", "uai, uai"], popularityStatus: "regional", region: "MG" },
  { term: "trem (MG)", meaning: "Qualquer coisa, objeto, assunto — pronome genérico mineiro por excelência.", adultTranslation: "Coisa / Objeto / Negócio / Qualquer coisa.", context: "Em MG, 'trem' substitui praticamente qualquer substantivo. 'Me passa aquele trem' = me passa aquela coisa.", category: "expressão", riskLevel: "green", safeExample: "Me passa aquele trem aí, por favor.", contextNotes: "Uso mineiro extremamente característico. 'Trem' pode ser qualquer coisa. Inofensivo e culturalmente rico.", origin: "Gíria mineira clássica, possivelmente influência de imigrantes que construíram ferrovias em MG.", variations: ["trem bão", "aquele trem", "não sei que trem é esse"], popularityStatus: "regional", region: "MG" },
  { term: "bicho (MG)", meaning: "Interjeição mineira de espanto ou ênfase.", adultTranslation: "Nossa! / Caramba! / Espanto.", context: "Interjeição muito usada em Minas Gerais para expressar surpresa.", category: "expressão", riskLevel: "green", safeExample: "Bicho, que frio tá fazendo em BH!", contextNotes: "Uso mineiro de 'bicho' como interjeição. Inofensivo e cultural.", origin: "Expressão mineira, uso interjetivo de 'bicho'.", variations: ["bicho!", "ah bicho"], popularityStatus: "regional", region: "MG" },
  { term: "cê", meaning: "Você — pronúncia mineira abreviada de 'você'.", adultTranslation: "Você.", context: "Forma mineira de dizer 'você', muito usada na fala casual.", category: "expressão", riskLevel: "green", safeExample: "Cê quer ir no cinema hoje?", contextNotes: "Redução de 'você' na pronúncia mineira. Comum e inofensivo.", origin: "Fonética mineira, redução de 'você' para 'cê'.", variations: ["cês", "cê tá"], popularityStatus: "regional", region: "MG" },
  { term: "tamuje", meaning: "Tamo junto — forma mineira de dizer 'estamos juntos'.", adultTranslation: "Estamos juntos / Conta comigo / Sou seu amigo.", context: "Expressão de amizade e lealdade, versão mineira de 'tamo junto'.", category: "saudacao", riskLevel: "green", safeExample: "Tamuje, pode contar comigo!", contextNotes: "Contração mineira de 'tamo junto'. Expressão de amizade muito forte. Totalmente positiva.", origin: "Gíria mineira, contração fonética de 'tamo junto'.", variations: ["tamo junto", "tamujunto", "tmj"], popularityStatus: "regional", region: "MG" },
  { term: "guenta", meaning: "Aguenta, suporta, resiste — forma mineira de 'aguenta'.", adultTranslation: "Aguenta / Suporta / Resiste / Segura.", context: "Usado para encorajar alguém a aguentar uma situação difícil ou a esperar.", category: "expressão", riskLevel: "green", safeExample: "Guenta aí que já estou chegando!", contextNotes: "Forma mineira de 'aguenta'. Comum e inofensiva.", origin: "Pronúncia mineira de 'aguenta', com o 'a' mais aberto.", variations: ["guenta firme", "guenta aí"], popularityStatus: "regional", region: "MG" },
  { term: "ici", meaning: "Aqui — pronúncia mineira de 'aqui'.", adultTranslation: "Aqui / Neste lugar.", context: "Forma mineira de pronunciar 'aqui', com o 'a' mais aberto.", category: "expressão", riskLevel: "green", safeExample: "Vem ici que é mais perto.", contextNotes: "Pronúncia característica de Minas Gerais. Inofensiva e cultural.", origin: "Fonética mineira, pronúncia aberta de 'aqui'.", variations: ["aqui", "vim ici"], popularityStatus: "regional", region: "MG" },
  { term: "vixe", meaning: "Interjeição mineira de surpresa, preocupação ou espanto.", adultTranslation: "Nossa! / Caramba! / Puxa vida! / Espanto.", context: "Interjeição muito usada em Minas Gerais para expressar surpresa ou preocupação.", category: "expressão", riskLevel: "green", safeExample: "Vixe, esqueci de fazer a lição!", contextNotes: "Interjeição cultural de Minas Gerais. Forma atenuada de expressões mais fortes. Inofensiva.", origin: "Expressão tradicional mineira, possivelmente variação de 'virgem maria'.", variations: ["vixe maria", "vixi", "vixe meu filho"], popularityStatus: "regional", region: "MG" },
  { term: "pra caramba", meaning: "Muito, demais — intensificador muito usado em Minas.", adultTranslation: "Muito / Demais / Extremamente.", context: "Intensificador para dizer que algo é em grande quantidade ou intensidade.", category: "expressão", riskLevel: "green", safeExample: "Tá quente pra caramba hoje!", contextNotes: "Expressão comum em Minas e em todo o Brasil. Inofensiva.", origin: "Expressão brasileira, forma atenuada de expressões mais fortes.", variations: ["pra caralho", "pra dedéu"], popularityStatus: "ativo", region: "MG" },
  { term: "proceis", meaning: "Professores — forma de gíria dos adolescentes mineiros para professores.", adultTranslation: "Professores / Professora.", context: "Gíria adolescente mineira para se referir aos professores de forma informal.", category: "escola", riskLevel: "green", safeExample: "Os proceis cobraram a atividade hoje.", contextNotes: "Redução informal de 'professores' entre adolescentes de Minas. Inofensivo, mas pode ser considerado desrespeitoso em contexto formal.", origin: "Gíria estudantil mineira, redução de 'professores'.", variations: ["profe", "professor"], popularityStatus: "regional", region: "MG" },
  { term: "arrombado", meaning: "Algo incrível, absurdo, surpreendente — usado por adolescentes mineiros como superlativo.", adultTranslation: "Incrível / Absurdo / Surpreendente / Muito bom.", context: "Entre adolescentes mineiros, usado como superlativo positivo para algo impressionante.", category: "elogio", riskLevel: "yellow", safeExample: "Esse gol foi arrombado!", contextNotes: "ATENÇÃO: Embora adolescentes usem como elogio, é uma palavra que originalmente tem conotação sexual vulgar. Pode ser muito mal interpretada por adultos e em contextos formais. Orientar sobre uso de linguagem adequada.", origin: "Gíria adolescente de Minas Gerais, uso irônico como superlativo.", variations: ["arrombado demais", "é arrombado"], popularityStatus: "ativo", region: "MG" },
  { term: "bala (MG)", meaning: "Muito bom, excelente — elogio forte dos adolescentes mineiros.", adultTranslation: "Muito bom / Excelente / Incrível.", context: "Adjetivo usado por adolescentes mineiros para elogiar algo muito bom.", category: "elogio", riskLevel: "green", safeExample: "Essa música é bala!", contextNotes: "Termo positivo e comum entre adolescentes de Minas. Inofensivo.", origin: "Gíria jovem de Minas Gerais, possivelmente do universo do funk e rap mineiro.", variations: ["bala demais", "é bala"], popularityStatus: "ativo", region: "MG" },
  { term: "doente (MG)", meaning: "Muito bom, incrível — elogio adolescente mineiro.", adultTranslation: "Muito bom / Incrível / Absurdo de bom.", context: "Adjetivo usado para elogiar algo impressionante, como algo tão bom que 'deixa doente'.", category: "elogio", riskLevel: "green", safeExample: "Esse jogo é doente!", contextNotes: "Termo adolescente positivo. Significa que algo é tão bom que impressiona. Inofensivo.", origin: "Gíria adolescente mineira, metáfora de algo tão bom que 'deixa doente de tão bom'.", variations: ["doente demais", "é doente"], popularityStatus: "ativo", region: "MG" },
  { term: "foda (MG)", meaning: "Muito bom, incrível — superlativo adolescente de Minas Gerais.", adultTranslation: "Muito bom / Incrível / Absurdo.", context: "Entre adolescentes mineiros, 'foda' é usado como elogio para algo muito bom. ATENÇÃO: pode ofender.", category: "elogio", riskLevel: "yellow", safeExample: "Essa roupa é foda!", contextNotes: "ATENÇÃO: Embora adolescentes usem como elogio em MG, 'foda' é uma palavra vulgar no português. Pode ofender adultos e é inapropriada em contextos formais. Orientar sobre linguagem adequada.", origin: "Gíria adolescente mineira, uso irônico como superlativo positivo.", variations: ["foda demais", "é foda"], popularityStatus: "ativo", region: "MG" },
  { term: "visão", meaning: "Opinião, ponto de vista, perspectiva — muito usado por adolescentes mineiros.", adultTranslation: "Opinião / Ponto de vista / Perspectiva.", context: "Usado para pedir ou dar opinião sobre algo.", category: "expressão", riskLevel: "green", safeExample: "Qual sua visão sobre isso?", contextNotes: "Uso comum entre adolescentes de Minas para falar sobre opiniões. Inofensivo.", origin: "Gíria jovem mineira, possivelmente influência de podcasts e cultura digital.", variations: ["dar visão", "visão sobre"], popularityStatus: "ativo", region: "MG" },

  // ===========================================================================
  // BAHIA (BA) — Baiano
  // ===========================================================================
  { term: "oxente", meaning: "Interjeição baiana clássica de surpresa, espanto ou chamado.", adultTranslation: "Nossa! / Caramba! / Ei! / Expressão de espanto.", context: "Marca registrada do falar baiano. Pode ser surpresa, espanto ou simplesmente chamado.", category: "expressão", riskLevel: "green", safeExample: "Oxente, nem acredito nisso!", contextNotes: "Interjeição cultural da Bahia, parte da identidade baiana. Totalmente inofensiva e cultural.", origin: "Expressão tradicional baiana, possivelmente de origem africana (iorubá).", variations: ["oxente!", "oxente gente"], popularityStatus: "regional", region: "BA" },
  { term: "que massa", meaning: "Que legal, que bom — expressão baiana de aprovação.", adultTranslation: "Que legal! / Que bom! / Bacana!", context: "Expressão muito usada na Bahia para aprovar algo ou demonstrar entusiasmo.", category: "elogio", riskLevel: "green", safeExample: "Que massa essa sua camisa nova!", contextNotes: "Expressão positiva e carinhosa da Bahia. Inofensiva.", origin: "Expressão popular baiana, de uso antigo na cultura baiana.", variations: ["massa!", "é massa"], popularityStatus: "ativo", region: "BA" },
  { term: "nego", meaning: "Pessoa, cara, indivíduo — tratamento muito comum na Bahia.", adultTranslation: "Pessoa / Cara / Indivíduo / Homem.", context: "Vocativo muito usado na Bahia para se referir a uma pessoa, geralmente do sexo masculino.", category: "saudacao", riskLevel: "green", safeExample: "E aí nego, tudo bem?", contextNotes: "Termo extremamente comum na Bahia. É um tratamento carinhoso e casual. Inofensivo.", origin: "Cultura afro-baiana, de 'negro' como termo de proximidade e identidade cultural.", variations: ["nego bom", "nego doido"], popularityStatus: "ativo", region: "BA" },
  { term: "amor", meaning: "Tratamento carinhoso universal na Bahia — usado para qualquer pessoa.", adultTranslation: "Amor / Querido / Querida — tratamento afetuoso.", context: "Na Bahia, 'amor' é usado como tratamento para praticamente qualquer pessoa, de forma espontânea.", category: "saudacao", riskLevel: "green", safeExample: "Amor, me passa o sal aí?", contextNotes: "Na Bahia, é normal chamar desconhecidos de 'amor'. Não é flerte, é apenas cultura local de ser acolhedor. Totalmente inofensivo.", origin: "Cultura baiana de acolhimento, possivelmente influência africana.", variations: ["amorzinho", "meu amor"], popularityStatus: "ativo", region: "BA" },
  { term: "maisena", meaning: "Gata bonita, mulher bonita — elogio baiano.", adultTranslation: "Gata bonita / Mulher bonita / Mulher atraente.", context: "Elogio baiano para uma mulher bonita, comparando-a com a brandura da maisena.", category: "elogio", riskLevel: "green", safeExample: "Essa menina é maisena demais!", contextNotes: "Elogio cultural baiano. Pode ser usado de forma simpática ou de flerte leve. Inofensivo.", origin: "Cultura baiana, referência à farinha de maisena (macia, suave).", variations: ["maisena gata", "gata maisena"], popularityStatus: "regional", region: "BA" },
  { term: "jegue", meaning: "Burro, lento, pessoa teimosa — termo baiano para quem é lerdo.", adultTranslation: "Lerdo / Burro / Lento / Teimoso.", context: "Pode ser usado para descrever alguém lento ou teimoso. Também é o animal (asno).", category: "expressão", riskLevel: "yellow", safeExample: "Para de ser jegue, apressa aí!", contextNotes: "Pode ser usado de forma leve entre amigos ou como provocação. Se usado de forma agressiva, pode ser ofensivo.", origin: "Cultura nordestina/baiana, referência ao jegue (asno) como sinônimo de lentidão.", variations: ["jegue puxado", "jegueada"], popularityStatus: "regional", region: "BA" },
  { term: "dengo", meaning: "Carinho, mimo, afeto — muito usado na Bahia e Nordeste.", adultTranslation: "Carinho / Mimo / Afeto / Tratamento doce.", context: "Expressão para demonstrar carinho ou para pedir algo de forma doce.", category: "elogio", riskLevel: "green", safeExample: "Que dengo de criança!", contextNotes: "Termo afetuoso muito usado na Bahia e Nordeste. Totalmente positivo e carinhoso.", origin: "Cultura afro-baiana e nordestina, de origem africana (quimbundo 'ndengo').", variations: ["dar dengo", "dengosa", "cheio de dengo"], popularityStatus: "ativo", region: "BA" },
  { term: "moleca", meaning: "Garota, menina — termo baiano para se referir a uma menina.", adultTranslation: "Garota / Menina / Moça.", context: "Termo usado na Bahia para se referir a uma menina ou garota jovem.", category: "saudacao", riskLevel: "green", safeExample: "Essa moleca é muito esperta!", contextNotes: "Termo cultural baiano, carinhoso e informal. Inofensivo.", origin: "Cultura baiana, variação de 'moleca' (menina).", variations: ["molequinha", "moleque"], popularityStatus: "regional", region: "BA" },

  // ===========================================================================
  // PERNAMBUCO (PE) — Pernambucano
  // ===========================================================================
  { term: "pega (PE)", meaning: "Vamos, pega, bora — expressão pernambucana de incentivo.", adultTranslation: "Vamos! / Bora! / Pega! / Coragem!", context: "Expressão de incentivo ou convocação, muito usada em Pernambuco.", category: "expressão", riskLevel: "green", safeExample: "Pega, que o ônibus tá chegando!", contextNotes: "Expressão cultural de Pernambuco. Inofensiva e enérgica.", origin: "Cultura pernambucana, expressão de incentivo comum no Nordeste.", variations: ["pega logo", "pega pra lá"], popularityStatus: "regional", region: "PE" },
  { term: "gogo", meaning: "Inteligente, esperto, pessoa que sabe das coisas — elogio pernambucano.", adultTranslation: "Inteligente / Esperto / Sabido / Astuto.", context: "Elogio para alguém esperto ou que percebe tudo rapidamente.", category: "elogio", riskLevel: "green", safeExample: "Esse menino é gogo, sabe de tudo!", contextNotes: "Termo cultural pernambucano, positivo. Significa inteligente e perspicaz.", origin: "Cultura pernambucana, possivelmente origem africana.", variations: ["gogo demais", "é gogo"], popularityStatus: "regional", region: "PE" },
  { term: "cabra (PE)", meaning: "Cara, homem, sujeito — muito usado em Pernambuco e Nordeste.", adultTranslation: "Homem / Cara / Sujeito / Pessoa.", context: "Vocativo muito usado no Nordeste para se referir a um homem.", category: "saudacao", riskLevel: "green", safeExample: "E aí cabra, tudo certo?", contextNotes: "Termo cultural nordestino, extremamente comum em Pernambuco. Equivalente a 'cara' ou 'mano'. Inofensivo.", origin: "Cultura sertaneja nordestina, de longa tradição.", variations: ["cabra macho", "cabra da peste"], popularityStatus: "ativo", region: "PE" },
  { term: "macambira", meaning: "Coisa ruim, situação ruim, algo de má qualidade — termo pernambucano.", adultTranslation: "Coisa ruim / Situação ruim / Má qualidade / Gambiarra.", context: "Pode descrever algo de qualidade ruim ou uma situação difícil.", category: "expressão", riskLevel: "yellow", safeExample: "Esse aparelho é macambira, não funciona.", contextNotes: "Termo cultural pernambucano. Pode ser usado para descrever coisas ruins ou gambiarras. Geralmente inofensivo.", origin: "Cultura pernambucana, a macambira é uma planta do sertão usada como alimento em época de seca.", variations: ["macambuira", "comida de macambira"], popularityStatus: "regional", region: "PE" },

  // ===========================================================================
  // RIO GRANDE DO SUL (RS) — Gaúcho
  // ===========================================================================
  { term: "tchê", meaning: "Interjeição gaúcha clássica, equivalente a 'ei', 'rapaz' ou 'amigo'.", adultTranslation: "Ei / Rapaz / Amigo / Interjeição gaúcha.", context: "Marca registrada do falar gaúcho. Usado como interjeição, vocativo ou ênfase.", category: "expressão", riskLevel: "green", safeExample: "Tchê, que frio tá fazendo hoje!", contextNotes: "Interjeição cultural do Rio Grande do Sul, parte fundamental da identidade gaúcha. Totalmente inofensiva.", origin: "Expressão gaúcha de origem indígena (guarani) ou espanhola ('che').", variations: ["tchê!", "tchê meu filho", "eh tchê"], popularityStatus: "regional", region: "RS" },
  { term: "bah", meaning: "Interjeição gaúcha de surpresa, espanto ou ênfase.", adultTranslation: "Nossa! / Caramba! / Espanto gaúcho.", context: "Interjeição típica do Rio Grande do Sul para expressar surpresa.", category: "expressão", riskLevel: "green", safeExample: "Bah, que gols espetaculares!", contextNotes: "Interjeição cultural do RS. Inofensiva e parte da identidade gaúcha.", origin: "Expressão gaúcha clássica, possivelmente de origem espanhola.", variations: ["bah!", "bah tchê"], popularityStatus: "regional", region: "RS" },
  { term: "brega (RS)", meaning: "Cafona, antiquado, ou algo emocional/romântico demais — depende do contexto.", adultTranslation: "Cafona / Antiquado / Romântico demais / Piegas.", context: "Pode significar algo sem bom gosto (cafona) ou algo muito romântico/emocional.", category: "expressão", riskLevel: "yellow", safeExample: "Essa música é muito brega, mas eu gosto!", contextNotes: "Dependendo do contexto, pode ser ofensivo (cafona) ou carinhoso (romântico). No Sul, tem uso forte como 'cafona'. Observar o tom.", origin: "Expressão comum no Sul, mas usada em todo o Brasil. No RS, tem conotação forte.", variations: ["breguinho", "breguice"], popularityStatus: "ativo", region: "RS" },
  { term: "guri", meaning: "Garoto, menino — termo gaúcho para menino.", adultTranslation: "Menino / Garoto / Rapaz.", context: "Vocativo gaúcho para se referir a um menino ou garoto jovem.", category: "saudacao", riskLevel: "green", safeExample: "Esse guri é muito esperto!", contextNotes: "Termo cultural do Rio Grande do Sul. Carinhoso e inofensivo.", origin: "Cultura gaúcha, possivelmente de origem indígena.", variations: ["gurizinho", "guri bom"], popularityStatus: "regional", region: "RS" },
  { term: "guria", meaning: "Garota, menina — termo gaúcho para menina.", adultTranslation: "Menina / Garota / Moça.", context: "Vocativo gaúcho para se referir a uma menina ou garota jovem.", category: "saudacao", riskLevel: "green", safeExample: "Aquela guria é muito simpática!", contextNotes: "Termo cultural do Rio Grande do Sul. Carinhoso e inofensivo.", origin: "Cultura gaúcha, possivelmente de origem indígena.", variations: ["guriazinha", "guria linda"], popularityStatus: "regional", region: "RS" },
  { term: "chimarrão (RS)", meaning: "Bebida gaúcha de erva-mate, símbolo da hospitalidade e amizade.", adultTranslation: "Bebida de erva-mate / Infusão gaúcha / Mate.", context: "Bebida tradicional do RS, símbolo de hospitalidade e amizade gaúcha.", category: "regional", riskLevel: "green", safeExample: "Vamos tomar um chimarrão no escritório?", contextNotes: "Bebida cultural do Sul. Inofensiva e rica em tradição. Não contém álcool. Cerimonial importante na cultura gaúcha.", origin: "Cultura gaúcha, tradição dos pampas, herdada dos povos indígenas guarani.", variations: ["mate", "erva-mate", "chimarrão gaúcho"], popularityStatus: "regional", region: "RS" },
  { term: "campeiro", meaning: "Do campo, pessoa do interior — referência à cultura rural gaúcha.", adultTranslation: "Pessoa do campo / Interiorano / Gaúcho do interior.", context: "Refere-se à pessoa ou cultura do campo, muito presente na identidade gaúcha.", category: "regional", riskLevel: "green", safeExample: "Meu avô é campeiro, mora no interior do RS.", contextNotes: "Termo cultural do RS que indica conexão com o campo. Pode ser usado com orgulho. Inofensivo.", origin: "Cultura gaúcha rural, do campo dos pampas.", variations: ["cultura campeira", "campeirismo"], popularityStatus: "regional", region: "RS" },
  { term: "bushado", meaning: "Bobo, iludido, enganado — termo gaúcho para quem se deixou enganar.", adultTranslation: "Bobo / Iludido / Enganado / Inocente.", context: "Pessoa que foi enganada ou iludida, ou que age de forma ingênua. Também chamado 'cabelo de milho'.", category: "expressão", riskLevel: "yellow", safeExample: "Ficou bushado com aquela história.", contextNotes: "Termo cultural do RS. Pode ser usado de forma leve entre amigos ou de forma mais cruel se a pessoa foi realmente enganada. Observar o tom.", origin: "Cultura gaúcha, possivelmente referência ao bush (arbusto) onde alguém se esconde.", variations: ["cabelo de milho", "ficou bushado"], popularityStatus: "regional", region: "RS" },
  { term: "massarico", meaning: "Confusão, bagunça, agitação — termo gaúcho.", adultTranslation: "Confusão / Bagunça / Agitação / Treta.", context: "Expressão gaúcha para uma situação confusa ou agitada.", category: "expressão", riskLevel: "yellow", safeExample: "Foi um massarico na festa ontem!", contextNotes: "Termo cultural do RS. Pode indicar confusão leve ou briga. Observar contexto.", origin: "Cultura gaúcha, de origem incerta.", variations: ["massaricada", "massarico daquele jeito"], popularityStatus: "regional", region: "RS" },
  { term: "farroupilha", meaning: "Cultura gaúcha, referência à Revolução Farroupilha — orgulho gaúcho.", adultTranslation: "Cultura gaúcha / Tradição do RS / Orgulho sulista.", context: "Refere-se à cultura e tradição gaúcha, especialmente a Revolução Farroupilha (1835-1845).", category: "regional", riskLevel: "green", safeExample: "O desfile farroupilha em setembro é incrível!", contextNotes: "Termo cultural de orgulho gaúcho. Totalmente positivo e histórico.", origin: "História do Rio Grande do Sul, Revolução Farroupilha (Guerra dos Farrapos).", variations: ["farroupilha!", "cultura farroupilha"], popularityStatus: "regional", region: "RS" },

  // ===========================================================================
  // CEARÁ (CE) — Cearense
  // ===========================================================================
  { term: "caraio", meaning: "Interjeição cearense de espanto, surpresa ou frustração.", adultTranslation: "Caramba! / Nossa! / Interjeição de espanto.", context: "Interjeição muito forte no Ceará, expressa espanto, surpresa ou frustração.", category: "expressão", riskLevel: "green", safeExample: "Caraio, que vento forte!", contextNotes: "Interjeição cultural do Ceará. Versão mais suave de expressões mais fortes. Inofensiva.", origin: "Expressão popular do Nordeste, especialmente forte no Ceará. Forma atenuada de 'caralho'.", variations: ["caraio!", "mas que caraio"], popularityStatus: "ativo", region: "CE" },
  { term: "nando", meaning: "Bonito, gostoso, atraente — gíria de adolescentes cearenses.", adultTranslation: "Bonito / Gostoso / Atraente.", context: "Elogio usado por adolescentes cearenses para descrever alguém bonito.", category: "elogio", riskLevel: "green", safeExample: "Esse menino é nando demais!", contextNotes: "Gíria adolescente do Ceará para elogiar aparência. Inofensiva.", origin: "Gíria jovem cearense, popularizada por redes sociais.", variations: ["nando", "é nando"], popularityStatus: "ativo", region: "CE" },
  { term: "pão (CE)", meaning: "Bonito, gostoso — gíria de adolescentes cearenses para elogiar aparência.", adultTranslation: "Bonito / Gostoso / Atraente / Bem-apessoido.", context: "Expressão cearense para elogiar alguém bonito: 'que pão' = que bonito.", category: "elogio", riskLevel: "green", safeExample: "Que pão de garoto!", contextNotes: "Gíria adolescente do Ceará. Pode soar estranho para quem não é do Ceará, mas é elogio. Inofensiva.", origin: "Gíria jovem cearense, possivelmente analogia com 'pão quente' (fresco, bom).", variations: ["que pão", "pão demais"], popularityStatus: "ativo", region: "CE" },
  { term: "marreco", meaning: "Besteira, absurdo, coisa sem sentido — gíria cearense.", adultTranslation: "Besteira / Absurdo / Coisa sem sentido.", context: "Expressão cearense para algo sem sentido ou alguém fazendo besteira.", category: "expressão", riskLevel: "green", safeExample: "Para de falar marreco, vai estudar!", contextNotes: "Gíria cearense, geralmente leve e usada entre amigos. Inofensiva.", origin: "Cultura cearense, possivelmente referência ao marreco (pato) que faz barulho sem parar.", variations: ["marreco!", "falar marreco"], popularityStatus: "regional", region: "CE" },
  { term: "marra", meaning: "Teimosia, persistência, raiva — gíria cearense.", adultTranslation: "Teimosia / Persistência / Enciumação / Birra.", context: "Pode ser teimosia, birra, ou ficar com raiva/enciumado.", category: "expressão", riskLevel: "yellow", safeExample: "Tirou marra comigo porque eu não fui na festa.", contextNotes: "Gíria cearense que pode descrever teimosia ou enciumamento. Pode gerar conflito se a pessoa estiver realmente com raiva.", origin: "Cultura cearense, possivelmente de 'marrar' (teimar).", variations: ["tirou marra", "marra da pega"], popularityStatus: "regional", region: "CE" },

  // ===========================================================================
  // AMAZONAS (AM) — Manauara
  // ===========================================================================
  { term: "caboco", meaning: "Pessoa do interior, pessoa simples — termo amazônico.", adultTranslation: "Pessoa do interior / Pessoa simples / Sertanejo.", context: "Termo usado no Amazonas para se referir a pessoas do interior ou da floresta.", category: "regional", riskLevel: "green", safeExample: "Meu avô é caboco do interior do AM.", contextNotes: "Termo cultural amazônico. Pode ser usado com carinho ou de forma pejorativa dependendo do tom. Geralmente é afetuoso.", origin: "Cultura amazônica, de 'caboclo' — mistura de branco com indígena.", variations: ["caboclo", "caboca"], popularityStatus: "regional", region: "AM" },
  { term: "roça (AM)", meaning: "Interior, área rural — no Amazonas, o oposto da cidade de Manaus.", adultTranslation: "Interior / Área rural / Zona rural.", context: "No Amazonas, 'roça' se refere às comunidades do interior, distantes de Manaus.", category: "regional", riskLevel: "green", safeExample: "Meus parentes moram na roça, perto de Parintins.", contextNotes: "Termo amazônico para o interior. Pode ser usado com saudade ou carinho. Inofensivo.", origin: "Cultura amazônica, referência às comunidades ribeirinhas e do interior.", variations: ["ir pra roça", "roceiro"], popularityStatus: "regional", region: "AM" },
  { term: "virote", meaning: "Pior, ruim, péssimo — gíria amazônica para algo de má qualidade.", adultTranslation: "Pior / Ruim / Péssimo / Horrível.", context: "Gíria do Amazonas para algo muito ruim ou de péssima qualidade.", category: "expressão", riskLevel: "yellow", safeExample: "Esse filme foi virote!", contextNotes: "Gíria amazônica. Pode ser usado de forma leve entre amigos. Pode ser ofensivo se direcionado a uma pessoa.", origin: "Cultura amazônica, origem incerta.", variations: ["virote mesmo", "é virote"], popularityStatus: "regional", region: "AM" },
  { term: "maloco (AM)", meaning: "Doido, maluco, pessoa excêntrica — gíria amazônica.", adultTranslation: "Doido / Maluco / Excêntrico / Louco.", context: "Gíria do Amazonas para descrever alguém doido ou que faz coisas diferentes.", category: "expressão", riskLevel: "yellow", safeExample: "Esse cara é maloco, faz umas coisas!", contextNotes: "Variação amazônica de 'maluco'. Pode ser carinhoso ou depreciativo dependendo do tom.", origin: "Cultura amazônica, variação de 'maluco' com sotaque local.", variations: ["maluco", "malocado"], popularityStatus: "regional", region: "AM" },

  // ===========================================================================
  // PARÁ (PA) — Paraense
  // ===========================================================================
  { term: "paraense", meaning: "Pessoa do estado do Pará — gentílico com orgulho.", adultTranslation: "Natural do Pará / Do estado do Pará.", context: "Gentílico usado com orgulho pelos moradores do Pará.", category: "regional", riskLevel: "green", safeExample: "Sou paraense e tenho orgulho da minha cultura!", contextNotes: "Gentílico cultural. Usado com muito orgulho. Inofensivo.", origin: "Cultura paraense, do estado do Pará na região Norte.", variations: ["paraense lindo", "paraense feliz"], popularityStatus: "regional", region: "PA" },
  { term: "marajó", meaning: "Referência à Ilha do Marajó, maior ilha fluvial do mundo — orgulho paraense.", adultTranslation: "Da Ilha do Marajó / Natural do Marajó.", context: "Referência cultural à Ilha do Marajó, no Pará, famosa pelo açaí e pela cultura ribeirinha.", category: "regional", riskLevel: "green", safeExample: "O açaí do Marajó é o melhor do Brasil!", contextNotes: "Referência cultural rica. O Marajó é um símbolo do Pará. Inofensivo e cultural.", origin: "Ilha do Marajó, no estado do Pará — maior ilha fluvial do mundo.", variations: ["marajoara", "do Marajó"], popularityStatus: "regional", region: "PA" },
  { term: "mangue (PA)", meaning: "Manguezal, área de natureza — referência cultural ao ecossistema paraense.", adultTranslation: "Manguezal / Área de preservação / Natureza.", context: "No Pará, 'mangue' é referência ao ecossistema costeiro e à cultura ribeirinha.", category: "regional", riskLevel: "green", safeExample: "Fomos passear no mangue no fim de semana.", contextNotes: "Referência cultural e ecológica do Pará. Inofensiva.", origin: "Ecossistema manguezal, muito presente na costa paraense.", variations: ["manguezal", "ir pro mangue"], popularityStatus: "regional", region: "PA" },

  // ===========================================================================
  // NORDESTE GERAL
  // ===========================================================================
  { term: "arrasta-pé", meaning: "Festa nordestina com forró e piseiro, ou evento musical animado.", adultTranslation: "Festa nordestina / Forró / Baile animado.", context: "No Nordeste, festa típica com forró, piseiro e outras músicas regionais.", category: "regional", riskLevel: "green", safeExample: "Bora no arrasta-pé que o piseiro tá bom!", contextNotes: "Evento cultural nordestino. Totalmente inofensivo e divertido.", origin: "Cultura nordestina, festa com forró e música regional.", variations: ["arrasta", "forró", "piseiro"], popularityStatus: "ativo", region: "Nordeste" },
  { term: "piseiro", meaning: "Estilo musical nordestino que mistura forró, brega e pop — muito popular entre jovens.", adultTranslation: "Estilo musical nordestino / Ritmo dançante.", context: "Gênero musical que mistura forró eletrônico, brega e pop. Muito popular entre jovens do Nordeste.", category: "regional", riskLevel: "green", safeExample: "Essa música de piseiro tá tocando em todo lugar!", contextNotes: "Gênero musical genuinamente nordestino, muito popular entre adolescentes. Totalmente positivo e cultural.", origin: "Cultura musical nordestina, popularizado por artistas como Barões da Pisadinha nos anos 2020.", variations: ["pisadinha", "piseiro bom"], popularityStatus: "ativo", region: "Nordeste" },
  { term: "mandei", meaning: "Enviei, já mandei — forma baiana/nordestina de dizer 'enviei'.", adultTranslation: "Enviei / Já mandei / Já foi enviado.", context: "Forma comum no Nordeste de dizer que algo foi enviado (mensagem, foto, documento).", category: "expressão", riskLevel: "green", safeExample: "Já mandei a foto no grupo.", contextNotes: "Forma coloquial nordestina. Totalmente inofensiva.", origin: "Fala coloquial nordestina, uso de 'mandei' para 'enviei'.", variations: ["mandeja", "já mandei"], popularityStatus: "ativo", region: "Nordeste" },
  { term: "axé", meaning: "Cultura baiana, energia positiva, ou saudação de origem africana.", adultTranslation: "Energia positiva / Cultura baiana / Força vital.", context: "Referência à cultura baiana e afro-brasileira. Pode ser saudação ou referência cultural.", category: "regional", riskLevel: "green", safeExample: "Sentindo o axé no Carnaval!", contextNotes: "Conceito cultural de origem africana (iorubá), muito presente na Bahia. Totalmente positivo.", origin: "Cultura afro-baiana, do iorubá 'axé' (força vital / energia).", variations: ["energia axé", "axé bahia"], popularityStatus: "ativo", region: "BA" },

  // ===========================================================================
  // SUL GERAL
  // ===========================================================================
  { term: "piá", meaning: "Menino, garoto — termo do Sul para menino, também usado em SP interior.", adultTranslation: "Menino / Garoto / Moço.", context: "Termo do Sul do Brasil para se referir a um menino ou garoto.", category: "regional", riskLevel: "green", safeExample: "Esse piá é muito estudioso!", contextNotes: "Termo cultural do Sul. Carinhoso e inofensivo.", origin: "Cultura gaúcha e paranaense, possivelmente de origem indígena.", variations: ["piá", "piázano"], popularityStatus: "regional", region: "Sul" },
  { term: "nhái", meaning: "Interjeição paranaense de espanto, ênfase ou chamado.", adultTranslation: "Nossa! / Ei! / Expressão de espanto.", context: "Interjeição típica do Paraná, similar a 'eita' ou 'caramba'.", category: "expressão", riskLevel: "green", safeExample: "Nhái, que calor tá fazendo!", contextNotes: "Expressão cultural do Paraná. Pode soar estranho para quem não é do Sul, mas é inofensiva.", origin: "Cultura paranaense, possivelmente de origem indígena ou influência gaúcha.", variations: ["nhái meu filho", "nhái papai"], popularityStatus: "regional", region: "PR" },

  // ===========================================================================
  // TERMOS REGIONAIS ESPALHADOS / DIFERENTES ESTADOS
  // ===========================================================================
  { term: "belezoca", meaning: "Beleza de verdade, tudo ótimo — expressão paulista reforçada.", adultTranslation: "Tudo ótimo / Perfeito / Muito bem.", context: "Versão intensificada de 'beleza', muito usada em São Paulo.", category: "elogio", riskLevel: "green", safeExample: "Tudo belezoca por aqui!", contextNotes: "Gíria regional de São Paulo. Versão intensificada de 'beleza'. Inofensiva.", origin: "Gíria paulista, variação de 'beleza' com sufixo '-oca'.", variations: ["belezura", "beleza pura"], popularityStatus: "regional", region: "SP" },
  { term: "cifra", meaning: "Bilhete com gabarito, cola — termo escolar paulista.", adultTranslation: "Bilhete com gabarito / Cola / Informação secreta.", context: "No ambiente escolar, bilhete com respostas. Comum entre estudantes de SP.", category: "escola", riskLevel: "yellow", safeExample: "Passa a cifra da prova pra mim!", contextNotes: "Termo escolar para 'cola'. Orientar sobre honestidade acadêmica, mas é gíria estudantil comum.", origin: "Cultura estudantil brasileira, especialmente forte em São Paulo.", variations: ["bilhete", "cola", "caba"], popularityStatus: "ativo", region: "SP" },
  { term: "néia", meaning: "Né mesmo, não é mesmo? — expressão carioca de concordância.", adultTranslation: "Não é mesmo? / Concordo / Pois é.", context: "Expressão de concordância muito comum no Rio de Janeiro.", category: "expressão", riskLevel: "green", safeExample: "Tá calor pra caramba, néia?", contextNotes: "Variação carioca de 'né'. Inofensiva e cultural.", origin: "Cultura carioca, variação fonética de 'né'.", variations: ["né", "néia mesmo"], popularityStatus: "regional", region: "RJ" },
  { term: "cumpadi", meaning: "Compadre, amigo próximo — muito usado em Minas Gerais.", adultTranslation: "Compadre / Amigo próximo / Parceiro.", context: "Vocativo afetuoso muito usado em Minas Gerais entre amigos.", category: "saudacao", riskLevel: "green", safeExample: "E aí cumpadi, tudo bem?", contextNotes: "Termo cultural de Minas Gerais. Indica proximidade e amizade. Inofensivo.", origin: "Cultura mineira, de 'compadre' (relação de padrinho).", variations: ["compadri", "cumpadi meu"], popularityStatus: "regional", region: "MG" },
  { term: "trem bão", meaning: "Coisa boa, algo de qualidade — expressão mineira.", adultTranslation: "Coisa boa / Algo excelente / Qualidade.", context: "Expressão mineira onde 'trem' significa 'coisa'. 'Trem bão' = coisa boa.", category: "elogio", riskLevel: "green", safeExample: "Esse doce é trem bão!", contextNotes: "Expressão cultural de Minas Gerais. Totalmente inofensiva e culturalmente rica.", origin: "Cultura mineira, 'trem' = 'coisa' e 'bão' = 'bom'.", variations: ["trem bom", "é trem bão"], popularityStatus: "regional", region: "MG" },
  { term: "bão", meaning: "Bom — pronúncia mineira característica com nasalização.", adultTranslation: "Bom / Muito bom.", context: "Forma mineira de dizer 'bom', com nasalização típica do sotaque mineiro.", category: "elogio", riskLevel: "green", safeExample: "Tá bão, pode ir!", contextNotes: "Forma regional de falar de Minas Gerais. Inofensiva.", origin: "Dialeto mineiro, pronúncia nasalada de 'bom'.", variations: ["bom", "tá bão", "é bão"], popularityStatus: "regional", region: "MG" },
  { term: "manauara", meaning: "Pessoa de Manaus — gentílico usado com orgulho.", adultTranslation: "Manauense / De Manaus / Do Amazonas.", context: "Gentílico de Manaus, usado com orgulho pelos moradores.", category: "regional", riskLevel: "green", safeExample: "Esse mano é manauara!", contextNotes: "Gentílico cultural. Usado com muito orgulho. Inofensivo.", origin: "Cultura amazônica, de Manaus.", variations: ["manauara", "manauense"], popularityStatus: "regional", region: "AM" },
  { term: "cearense way", meaning: "Jeito cearense de ser, estilo de vida do Ceará.", adultTranslation: "Jeito cearense / Estilo de vida / Vibes do Ceará.", context: "Expressão que descreve o estilo descontraído e acolhedor do povo cearense.", category: "regional", riskLevel: "green", safeExample: "Tô no cearense way hoje, só relaxar!", contextNotes: "Expressão cultural positiva, mistura de português com inglês. Totalmente inofensiva.", origin: "Cultura cearense, popularizada nas redes sociais por jovens do Ceará.", variations: ["cearense", "ceara way"], popularityStatus: "regional", region: "CE" },
  { term: "sô", meaning: "Interjeição baiana de chamado, equivalente a 'ei' ou 'psiu'.", adultTranslation: "Ei / Oi / Chamado atencioso.", context: "Interjeição típica da Bahia para chamar a atenção de alguém.", category: "saudacao", riskLevel: "green", safeExample: "Sô, me explica isso aí!", contextNotes: "Interjeição cultural baiana. É apenas um chamado carinhoso, não é desrespeitoso. Inofensiva.", origin: "Cultura baiana, de origem africana.", variations: ["sô boy", "sô lindo"], popularityStatus: "regional", region: "BA" },
  { term: "pé de moleque", meaning: "Doce típico do Nordeste de amendoim com rapadura, ou criança levada.", adultTranslation: "Doce de amendoim / Criança bagunceira.", context: "Pode ser o doce típico ou se referir a uma criança levada, dependendo do contexto.", category: "regional", riskLevel: "green", safeExample: "Comi um pé de moleque na feira!", contextNotes: "Pode ser doce ou referência a criança. Se usado para criança, pode ser carinhoso ou leve.", origin: "Cultura nordestina, doce tradicional de amendoim e rapadura.", variations: ["pé de moleque doce", "moleque"], popularityStatus: "regional", region: "Nordeste" },
  { term: "rapadura", meaning: "Doce de açúcar típico do Nordeste, ou dinheiro em gíria.", adultTranslation: "Doce típico / Dinheiro / Coisa dura.", context: "No Nordeste, doce típico. Na gíria jovem, pode significar dinheiro.", category: "regional", riskLevel: "green", safeExample: "Comi rapadura com café, vida boa!", contextNotes: "Alimento cultural nordestino. Inofensivo e delicioso.", origin: "Cultura alimentar nordestina, doce de cana-de-açúcar.", variations: ["rapadura doce", "rapadura com café"], popularityStatus: "regional", region: "Nordeste" },
  { term: "caipira", meaning: "Pessoa do interior, do campo — pode ser carinhoso ou pejorativo.", adultTranslation: "Pessoa do interior / Do campo / Sertanejo.", context: "Refere-se a pessoa do interior. Pode ser usado com carinho ou de forma preconceituosa.", category: "regional", riskLevel: "yellow", safeExample: "Adoro a cultura caipira de São Paulo.", contextNotes: "Se usado com carinho, é positivo. Se usado como xingamento, pode ser preconceituoso contra pessoas do interior. Orientar sobre respeito.", origin: "Cultura rural brasileira, especialmente forte em SP, MG e GO.", variations: ["caipirinha", "cultura caipira"], popularityStatus: "regional", region: "SP, MG" },
  { term: "vapo", meaning: "Ir embora, sair de perto — gíria jovem nacional com origem no funk.", adultTranslation: "Ir embora / Sair / Dar o cano.", context: "Gíria para dizer que vai sair ou que alguém se mandou.", category: "expressão", riskLevel: "yellow", safeExample: "Ele vapou da festa sem avisar.", contextNotes: "Gíria que significa ir embora ou dar o cano. Pode gerar frustração se a pessoa foi 'vapada'.", origin: "Cultura funk jovem brasileira, possivelmente de 'evaporar'.", variations: ["vapor", "vapou", "dar vapo"], popularityStatus: "ativo", region: "Brasil" },
  { term: "demorou", meaning: "Combinado, confirmado, entendi — expressão de confirmação.", adultTranslation: "Combinado / Entendido / Confirmado.", context: "Expressão para confirmar um combinado ou dizer que entendeu.", category: "saudacao", riskLevel: "green", safeExample: "— Nos vemos amanhã às 8h. — Demorou!", contextNotes: "Expressão jovem de confirmação. Pode soar estranho para quem não conhece, mas é positiva.", origin: "Possivelmente originada no Rio de Janeiro, mas hoje é usada em todo o Brasil.", variations: ["demorô", "demorou mesmo"], popularityStatus: "ativo", region: "RJ" },
  { term: "enrolation", meaning: "Enrolação, ato de enrolar, demorar para fazer algo.", adultTranslation: "Enrolação / Demora / Ficar enrolando.", context: "Palavra misturando português com sufixo inglês que significa enrolar.", category: "zoeira", riskLevel: "green", safeExample: "Para de enrolation e vem já!", contextNotes: "Mistura de 'enrolar' com sufixo inglês '-tion'. Comum entre adolescentes paulistas. Inofensivo.", origin: "Gíria jovem paulista, mistura de português com inglês.", variations: ["enrolação", "enrolar"], popularityStatus: "ativo", region: "SP" },
  { term: "cifrao", meaning: "Dinheiro, grana — gíria jovem para dinheiro.", adultTranslation: "Dinheiro / Grana / Quantia em dinheiro.", context: "Gíria jovem para falar de dinheiro, especialmente em quantias maiores.", category: "dinheiro", riskLevel: "green", safeExample: "Preciso de mais cifrão pra comprar isso.", contextNotes: "Referência ao símbolo R$ (cifrão). Inofensivo.", origin: "Cultura jovem brasileira, referência ao símbolo monetário.", variations: ["cifrão", "grana", "dinheiro"], popularityStatus: "ativo", region: "Brasil" },
  { term: "seca (RS)", meaning: "Fome extrema, estar morrendo de fome — gíria gaúcha.", adultTranslation: "Fome extrema / Morrendo de fome / Estômago roncando.", context: "No Rio Grande do Sul, 'seca' é fome extrema. Diferente do resto do Brasil onde pode significar 'segurança'.", category: "expressão", riskLevel: "green", safeExample: "Tô com uma seca danada!", contextNotes: "Uso gaúcho de 'seca' como fome. Contexto regional importante — no RS significa fome, no RJ significa segurança. Inofensivo.", origin: "Cultura gaúcha, uso regional de 'seca' para fome.", variations: ["seca danada", "com seca"], popularityStatus: "regional", region: "RS" },
  { term: "abana", meaning: "Vai embora, sai daqui — gíria baiana/nordestina.", adultTranslation: "Vai embora / Sai daqui / Se manda.", context: "Expressão para mandar alguém embora, geralmente de forma leve.", category: "expressão", riskLevel: "yellow", safeExample: "Abana daqui, menino!", contextNotes: "Pode ser usado de forma leve entre amigos ou de forma mais séria. Observar o tom e o contexto.", origin: "Cultura nordestina/baiana.", variations: ["abana logo", "abana pra lá"], popularityStatus: "regional", region: "BA" },
  { term: "tá joia", meaning: "Tudo ótimo, tudo bem — expressão de positividade nacional.", adultTranslation: "Tudo ótimo / Tudo bem / Perfeito.", context: "Expressão para dizer que está tudo muito bem.", category: "saudacao", riskLevel: "green", safeExample: "— Tudo bem? — Tá joia!", contextNotes: "Expressão muito positiva e comum em todo o Brasil. Totalmente inofensiva.", origin: "Expressão popular brasileira, possivelmente de origem paulista.", variations: ["tá joia?", "joia pura"], popularityStatus: "ativo", region: "SP" },
  { term: "vaiter", meaning: "Vai ter — expressão baiana para dizer que algo vai acontecer.", adultTranslation: "Vai ter / Vai acontecer / Terá.", context: "Forma baiana de dizer 'vai ter'. Muito usada em anúncios de festas e eventos.", category: "expressão", riskLevel: "green", safeExample: "Vaiter festa sábado!", contextNotes: "Forma escrita fonética baiana. Inofensiva e cultural.", origin: "Fonética baiana de 'vai ter', escrita junta.", variations: ["vaiter sim", "vaiter rolê"], popularityStatus: "ativo", region: "BA" },
  { term: "caraminguá", meaning: "Pessoa acolhedora, simpática — referência à cidade paulista.", adultTranslation: "Acolhedor / Simpático / Pessoa boa.", context: "Referência à cidade de Caraminguá/SP, usada como elogio a pessoas simpáticas.", category: "elogio", riskLevel: "green", safeExample: "Você é caraminguá, sempre me ajuda!", contextNotes: "Termo regional paulista, referência à cidade. Positivo e inofensivo.", origin: "Cidade de Caraminguá, interior de São Paulo, conhecida pela hospitalidade.", variations: ["caramingaense"], popularityStatus: "regional", region: "SP (interior)" },
  { term: "massaroca", meaning: "Coisa boa, pessoa legal — gíria nordestina de elogio.", adultTranslation: "Coisa boa / Pessoa legal / Algo de qualidade.", context: "Gíria nordestina para elogiar algo ou alguém de forma carinhosa.", category: "elogio", riskLevel: "green", safeExample: "Esse acarajé é massaroca!", contextNotes: "Termo afetivo nordestino. Totalmente positivo e inofensivo.", origin: "Cultura nordestina, possivelmente de origem africana.", variations: ["massa", "massaroca demais"], popularityStatus: "regional", region: "Nordeste" },
  { term: "macaxeira", meaning: "Mandioca, alimento típico do Nordeste.", adultTranslation: "Mandioca / Comida típica / Aipim.", context: "Alimento típico do Nordeste, muito presente na cultura e culinária regional.", category: "regional", riskLevel: "green", safeExample: "Vou comer macaxeira com carne-de-sol!", contextNotes: "Alimento cultural nordestino. Pode ser usado com orgulho da identidade cultural. Inofensivo.", origin: "Cultura alimentar nordestina brasileira.", variations: ["mandioca", "aipim"], popularityStatus: "regional", region: "Nordeste" },
  { term: "mecar", meaning: "Zoar, provocar, sacanear — gíria paulista.", adultTranslation: "Zoar / Provocar / Sacanear.", context: "Expressão paulista para provocar ou zoar com alguém de forma leve.", category: "zoeira", riskLevel: "yellow", safeExample: "Para de mecar comigo!", contextNotes: "Gíria paulista que significa provocar. Pode ser brincadeira entre amigos ou bullying dependendo da intensidade.", origin: "Gíria tradicional de São Paulo, possivelmente de origem imigrante.", variations: ["mecar na cara", "mecada"], popularityStatus: "regional", region: "SP" },
  { term: "piranha (Norte)", meaning: "Peixe comum na Amazônia, ou gíria para pessoa que fala muito.", adultTranslation: "Peixe amazônico / Pessoa que fala muito / Fofoqueira.", context: "Na Amazônia, principalmente o peixe. Na gíria, pessoa que fala muito ou fofoqueira.", category: "regional", riskLevel: "yellow", safeExample: "Comemos piranha assada no Amazonas!", contextNotes: "ORIENTAÇÃO: No contexto amazônico, é o peixe (inofensivo). Em outras regiões, pode ter conotação sexual negativa. Contexto é fundamental.", origin: "Peixe amazônico / Cultura popular brasileira.", variations: ["piranha frita", "piranheira"], popularityStatus: "regional", region: "AM" },
  { term: "cacetada", meaning: "Surra, pancada — gíria nacional para porrada.", adultTranslation: "Surra / Pancada / Porrada.", context: "Gíria para surra ou pancada. Pode ser literal ou figurado ('tomar uma cacetada na prova').", category: "expressão", riskLevel: "yellow", safeExample: "Tomei uma cacetada na prova de física.", contextNotes: "Pode significar surra literal ou figurado (resultado ruim em prova). Observar contexto para violência.", origin: "Expressão popular brasileira de longa data.", variations: ["cacetada boa", "tomar cacetada"], popularityStatus: "ativo", region: "Brasil" },
  { term: "fofoca", meaning: "Intriga, fofoca, mexerico — muito comum entre adolescentes.", adultTranslation: "Fofoca / Intriga / Mexerico / Rumor.", context: "Conversa sobre a vida dos outros, muito comum entre adolescentes em qualquer estado.", category: "expressão", riskLevel: "yellow", safeExample: "Tem fofoca nova no grupo de WhatsApp!", contextNotes: "Fofoca é natural entre adolescentes, mas pode envolver bullying se for maliciosa. Orientar sobre respeito.", origin: "Cultura social brasileira, presente em todas as regiões.", variations: ["fofocar", "fofoqueiro", "fofoca boa"], popularityStatus: "ativo", region: "Brasil" },
  { term: "puxa o saco", meaning: "Adular, bajular alguém para ganhar vantagem.", adultTranslation: "Adular / Bajular / Puxassaco.", context: "Crítica a alguém que tenta agradar excessivamente para ganhar vantagem.", category: "expressão", riskLevel: "yellow", safeExample: "Para de puxar o saco do professor!", contextNotes: "Expressão crítica à adulação. Pode ser ofensiva se usada de forma agressiva.", origin: "Expressão popular brasileira de longa data.", variations: ["puxa-saco", "bajulador"], popularityStatus: "ativo", region: "Brasil" },
  { term: "e aí?", meaning: "Saudação universal brasileira — equivalente a 'tudo bem?' ou 'how are you?'.", adultTranslation: "Tudo bem? / Como vai? / Qual é a boa?", context: "A saudação mais universal do Brasil, usada em todos os estados.", category: "saudacao", riskLevel: "green", safeExample: "E aí? Tudo bem com você?", contextNotes: "Saudação universal brasileira. Totalmente inofensiva e amigável.", origin: "Expressão de longa data na língua portuguesa brasileira.", variations: ["e ai", "eaí", "eai"], popularityStatus: "ativo", region: "Brasil" },
  { term: "belezura", meaning: "Beleza, tudo ótimo — expressão positiva nacional.", adultTranslation: "Tudo ótimo / Beleza / Tudo certo.", context: "Expressão para confirmar que está tudo bem ou que algo é ótimo.", category: "saudacao", riskLevel: "green", safeExample: "— A gente se vê às 15h? — Belezura!", contextNotes: "Expressão muito positiva, usada em todo o Brasil. Inofensiva.", origin: "Expressão popular brasileira, derivação de 'beleza'.", variations: ["beleza", "belezoca", "belezura pura"], popularityStatus: "ativo", region: "Brasil" },
  { term: "feijoada", meaning: "Prato típico brasileiro — referência cultural e gastronômica.", adultTranslation: "Prato típico brasileiro / Comida nacional.", context: "Referência ao prato mais icônico da culinária brasileira.", category: "regional", riskLevel: "green", safeExample: "No sábado teve feijoada na casa da vó!", contextNotes: "Referência cultural e gastronômica brasileira. Pode ser usada como símbolo de identidade nacional. Inofensiva.", origin: "Culinária brasileira, prato de origem afro-brasileira (Rio de Janeiro).", variations: ["feijoada completa", "feijoada de sábado"], popularityStatus: "ativo", region: "RJ" },
  { term: "tapioca", meaning: "Comida típica do Nordeste, massa de farinha de mandioca.", adultTranslation: "Comida típica nordestina / Massa de mandioca.", context: "Comida típica do Nordeste, muito popular em todo o Brasil.", category: "regional", riskLevel: "green", safeExample: "Comi uma tapioca com queijo no café da manhã!", contextNotes: "Comida cultural nordestina que se espalhou pelo Brasil. Totalmente inofensiva e cultural.", origin: "Cultura alimentar nordestina, especialmente forte no RN e PB.", variations: ["tapioca recheada", "beiju"], popularityStatus: "ativo", region: "Nordeste" },
  { term: "acarajé", meaning: "Comida típica da Bahia, bolinho de feijão-fradinho frito no azeite de dendê.", adultTranslation: "Comida típica baiana / Bolinho frito.", context: "Comida icônica da Bahia, vendida nas ruas por baianas de acarajé.", category: "regional", riskLevel: "green", safeExample: "Comi um acarajé na festa de Yemanjá!", contextNotes: "Comida cultural da Bahia, de origem afro-brasileira. Símbolo da identidade baiana. Inofensiva.", origin: "Cultura afro-baiana, de origem iorubá.", variations: ["acarajé com vatapá", "abará"], popularityStatus: "ativo", region: "BA" },
  { term: "vaqueiro", meaning: "Profissional do sertão nordestino que cuida do gado.", adultTranslation: "Profissional do sertão / Condutor de gado / Peão.", context: "Figura cultural do sertão nordestino, especialmente forte no Ceará.", category: "regional", riskLevel: "green", safeExample: "Meu tio é vaqueiro no sertão do Ceará.", contextNotes: "Profissão cultural e tradicional do sertão. Usado com orgulho. Inofensivo.", origin: "Cultura sertaneja nordestina, tradição de séculos.", variations: ["vaquejada", "vaqueiro nordestino"], popularityStatus: "regional", region: "CE" },
  { term: "paletó", meaning: "Jaqueta, casaco — gíria nacional para jaqueta.", adultTranslation: "Jaqueta / Casaco / Blazer.", context: "Gíria para se referir a jaqueta ou casaco. Muito usada no Sul.", category: "regional", riskLevel: "green", safeExample: "Tá frio, bota o paletó!", contextNotes: "Gíria comum para jaqueta. Inofensiva.", origin: "Uso popular de 'paletó' para se referir a qualquer casaco.", variations: ["jaqueta", "casaco"], popularityStatus: "ativo", region: "Sul" },
  { term: "pior que tô nem aí", meaning: "Não me importo, não estou nem aí — expressão de descaso.", adultTranslation: "Não me importo / Não estou nem aí / Descaso.", context: "Expressão para dizer que não se importa com algo.", category: "expressão", riskLevel: "green", safeExample: "Pior que tô nem aí pro que ele falou.", contextNotes: "Expressão de indiferença. Pode ser saudável (limites) ou preocupante (desapego excessivo). Inofensiva na maioria dos casos.", origin: "Expressão popular brasileira, de uso generalizado.", variations: ["tô nem aí", "nem aí"], popularityStatus: "ativo", region: "Brasil" },
  { term: "vixi", meaning: "Interjeição de surpresa ou preocupação — variação de 'vixe'.", adultTranslation: "Nossa! / Puxa! / Surpresa / Preocupação.", context: "Variação de 'vixe', interjeição de espanto.", category: "expressão", riskLevel: "green", safeExample: "Vixi, esqueci a mochila!", contextNotes: "Variação comum de 'vixe'. Inofensiva.", origin: "Variação de 'vixe', possivelmente de 'virgem maria'.", variations: ["vixe", "vixi maria"], popularityStatus: "ativo", region: "MG, Nordeste" },
  { term: "tô nem aí", meaning: "Não estou nem aí, não me importo — expressão de indiferença.", adultTranslation: "Não me importo / Não estou preocupado / Indiferença.", context: "Expressão de descaso ou indiferença diante de algo.", category: "expressão", riskLevel: "green", safeExample: "Tô nem aí pra opinião dos outros.", contextNotes: "Pode demonstrar autoconfiança (limites saudáveis) ou apatia. Inofensiva na maioria dos casos.", origin: "Expressão popular brasileira.", variations: ["nem aí", "não tô nem aí"], popularityStatus: "ativo", region: "Brasil" },
  { term: "cortejada", meaning: "Festa comunitária no interior do Nordeste, com comida e música.", adultTranslation: "Festa comunitária / Festa de interior / Celebração.", context: "No interior do Nordeste, festa comunitária onde as pessoas se reúnem.", category: "regional", riskLevel: "green", safeExample: "No fim de semana tem cortejada no sítio!", contextNotes: "Tradição cultural do interior do Nordeste. Totalmente inofensiva e cultural.", origin: "Cultura sertaneja nordestina, tradição comunitária.", variations: ["cortejo", "festa de cortejada"], popularityStatus: "regional", region: "Nordeste" },
  { term: "carroça", meaning: "Carro velho, mala — gíria para carro em péssimo estado.", adultTranslation: "Carro velho / Carro ruim / Sucata.", context: "Gíria para carro muito velho ou em mau estado.", category: "expressão", riskLevel: "yellow", safeExample: "Aquele carro é uma carroça!", contextNotes: "Pode ser brincadeira entre amigos ou provocação se for sobre o carro de alguém. Observar contexto.", origin: "Gíria popular brasileira para veículos velhos.", variations: ["carroça mesmo", "tanque de guerra"], popularityStatus: "ativo", region: "Brasil" },
  { term: "jacaré", meaning: "Animal comum no Pantanal e Norte — também gíria para pessoa mentirosa.", adultTranslation: "Animal (jacaré) / Pessoa mentirosa / Falso.", context: "No contexto literal, o animal. Na gíria, pessoa falsa ou mentirosa.", category: "expressão", riskLevel: "yellow", safeExample: "Esse cara é jacaré, não acredita em nada!", contextNotes: "Na gíria, 'jacaré' = mentiroso. Pode ser ofensivo se direcionado a alguém. Observar contexto.", origin: "Cultura popular brasileira, especialmente do Norte/Nordeste.", variations: ["jacaré de papo amarelo", "fazendo jacaré"], popularityStatus: "regional", region: "Norte, Nordeste" },
  { term: "demoro", meaning: "Confirmação, combinado — variação de 'demorou' muito usada no RJ.", adultTranslation: "Combinado / Entendido / Confirmado / Valeu.", context: "Forma de confirmar um combinado ou agradecer por algo. Muito usado no Rio.", category: "saudacao", riskLevel: "green", safeExample: "— Vou te buscar às 17h. — Demoro!", contextNotes: "Variação de 'demorou'. Expressão jovem de confirmação, especialmente no Rio. Inofensiva.", origin: "Cultura carioca, variação de 'demorou'.", variations: ["demorou", "demorô"], popularityStatus: "ativo", region: "RJ" },
  { term: "pra frente", meaning: "Vai em frente, continue, vamos — expressão de encorajamento nacional.", adultTranslation: "Vai em frente / Continue / Bora.", context: "Expressão de incentivo e encorajamento, usada em todo o Brasil.", category: "expressão", riskLevel: "green", safeExample: "Pra frente, não desiste agora!", contextNotes: "Expressão muito positiva e motivacional. Totalmente inofensiva.", origin: "Expressão popular brasileira de uso generalizado.", variations: ["pra frente que é pra frente", "bora pra frente"], popularityStatus: "ativo", region: "Brasil" },
  { term: "sicrano", meaning: "Fulano, qualquer pessoa — pronome genérico para alguém cujo nome não se lembra.", adultTranslation: "Fulano / Tal pessoa / Qualquer pessoa.", context: "Pronome genérico para uma pessoa cujo nome não se recorda ou que não quer mencionar.", category: "expressão", riskLevel: "green", safeExample: "Aquele sicrano lá da escola veio falar comigo.", contextNotes: "Expressão clássica da língua portuguesa, acompanhada de 'fulano' e 'beltrano'. Inofensiva.", origin: "Expressão tradicional da língua portuguesa.", variations: ["fulano", "beltrano", "fulano de tal"], popularityStatus: "ativo", region: "Brasil" },
  { term: "tchurma", meaning: "Grupo de amigos, turma, galera — termo de amizade.", adultTranslation: "Grupo de amigos / Turma / Galera / Equipe.", context: "Referência ao grupo de amigos ou pessoas que andam juntas.", category: "saudacao", riskLevel: "green", safeExample: "Minha tchurma toda vai na festa!", contextNotes: "Termo carinhoso para grupo de amigos. Totalmente positivo e inofensivo.", origin: "Expressão popular brasileira, possivelmente de origem indígena.", variations: ["turma", "galera", "tchurminha"], popularityStatus: "ativo", region: "Brasil" },
  { term: "morto", meaning: "Muito bom, incrível — gíria adolescente para elogiar algo excelente.", adultTranslation: "Muito bom / Incrível / Absurdo de bom.", context: "Usado como superlativo positivo entre adolescentes, especialmente no funk e cultura urbana.", category: "elogio", riskLevel: "yellow", safeExample: "Essa música é morto!", contextNotes: "Uso adolescente como superlativo. Embora 'morto' pareça negativo, entre adolescentes é elogio. Pode confundir adultos. Orientar sobre contexto.", origin: "Cultura funk e jovem brasileira, uso irônico como superlativo positivo.", variations: ["é morto", "morto demais"], popularityStatus: "ativo", region: "SP, RJ" },
  { term: "cabra macho", meaning: "Homem valente, corajoso, pessoa forte — expressão nordestina de respeito.", adultTranslation: "Homem valente / Corajoso / Pessoa forte.", context: "Elogio nordestino para um homem corajoso e trabalhador.", category: "elogio", riskLevel: "green", safeExample: "Meu pai é cabra macho, trabalha o dia inteiro!", contextNotes: "Expressão cultural do Nordeste, de muito respeito. Totalmente positiva.", origin: "Cultura sertaneja nordestina, referência ao cabra (bode) como símbolo de força.", variations: ["cabra da peste", "cabra bom"], popularityStatus: "regional", region: "Nordeste" },
  { term: "felicidade", meaning: "Expressão de demonstração de alegria — 'tô na felicidade'.", adultTranslation: "Muito feliz / Alegria total / Momento bom.", context: "Usado por adolescentes quando algo muito bom acontece: 'tô na felicidade'.", category: "elogio", riskLevel: "green", safeExample: "Passei na prova, tô na felicidade!", contextNotes: "Expressão genuína de alegria entre adolescentes. Totalmente positiva e inofensiva.", origin: "Expressão popular brasileira, popularizada em memes e redes sociais.", variations: ["tô na felicidade", "pura felicidade"], popularityStatus: "ativo", region: "Brasil" },
  { term: "saudade", meaning: "Sentimento de falta de alguém ou algo — palavra praticamente intraduzível.", adultTranslation: "Sentimento de falta / Nostalgia / Saudade.", context: "Um dos sentimentos mais brasileiros, muito forte especialmente no Nordeste e cultura nordestina.", category: "expressão", riskLevel: "green", safeExample: "Tenho saudade da época do colégio.", contextNotes: "Sentimento genuíno e positivo. Pode indicar apego saudável ou tristeza leve. Parte da identidade brasileira.", origin: "Palavra portuguesa de origem latina, muito forte na cultura brasileira e nordestina.", variations: ["saudade demais", "matar saudade"], popularityStatus: "ativo", region: "Nordeste, Brasil" },
  { term: "bicho (PE)", meaning: "Interjeição pernambucana de espanto — 'bicho, que cena!'.", adultTranslation: "Nossa! / Caramba! / Espanto.", context: "Interjeição muito comum em Pernambuco para expressar surpresa.", category: "expressão", riskLevel: "green", safeExample: "Bicho, que calor em Recife!", contextNotes: "Uso pernambucano de 'bicho' como interjeição, similar ao SP e MG. Inofensivo.", origin: "Expressão pernambucana, uso interjetivo de 'bicho'.", variations: ["bicho!", "ah bicho"], popularityStatus: "ativo", region: "PE" },
  { term: "menino (PE)", meaning: "Garoto, amigo — vocativo pernambucano para um jovem.", adultTranslation: "Garoto / Rapaz / Amigo.", context: "Vocativo usado em Pernambuco para se referir a um menino ou amigo jovem.", category: "saudacao", riskLevel: "green", safeExample: "E aí menino, tudo certo?", contextNotes: "Vocativo cultural pernambucano. Carinhoso e informal. Inofensivo.", origin: "Cultura pernambucana, uso de 'menino' como vocativo amigável.", variations: ["menina", "menino bom"], popularityStatus: "ativo", region: "PE" },
  { term: "bando de corno", meaning: "Grupo grande, muita gente — expressão nordestina exagerada.", adultTranslation: "Grupo grande / Muita gente / Montão de pessoas.", context: "Expressão exagerada do Nordeste para dizer que tem muita gente em um lugar.", category: "expressão", riskLevel: "yellow", safeExample: "Tinha bando de corno na festa ontem!", contextNotes: "ATENÇÃO: Embora seja uma expressão popular no Nordeste, contém uma palavra vulgar ('corno'). Orientar sobre linguagem adequada em contexto escolar.", origin: "Cultura nordestina, expressão exagerada e coloquial.", variations: ["bando de gente", "monte de gente"], popularityStatus: "regional", region: "Nordeste" },
  { term: "vaquejada", meaning: "Festa nordestina com competição de laço, evento cultural do sertão.", adultTranslation: "Evento cultural nordestino / Competição de laço / Festa sertaneja.", context: "Tradição cultural do Nordeste, especialmente forte no Ceará e Paraíba.", category: "regional", riskLevel: "green", safeExample: "No feriado foi vaquejada no sertão!", contextNotes: "Evento cultural importante do Nordeste. Totalmente inofensivo e cultural.", origin: "Cultura sertaneja nordestina, tradição de séculos.", variations: ["vaquejada 2024", "festa de vaquejada"], popularityStatus: "ativo", region: "CE, PB" },
  { term: "pipa (CE)", meaning: "Pipa, papagaio de papel — brincadeira tradicional muito forte no Nordeste.", adultTranslation: "Pipa / Papagaio de papel / Brinquedo voador.", context: "Brincadeira tradicional muito popular no Ceará e Nordeste, especialmente em época de ventos.", category: "regional", riskLevel: "green", safeExample: "Vou empinar pipa no parque!", contextNotes: "Brincadeira cultural nordestina, muito forte no Ceará. Totalmente inofensiva e divertida.", origin: "Cultura nordestina, tradição de empinar pipas que passa de geração em geração.", variations: ["pipão", "papagaio", "raia de pipa"], popularityStatus: "ativo", region: "CE, Nordeste" },
  { term: "doido (PA)", meaning: "Maluco, pessoa doida — gíria paraense para alguém excêntrico.", adultTranslation: "Maluco / Doido / Excêntrico / Louco.", context: "Gíria do Pará para descrever alguém que faz coisas diferentes ou engraçadas.", category: "expressão", riskLevel: "green", safeExample: "Esse cara é doido, faz umas piadas incríveis!", contextNotes: "Uso paraense de 'doido'. Geralmente é carinhoso e leve. Inofensivo.", origin: "Gíria popular do Pará, uso de 'doido' como adjetivo informal.", variations: ["doido demais", "doidera"], popularityStatus: "ativo", region: "PA" },
  { term: "parceiro (AM)", meaning: "Amigo, companheiro — muito usado no Amazonas.", adultTranslation: "Amigo / Companheiro / Parceiro.", context: "Vocativo muito usado no Amazonas para se referir a um amigo.", category: "saudacao", riskLevel: "green", safeExample: "E aí parceiro, tudo beleza?", contextNotes: "Termo amazônico de amizade. Totalmente positivo e carinhoso.", origin: "Cultura amazônica, uso de 'parceiro' como vocativo de amizade.", variations: ["parceiro bom", "parceria"], popularityStatus: "ativo", region: "AM" },
  { term: "bicho (AM)", meaning: "Interjeição amazônica de espanto — 'bicho, que calor!'.", adultTranslation: "Nossa! / Caramba! / Espanto.", context: "Interjeição muito usada no Amazonas para expressar surpresa.", category: "expressão", riskLevel: "green", safeExample: "Bicho, que chuva forte em Manaus!", contextNotes: "Uso amazônico de 'bicho' como interjeição. Inofensivo.", origin: "Expressão popular amazônica, uso interjetivo de 'bicho'.", variations: ["bicho!", "ah bicho"], popularityStatus: "ativo", region: "AM" },
  { term: "açaí (PA)", meaning: "Fruta amazônica icônica, símbolo do Pará — comida cultural.", adultTranslation: "Fruta amazônica / Comida típica do Pará.", context: "Fruta icônica da Amazônia, muito consumida no Pará e em todo o Brasil.", category: "regional", riskLevel: "green", safeExample: "Tomar açaí é tradição no Pará!", contextNotes: "Referência cultural e gastronômica da Amazônia. Totalmente inofensiva e cultural.", origin: "Cultura amazônica, fruta nativa da região, especialmente forte no Pará.", variations: ["açaí na tigela", "açaí paraense"], popularityStatus: "ativo", region: "PA" },
];
