import type { SlangTerm } from './slang-data';

// =============================================================================
// Brazilian Teen & Internet Abbreviation Slang — Extra 18
// Abreviações reais usadas por adolescentes brasileiros em redes sociais
// =============================================================================

export const EXTRA_SLANG_DATA_18: SlangTerm[] = [
  // --- Abreviações Brasileiras Clássicas ---
  {
    term: "pq",
    meaning: "Por que / porque. Abreviação muito comum em mensagens de texto.",
    adultTranslation: "Por que / Porque.",
    context: "Usado em mensagens para perguntar ou explicar algo de forma rápida.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Pq você não veio ontem?",
    contextNotes: "Abreviação extremamente comum em mensagens de texto e WhatsApp. Totalmente inofensiva.",
    origin: "Abreviação de 'porque/por que', surgida com o uso de SMS e mensagens instantâneas no Brasil.",
    variations: ["porque", "por que", "porq"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pqp",
    meaning: "Para/quê/porra. Interjeição de surpresa, raiva ou espanto.",
    adultTranslation: "Expressão de espanto / Interjeição forte.",
    context: "Usado como interjeição de surpresa, raiva ou incredulidade. Variação mais leve de palavrão.",
    category: "abreviação",
    riskLevel: "yellow",
    safeExample: "Pqp, que prova difícil!",
    contextNotes: "Abreviação que pode esconder um palavrão. Na maioria das vezes é usada como expressão de espanto sem intenção ofensiva. Atenção ao contexto.",
    origin: "Abreviação popular de internet, possivelmente de 'puta que pariu' ou 'para/quê/porra'.",
    variations: ["puta que pariu", "pqp"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cmg",
    meaning: "Comigo. Abreviação usada em mensagens para dizer 'comigo'.",
    adultTranslation: "Comigo.",
    context: "Usado em mensagens rápidas para dizer 'comigo' ou perguntar algo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vem cmg!",
    contextNotes: "Abreviação comum no WhatsApp e redes sociais. Significa 'comigo'. Totalmente inofensiva.",
    origin: "Abreviação de 'comigo', popularizada pelo uso de mensagens de texto.",
    variations: ["comigo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ctz",
    meaning: "Certeza. Abreviação usada para afirmar certeza sobre algo.",
    adultTranslation: "Certeza / Com certeza.",
    context: "Usado para afirmar que tem certeza sobre algo, ou concordar enfaticamente.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ctz que o jogo vai ser bom!",
    contextNotes: "Abreviação de 'certeza'. Muito comum em conversas informais entre adolescentes.",
    origin: "Abreviação de 'certeza', popularizada em mensagens de texto e redes sociais.",
    variations: ["certeza", "certeza!"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "aki",
    meaning: "Aqui. Forma abreviada de escrever 'aqui', usando 'k' no lugar de 'qu'.",
    adultTranslation: "Aqui / Neste lugar.",
    context: "Usado em mensagens para indicar localização ou presença.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tô aki esperando.",
    contextNotes: "Abreviação de 'aqui' usando 'k' em vez de 'qu'. Muito comum entre jovens em mensagens de texto.",
    origin: "Abreviação de 'aqui', parte do estilo de escrita informal da internet brasileira.",
    variations: ["aqui"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ngm",
    meaning: "Ninguém. Abreviação para dizer que não há ninguém.",
    adultTranslation: "Ninguém.",
    context: "Usado em mensagens para dizer que não tem ninguém presente.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tá vazio aki, ngm veio.",
    contextNotes: "Abreviação de 'ninguém'. Comum em mensagens rápidas de WhatsApp e grupos.",
    origin: "Abreviação de 'ninguém', popularizada pelo uso de mensagens de texto.",
    variations: ["ninguém", "ngm"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tbm",
    meaning: "Também. Abreviação usada para concordar ou adicionar algo.",
    adultTranslation: "Também / Igualmente.",
    context: "Usado para concordar com alguém ou adicionar uma informação similar.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tbm quero ir!",
    contextNotes: "Abreviação de 'também'. Uma das abreviações mais usadas em português na internet.",
    origin: "Abreviação de 'também', surgida com SMS e popularizada no WhatsApp.",
    variations: ["também", "tb"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mto",
    meaning: "Muito. Abreviação usada para intensificar algo.",
    adultTranslation: "Muito / Bastante.",
    context: "Usado para intensificar uma afirmação ou sentimento.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tá mto bonito!",
    contextNotes: "Abreviação de 'muito'. Extremamente comum em mensagens de texto.",
    origin: "Abreviação de 'muito', popularizada pelo uso de SMS e WhatsApp.",
    variations: ["muito", "mt", "mta"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "wpp",
    meaning: "WhatsApp. Abreviação para o aplicativo de mensagens.",
    adultTranslation: "WhatsApp.",
    context: "Usado para se referir ao WhatsApp, especialmente quando pedindo para enviar mensagem.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me manda no wpp.",
    contextNotes: "Abreviação de 'WhatsApp'. Universalmente compreendida no Brasil. Totalmente inofensiva.",
    origin: "Abreviação de 'WhatsApp', comum na internet brasileira desde o popularização do app.",
    variations: ["whatsapp", "zap", "zapzap"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "zap",
    meaning: "WhatsApp / Mensagem. Usado como sinônimo de mandar mensagem ou o próprio app.",
    adultTranslation: "WhatsApp / Mandar mensagem.",
    context: "Usado como verbo ('me da um zap') ou substantivo para o WhatsApp.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me passa o zap aí.",
    contextNotes: "Diminutivo de WhatsApp. Virou sinônimo de 'mensagem' no Brasil. 'Me dá um zap' = me manda uma mensagem.",
    origin: "Diminutivo de 'WhatsApp', popularizado como verbo e substantivo na cultura digital brasileira.",
    variations: ["zapzap", "wpp", "whatsapp"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bjs",
    meaning: "Beijos. Abreviação usada como despedida carinhosa em mensagens.",
    adultTranslation: "Beijos.",
    context: "Usado no final de mensagens como despedida carinhosa, especialmente entre amigos e familiares.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Bjs, até amanhã!",
    contextNotes: "Abreviação de 'beijos'. Muito comum em mensagens de WhatsApp, especialmente entre mulheres e familiares.",
    origin: "Abreviação de 'beijos', tradicional no Brasil em mensagens de texto.",
    variations: ["beijos", "bj"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "abs",
    meaning: "Abraços. Abreviação usada como despedida amigável em mensagens.",
    adultTranslation: "Abraços.",
    context: "Usado como despedida amigável, geralmente entre amigos e colegas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Abs, boa sorte na prova!",
    contextNotes: "Abreviação de 'abraços'. Comum em mensagens de texto como despedida amigável.",
    origin: "Abreviação de 'abraços', tradicional no Brasil em mensagens de texto.",
    variations: ["abraços", "abç"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "qqr",
    meaning: "Qualquer. Abreviação para dizer 'qualquer' pessoa, coisa ou lugar.",
    adultTranslation: "Qualquer / Qualquer um.",
    context: "Usado para se referir a algo indeterminado ou qualquer pessoa.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Qqr dia serve pra mim.",
    contextNotes: "Abreviação de 'qualquer'. Comum em mensagens rápidas.",
    origin: "Abreviação de 'qualquer', popularizada pelo uso de mensagens de texto.",
    variations: ["qualquer"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "nda",
    meaning: "Nada. Abreviação para dizer que não há nada ou nada aconteceu.",
    adultTranslation: "Nada.",
    context: "Usado para responder que não há problema, nada ocorreu, ou nada a fazer.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Nda, pode deixar.",
    contextNotes: "Abreviação de 'nada'. Comum em mensagens rápidas para dizer que tudo bem.",
    origin: "Abreviação de 'nada', popularizada pelo uso de mensagens de texto.",
    variations: ["nada"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mt",
    meaning: "Muito. Versão ainda mais curta de 'mto'.",
    adultTranslation: "Muito / Bastante.",
    context: "Usado para intensificar algo. Versão mais curta que 'mto'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Mt obrigado pela ajuda!",
    contextNotes: "Abreviação ultra-curta de 'muito'. Comum em tweets e mensagens com limite de caracteres.",
    origin: "Abreviação de 'muito', popularizada pelo Twitter e mensagens de texto.",
    variations: ["muito", "mto", "mta"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "qdo",
    meaning: "Quando. Abreviação para perguntar ou indicar um momento.",
    adultTranslation: "Quando.",
    context: "Usado em perguntas sobre horários ou momentos.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Qdo a gente se encontra?",
    contextNotes: "Abreviação de 'quando'. Muito comum em mensagens de texto e WhatsApp.",
    origin: "Abreviação de 'quando', popularizada pelo uso de mensagens de texto.",
    variations: ["quando"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dsp",
    meaning: "Depois. Abreviação para indicar algo que acontece depois.",
    adultTranslation: "Depois / Mais tarde.",
    context: "Usado para adiar algo ou indicar que vai fazer depois.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "A gente faz dsp.",
    contextNotes: "Abreviação de 'depois'. Comum em mensagens rápidas para combinar horários.",
    origin: "Abreviação de 'depois', popularizada pelo uso de mensagens de texto.",
    variations: ["depois"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "slc",
    meaning: "Sou louco careca. Expressão de espanto ou indignação exagerada.",
    adultTranslation: "Inacreditável / Não posso acreditar.",
    context: "Usado para expressar espanto, indignação ou surpresa de forma cômica.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Slc, que preço absurdo!",
    contextNotes: "Abreviação de 'sou louco careca'. Expressão muito popular entre adolescentes para demonstrar espanto. Não tem relação com saúde mental real.",
    origin: "Abreviação de 'sou louco careca', popularizada no Twitter e redes sociais brasileiras.",
    variations: ["sou louco careca"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "gnt",
    meaning: "Gente. Abreviação usada para se referir a pessoas em geral.",
    adultTranslation: "Gente / Pessoas.",
    context: "Usado para se referir a um grupo de pessoas ou como interjeição.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Gnt, vocês viram isso?",
    contextNotes: "Abreviação de 'gente'. Comum como interjeição ou para se referir a um grupo.",
    origin: "Abreviação de 'gente', popularizada pelo uso de mensagens de texto.",
    variations: ["gente"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "sdd",
    meaning: "Saudade. Abreviação usada para expressar que sente falta de alguém.",
    adultTranslation: "Saudade / Sinto sua falta.",
    context: "Usado para expressar saudade de alguém, especialmente em mensagens afetuosas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Sdd de você, amiga!",
    contextNotes: "Abreviação de 'saudade'. Muito usada entre amigos e casais em mensagens.",
    origin: "Abreviação de 'saudade', popularizada pelo uso de mensagens de texto.",
    variations: ["saudade"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "xau",
    meaning: "Tchau. Forma abreviada de se despedir.",
    adultTranslation: "Tchau / Adeus.",
    context: "Usado como despedida em mensagens de texto.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Xau, até amanhã!",
    contextNotes: "Abreviação de 'tchau'. Muito comum em mensagens de texto e WhatsApp.",
    origin: "Abreviação de 'tchau', adaptada para escrita informal na internet brasileira.",
    variations: ["tchau", "xauzinho"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "eae",
    meaning: "E aí. Abreviação de saudação, forma rápida de perguntar 'como vai?'.",
    adultTranslation: "E aí / Como vai? / Oi.",
    context: "Usado como saudação informal entre amigos.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Eae, tudo bem?",
    contextNotes: "Abreviação de 'e aí'. Uma das saudações mais comuns na internet brasileira.",
    origin: "Abreviação de 'e aí', saudação brasileira adaptada para mensagens de texto.",
    variations: ["e aí", "eaí"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "x9",
    meaning: "Informante / Dedo duro. Pessoa que conta segredos ou delata os outros.",
    adultTranslation: "X9 / Informante / Dedo duro.",
    context: "Usado para se referir a alguém que conta segredos ou revela informações confidenciais.",
    category: "abreviação",
    riskLevel: "yellow",
    safeExample: "Não conta pra ngm, não seja x9!",
    contextNotes: "Termo que remete a 'dedo-duro' ou informante. Pode ser usado de forma cômica entre amigos, mas em contextos sérios pode ser ofensivo. Atenção ao uso.",
    origin: "Do código X9, usado na polícia militar para identificar o informante. Popularizado na cultura brasileira.",
    variations: ["x9", "dedo duro", "informante"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fl",
    meaning: "Filé. Significa que algo é muito bom, excelente, de primeira qualidade.",
    adultTranslation: "Muito bom / Excelente / De primeira.",
    context: "Usado para elogiar algo ou dizer que algo é muito bom.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Esse filme foi filé!",
    contextNotes: "Abreviação de 'filé'. Significa que algo é excelente. Muito comum no Rio de Janeiro, mas usado nacionalmente.",
    origin: "Diminutivo de 'filé', popularizado na cultura carioca e expandido para todo o Brasil.",
    variations: ["filé", "é filé"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tc",
    meaning: "Tudo certo. Abreviação usada para confirmar que está tudo bem.",
    adultTranslation: "Tudo certo / Tudo bem.",
    context: "Usado para confirmar que está tudo bem ou como despedida positiva.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Blz, tc!",
    contextNotes: "Abreviação de 'tudo certo'. Comum como resposta rápida para confirmar que está tudo bem.",
    origin: "Abreviação de 'tudo certo', popularizada em mensagens de texto.",
    variations: ["tudo certo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "rs",
    meaning: "Risadas. Abreviação usada para indicar que algo é engraçado.",
    adultTranslation: "Risadas / Haha.",
    context: "Usado no final de mensagens para indicar humor ou leveza.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Olha o que ele fez rs",
    contextNotes: "Abreviação de 'risos' ou 'risadas'. Usado como indicador de humor em mensagens. Similar ao 'kkk'.",
    origin: "Abreviação de 'risos', tradicional na internet brasileira desde os primórdios dos fóruns e chats.",
    variations: ["rsrs", "rsrsrs", "risos"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },

  // --- Abreviações Teen Populares ---
  {
    term: "pprt",
    meaning: "Pode crer. Expressão de concordância, confiança ou confirmação.",
    adultTranslation: "Pode crer / Pode confiar / Combinado.",
    context: "Usado para concordar com alguém ou confirmar algo. Expressa confiança e cumplicidade.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vai ter rolê hoje? — Pprt, tô dentro!",
    contextNotes: "Abreviação de 'pode crer'. Muito popular entre adolescentes e jovens adultos. Totalmente inofensiva e positiva.",
    origin: "Abreviação de 'pode crer', expressão de longa data na cultura jovem brasileira, adaptada para escrita de internet.",
    variations: ["pode crer", "pode crê"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "nmrl",
    meaning: "Não me recordo. Usado quando alguém não se lembra de algo.",
    adultTranslation: "Não me lembro / Não me recordo.",
    context: "Usado para dizer que não se lembra de algo que foi dito ou feito.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Nmrl o que eu comi ontem.",
    contextNotes: "Abreviação de 'não me recordo'. Muito comum em conversas informais entre adolescentes.",
    origin: "Abreviação de 'não me recordo', popularizada no Twitter e WhatsApp entre jovens brasileiros.",
    variations: ["não me recordo", "nml"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mlk",
    meaning: "Moleque. Usado como sinônimo de cara, amigo, rapaz.",
    adultTranslation: "Cara / Rapaz / Amigo.",
    context: "Usado para se referir a um cara, amigo ou rapaz de forma carinhosa.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Esse mlk é muito engraçado.",
    contextNotes: "Abreviação de 'moleque'. Muito usada no funk e entre jovens como sinônimo de 'cara' ou 'rapaz'. Pode ser usado de forma carinhosa ou de provocação leve.",
    origin: "Abreviação de 'moleque', popularizada pela cultura funk e hip-hop brasileira.",
    variations: ["moleque", "mlkk"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fds",
    meaning: "Fim de semana. Usado para se referir ao fim de semana.",
    adultTranslation: "Fim de semana.",
    context: "Usado para falar sobre planos ou eventos do fim de semana.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Que fds massa!",
    contextNotes: "Abreviação de 'fim de semana'. Universalmente compreendida no Brasil. Inofensiva, mas também pode ser lida como 'filho da...' em contextos de raiva. Verificar tom.",
    origin: "Abreviação de 'fim de semana', popularizada em mensagens de texto e redes sociais.",
    variations: ["fim de semana", "semana"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mds",
    meaning: "Meu Deus. Expressão de espanto, surpresa ou choque.",
    adultTranslation: "Meu Deus / Nossa.",
    context: "Interjeição usada para expressar espanto, surpresa, ou às vezes decepção.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Mds, não acredito que isso aconteceu!",
    contextNotes: "Abreviação de 'meu Deus'. Uma das interjeições mais comuns na internet brasileira. Totalmente inofensiva na maioria dos contextos.",
    origin: "Abreviação de 'meu Deus', popularizada em redes sociais e mensagens de texto.",
    variations: ["meu deus", "mds!", "meu deus do céu"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "obg",
    meaning: "Obrigado/a. Abreviação usada para agradecer.",
    adultTranslation: "Obrigado / Obrigada.",
    context: "Usado para agradecer de forma rápida em mensagens de texto.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Obg pela ajuda!",
    contextNotes: "Abreviação de 'obrigado/obrigada'. Uma das abreviações mais universais em português. Totalmente positiva.",
    origin: "Abreviação de 'obrigado/obrigada', surgida com SMS e popularizada no WhatsApp.",
    variations: ["obrigado", "obrigada", "obgd", "vlw"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tmj",
    meaning: "Tamo junto. Expressão de lealdade, amizade e união.",
    adultTranslation: "Estamos juntos / Sempre juntos / Lealdade.",
    context: "Usado para demonstrar amizade, lealdade e união entre amigos. Também usado como 'tamo junto, Jesus' em contexto religioso.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Amigo pra sempre, tmj!",
    contextNotes: "Abreviação de 'tamo junto'. Expressão de forte amizade e lealdade. Muito popular entre adolescentes e jovens.",
    origin: "Abreviação de 'tamo junto', popularizada pela cultura funk e hip-hop brasileira como símbolo de amizade.",
    variations: ["tamo junto", "tamos junto", "tamo junto jesus"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "flw",
    meaning: "Falou. Usado como despedida, significando 'tchau' ou 'até logo'.",
    adultTranslation: "Tchau / Falou / Até logo.",
    context: "Usado como despedida informal em mensagens de texto.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Flw, até mais!",
    contextNotes: "Abreviação de 'falou'. Significa 'tchau' ou 'combinado'. Uma das despedidas mais comuns na internet brasileira.",
    origin: "Abreviação de 'falou', popularizada como despedida na cultura digital brasileira.",
    variations: ["falou"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "sqn",
    meaning: "Só que não. Expressão de ironia ou contradição cômica.",
    adultTranslation: "Só que não / De jeito nenhum.",
    context: "Usado para contradizer algo que foi dito de forma irônica ou cômica.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "— Ela é bonita. — Sqn, o padrão é outro.",
    contextNotes: "Abreviação de 'só que não'. Expressão de ironia muito comum entre adolescentes. Geralmente usada de forma leve e cômica, não agressiva.",
    origin: "Abreviação de 'só que não', popularizada no Twitter e redes sociais brasileiras como forma de ironia.",
    variations: ["só que não"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "oq",
    meaning: "O que. Abreviação para perguntas.",
    adultTranslation: "O que.",
    context: "Usado em perguntas, especialmente em mensagens rápidas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Oq vc quer fazer hoje?",
    contextNotes: "Abreviação de 'o que'. Extremamente comum em mensagens de texto.",
    origin: "Abreviação de 'o que', popularizada pelo uso de mensagens de texto.",
    variations: ["o que"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "td",
    meaning: "Tudo. Abreviação usada para dizer 'tudo'.",
    adultTranslation: "Tudo.",
    context: "Usado em expressões como 'td bem' (tudo bem) ou 'td certo' (tudo certo).",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Td bem comigo.",
    contextNotes: "Abreviação de 'tudo'. Muito comum em mensagens rápidas do WhatsApp.",
    origin: "Abreviação de 'tudo', popularizada pelo uso de mensagens de texto.",
    variations: ["tudo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vc",
    meaning: "Você. Abreviação para 'você'.",
    adultTranslation: "Você.",
    context: "Usado para se referir à pessoa com quem se fala.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vc vai na festa?",
    contextNotes: "Abreviação de 'você'. Uma das mais usadas em português na internet. Totalmente inofensiva.",
    origin: "Abreviação de 'você', surgida com SMS e popularizada no WhatsApp.",
    variations: ["você", "vcs"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tb",
    meaning: "Também. Versão curta da abreviação 'tbm'.",
    adultTranslation: "Também / Igualmente.",
    context: "Usado para concordar rapidamente com alguém.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Eu tb quero ir!",
    contextNotes: "Abreviação de 'também'. Versão ainda mais curta que 'tbm'.",
    origin: "Abreviação de 'também', popularizada pelo Twitter e mensagens com limite de caracteres.",
    variations: ["também", "tbm"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vcs",
    meaning: "Vocês. Abreviação para o plural de 'você'.",
    adultTranslation: "Vocês.",
    context: "Usado para se referir a um grupo de pessoas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vcs vão na festa?",
    contextNotes: "Abreviação de 'vocês'. Comum em mensagens de grupo do WhatsApp.",
    origin: "Abreviação de 'vocês', popularizada pelo uso de mensagens de texto em grupo.",
    variations: ["vocês"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "kkk",
    meaning: "Risada. Representação visual de risada na internet brasileira.",
    adultTranslation: "Hahaha / Risada.",
    context: "Usado para indicar que algo é engraçado. Equivalente ao 'hahaha' ou 'lol'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Kkkk você é muito engraçado!",
    contextNotes: "Representação de risada. Muito comum na internet brasileira, especialmente no WhatsApp e Twitter. A quantidade de 'k's indica a intensidade da risada.",
    origin: "Adaptação brasileira de 'kkk' como representação de risada, surgida nos primórdios da internet brasileira.",
    variations: ["kk", "kkkk", "kkkkk", "hahaha", "ahaha"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "blk",
    meaning: "Bloqueou. Quando alguém te bloqueou nas redes sociais ou WhatsApp.",
    adultTranslation: "Bloqueou / Cortou contato.",
    context: "Usado para dizer que alguém te bloqueou em uma rede social ou aplicativo de mensagens.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Acho que ele me blk no Instagram.",
    contextNotes: "Abreviação de 'bloqueou'. Muito comum entre adolescentes para falar sobre bloqueios em redes sociais. Pode indicar drama ou término.",
    origin: "Abreviação de 'bloqueou', popularizada nas redes sociais entre jovens brasileiros.",
    variations: ["bloqueou", "block"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "msg",
    meaning: "Mensagem. Abreviação para mensagem de texto.",
    adultTranslation: "Mensagem.",
    context: "Usado para se referir a mensagens de texto, WhatsApp ou redes sociais.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Manda a msg no wpp.",
    contextNotes: "Abreviação de 'mensagem'. Universalmente compreendida no contexto digital.",
    origin: "Abreviação de 'mensagem', popularizada pelo uso de SMS e redes sociais.",
    variations: ["mensagem", "mensagen"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cq",
    meaning: "Caguei. Expressão de indiferença, usada quando não se importa com algo.",
    adultTranslation: "Não me importo / Caguei / Dan-se.",
    context: "Usado para demonstrar indiferença ou falta de interesse em algo.",
    category: "abreviação",
    riskLevel: "yellow",
    safeExample: "Cq pro que vão falar de mim.",
    contextNotes: "Abreviação de 'caguei'. Expressão de indiferença. Embora tenha origem em um palavrão, entre adolescentes é usado de forma leve para demonstrar confiança e autoestima.",
    origin: "Abreviação de 'caguei', popularizada no Twitter e WhatsApp entre jovens brasileiros.",
    variations: ["caguei"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "aff",
    meaning: "Expressão de tédio, irritação, impaciência ou decepção.",
    adultTranslation: "Que tédio / Irritação / Decepção.",
    context: "Interjeição usada para expressar tédio, irritação ou impaciência.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Aff, que aula longa!",
    contextNotes: "Interjeição muito comum que expressa desânimo, tédio ou leve irritação. Similar a 'ai' ou 'ufa'. Totalmente inofensiva.",
    origin: "Onomatopeia de suspiro/frustração, popularizada na internet brasileira. Pode derivar de 'uff' ou 'ai'.",
    variations: ["afff", "affz", "uff"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "btf",
    meaning: "Butaface / Butafaca. Pessoa muito feia, com cara de bunda (deboche).",
    adultTranslation: "Pessoa feia (deboche) / Cara feia.",
    context: "Usado como xingamento leve ou deboche para dizer que alguém é feio.",
    category: "abreviação",
    riskLevel: "orange",
    safeExample: "Ele é btf demais, não dá.",
    contextNotes: "Abreviação de 'butaface' ou 'butafaca'. Termo pejorativo usado para descrever alguém como feio. Pode ser ofensivo dependendo do contexto e da intenção.",
    origin: "Abreviação de 'butaface', popularizada pela cultura funk e memes da internet brasileira. Significa literalmente 'cara de bunda'.",
    variations: ["butaface", "butafaca", "btf demais"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vlw",
    meaning: "Valeu. Abreviação de agradecimento rápido.",
    adultTranslation: "Obrigado / Valeu.",
    context: "Usado como agradecimento rápido e informal.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vlw pela ajuda!",
    contextNotes: "Abreviação de 'valeu'. Muito comum como forma rápida de agradecer entre amigos.",
    origin: "Abreviação de 'valeu', popularizada pelo uso de mensagens de texto.",
    variations: ["valeu", "vlww"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "nv",
    meaning: "Nunca. Abreviação para dizer que nunca fez algo ou nunca vai fazer.",
    adultTranslation: "Nunca.",
    context: "Usado para enfatizar que algo nunca aconteceu ou nunca vai acontecer.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Nv fiz isso na vida.",
    contextNotes: "Abreviação de 'nunca'. Comum em conversas informais.",
    origin: "Abreviação de 'nunca', popularizada pelo uso de mensagens de texto.",
    variations: ["nunca"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dnv",
    meaning: "De novo. Usado quando algo se repete.",
    adultTranslation: "De novo / Outra vez.",
    context: "Usado para expressar frustração ou surpresa quando algo se repete.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ele esqueceu dnv!",
    contextNotes: "Abreviação de 'de novo'. Comum em mensagens rápidas para indicar repetição.",
    origin: "Abreviação de 'de novo', popularizada pelo uso de mensagens de texto.",
    variations: ["de novo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vdd",
    meaning: "Verdade. Abreviação para concordar ou confirmar algo.",
    adultTranslation: "Verdade / É verdade.",
    context: "Usado para concordar com algo que foi dito ou confirmar uma informação.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vdd, eu também vi isso.",
    contextNotes: "Abreviação de 'verdade'. Muito comum como resposta de concordância.",
    origin: "Abreviação de 'verdade', popularizada pelo uso de mensagens de texto.",
    variations: ["verdade", "é vdd"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "nzs",
    meaning: "Não é sério / Não é assim. Expressão de incredulidade.",
    adultTranslation: "Não é sério / Não pode ser.",
    context: "Usado para expressar incredulidade ou surpresa diante de algo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Nzs, não acredito!",
    contextNotes: "Abreviação de 'nézão' ou 'não é sério'. Usado como expressão de espanto.",
    origin: "Abreviação de 'não é sério', popularizada no Twitter e entre adolescentes.",
    variations: ["não é sério"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "add",
    meaning: "Adicionar. Usado para pedir para adicionar alguém em um grupo ou rede social.",
    adultTranslation: "Adicionar.",
    context: "Usado quando pede para alguém ser adicionado a um grupo de WhatsApp ou seguido nas redes sociais.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me add no grupo!",
    contextNotes: "Abreviação de 'adicionar'. Muito usada no contexto de redes sociais e grupos de WhatsApp.",
    origin: "Abreviação de 'addicionar', do inglês 'add', adaptada para o português na internet brasileira.",
    variations: ["adicionar", "adiciona"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "obgd",
    meaning: "Obrigado/a. Versão um pouco mais carinhosa da abreviação obg.",
    adultTranslation: "Muito obrigado / Obrigada.",
    context: "Usado para agradecer de forma mais enfática que 'obg'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Obgd pela força!",
    contextNotes: "Abreviação de 'obrigado' ou 'obrigada'. Versão mais entusiasmada.",
    origin: "Abreviação de 'obrigado/obrigada', variante de 'obg'.",
    variations: ["obrigado", "obg"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bn",
    meaning: "Bom noite. Abreviação para desejar boa noite.",
    adultTranslation: "Boa noite.",
    context: "Usado como despedida noturna em mensagens.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Bn, durma bem!",
    contextNotes: "Abreviação de 'boa noite'. Comum em mensagens de WhatsApp como despedida noturna.",
    origin: "Abreviação de 'boa noite', popularizada em mensagens de texto.",
    variations: ["boa noite"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bd",
    meaning: "Bom dia. Abreviação para cumprimentar de manhã.",
    adultTranslation: "Bom dia.",
    context: "Usado como cumprimento matinal em mensagens.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Bd, como dormiu?",
    contextNotes: "Abreviação de 'bom dia'. Comum em mensagens de WhatsApp como cumprimento matinal.",
    origin: "Abreviação de 'bom dia', popularizada em mensagens de texto.",
    variations: ["bom dia"],
    popularityStatus: "ativo",
    region: "Brasil",
  },

  // --- Abreviações Internacionais ---
  {
    term: "lol",
    meaning: "Rindo muito. Expressão usada para indicar que algo é engraçado.",
    adultTranslation: "Muito engraçado / Rindo muito.",
    context: "Usado para indicar que algo é engraçado. Equivalente brasileiro: 'kkk' ou 'hahaha'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Lol, que situação mais engraçada!",
    contextNotes: "Do inglês 'Laughing Out Loud'. Uma das abreviações mais usadas globalmente na internet. No Brasil, 'kkk' é mais comum, mas 'lol' também é amplamente usado por adolescentes.",
    origin: "Do inglês 'Laughing Out Loud', surgido nos primórdios da internet e adotado globalmente.",
    variations: ["lmao", "kkk", "hahaha"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "lmao",
    meaning: "Rindo MUITO. Versão mais forte de 'lol'.",
    adultTranslation: "Rindo muito / Muito engraçado.",
    context: "Versão mais intensa de 'lol', usada quando algo é extremamente engraçado.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Lmao, não consigo parar de rir!",
    contextNotes: "Do inglês 'Laughing My Ass Off'. Versão mais forte de 'lol'. Muito popular entre adolescentes brasileiros que consomem conteúdo em inglês.",
    origin: "Do inglês 'Laughing My Ass Off', popularizado por memes e redes sociais globais.",
    variations: ["lol", "rofl"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "rofl",
    meaning: "Rindo no chão. Versão clássica de risada intensa na internet.",
    adultTranslation: "Rindo muito / No chão de tanto rir.",
    context: "Versão clássica de risada intensa, usada quando algo é extremamente engraçado.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Rofl, morri de rir!",
    contextNotes: "Do inglês 'Rolling On Floor Laughing'. Expressão clássica da internet. Menos usada que 'kkk' no Brasil, mas ainda compreendida.",
    origin: "Do inglês 'Rolling On Floor Laughing', dos primórdios da internet global.",
    variations: ["lol", "lmao"],
    popularityStatus: "em_queda",
    region: "internacional",
  },
  {
    term: "brb",
    meaning: "Volto já. Usado quando vai se ausentar por pouco tempo.",
    adultTranslation: "Volto já / Já volto.",
    context: "Usado em conversas online para avisar que vai se ausentar brevemente.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Brb, vou pegar água.",
    contextNotes: "Do inglês 'Be Right Back'. Muito usado em jogos online e conversas de WhatsApp.",
    origin: "Do inglês 'Be Right Back', popularizado por jogos online e chats.",
    variations: ["volto já"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "afk",
    meaning: "Longe do teclado. Usado em jogos para indicar que não está no computador.",
    adultTranslation: "Longe do teclado / Ausente.",
    context: "Usado em jogos online e chats para indicar que está temporariamente ausente.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tô afk um minutinho.",
    contextNotes: "Do inglês 'Away From Keyboard'. Termo clássico de jogos online. Usado principalmente no contexto de gaming.",
    origin: "Do inglês 'Away From Keyboard', cultura gamer dos anos 1990-2000.",
    variations: ["brb"],
    popularityStatus: "em_queda",
    region: "internacional",
  },
  {
    term: "tbt",
    meaning: "Throwback Thursday. Hashtag usada para postar fotos/memórias antigas às quintas-feiras.",
    adultTranslation: "Quinta-feira da nostalgia / Lembrança.",
    context: "Usado em redes sociais para postar fotos ou lembranças do passado, especialmente às quintas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "#tbt dessa viagem incrível!",
    contextNotes: "Do inglês 'Throwback Thursday'. Tendência global do Instagram e Twitter. Totalmente inofensivo.",
    origin: "Do inglês 'Throwback Thursday', tendência das redes sociais iniciada no Instagram.",
    variations: ["throwback thursday"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "bff",
    meaning: "Melhor amigo(a). Usado para descrever a melhor amizade de alguém.",
    adultTranslation: "Melhor amigo(a) para sempre.",
    context: "Usado para se referir à melhor amiga ou melhor amigo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ela é minha bff desde a infância!",
    contextNotes: "Do inglês 'Best Friend Forever'. Muito popular entre adolescentes, especialmente meninas. Expressão de forte amizade.",
    origin: "Do inglês 'Best Friend Forever', popularizado por séries como 'iCarly' e redes sociais.",
    variations: ["best friend forever", "melhor amiga"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "btw",
    meaning: "A propósito / por falar nisso. Usado para introduzir uma informação adicional.",
    adultTranslation: "A propósito / Por falar nisso.",
    context: "Usado para adicionar uma informação lateral a uma conversa.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Btw, esqueci de te contar uma coisa.",
    contextNotes: "Do inglês 'By The Way'. Usado em conversas online para introduzir um assunto paralelo.",
    origin: "Do inglês 'By The Way', popularizado por e-mails e mensagens instantâneas.",
    variations: ["by the way"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "irl",
    meaning: "Na vida real. Usado para distinguir o mundo online do offline.",
    adultTranslation: "Na vida real / Pessoalmente.",
    context: "Usado para diferenciar interações online de interações presenciais.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "A gente se conheceu online, mas já nos vimos irl.",
    contextNotes: "Do inglês 'In Real Life'. Muito comum entre adolescentes que fazem amigos online e depois se encontram pessoalmente.",
    origin: "Do inglês 'In Real Life', popularizado por fóruns e redes sociais.",
    variations: ["in real life"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "idk",
    meaning: "Não sei. Abreviação usada quando não se sabe a resposta.",
    adultTranslation: "Não sei / Não tenho ideia.",
    context: "Usado para dizer que não sabe algo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Idk, pergunta pro professor.",
    contextNotes: "Do inglês 'I Don't Know'. Muito comum entre adolescentes que consomem conteúdo em inglês.",
    origin: "Do inglês 'I Don't Know', popularizado por redes sociais e memes globais.",
    variations: ["i don't know"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "ngl",
    meaning: "Para ser sincero. Usado antes de uma opinião honesta, às vezes polêmica.",
    adultTranslation: "Para ser sincero / Sendo honesto.",
    context: "Usado antes de expressar uma opinião honesta, especialmente quando pode ser impopular.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ngl, aquela música não é tão boa assim.",
    contextNotes: "Do inglês 'Not Gonna Lie'. Muito popular entre adolescentes para introduzir opiniões honestas.",
    origin: "Do inglês 'Not Gonna Lie', popularizado pelo TikTok e Twitter.",
    variations: ["not gonna lie"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "tbh",
    meaning: "Para ser honesto. Similar a 'ngl', usado para dar uma opinião sincera.",
    adultTranslation: "Para ser honesto / Sendo franco.",
    context: "Usado para dar uma opinião franca e direta.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tbh, prefiro ficar em casa.",
    contextNotes: "Do inglês 'To Be Honest'. Muito comum entre adolescentes em redes sociais.",
    origin: "Do inglês 'To Be Honest', popularizado por redes sociais globais.",
    variations: ["to be honest"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "smh",
    meaning: "Balancando a cabeça. Usado para expressar decepção ou vergonha alheia.",
    adultTranslation: "Que decepção / Vergonha alheia / Meu Deus.",
    context: "Usado para expressar decepção, frustração ou vergonha alheia diante de algo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Smh, não consigo acreditar que ele fez isso.",
    contextNotes: "Do inglês 'Shaking My Head'. Usado para expressar desaprovação silenciosa ou decepção.",
    origin: "Do inglês 'Shaking My Head', popularizado pelo Twitter e redes sociais.",
    variations: ["shaking my head"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "lmk",
    meaning: "Me avise. Usado para pedir que alguém informe sobre algo.",
    adultTranslation: "Me avise / Me diga quando souber.",
    context: "Usado para pedir que alguém comunique algo no futuro.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Lmk quando chegar, vou te buscar.",
    contextNotes: "Do inglês 'Let Me Know'. Muito comum em mensagens e redes sociais.",
    origin: "Do inglês 'Let Me Know', popularizado por mensagens de texto e redes sociais.",
    variations: ["let me know"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "rn",
    meaning: "Agora mesmo / Neste momento.",
    adultTranslation: "Agora / Neste momento.",
    context: "Usado para indicar que algo está acontecendo agora.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tô muito ocupado rn.",
    contextNotes: "Do inglês 'Right Now'. Muito comum no Twitter e em mensagens rápidas.",
    origin: "Do inglês 'Right Now', popularizado pelo Twitter e redes sociais.",
    variations: ["right now"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "fr",
    meaning: "Sério / Verdade. Usado para enfatizar que algo é verdadeiro.",
    adultTranslation: "Sério mesmo / Verdade.",
    context: "Usado para enfatizar a sinceridade ou verdade de uma afirmação.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Esse lugar é bom demais, fr.",
    contextNotes: "Do inglês 'For Real'. Muito comum entre adolescentes, usado sozinho ou após uma afirmação.",
    origin: "Do inglês 'For Real', popularizado pelo TikTok e Twitter.",
    variations: ["for real", "fr fr"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "sus",
    meaning: "Suspeito / Estranho. Usado quando algo parece duvidoso ou questionável.",
    adultTranslation: "Suspeito / Estranho / Duvidoso.",
    context: "Usado para descrever algo ou alguém que parece não confiável ou estranho.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Essa mensagem tá meio sus.",
    contextNotes: "Do inglês 'Suspicious'. Muito popular entre adolescentes após o jogo Among Us (2020). Usado de forma cômica na maioria das vezes.",
    origin: "Do inglês 'Suspicious', popularizado massivamente pelo jogo Among Us em 2020.",
    variations: ["suspicious", "sus af"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "otp",
    meaning: "Casal perfeito. Usado em fandoms para descrever o casal ideal.",
    adultTranslation: "Casal perfeito / O casal dos meus sonhos.",
    context: "Usado em fandoms e entre amigos para dizer que duas pessoas combinam perfeitamente como casal.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Eles são meu OTP, são perfeitos juntos!",
    contextNotes: "Do inglês 'One True Pairing'. Muito usado em fandoms de séries, animes e K-pop para expressar que duas pessoas deveriam ficar juntas.",
    origin: "Do inglês 'One True Pairing', cultura de fandoms de séries e animações.",
    variations: ["one true pairing", "ship"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "asap",
    meaning: "O mais rápido possível. Urgência máxima.",
    adultTranslation: "O mais rápido possível / Com urgência.",
    context: "Usado para pedir algo com urgência.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me responde asap, por favor!",
    contextNotes: "Do inglês 'As Soon As Possible'. Universalmente compreendido no Brasil. Indica urgência.",
    origin: "Do inglês 'As Soon As Possible', amplamente usado em contexto profissional e pessoal.",
    variations: ["as soon as possible"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "wyd",
    meaning: "O que você está fazendo? Pergunta comum em mensagens.",
    adultTranslation: "O que você está fazendo?",
    context: "Usado como pergunta em mensagens de texto para saber o que a pessoa está fazendo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Wyd? Tá livre pra jogar?",
    contextNotes: "Do inglês 'What You Doing?'. Muito comum em mensagens de texto entre adolescentes.",
    origin: "Do inglês 'What You Doing?', popularizado por SMS e WhatsApp.",
    variations: ["what you doing"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "omg",
    meaning: "Meu Deus! Expressão de espanto ou surpresa.",
    adultTranslation: "Meu Deus! / Nossa! / Caramba!",
    context: "Interjeição usada para expressar espanto, surpresa ou choque.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "OMG, não acredito nisso!",
    contextNotes: "Do inglês 'Oh My God'. Uma das interjeições mais usadas globalmente. Equivalente a 'meu deus' ou 'nossa' em português.",
    origin: "Do inglês 'Oh My God', popularizado globalmente por séries, filmes e redes sociais.",
    variations: ["oh my god", "oh my gosh"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "wbu",
    meaning: "E você? Resposta comum quando alguém pergunta 'wyd'.",
    adultTranslation: "E você? / Com você?",
    context: "Usado como resposta a 'wyd' ou para devolver a pergunta.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "— Wyd? — Nada, e você? (Wbu)",
    contextNotes: "Do inglês 'What About You?'. Resposta padrão a 'wyd' em mensagens de texto.",
    origin: "Do inglês 'What About You?', popularizado por SMS e WhatsApp.",
    variations: ["what about you"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "gl",
    meaning: "Boa sorte. Abreviação usada para desejar sorte a alguém.",
    adultTranslation: "Boa sorte!",
    context: "Usado para desejar boa sorte antes de um evento como prova, jogo, entrevista.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "GL na prova de amanhã!",
    contextNotes: "Do inglês 'Good Luck'. Muito comum entre adolescentes, especialmente antes de provas e competições.",
    origin: "Do inglês 'Good Luck', popularizado por jogos online e mensagens de texto.",
    variations: ["good luck"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "gg",
    meaning: "Bom jogo. Usado para reconhecer um bom desempenho.",
    adultTranslation: "Bom jogo / Parabéns / Merecido.",
    context: "Usado ao final de uma partida de jogo ou para reconhecer um bom resultado.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "GG, você jogou muito bem!",
    contextNotes: "Do inglês 'Good Game'. Termo de cortesia gamer que se expandiu para o dia a dia.",
    origin: "Do inglês 'Good Game', tradição da cultura gamer global.",
    variations: ["good game", "gg wp"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "wp",
    meaning: "Bem jogado. Reconhecimento de boa jogada ou bom desempenho.",
    adultTranslation: "Bem jogado / Bom desempenho.",
    context: "Usado para reconhecer uma boa jogada ou desempenho, geralmente junto com 'gg'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "GG WP, partida incrível!",
    contextNotes: "Do inglês 'Well Played'. Complemento comum ao 'gg'. Termo de respeito gamer.",
    origin: "Do inglês 'Well Played', tradição da cultura gamer global.",
    variations: ["well played"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "alt",
    meaning: "Conta alternativa. Uma segunda conta em redes sociais, geralmente anônima.",
    adultTranslation: "Conta alternativa / Conta reserva.",
    context: "Usado para se referir a uma conta secundária em redes sociais, geralmente usada para postar anonymously.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vi isso no alt de um amigo.",
    contextNotes: "Do inglês 'Alt account'. Muito comum entre adolescentes no Twitter e Instagram. Uma 'alt' é uma conta anônima ou secundária.",
    origin: "Do inglês 'Alt account', popularizado pelo Twitter e Instagram entre jovens.",
    variations: ["alt account", "finsta"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "rep",
    meaning: "Reputação / Reputar. Reputação em jogo ou redes sociais.",
    adultTranslation: "Reputação.",
    context: "Usado em jogos para se referir à reputação do jogador. Também pode significar 'repostar'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "A rep dele no jogo é altíssima.",
    contextNotes: "Do inglês 'Reputation'. Pode significar reputação em jogos ou 'repostar' conteúdo em redes sociais.",
    origin: "Do inglês 'Reputation', popularizado por jogos online e redes sociais.",
    variations: ["reputation", "repost"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "imo",
    meaning: "Na minha opinião. Usado antes de dar uma opinião pessoal.",
    adultTranslation: "Na minha opinião.",
    context: "Usado para introduzir uma opinião pessoal de forma clara.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Imo, esse filme é superado.",
    contextNotes: "Do inglês 'In My Opinion'. Comum em discussões online e redes sociais.",
    origin: "Do inglês 'In My Opinion', popularizado por fóruns e redes sociais.",
    variations: ["in my opinion"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "stg",
    meaning: "Juro por Deus. Usado para enfatizar que se está falando a verdade.",
    adultTranslation: "Juro / Juro por Deus.",
    context: "Usado para jurar que algo é verdade, enfatizando a sinceridade.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Stg, isso realmente aconteceu!",
    contextNotes: "Do inglês 'Swear To God'. Usado por adolescentes para dar ênfase extra à veracidade de uma história.",
    origin: "Do inglês 'Swear To God', popularizado pelo TikTok e Twitter.",
    variations: ["swear to god"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "hf",
    meaning: "Divirta-se. Usado em jogos ou quando alguém vai fazer algo legal.",
    adultTranslation: "Divirta-se / Bom proveito.",
    context: "Usado para desejar que alguém aproveite uma experiência.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "HF no jogo!",
    contextNotes: "Do inglês 'Have Fun'. Comum em jogos online como saudação amigável.",
    origin: "Do inglês 'Have Fun', tradição da cultura gamer.",
    variations: ["have fun"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "op",
    meaning: "Autor original / Postador original. Pessoa que criou um post ou thread.",
    adultTranslation: "Autor do post / Postador original.",
    context: "Usado em fóruns e redes sociais para se referir à pessoa que criou o conteúdo original.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "O OP explicou muito bem.",
    contextNotes: "Do inglês 'Original Poster'. Muito comum em Reddit, Twitter e fóruns para se referir ao autor do post.",
    origin: "Do inglês 'Original Poster', popularizado por fóruns como Reddit e 4chan.",
    variations: ["original poster"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "ig",
    meaning: "Instagram. Abreviação para a rede social.",
    adultTranslation: "Instagram.",
    context: "Usado para se referir ao Instagram em mensagens rápidas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me marca no ig!",
    contextNotes: "Abreviação de 'Instagram'. Universalmente compreendida no Brasil. Pode também significar 'I guess' (acho) em inglês, mas no Brasil é quase sempre Instagram.",
    origin: "Abreviação de 'Instagram', popularizada por mensagens de texto e conversas informais.",
    variations: ["instagram", "insta"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "rt",
    meaning: "Retweetar / Republicar. Compartilhar um post no Twitter/X.",
    adultTranslation: "Retweetar / Republicar.",
    context: "Usado no Twitter/X para compartilhar um post, ou como verbo para dizer que vai compartilhar.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "RT se você concorda!",
    contextNotes: "Do inglês 'Retweet'. Ação de republicar conteúdo no Twitter/X. Muito comum como pedido de engajamento.",
    origin: "Do inglês 'Retweet', funcionalidade nativa do Twitter/X.",
    variations: ["retweet"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "dm",
    meaning: "Mensagem direta. Mensagem privada em redes sociais.",
    adultTranslation: "Mensagem direta / Mensagem privada.",
    context: "Usado para se referir a mensagens privadas no Instagram, Twitter ou outras redes.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Me manda um dm.",
    contextNotes: "Do inglês 'Direct Message'. Pode ser usado como substantivo ou verbo ('me dma'). Universalmente compreendido.",
    origin: "Do inglês 'Direct Message', das redes sociais como Twitter e Instagram.",
    variations: ["direct message", "direct", "inbox"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "af",
    meaning: "Pra caralho. Sufixo intensificador em inglês, equivalente a 'muito' ou 'demais'.",
    adultTranslation: "Pra caralho / Demais / Muito intensamente.",
    context: "Usado como sufixo intensificador. Ex: 'tired af' = cansado pra caralho. Pode ser ofensivo pois contém palavrão implícito.",
    category: "abreviação",
    riskLevel: "yellow",
    safeExample: "Tô cansado af hoje.",
    contextNotes: "Do inglês 'As Fuck'. Sufixo intensificador que contém um palavrão implícito em inglês. Muito usado por adolescentes, mas pode soar vulgar. Em inglês é mais leve que em português, mas atenção ao contexto.",
    origin: "Do inglês 'As Fuck', popularizado pelo Twitter e TikTok como intensificador.",
    variations: ["as fuck"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "wtf",
    meaning: "Que porra?! Expressão forte de espanto ou choque.",
    adultTranslation: "Que porra?! / Meu Deus! / Inacreditável!",
    context: "Interjeição forte usada para expressar choque, espanto ou indignação intensa.",
    category: "abreviação",
    riskLevel: "orange",
    safeExample: "Wtf aconteceu aqui?!",
    contextNotes: "Do inglês 'What The Fuck'. Contém palavrão explícito em inglês. Muito usado por adolescentes em momentos de espanto extremo, mas é uma linguagem vulgar. Orientar sobre uso em contextos formais.",
    origin: "Do inglês 'What The Fuck', da cultura de internet global. Um dos termos mais usados para expressar choque.",
    variations: ["what the fuck"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "kms",
    meaning: "Vou me matar. Expressão exagerada de frustração ou embaraço, NÃO literal.",
    adultTranslation: "Expressão de frustração exagerada (não literal).",
    context: "Usado de forma hiperbólica para expressar frustração, vergonha ou embaraço. NÃO é uma ameaça real.",
    category: "abreviação",
    riskLevel: "orange",
    safeExample: "Kms, esqueci a senha de novo.",
    contextNotes: "Do inglês 'Kill Myself'. ⚠️ IMPORTANTE: Esta é uma expressão hiperbólica usada por adolescentes para expressar frustração leve, similar a 'vou morrer de vergonha'. NÃO deve ser interpretada como ameaça real. Porém, se usado repetidamente com contexto emocional negativo, pode indicar sofrimento e merece atenção.",
    origin: "Do inglês 'Kill Myself', popularizado como hiperbole na internet. Usado como exagero cômico por adolescentes.",
    variations: ["kill myself"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "npc",
    meaning: "Personagem sem personalidade própria. Alguém que não pensa por si mesmo.",
    adultTranslation: "Sem personalidade / Seguidor cego / Automático.",
    context: "Usado como insulto leve para alguém que age sem pensar ou segue tudo sem questionar.",
    category: "abreviação",
    riskLevel: "yellow",
    safeExample: "Ele só repete o que os outros falam, é um npc.",
    contextNotes: "Do inglês 'Non-Player Character'. Originalmente dos videogames, virou insulto para descrever alguém sem opinião própria ou que age de forma robótica.",
    origin: "Do inglês 'Non-Player Character', dos videogames. Virou meme e insulto popular na internet a partir de 2023.",
    variations: ["non-player character"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "pdp",
    meaning: "Pode parar de dar / 'Puta que pariu'. No contexto teen/funk: 'pode dar o papo' (expressão).",
    adultTranslation: "Expressão forte / Contexto funk: interjeição de afirmação.",
    context: "Pode ter diferentes significados dependendo do contexto. No funk, pode ser interjeição. Na internet, geralmente é abreviação de um palavrão.",
    category: "abreviação",
    riskLevel: "red",
    safeExample: "PDP, que absurdo!",
    contextNotes: "⚠️ Termo sensível. Abreviação que pode esconder um palavrão explícito ('puta que pariu'). No contexto do funk pode ter outros significados, mas na maioria dos casos é a abreviação do palavrão. Orientar fortemente sobre uso.",
    origin: "Abreviação de 'puta que pariu', muito comum na internet brasileira como expressão de espanto ou raiva.",
    variations: ["puta que pariu"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fss",
    meaning: "Fé em sério? Expressão de espanto ou incredulidade.",
    adultTranslation: "Sério mesmo? / Não pode ser.",
    context: "Interjeição usada para expressar espanto ou descrença diante de algo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Fss, você fez isso?",
    contextNotes: "Abreviação de 'fé em sério?'. Usada como expressão de espanto entre adolescentes.",
    origin: "Abreviação de 'fé em sério?', popularizada no WhatsApp e redes sociais brasileiras.",
    variations: ["fé em sério"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "sla",
    meaning: "Não sei / Salve. Pode significar 'sei lá' ou ser usado como saudação.",
    adultTranslation: "Sei lá / Salve.",
    context: "Usado como resposta vaga ('sei lá') ou como saudação rápida ('salve').",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "O que vamos fazer? — Sla.",
    contextNotes: "Abreviação versátil. Pode ser 'sei lá' (incerteza) ou 'salve' (saudação). Contexto determina o significado.",
    origin: "Abreviação de 'sei lá' ou 'salve', popularizada no Twitter e WhatsApp entre jovens brasileiros.",
    variations: ["sei lá", "salve"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ex",
    meaning: "Ex-namorado(a). Pessoa com quem se teve um relacionamento no passado.",
    adultTranslation: "Ex-namorado / Ex-namorada.",
    context: "Usado para se referir a um ex-parceiro romântico.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vi meu ex no shopping hoje.",
    contextNotes: "Abreviação de 'ex-namorado/ex-namorada'. Muito comum entre adolescentes para falar de relacionamentos passados.",
    origin: "Do inglês 'ex' (antigo), universalmente usado em português para se referir a ex-parceiros.",
    variations: ["ex-namorado", "ex-namorada"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "bf",
    meaning: "Namorado / Boyfriend. Parceiro romântico masculino.",
    adultTranslation: "Namorado / Parceiro.",
    context: "Usado para se referir ao namorado ou parceiro romântico.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vou sair com meu bf hoje.",
    contextNotes: "Do inglês 'Boyfriend'. Muito comum entre adolescentes em conversas sobre relacionamentos.",
    origin: "Do inglês 'Boyfriend', popularizado por séries e redes sociais.",
    variations: ["boyfriend", "namorado"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "gf",
    meaning: "Namorada / Girlfriend. Parceira romântica feminina.",
    adultTranslation: "Namorada / Parceira.",
    context: "Usado para se referir à namorada ou parceira romântica.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Minha gf é incrível.",
    contextNotes: "Do inglês 'Girlfriend'. Muito comum entre adolescentes em conversas sobre relacionamentos.",
    origin: "Do inglês 'Girlfriend', popularizado por séries e redes sociais.",
    variations: ["girlfriend", "namorada"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "pnc",
    meaning: "Pode não crer. Expressão de espanto ou descrença.",
    adultTranslation: "Não pode ser / Sério? / Incrível.",
    context: "Interjeição usada para expressar espanto extremo.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Pnc, que coisa absurda!",
    contextNotes: "Abreviação de 'pode não crer'. Muito popular no Rio de Janeiro e expandido nacionalmente. Expressão de espanto intenso.",
    origin: "Abreviação de 'pode não crer', popularizada pela cultura carioca e funk brasileiro.",
    variations: ["pode não crer"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pd",
    meaning: "Pronto. Usado para indicar que algo está feito ou pronto.",
    adultTranslation: "Pronto / Feito.",
    context: "Usado para avisar que algo foi concluído.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Pd, já terminei.",
    contextNotes: "Abreviação de 'pronto'. Comum em mensagens rápidas do WhatsApp.",
    origin: "Abreviação de 'pronto', popularizada pelo uso de mensagens de texto.",
    variations: ["pronto"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pf",
    meaning: "Para / Por favor. Contexto determina o significado.",
    adultTranslation: "Para / Por favor.",
    context: "Pode significar 'para' ou 'por favor' dependendo do contexto da frase.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Pf, me ajuda aqui.",
    contextNotes: "Abreviação de 'para' ou 'por favor'. Uma das abreviações mais curtas e versáteis.",
    origin: "Abreviação versátil, popularizada pelo uso de mensagens de texto.",
    variations: ["para", "por favor"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tt",
    meaning: "Treta. Confusão, drama ou briga, especialmente em redes sociais.",
    adultTranslation: "Drama / Confusão / Briga.",
    context: "Usado para descrever uma situação de drama ou confusão.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Hoje teve tt no grupo do WhatsApp.",
    contextNotes: "Abreviação de 'treta'. Muito comum entre adolescentes para descrever drama, confusão ou briga.",
    origin: "Abreviação de 'treta', popularizada no Twitter e WhatsApp entre jovens brasileiros.",
    variations: ["treta"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cc",
    meaning: "Com cócegas. Usado para dizer que algo é muito engraçado.",
    adultTranslation: "Muito engraçado / De rir muito.",
    context: "Usado como reação a algo engraçado. Similar a 'kkk' ou 'lol'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Esse vídeo é cc demais!",
    contextNotes: "Abreviação de 'com cócegas'. Expressão de humor muito popular no WhatsApp entre adolescentes. Significa que algo deu 'cócegas de rir'.",
    origin: "Abreviação de 'com cócegas', popularizada no WhatsApp e grupos de adolescentes.",
    variations: ["com cócegas"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cam",
    meaning: "Camiseta. Usado para se referir a uma camiseta, especialmente de time ou marca.",
    adultTranslation: "Camiseta.",
    context: "Usado para falar de camisetas, especialmente de times de futebol ou marcas.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vou usar a cam do Brasil hoje.",
    contextNotes: "Abreviação de 'camiseta'. Comum entre adolescentes para falar de roupas e futebol.",
    origin: "Abreviação de 'camiseta', popularizada em grupos de WhatsApp e conversas sobre futebol.",
    variations: ["camiseta", "camisa"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "insta",
    meaning: "Instagram. Nome popular da rede social.",
    adultTranslation: "Instagram.",
    context: "Usado para se referir ao Instagram.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Postei uma foto no insta.",
    contextNotes: "Diminutivo de 'Instagram'. Universalmente compreendido no Brasil. Totalmente inofensivo.",
    origin: "Diminutivo de 'Instagram', popularizado como nome coloquial da rede social no Brasil.",
    variations: ["instagram", "ig"],
    popularityStatus: "ativo",
    region: "internacional",
  },
  {
    term: "tlgd",
    meaning: "Tá ligado. Usado para perguntar se a pessoa sabe de algo.",
    adultTranslation: "Sabe? / Está ciente?",
    context: "Usado para perguntar se alguém está ciente de algo, similar a 'sabe?'.",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tlgd que a prova foi adiada?",
    contextNotes: "Abreviação de 'tá ligado'. Forma rápida de perguntar se alguém sabe de algo.",
    origin: "Abreviação de 'tá ligado', popularizada no WhatsApp e Twitter entre jovens brasileiros.",
    variations: ["tá ligado"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
];
