import type { SlangTerm } from "./slang-data";

export const REGIONAL_SLANG_DATA: SlangTerm[] = [

  {
    term: "égua",
    meaning: "Interjeição de surpresa, admiração ou espanto.",
    adultTranslation: "Nossa! / Caramba!",
    context: "Muito comum no Pará e no Norte em falas cotidianas.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Égua, que chuva forte!",
    contextNotes: "Uso emocional, sem teor ofensivo por padrão.",
    origin: "Fala popular paraense.",
    variations: ["eita égua", "egua"],
    popularityStatus: "regional",
    region: "Norte (PA)",
  },
  {
    term: "pai d'égua",
    meaning: "Algo excelente, de altíssima qualidade.",
    adultTranslation: "Muito bom / Excelente.",
    context: "Expressão típica do Norte, especialmente no Pará.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse açaí tá pai d'égua.",
    contextNotes: "Elogio bastante cultural e positivo.",
    origin: "Expressão tradicional paraense.",
    variations: ["paidegua", "pai de égua"],
    popularityStatus: "regional",
    region: "Norte",
  },
  {
    term: "véi",
    meaning: "Forma informal de chamar alguém, como 'cara' ou 'mano'.",
    adultTranslation: "Amigo / Cara.",
    context: "Muito usada no Sudeste e Centro-Oeste em conversas rápidas.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Véi, cê viu isso?",
    contextNotes: "Pode soar íntimo; evite em contexto formal.",
    origin: "Variação oral de 'velho' com uso afetivo.",
    variations: ["véi do céu", "vei"],
    popularityStatus: "regional",
    region: "Sudeste / Centro-Oeste",
  },
  {
    term: "trem",
    meaning: "Palavra curinga para se referir a objetos, situações ou fatos.",
    adultTranslation: "Coisa / Assunto.",
    context: "Muito comum em Minas Gerais e áreas de influência mineira.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse trem tá difícil de resolver.",
    contextNotes: "Marca linguística mineira clássica.",
    origin: "Uso histórico na fala mineira.",
    variations: ["trem bão", "trem doido"],
    popularityStatus: "regional",
    region: "Sudeste (MG)",
  },
  {
    term: "num instante",
    meaning: "Expressão para indicar que algo será feito em breve.",
    adultTranslation: "Já já / Em breve.",
    context: "Uso cotidiano no Norte e Nordeste em situações informais.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Num instante eu te respondo.",
    contextNotes: "Termo neutro e educado, sem risco.",
    origin: "Fala oral tradicional em múltiplas regiões.",
    variations: ["num estante", "num minuto"],
    popularityStatus: "regional",
    region: "Norte / Nordeste",
  },
  {
    term: "avexado",
    meaning: "Pessoa apressada ou ansiosa.",
    adultTranslation: "Apressado / Ansioso.",
    context: "Muito frequente no Nordeste para descrever pressa.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Deixa de ser avexado, vai dar tempo.",
    contextNotes: "Pode soar bronca leve, mas costuma ser afetuoso.",
    origin: "Nordeste brasileiro.",
    variations: ["avexar", "avexadinho"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "mangar",
    meaning: "Zombar de alguém em tom de brincadeira.",
    adultTranslation: "Tirar sarro / Zoar.",
    context: "Usada no Nordeste em ambiente familiar ou entre amigos.",
    category: "regional",
    riskLevel: "yellow",
    safeExample: "Ele vive mangando do meu sotaque.",
    contextNotes: "Pode gerar desconforto dependendo do tom.",
    origin: "Vocabulário popular nordestino.",
    variations: ["mangação", "mangar de"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "piá",
    meaning: "Menino, garoto.",
    adultTranslation: "Garoto / Menino.",
    context: "Comum no Sul e em parte do Centro-Oeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "O piá foi jogar bola na rua.",
    contextNotes: "Uso tradicional e afetivo.",
    origin: "Herança linguística do Sul do Brasil.",
    variations: ["piazada", "piazinho"],
    popularityStatus: "regional",
    region: "Sul",
  },
  {
    term: "guria",
    meaning: "Menina, garota.",
    adultTranslation: "Garota / Menina.",
    context: "Termo muito frequente na região Sul.",
    category: "regional",
    riskLevel: "green",
    safeExample: "A guria mandou bem na prova.",
    contextNotes: "Neutro e bastante comum no dia a dia.",
    origin: "Fala gaúcha e sulista.",
    variations: ["guri", "guriada"],
    popularityStatus: "regional",
    region: "Sul",
  },
  {
    term: "capiau",
    meaning: "Pessoa do interior; pode ser elogio raiz ou crítica.",
    adultTranslation: "Interiorano / Pessoa da roça.",
    context: "Usada no interior do Sudeste e Centro-Oeste.",
    category: "regional",
    riskLevel: "yellow",
    safeExample: "Sou capiau com orgulho, uai!",
    contextNotes: "Pode ser pejorativo se usado com desprezo.",
    origin: "Vocabulário rural brasileiro.",
    variations: ["capiauzão", "caipira"],
    popularityStatus: "regional",
    region: "Sudeste / Centro-Oeste",
  },
  {
    term: "bão",
    meaning: "Forma coloquial de 'bom'.",
    adultTranslation: "Bom / Legal.",
    context: "Muito usada em Minas Gerais e interior paulista.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse pão de queijo tá bão demais.",
    contextNotes: "Marca de sotaque e identidade regional.",
    origin: "Fala mineira e caipira.",
    variations: ["bão demais", "bom demais da conta"],
    popularityStatus: "regional",
    region: "Sudeste (MG/SP interior)",
  },
  {
    term: "paieta",
    meaning: "Conversa exagerada ou enrolação.",
    adultTranslation: "Papo furado / Enrolação.",
    context: "Ouvida em áreas urbanas do Nordeste.",
    category: "regional",
    riskLevel: "yellow",
    safeExample: "Para de paieta e fala logo a verdade.",
    contextNotes: "Pode carregar tom de repreensão.",
    origin: "Uso oral popular nordestino.",
    variations: ["paitar", "papo paieta"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "brocado",
    meaning: "Com muita fome.",
    adultTranslation: "Faminto / Morrendo de fome.",
    context: "Comum no Nordeste em linguagem jovem.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Tô brocado, bora comer agora.",
    contextNotes: "Uso descontraído e frequente.",
    origin: "Gíria urbana nordestina.",
    variations: ["broca", "brocão"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "leseira",
    meaning: "Bobeira, atitude sem noção.",
    adultTranslation: "Besteira / Bobagem.",
    context: "Usada no Nordeste para repreensão leve.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Deixa de leseira e vem estudar.",
    contextNotes: "Tom varia entre carinho e bronca.",
    origin: "Linguagem popular nordestina.",
    variations: ["leso", "lesado"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "tri massa",
    meaning: "Muito legal, ótimo, excelente.",
    adultTranslation: "Muito bom / Excelente.",
    context: "Expressão de elogio bastante comum no Sul do Brasil.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse show foi tri!",
    contextNotes: "Uso positivo e inofensivo, geralmente no Rio Grande do Sul.",
    origin: "Uso popular da região Sul, especialmente no RS.",
    variations: ["tri legal", "tri bom", "tri"],
    popularityStatus: "regional",
    region: "Sul (RS)",
  },
  {
    term: "bah guri",
    meaning: "Interjeição de surpresa ou intensidade.",
    adultTranslation: "Nossa! / Caramba!",
    context: "Muito usada no Sul em conversa casual.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Bah guri, que frio hoje!",
    contextNotes: "Tom informal e amistoso.",
    origin: "Fala popular gaúcha.",
    variations: ["bah", "guri", "guria"],
    popularityStatus: "regional",
    region: "Sul",
  },
  {
    term: "oxi mainha",
    meaning: "Interjeição de surpresa, espanto ou dúvida.",
    adultTranslation: "Ué / Nossa / Como assim?",
    context: "Interjeição típica em contextos informais no Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Oxi mainha, já acabou a aula?",
    contextNotes: "Expressão tradicional e sem conotação ofensiva.",
    origin: "Expressão histórica da cultura nordestina.",
    variations: ["oxente", "o xente"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "visse",
    meaning: "Partícula para reforçar ou pedir confirmação.",
    adultTranslation: "Entendeu? / Viu? / Certo?",
    context: "Usado no fim da frase em conversas informais no Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Chega cedo amanhã, visse?",
    contextNotes: "Uso coloquial regional, geralmente amigável.",
    origin: "Variação oral de 'viste/viu' na fala regional.",
    variations: ["vixe", "viu"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "papo reto",
    meaning: "Falar a verdade de forma direta.",
    adultTranslation: "Sem enrolação / Sinceridade.",
    context: "Muito presente em funk e periferias do Sudeste.",
    category: "funk",
    riskLevel: "green",
    safeExample: "Papo reto, esse som tá brabo.",
    contextNotes: "Pode aparecer em música e redes sociais.",
    origin: "Cultura urbana RJ/SP.",
    variations: ["reta", "na real"],
    popularityStatus: "trending",
    region: "Rio/São Paulo",
  },
  {
    term: "amassou",
    meaning: "Foi muito bem em algo.",
    adultTranslation: "Arrasou / Mandou muito.",
    context: "Linguagem de adolescentes em escola, jogos e TikTok.",
    category: "internet",
    riskLevel: "green",
    safeExample: "Ele amassou na apresentação.",
    contextNotes: "Uso positivo e comum em vídeo curto.",
    origin: "Internet/TikTok.",
    variations: ["amassando", "amasso"],
    popularityStatus: "trending",
    region: "Brasil",
  },
  {
    term: "pai tá on",
    meaning: "Expressa animação e confiança.",
    adultTranslation: "Estou no clima / Estou pronto.",
    context: "Gíria de memes e música, muito usada em redes sociais.",
    category: "internet",
    riskLevel: "green",
    safeExample: "Sextou, pai tá on!",
    contextNotes: "Tom brincalhão, bastante popular.",
    origin: "Memes e funk nacional.",
    variations: ["tá on", "on demais"],
    popularityStatus: "trending",
    region: "Brasil",
  },
  {
    term: "pequiado",
    meaning: "Pessoa com forte identidade do Centro-Oeste.",
    adultTranslation: "Bem regional / Raiz.",
    context: "Uso descontraído em Goiás e entorno.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Ele é pequiado, conhece tudo de Goiânia.",
    contextNotes: "Referência cultural ao pequi.",
    origin: "Centro-Oeste.",
    variations: ["raiz do pequi"],
    popularityStatus: "regional",
    region: "Centro-Oeste",
  },
  {
    term: "esculacho",
    meaning: "Situação de bagunça, confusão ou bronca pesada.",
    adultTranslation: "Desordem / Repreensão forte.",
    context: "Muito usada em funk e cotidiano urbano no RJ.",
    category: "funk",
    riskLevel: "yellow",
    safeExample: "Virou esculacho quando o som estourou.",
    contextNotes: "Tom pode variar entre humor e crítica.",
    origin: "Cultura urbana carioca.",
    variations: ["esculachar", "esculachado"],
    popularityStatus: "trending",
    region: "Rio de Janeiro",
  },
  {
    term: "chave",
    meaning: "Algo muito bom, estiloso ou impressionante.",
    adultTranslation: "Muito top / De alto nível.",
    context: "Gíria presente em músicas e redes sociais de SP/DF.",
    category: "funk",
    riskLevel: "green",
    safeExample: "Esse tênis tá chave demais.",
    contextNotes: "Uso positivo em conversas jovens.",
    origin: "Funk paulista e cultura de rua.",
    variations: ["na chave", "chavoso"],
    popularityStatus: "trending",
    region: "São Paulo / Brasília",
  },
  {
    term: "flopou",
    meaning: "Não deu certo, não teve engajamento.",
    adultTranslation: "Fracassou / Não performou bem.",
    context: "Muito comum em TikTok, Instagram e X.",
    category: "internet",
    riskLevel: "green",
    safeExample: "O vídeo flopou, vou postar outro horário.",
    contextNotes: "Contexto digital e métricas sociais.",
    origin: "Internet/global slang adaptada ao PT-BR.",
    variations: ["flop", "flopar", "flopado"],
    popularityStatus: "trending",
    region: "Brasil",
  },
  {
    term: "cringei",
    meaning: "Senti vergonha alheia de algo.",
    adultTranslation: "Achei constrangedor.",
    context: "Usada por adolescentes em escola e redes sociais.",
    category: "internet",
    riskLevel: "green",
    safeExample: "Cringei com aquele áudio no grupo da sala.",
    contextNotes: "Tom irônico, popular em gerações mais novas.",
    origin: "Adaptação de 'cringe'.",
    variations: ["cringe", "cringei muito"],
    popularityStatus: "trending",
    region: "Brasil",
  },
  {
    term: "arretado",
    meaning: "Algo muito bom, intenso ou marcante.",
    adultTranslation: "Excelente / Impressionante.",
    context: "Tradicional no Nordeste, também em tom de surpresa.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse forró tá arretado!",
    contextNotes: "Pode variar de elogio para intensidade.",
    origin: "Nordeste brasileiro.",
    variations: ["retado", "arretada"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "capaz",
    meaning: "Interjeição de negação, surpresa ou discordância.",
    adultTranslation: "Imagina! / De jeito nenhum!",
    context: "Muito comum na fala cotidiana do Sul.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Capaz que vou perder esse jogo.",
    contextNotes: "Tom coloquial, sem ofensa.",
    origin: "Uso popular no RS e SC.",
    variations: ["mas capaz", "capaz mesmo"],
    popularityStatus: "regional",
    region: "Sul",
  },
  {
    term: "uai sô",
    meaning: "Expressão de surpresa/ênfase típica de Minas e Centro-Oeste.",
    adultTranslation: "Ué, poxa.",
    context: "Conversa informal em MG, GO e DF.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Uai sô, já acabou o lanche?",
    contextNotes: "Marca identidade regional.",
    origin: "Fala mineira e influência no Centro-Oeste.",
    variations: ["uai", "sô"],
    popularityStatus: "regional",
    region: "Centro-Oeste / Minas",
  },

  {
    term: "arre diacho",
    meaning: "Interjeição de espanto, surpresa ou impaciência leve.",
    adultTranslation: "Nossa! / Que coisa! / Poxa!",
    context: "Usada em conversas informais no Acre e em áreas do Norte.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Arre diacho, esqueci o caderno em casa.",
    contextNotes: "Expressão emocional e coloquial; normalmente não é ofensiva.",
    origin: "Fala popular acreana e nortista.",
    variations: ["arre", "diacho"],
    popularityStatus: "regional",
    region: "Norte (AC)",
  },
  {
    term: "de rocha",
    meaning: "De verdade, com certeza, algo levado a sério.",
    adultTranslation: "É sério / De verdade / Confirmado.",
    context: "Marca afirmação forte em conversas jovens no Norte.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Pode confiar, é de rocha.",
    contextNotes: "Uso positivo para reforçar compromisso ou convicção.",
    origin: "Fala urbana nortista.",
    variations: ["é de rocha", "de rocha mesmo"],
    popularityStatus: "regional",
    region: "Norte (AM/PA)",
  },
  {
    term: "cunhantã",
    meaning: "Menina ou garota, em uso regional amazônico.",
    adultTranslation: "Menina / Garota.",
    context: "Aparece em fala popular e referências culturais amazônicas.",
    category: "regional",
    riskLevel: "green",
    safeExample: "A cunhantã chegou cedo para a apresentação.",
    contextNotes: "Termo de identidade regional; use com respeito ao contexto cultural.",
    origin: "Vocabulário amazônico com raiz indígena.",
    variations: ["cunhã", "cunhantazinha"],
    popularityStatus: "regional",
    region: "Norte (AM)",
  },
  {
    term: "borimbora",
    meaning: "Chamada para ir embora ou começar algo.",
    adultTranslation: "Vamos embora / Vamos nessa.",
    context: "Usada em fala rápida no Norte e Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Borimbora que o ônibus já vai passar.",
    contextNotes: "Expressão de movimento, sem teor ofensivo.",
    origin: "Contração oral de 'bora embora'.",
    variations: ["bora simbora", "simbora"],
    popularityStatus: "regional",
    region: "Norte / Nordeste (PA/MA/PE)",
  },
  {
    term: "arre égua",
    meaning: "Interjeição de susto, surpresa ou intensidade.",
    adultTranslation: "Nossa! / Caramba!",
    context: "Muito associada ao Ceará e ao Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Arre égua, que chuva forte!",
    contextNotes: "Expressão emocional e culturalmente marcada.",
    origin: "Fala popular nordestina.",
    variations: ["arriégua", "arreégua"],
    popularityStatus: "regional",
    region: "Nordeste (CE)",
  },
  {
    term: "caba",
    meaning: "Pessoa, sujeito, cara.",
    adultTranslation: "Pessoa / Cara / Sujeito.",
    context: "Vocativo informal em partes do Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Aquele caba sabe jogar demais.",
    contextNotes: "Pode soar muito informal fora da região.",
    origin: "Redução oral de 'cabra' no Nordeste.",
    variations: ["cabra", "caba da peste"],
    popularityStatus: "regional",
    region: "Nordeste (CE/PB/RN)",
  },
  {
    term: "macho véi",
    meaning: "Vocativo informal equivalente a amigo, cara ou rapaz.",
    adultTranslation: "Cara / Amigo / Rapaz.",
    context: "Muito usado no Ceará em conversa descontraída.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Macho véi, tu viu o gol?",
    contextNotes: "Tom depende da intimidade; não use em contexto formal.",
    origin: "Fala urbana cearense.",
    variations: ["macho", "mah", "macho do céu"],
    popularityStatus: "regional",
    region: "Nordeste (CE)",
  },
  {
    term: "arengar",
    meaning: "Implicar, provocar discussão ou ficar brigando por pouco.",
    adultTranslation: "Discutir / Implicar / Criar confusão.",
    context: "Usada no Nordeste para conflitos leves ou insistência chata.",
    category: "regional",
    riskLevel: "yellow",
    safeExample: "Para de arengar com teu irmão.",
    contextNotes: "Pode indicar provocação; vale observar o tom.",
    origin: "Vocabulário popular nordestino.",
    variations: ["arenga", "arengueiro"],
    popularityStatus: "regional",
    region: "Nordeste (PE/PB/RN)",
  },
  {
    term: "aperreado",
    meaning: "Preocupado, estressado, pressionado ou com pressa.",
    adultTranslation: "Aflito / Estressado / Preocupado.",
    context: "Muito comum no Nordeste para falar de ansiedade cotidiana.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Tô aperreado com tanta prova essa semana.",
    contextNotes: "Pode sinalizar sobrecarga emocional; acolha antes de corrigir.",
    origin: "Fala popular nordestina.",
    variations: ["aperreio", "aperrear"],
    popularityStatus: "regional",
    region: "Nordeste (PE/BA/CE)",
  },
  {
    term: "abestado",
    meaning: "Pessoa boba, distraída ou sem malícia.",
    adultTranslation: "Bobo / Distraído / Ingênuo.",
    context: "Usada em tom de brincadeira ou crítica no Nordeste.",
    category: "regional",
    riskLevel: "yellow",
    safeExample: "Deixa de ser abestado e presta atenção.",
    contextNotes: "Pode virar ofensa se usado para humilhar.",
    origin: "Fala popular nordestina.",
    variations: ["abestalhado", "abestaiado"],
    popularityStatus: "regional",
    region: "Nordeste (PB/PE/CE)",
  },
  {
    term: "marrapá",
    meaning: "Interjeição de espanto ou incredulidade.",
    adultTranslation: "Nossa! / Sério? / Não acredito!",
    context: "Expressão associada ao Maranhão e áreas próximas.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Marrapá, tu chegou cedo hoje!",
    contextNotes: "Uso leve e identitário.",
    origin: "Fala popular maranhense.",
    variations: ["marrapaz", "rapaz"],
    popularityStatus: "regional",
    region: "Nordeste (MA)",
  },
  {
    term: "pocar",
    meaning: "Estourar, fazer sucesso ou ficar muito cheio.",
    adultTranslation: "Bombar / Estourar / Lotar.",
    context: "Usada na Bahia e também no Espírito Santo para eventos e redes.",
    category: "regional",
    riskLevel: "green",
    safeExample: "A festa vai pocar no fim de semana.",
    contextNotes: "Uso positivo quando indica sucesso; observe contexto de aglomeração.",
    origin: "Fala popular da Bahia e do Espírito Santo.",
    variations: ["pocou", "vai pocar"],
    popularityStatus: "trending",
    region: "Nordeste / Sudeste (BA/ES)",
  },
  {
    term: "camelo",
    meaning: "Bicicleta em uso regional informal.",
    adultTranslation: "Bicicleta.",
    context: "Aparece no Centro-Oeste e no Rio em fala cotidiana.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Vou de camelo até a escola.",
    contextNotes: "Termo neutro; pode confundir quem conhece apenas o animal.",
    origin: "Regionalismo urbano brasileiro.",
    variations: ["bike", "bicicleta"],
    popularityStatus: "regional",
    region: "Centro-Oeste / Sudeste (DF/RJ)",
  },
  {
    term: "renca",
    meaning: "Grande quantidade ou grupo numeroso.",
    adultTranslation: "Um monte / Muita gente / Vários.",
    context: "Usada no Centro-Oeste e interior para falar de quantidade.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Chegou uma renca de mensagem no grupo.",
    contextNotes: "Uso informal e expressivo.",
    origin: "Fala interiorana do Centro-Oeste.",
    variations: ["renca de gente", "um tanto"],
    popularityStatus: "regional",
    region: "Centro-Oeste (GO/MT)",
  },
  {
    term: "bitelo",
    meaning: "Algo muito grande, forte ou chamativo.",
    adultTranslation: "Enorme / Grande / Forte.",
    context: "Usada no Centro-Oeste e interior para intensificar tamanho.",
    category: "regional",
    riskLevel: "green",
    safeExample: "O lanche veio bitelo demais.",
    contextNotes: "Geralmente elogio ou surpresa positiva.",
    origin: "Fala popular interiorana.",
    variations: ["bitelão", "bitela"],
    popularityStatus: "regional",
    region: "Centro-Oeste (MT/MS/GO)",
  },
  {
    term: "arreda",
    meaning: "Pedido para sair do lugar ou abrir espaço.",
    adultTranslation: "Afasta / Dá licença / Sai um pouco.",
    context: "Comum em Minas, Goiás e interior do Brasil.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Arreda um pouquinho pra eu passar.",
    contextNotes: "Pode soar seco se dito sem cuidado, mas costuma ser cotidiano.",
    origin: "Português oral interiorano.",
    variations: ["arreda aí", "arredar"],
    popularityStatus: "regional",
    region: "Centro-Oeste / Sudeste (GO/MG)",
  },
  {
    term: "pão de sal",
    meaning: "Nome regional para pão francês.",
    adultTranslation: "Pão francês.",
    context: "Muito usado em Minas Gerais e em outras áreas do Sudeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Compra seis pães de sal na padaria.",
    contextNotes: "Variação regional de vocabulário alimentar.",
    origin: "Uso mineiro e sudestino.",
    variations: ["pão francês", "pãozinho"],
    popularityStatus: "regional",
    region: "Sudeste (MG)",
  },
  {
    term: "biscoito de polvilho",
    meaning: "Forma regional de se referir ao snack de polvilho; em alguns lugares contrasta com 'bolacha'.",
    adultTranslation: "Biscoito / Snack de polvilho.",
    context: "Termo comum no Sudeste, especialmente RJ/MG, em conversas sobre lanche.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Trouxe biscoito de polvilho pro recreio.",
    contextNotes: "Neutro; ajuda a explicar diferenças de vocabulário regional.",
    origin: "Vocabulário alimentar regional.",
    variations: ["biscoito", "polvilho"],
    popularityStatus: "regional",
    region: "Sudeste (RJ/MG)",
  },
  {
    term: "carioquinha",
    meaning: "Nome regional para pão francês em partes do Ceará.",
    adultTranslation: "Pão francês.",
    context: "Usada em padarias e conversas cotidianas no Ceará.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Pega quatro carioquinhas pra merenda.",
    contextNotes: "Variação alimentar regional, sem risco.",
    origin: "Vocabulário cearense de padaria.",
    variations: ["pão carioquinha", "pão francês"],
    popularityStatus: "regional",
    region: "Nordeste (CE)",
  },
  {
    term: "pão de jacó",
    meaning: "Nome regional para pão francês em partes de Pernambuco.",
    adultTranslation: "Pão francês.",
    context: "Aparece no vocabulário cotidiano de padarias pernambucanas.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Vou comprar pão de jacó antes da aula.",
    contextNotes: "Variação alimentar regional, sem risco.",
    origin: "Vocabulário pernambucano de padaria.",
    variations: ["pão francês", "pãozinho"],
    popularityStatus: "regional",
    region: "Nordeste (PE)",
  },
  {
    term: "cacetinho",
    meaning: "Nome regional para pão francês no Rio Grande do Sul.",
    adultTranslation: "Pão francês.",
    context: "Usado em padarias e conversas familiares no Sul.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Traz meia dúzia de cacetinhos.",
    contextNotes: "Apesar do som ambíguo fora da região, é termo neutro para pão.",
    origin: "Vocabulário gaúcho.",
    variations: ["pão francês", "pãozinho"],
    popularityStatus: "regional",
    region: "Sul (RS)",
  },
  {
    term: "lagartear",
    meaning: "Ficar no sol para se aquecer ou descansar.",
    adultTranslation: "Tomar sol / Ficar se aquecendo.",
    context: "Expressão comum no Sul, especialmente em dias frios.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Depois do almoço vou lagartear no pátio.",
    contextNotes: "Termo bem-humorado e inofensivo.",
    origin: "Comparação com lagartos tomando sol.",
    variations: ["lagarteando", "lagarteada"],
    popularityStatus: "regional",
    region: "Sul (RS/SC)",
  },
  {
    term: "bergamota",
    meaning: "Nome regional para mexerica/tangerina.",
    adultTranslation: "Tangerina / Mexerica.",
    context: "Muito usada no Rio Grande do Sul e em partes de Santa Catarina.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Levei bergamota de lanche.",
    contextNotes: "Variação alimentar regional, sem risco.",
    origin: "Vocabulário sulista.",
    variations: ["mexerica", "tangerina", "vergamota"],
    popularityStatus: "regional",
    region: "Sul (RS/SC)",
  },
  {
    term: "ratiar",
    meaning: "Errar, vacilar ou perder uma chance por distração.",
    adultTranslation: "Vacilar / Errar / Dar bobeira.",
    context: "Usada no Sul em conversas jovens e cotidianas.",
    category: "regional",
    riskLevel: "yellow",
    safeExample: "Eu ratiei e perdi o prazo do trabalho.",
    contextNotes: "Pode soar autocrítica ou cobrança leve.",
    origin: "Fala popular sulista.",
    variations: ["ratiei", "ratear"],
    popularityStatus: "regional",
    region: "Sul (RS/SC/PR)",
  },
  {
    term: "baita",
    meaning: "Muito grande, intenso ou excelente.",
    adultTranslation: "Enorme / Excelente / Muito bom.",
    context: "Intensificador bastante comum no Sul.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Foi uma baita apresentação.",
    contextNotes: "Uso positivo ou de intensidade.",
    origin: "Fala sulista e português coloquial.",
    variations: ["baita de um", "baita coisa"],
    popularityStatus: "regional",
    region: "Sul (RS/SC/PR)",
  },
];
