// =============================================================================
// Brazilian Teen Slang Dictionary — Extra Set 11 (150 terms)
// Gen Alpha / TikTok / Gaming Focus
// =============================================================================

import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_11: SlangTerm[] = [
  // 1. skibidi
  { term: "skibidi", meaning: "Termo sem sentido fixo usado como interjeição, adjetivo ou advérbio para enfatizar algo bizarro ou aleatório.", adultTranslation: "Expressão sem sentido / Interjeição de ênfase / Termo bizarro.", context: "Usado isoladamente ou como adjetivo em frases sem lógica aparente, tipicamente pelo Gen Alpha.", category: "meme", riskLevel: "green", safeExample: "Skibidi toilet é a coisa mais aleatória que já vi.", contextNotes: "Termo originado de memes que perdeu qualquer significado literal. É usado como filler word pelos mais jovens. Inofensivo, mas pode confundir adultos.", origin: "Meme do YouTube/TikTok 'Skibidi Toilet', viralizado em 2023.", variations: ["skibidi toilet", "skibidi sigma"], popularityStatus: "ativo", region: "internacional" },

  // 2. mewing
  { term: "mewing", meaning: "Técnica de postura da mandíbula e língua para melhorar a definição do maxilar e aparência facial.", adultTranslation: "Técnica de postura facial / Exercício de mandíbula.", context: "Usado quando alguém faz pose de mewing silenciosamente, geralmente em fotos ou vídeos.", category: "gaming", riskLevel: "green", safeExample: "Ele tava mewing na foto e ficou com uma cara diferente.", contextNotes: "Prática de beleza masculina popularizada no TikTok. Envolve colocar a língua no céu da boca. Inofensivo, mas pode gerar preocupações com imagem corporal.", origin: "Do ortodontista John Mew, popularizado pelo TikTok em 2023.", variations: ["mew", "mewing streak", "looksmaxxing mewing"], popularityStatus: "ativo", region: "internacional" },

  // 3. gyatt
  { term: "gyatt", meaning: "Interjeição usada para expressar admiração por uma pessoa atraente, especialmente curvas femininas.", adultTranslation: "Nossa / Caramba (por atratividade) / Interjeição de admiração.", context: "Usado como reação a fotos ou vídeos de pessoas consideradas muito atraentes.", category: "elogio", riskLevel: "yellow", safeExample: "Gyatt! Ela tá muito bem nessa foto.", contextNotes: "Interjeição que pode soar inadequada dependendo do contexto. Geralmente usada para comentar sobre aparência física de forma exagerada. Orientar sobre respeito.", origin: "Do inglês 'god' ou 'goddamn' deturpado, popularizado por streamers no Twitch e TikTok.", variations: ["gyat", "gyatt damn"], popularityStatus: "ativo", region: "internacional" },

  // 4. fanum tax
  { term: "fanum tax", meaning: "Ato de pegar comida de alguém sem permissão, especialmente de amigos, como uma 'taxa'.", adultTranslation: "Pegar comida do outro / 'Taxa' de comida / Roubar petisco.", context: "Usado de forma cômica quando alguém pega um pedaço da comida de amigo.", category: "humor", riskLevel: "green", safeExample: "Vou aplicar o fanum tax nessa batata frita sua!", contextNotes: "Meme cômico do streamer Fanum que pegava comida dos amigos. Usado de forma leve e humorística. Totalmente inofensivo entre amigos.", origin: "Do streamer Fanum, do grupo AMP, popularizado no TikTok a partir de 2022.", variations: ["fanum", "taxar a comida", "fanum taxou"], popularityStatus: "ativo", region: "internacional" },

  // 5. ohio
  { term: "ohio", meaning: "Referência ao estado dos EUA associado a coisas estranhas, bizarros e inexplicáveis.", adultTranslation: "Coisa bizarra / Estranho / Fora do normal.", context: "Usado para descrever algo estranho, engraçado ou inexplicável, comparando ao Ohio.", category: "meme", riskLevel: "green", safeExample: "Essa situação foi muito ohio, nem sei explicar.", contextNotes: "Meme que satiriza o estado de Ohio como lugar de coisas estranhas. Totalmente humorístico e inofensivo. Pode confundir quem não conhece a referência.", origin: "Meme do TikTok que associa Ohio a coisas estranhas e inexplicáveis, a partir de 2022.", variations: ["only in ohio", "ohio moment", "ohio energy"], popularityStatus: "ativo", region: "internacional" },

  // 6. rizzler
  { term: "rizzler", meaning: "Pessoa com muita habilidade de sedução e carisma, mestre do rizz.", adultTranslation: "Pessoa carismática / Sedutor nato / Mestre da paquera.", context: "Elogio para alguém que é muito bom em conquistar e se comunicar.", category: "elogio", riskLevel: "green", safeExample: "Esse cara é o rizzler, todo mundo gosta dele.", contextNotes: "Derivado de 'rizz' (charisma). Refere-se a alguém com muita habilidade social e de paquera. Positivo e inofensivo.", origin: "Do streamer Kai Cenat, combinação de 'rizz' com '-er'. Popularizado no TikTok.", variations: ["rizz god", "rizz king", "rizzlord"], popularityStatus: "ativo", region: "internacional" },

  // 7. looksmaxxing
  { term: "looksmaxxing", meaning: "Prática de melhorar a aparência física ao máximo usando rotinas, cosméticos, exercícios e dicas.", adultTranslation: "Maximizar a aparência / Melhorar o visual ao máximo.", context: "Usado por jovens que buscam melhorar sua aparência seguindo dicas e rotinas.", category: "gaming", riskLevel: "green", safeExample: "Ele tá no looksmaxxing há 3 meses e mudou bastante.", contextNotes: "Pode ser saudável quando envolve autocuidado, mas versões extremas podem gerar problemas de autoestima. Observar se o jovem não desenvolve obsessão com aparência.", origin: "Comunidades de fóruns como Looksmax.org, popularizado no TikTok a partir de 2023.", variations: ["looksmax", "maxxar o look", "mewing looksmaxxing"], popularityStatus: "ativo", region: "internacional" },

  // 8. mogging
  { term: "mogging", meaning: "Superar alguém em aparência ou habilidade, deixando a pessoa em desvantagem visual.", adultTranslation: "Superar em aparência / Destacar-se visualmente.", context: "Usado quando alguém se destaca mais que outro em termos de aparência ou presença.", category: "gaming", riskLevel: "yellow", safeExample: "Ele tá mogging todo mundo na foto de grupo.", contextNotes: "Termo que pode ser usado de forma competitiva e negativa, criando comparações. Pode afetar a autoestima de quem é 'mogged'. Orientar sobre valor individual.", origin: "Do termo 'AMOG' (Alpha Male Of Group), de fóruns de pua/hypermasculinidade, popularizado no TikTok.", variations: ["mog", "mogged", "mog or be mogged"], popularityStatus: "ativo", region: "internacional" },

  // 9. edging
  { term: "edging", meaning: "Levar algo ao limite sem concluir, segurar a empolgação ou adrenalina no limite.", adultTranslation: "Segurar no limite / Protelar algo no ápice.", context: "Usado metaforicamente para descrever segurar emoção ou excitação.", category: "humor", riskLevel: "orange", safeExample: "Esse filme foi puro edging, não chegava ao clímax.", contextNotes: "Originalmente termo sexual, entre jovens passou a ser usado metaforicamente para 'segurar no limite'. Pode ter duplo sentido dependendo do contexto. Investigar o uso.", origin: "Termo sexual adotado como metáfora pelo Gen Alpha no TikTok.", variations: ["edge", "edging meme", "edging moment"], popularityStatus: "ativo", region: "internacional" },

  // 10. yapping
  { term: "yapping", meaning: "Falar demais, tagarelar sem parar sobre algo que não tem muita importância.", adultTranslation: "Tagarelar / Falar demais / Blábláblá.", context: "Usado quando alguém está falando muito sem parar sobre algo sem relevância.", category: "humor", riskLevel: "green", safeExample: "Para de yapping e vamos assistir o filme!", contextNotes: "Termo leve para descrever alguém falativo. Pode soar rude se usado para interromper alguém. Orientar sobre escuta ativa e respeito ao outro.", origin: "Do inglês 'yap' (latido), popularizado no TikTok em 2024 como 'yapper'.", variations: ["yap", "yapper", "stop yapping"], popularityStatus: "ativo", region: "internacional" },

  // 11. aura
  { term: "aura", meaning: "Energia, vibração ou presença que alguém transmite. Também usado como ponto de status social.", adultTranslation: "Energia pessoal / Vibração / Presença / Status.", context: "Usado para classificar a energia ou presença de alguém em uma escala.", category: "elogio", riskLevel: "green", safeExample: "O aura dele tá alto hoje, confiança total!", contextNotes: "Termo positivo para descrever boa energia ou presença. No entanto, 'perder aura' pode ser usado para zoar. Contextualizar como autoconfiança positiva.", origin: "Conceito esotérico adaptado pelo TikTok, especialmente comunidade de memes e gaming.", variations: ["aura points", "negative aura", "farmar aura", "max aura"], popularityStatus: "ativo", region: "internacional" },

  // 12. farmar aura
  { term: "farmar aura", meaning: "Acumular pontos de aura fazendo coisas legais, engraçadas ou impressionantes.", adultTranslation: "Ganhar pontos de respeito / Acumular boa reputação.", context: "Usado quando alguém faz algo que aumenta sua imagem social positivamente.", category: "elogio", riskLevel: "green", safeExample: "Essa jogada genial vai farmar muito aura pra ele.", contextNotes: "Metáfora de jogos onde 'farmar' significa colecionar recursos. Aqui significa ganhar reputação. Positivo e motivador.", origin: "Combinação do gaming term 'farmar' com 'aura', popularizado no TikTok brasileiro.", variations: ["farming aura", "ganhar aura", "aura farm"], popularityStatus: "ativo", region: "Brasil" },

  // 13. bussin
  { term: "bussin", meaning: "Algo muito bom, delicioso, incrível. Usado especialmente para comida.", adultTranslation: "Muito bom / Delicioso / Incrível.", context: "Usado para descrever comida deliciosa ou algo muito bom de forma geral.", category: "elogio", riskLevel: "green", safeExample: "Esse bolo tá bussin, preciso da receita!", contextNotes: "Termo positivo para elogiar, especialmente comida. Inofensivo e muito comum no TikTok.", origin: "AAVE (African American Vernacular English), popularizado pelo TikTok em 2021.", variations: ["bussin bussin", "that's bussin"], popularityStatus: "ativo", region: "internacional" },

  // 14. betabuxxing
  { term: "betabuxxing", meaning: "Comportamento de gastar dinheiro excessivamente com alguém tentando impressionar ou conquistar.", adultTranslation: "Gastar para impressionar / Pagar mimos em excesso.", context: "Usado para criticar quem gasta demais tentando comprar afeto ou atenção.", category: "humor", riskLevel: "yellow", safeExample: "Ele tá no betabuxxing, gastando tudo em presentes.", contextNotes: "Termo que pode reforçar estereótipos de gênero. Usado para descrever comportamento de 'pagador'. Pode ser machista dependendo do contexto.", origin: "Comunidades de fóruns como incels/Red Pill, adaptado como meme no TikTok.", variations: ["betabux", "beta bux"], popularityStatus: "ativo", region: "internacional" },

  // 15. no cap
  { term: "no cap", meaning: "Sem mentira, falando sério, de verdade, sem exagero.", adultTranslation: "Sem mentira / Falando sério / É verdade.", context: "Usado para enfatizar que se está dizendo a verdade.", category: "saudacao", riskLevel: "green", safeExample: "No cap, esse foi o melhor jogo que já assisti.", contextNotes: "Expressão muito comum entre jovens para autenticar uma afirmação. Equivalente a 'juro por Deus'. Inofensivo.", origin: "AAVE e cultura hip-hop, 'cap' = mentira. 'No cap' = sem mentira. Popularizado globalmente.", variations: ["cap", "no cap fr", "capping"], popularityStatus: "ativo", region: "internacional" },

  // 16. fr fr
  { term: "fr fr", meaning: "Para real, literalmente, sério mesmo. Dupla ênfase em 'for real'.", adultTranslation: "Sério mesmo / Literalmente / De verdade.", context: "Usado para concordar enfaticamente ou afirmar algo com convicção.", category: "saudacao", riskLevel: "green", safeExample: "Fr fr, esse professor é muito bom.", contextNotes: "Abreviação dupla de 'for real'. Totalmente inofensivo, expressão de concordância e ênfase.", origin: "AAVE, popularizado pelo TikTok e Instagram entre adolescentes.", variations: ["fr", "for real", "fr tho"], popularityStatus: "ativo", region: "internacional" },

  // 17. bombastic side eye
  { term: "bombastic side eye", meaning: "Olhar de canto extremamente julgador, expressão facial de reprovação exagerada.", adultTranslation: "Olhar de reprovação / Olhar de julgamento intenso.", context: "Usado como reação a algo cringe ou inapropriado, acompanhado de表情 de julgamento.", category: "humor", riskLevel: "green", safeExample: "Dei um bombastic side eye quando ele disse aquilo.", contextNotes: "Meme cômico de reação facial. Totalmente humorístico e inofensivo. Pode ser usado de forma passivo-agressiva.", origin: "Meme do TikTok com a música 'Bombastic Side Eye' de Chloe e Halle, viralizado em 2023.", variations: ["side eye", "criminal offensive side eye"], popularityStatus: "ativo", region: "internacional" },

  // 18. NPC
  { term: "NPC", meaning: "Pessoa sem personalidade própria, que segue a massa, ou personagem de jogo controlado por IA.", adultTranslation: "Pessoa sem originalidade / Seguidor / Personagem de jogo.", context: "Usado para descrever alguém que age de forma robótica ou segue tendências sem pensar.", category: "ironia", riskLevel: "yellow", safeExample: "Ele não tem opinião própria, é NPC demais.", contextNotes: "Do gaming 'Non-Player Character'. Pode ser usado como ofensa a quem pensa diferente. Orientar sobre respeito à diversidade de opiniões.", origin: "Termo de videogames (Non-Player Character), adaptado como insulto político e social.", variations: ["NPC energy", "NPC behavior", "being NPC"], popularityStatus: "ativo", region: "internacional" },

  // 19. sigma
  { term: "sigma", meaning: "Pessoa independente, autoconfiante, que não precisa de validação social. Macho solitário bem-sucedido.", adultTranslation: "Pessoa independente / Autoconfiante / Solitário bem-sucedido.", context: "Elogio para quem é autoconfiante e não segue as regras sociais tradicionais.", category: "elogio", riskLevel: "yellow", safeExample: "Ele é sigma, não liga pra opinião de ninguém.", contextNotes: "Pode ter conotação de masculinidade tóxica quando leva ao extremo. Versão leve significa apenas independência. Observar o contexto de uso.", origin: "Comunidades de memes e fóruns masculinos, associado ao 'sigma male'. Patrick Bateman é meme sigma.", variations: ["sigma male", "sigma grindset", "sigma meme"], popularityStatus: "ativo", region: "internacional" },

  // 20. wallah
  { term: "wallah", meaning: "Juro, eu juro. Expressão de juramento emprestada do árabe.", adultTranslation: "Juro / Eu juro por Deus.", context: "Usado como juramento para enfatizar que se está dizendo a verdade.", category: "saudacao", riskLevel: "green", safeExample: "Wallah, eu não fui eu que quebrei isso!", contextNotes: "Empréstimo linguístico do árabe. Muito usado por jovens muçulmanos e popularizado entre adolescentes em geral. Inofensivo.", origin: "Do árabe 'wallahi' (juro por Deus), popularizado entre jovens europeus e brasileiros via TikTok.", variations: ["wallahi", "bro wallah"], popularityStatus: "ativo", region: "internacional" },

  // 21. on god
  { term: "on god", meaning: "Juro por Deus, é sério, de verdade.", adultTranslation: "Juro por Deus / É verdade / Sério.", context: "Expressão de juramento semelhante a 'no cap' mas com mais ênfase.", category: "saudacao", riskLevel: "green", safeExample: "On god, esse foi o melhor dia da minha vida.", contextNotes: "Expressão de autenticidade muito comum entre jovens. Equivalente a 'juro'. Inofensivo.", origin: "AAVE e cultura hip-hop, popularizado globalmente pelo TikTok.", variations: ["ongod", "on god fr", "on god period"], popularityStatus: "ativo", region: "internacional" },

  // 22. chat
  { term: "chat", meaning: "Referência à audiência de stream, os espectadores assistindo uma live.", adultTranslation: "Audiência / Espectadores / Público da live.", context: "Usado por quem assiste streams para se referir a si e aos outros espectadores.", category: "gaming", riskLevel: "green", safeExample: "Chat, vocês viram essa jogada insana?", contextNotes: "Termo do streaming. Os jovens usam ironicamente no dia a dia para falar com um público imaginário. Inofensivo.", origin: "Cultura de streaming na Twitch e YouTube, adotado como gíria pelo Gen Alpha.", variations: ["chat relaxa", "chat chorou", "chat é isso"], popularityStatus: "ativo", region: "internacional" },

  // 23. lowkey
  { term: "lowkey", meaning: "Secretamente, discretamente, de forma sutil, ou meio/mais ou menos.", adultTranslation: "Discretamente / Secretamente / Mais ou menos.", context: "Usado para suavizar uma afirmação ou falar sobre algo de forma discreta.", category: "outros", riskLevel: "green", safeExample: "Lowkey quero ir na festa, mas não quero parecer desesperado.", contextNotes: "Termo muito versátil que pode significar 'discretamente' ou 'mais ou menos'. Inofensivo e extremamente comum.", origin: "AAVE, popularizado pelo hip-hop e redes sociais entre adolescentes.", variations: ["lowkey kinda", "lowkey fr"], popularityStatus: "ativo", region: "internacional" },

  // 24. highkey
  { term: "highkey", meaning: "Abrutamente, abertamente, sem esconder, definitivamente.", adultTranslation: "Abertamente / Sem dúvida / Definitivamente.", context: "Oposto de lowkey, usado para enfatizar algo sem reservas.", category: "outros", riskLevel: "green", safeExample: "Highkey quero ir na festa, tô muito empolgado!", contextNotes: "Oposto de lowkey. Expressão de ênfase positiva. Inofensivo.", origin: "AAVE, popularizado como antônimo de lowkey no TikTok.", variations: ["highkey fr", "highkey obsessed"], popularityStatus: "ativo", region: "internacional" },

  // 25. tight
  { term: "tight", meaning: "Legal, bom, arrumado, ou situação boa.", adultTranslation: "Legal / Bom / Maneiro / Situação boa.", context: "Usado como elogio para algo que é bom ou uma situação legal.", category: "elogio", riskLevel: "green", safeExample: "Essa camisa está tight, combina com tudo!", contextNotes: "Termo em inglês que significa 'apertado' mas na gíria significa 'legal'. Pode confundir tradutores. Inofensivo.", origin: "Slang americano de longa data, mantido entre jovens via cultura pop.", variations: ["that's tight", "tight af"], popularityStatus: "ativo", region: "internacional" },

  // 26. slaps
  { term: "slaps", meaning: "Algo muito bom, especialmente música ou comida. Bateu diferente, ficou incrível.", adultTranslation: "Muito bom / Incrível / Sensacional.", context: "Usado para elogiar música, comida ou qualquer coisa muito boa.", category: "elogio", riskLevel: "green", safeExample: "Essa música slaps demais, não tiro do repeat!", contextNotes: "Termo extremamente positivo, especialmente para música. Totalmente inofensivo.", origin: "Slang americano, popularizado pelo TikTok e cultura musical.", variations: ["this slaps", "slaps hard", "slaps different"], popularityStatus: "ativo", region: "internacional" },

  // 27. fire
  { term: "fire", meaning: "Incrível, excelente, algo muito bom e impressionante.", adultTranslation: "Incrível / Excelente / Arrasador.", context: "Elogio genérico para algo muito bom, especialmente música, visual ou performance.", category: "elogio", riskLevel: "green", safeExample: "Essa playlist está fire, curti muito!", contextNotes: "Um dos elogios mais comuns entre jovens. Significa 'fogo' no sentido de incrível. Totalmente positivo.", origin: "Slang hip-hop americano, popularizado globalmente.", variations: ["fire af", "that's fire", "straight fire"], popularityStatus: "ativo", region: "internacional" },

  // 28. mid
  { term: "mid", meaning: "Mediano, medíocre, nada especial, ok mas não impressionante.", adultTranslation: "Medíocre / Mais ou menos / Nada especial.", context: "Usado para descrever algo que não é ruim nem bom, apenas mediano.", category: "ironia", riskLevel: "yellow", safeExample: "O filme era mid, nem bom nem ruim.", contextNotes: "Pode soar desdenhoso quando aplicado ao trabalho de alguém. Orientar sobre construtividade nas críticas.", origin: "Slang americano, popularizado pelo streamer Tyler1 e espalhado pelo TikTok.", variations: ["mid tier", "mid af", "kinda mid"], popularityStatus: "ativo", region: "internacional" },

  // 29. cooked
  { term: "cooked", meaning: "Ferrado, sem saída, em apuros sérios, destruído.", adultTranslation: "Ferrado / Sem saída / Em apuros.", context: "Usado quando alguém está em uma situação difícil sem solução.", category: "humor", riskLevel: "yellow", safeExample: "Esqueci a prova amanhã, tô cooked.", contextNotes: "Termo usado de forma cômica para descrever problemas. Geralmente é leve e humorístico, mas pode indicar ansiedade real. Verificar se o jovem está bem.", origin: "Slang americano, popularizado no TikTok como meme reaction.", variations: ["we're cooked", "totally cooked", "cooked af"], popularityStatus: "ativo", region: "internacional" },

  // 30. goated
  { term: "goated", meaning: "O melhor de todos, lendário, imbatível. Derivado de GOAT (Greatest Of All Time).", adultTranslation: "O melhor / Lendário / Imbatível.", context: "Elogio máximo para alguém ou algo excepcional.", category: "elogio", riskLevel: "green", safeExample: "O Messi é goated, nunca vi ninguém jogar assim.", contextNotes: "Abreviação de GOAT. Elogio extremamente positivo e comum. Totalmente inofensivo.", origin: "Do acrônimo GOAT (Greatest Of All Time), cultura esportiva e hip-hop.", variations: ["GOAT", "the goat", "goated af"], popularityStatus: "ativo", region: "internacional" },

  // 31. W
  { term: "W", meaning: "Vitória, win, algo positivo, resultado bom.", adultTranslation: "Vitória / Ganho / Resultado positivo.", context: "Usado para celebrar algo bom que aconteceu.", category: "elogio", riskLevel: "green", safeExample: "Passei na prova, pura W!", contextNotes: "Letra W de 'win'. Expressão de celebração muito comum. Totalmente positiva.", origin: "Cultura gaming e esports, popularizado entre jovens.", variations: ["dub", "big W", "take the W"], popularityStatus: "ativo", region: "internacional" },

  // 32. L
  { term: "L", meaning: "Derrota, perda, algo negativo, erro.", adultTranslation: "Derrota / Perda / Resultado negativo.", context: "Usado para descrever algo ruim que aconteceu ou um erro.", category: "ironia", riskLevel: "green", safeExample: "Rodou na prova, tomou um L.", contextNotes: "Letra L de 'loss'. Pode ser usado de forma cômica ou para minimizar algo ruim. Observar se está sendo usado para zoar de alguém de forma cruel.", origin: "Cultura gaming e esports, oposto de W.", variations: ["take the L", "big L", "massive L"], popularityStatus: "ativo", region: "internacional" },

  // 33. ratioed
  { term: "ratioed", meaning: "Quando uma resposta tem mais curtidas que o post original, significando que a resposta venceu.", adultTranslation: "Superado em resposta / Perdeu o debate / Contrapostado.", context: "Usado quando alguém responde de forma mais inteligente ou engraçada que o original.", category: "ironia", riskLevel: "green", safeExample: "Ele tentou ser engraçado mas foi ratioado.", contextNotes: "Termo de redes sociais. Pode ser usado como forma de cyberbullying se o objetivo for humilhar. Orientar sobre debate saudável.", origin: "Cultura do Twitter/X, onde o ratio (proporção de likes) determina quem venceu.", variations: ["ratio", "get ratioed", "ratio'd"], popularityStatus: "ativo", region: "internacional" },

  // 34. clutch
  { term: "clutch (gen alpha)", meaning: "Agir bem sob pressão nos últimos momentos, salvar a situação no apito final.", adultTranslation: "Salvador de última hora / Agir sob pressão.", context: "Usado para elogiar quem se sai bem em momentos decisivos.", category: "gaming", riskLevel: "green", safeExample: "Ele acertou a questão no último minuto, clutch!", contextNotes: "Termo positivo que destaca resiliência e competência sob pressão. Inofensivo e motivador.", origin: "Esportes e gaming, popularizado entre jovens Gen Alpha.", variations: ["clutch moment", "clutch af"], popularityStatus: "ativo", region: "internacional" },

  // 35. carry
  { term: "carry", meaning: "Carregar o time, ser o principal responsável pela vitória ou bom resultado.", adultTranslation: "Carregar o time / Ser o destaque / Puxar o peso.", context: "Usado em jogos ou trabalhos em grupo quando alguém faz a maior parte.", category: "gaming", riskLevel: "green", safeExample: "Ele deu carry no trabalho em grupo inteiro.", contextNotes: "Termo positivo quando se destaca por esforço. Pode gerar ressentimento se usado para diminuir o esforço dos outros. Inofensivo no geral.", origin: "Cultura gaming, especialmente LoL e jogos competitivos.", variations: ["carry hard", "hard carry", "being carried"], popularityStatus: "ativo", region: "internacional" },

  // 36. feed
  { term: "feed", meaning: "Dar kills repetidas ao inimigo, alimentar o adversário deixando-o forte.", adultTranslation: "Facilitar para o inimigo / Errar repetidamente.", context: "Usado quando alguém comete muitos erros que beneficiam o adversário.", category: "gaming", riskLevel: "green", safeExample: "Para de feedar que o jogo tá perdido!", contextNotes: "Termo gamer que pode ser usado para culpar colegas. Pode gerar conflito se usado de forma agressiva. Orientar sobre trabalho em equipe.", origin: "Cultura gaming, especialmente LoL e Dota.", variations: ["feeding", "feeder", "stop feeding"], popularityStatus: "ativo", region: "internacional" },

  // 37. smurf
  { term: "smurf", meaning: "Jogador experiente jogando com conta nova de nível baixo para dominar iniciantes.", adultTranslation: "Jogador experiente com conta falsa / Dominar novatos.", context: "Usado para descrever alguém que é muito melhor que o nível da partida.", category: "gaming", riskLevel: "green", safeExample: "Esse cara é smurf, ninguém consegue ganhar dele.", contextNotes: "Termo neutro do gaming. Pode ser elogio ou reclamação. Inofensivo no contexto de jogos.", origin: "Cultura gaming, lendária história de jogadores profissionais de Warcraft III.", variations: ["smurfing", "smurf account", "smurf player"], popularityStatus: "ativo", region: "internacional" },

  // 38. tilt
  { term: "tilt", meaning: "Ficar irritado, perder o controle emocional, jogar mal por raiva.", adultTranslation: "Ficar irritado / Perder a cabeça / Frustrado.", context: "Usado quando alguém perde o controle emocional durante um jogo ou situação.", category: "gaming", riskLevel: "green", safeExample: "Ele tá em tilt, melhor deixar quieto por enquanto.", contextNotes: "Termo que descreve perda emocional. Pode afetar relacionamentos. Orientar sobre regulação emocional.", origin: "Pôquer e cultura gaming, popularizado globalmente.", variations: ["tilted", "tilting", "on tilt"], popularityStatus: "ativo", region: "internacional" },

  // 39. rage quit
  { term: "rage quit", meaning: "Sair de um jogo ou situação de forma brusca por frustração ou raiva.", adultTranslation: "Sair com raiva / Abandonar de forma explosiva.", context: "Usado quando alguém sai abruptamente de um jogo por estar perdendo.", category: "gaming", riskLevel: "green", safeExample: "Ele deu rage quit no meio da partida, tava nervoso.", contextNotes: "Comum em jogos, pode indicar falta de controle emocional. Discutir sobre resiliência e esportividade.", origin: "Cultura gaming desde os anos 2000, popularizado por vídeos de reação.", variations: ["ragequit", "rq", "rage quitting"], popularityStatus: "ativo", region: "internacional" },

  // 40. tryhard
  { term: "tryhard", meaning: "Alguém que tenta demais, se esforça excessivamente para impressionar ou vencer.", adultTranslation: "Esforçado demais / Tentador / Que tenta demais.", context: "Usado para descrever quem se esforça demais em algo, geralmente de forma visível.", category: "ironia", riskLevel: "yellow", safeExample: "Ele é tryhard demais na aula de educação física.", contextNotes: "Pode ser usado para zombar de quem se esforça. Pode desmotivar pessoas que estão apenas tentando fazer seu melhor. Orientar sobre respeito ao esforço alheio.", origin: "Cultura gaming, depois adotado no dia a dia.", variations: ["tryharding", "tryhard energy", "such a tryhard"], popularityStatus: "ativo", region: "internacional" },

  // 41. sweat
  { term: "sweat", meaning: "Jogador que se esforça demais, joga com muita intensidade e seriedade, geralmente em jogos casuais.", adultTranslation: "Jogador intenso / Excessivamente competitivo.", context: "Usado para descrever jogadores que levam jogos casuais a sério demais.", category: "gaming", riskLevel: "green", safeExample: "Esse cara é sweat demais pra um modo casual.", contextNotes: "Termo gamer neutro. Pode ser elogio (dedicação) ou crítica (excesso). Contextualizar.", origin: "Cultura gaming, especialmente Fortnite e Call of Duty.", variations: ["sweaty", "sweaty player", "sweatlord"], popularityStatus: "ativo", region: "internacional" },

  // 42. noob
  { term: "noob", meaning: "Iniciante, novato, alguém que não tem experiência em algo.", adultTranslation: "Iniciante / Novato / Principiante.", context: "Usado para descrever alguém sem experiência em jogos ou qualquer atividade.", category: "gaming", riskLevel: "yellow", safeExample: "Todo mundo já foi noob em alguma coisa.", contextNotes: "Pode ser usado de forma acolhedora ou como insulto. Orientar sobre paciência com iniciantes e empatia.", origin: "Cultura gaming desde os anos 1990, do inglês 'newbie'.", variations: ["newb", "newbie", "noobz"], popularityStatus: "ativo", region: "internacional" },

  // 43. op
  { term: "op", meaning: "Overpowered, algo ou alguém muito forte, acima do normal, injustamente poderoso.", adultTranslation: "Excessivamente forte / Muito poderoso / Acima do normal.", context: "Usado para descrever algo muito forte em jogos ou na vida real.", category: "gaming", riskLevel: "green", safeExample: "Essa arma é muito op, precisa de nerf.", contextNotes: "Termo neutro do gaming. Inofensivo no contexto de jogos.", origin: "Cultura gaming, especialmente RPGs e jogos competitivos.", variations: ["overpowered", "too op", "op af"], popularityStatus: "ativo", region: "internacional" },

  // 44. meta
  { term: "meta", meaning: "Melhor estratégia, tática ou tendência atual em jogos ou na vida.", adultTranslation: "Melhor estratégia / Tendência atual / Padrão ideal.", context: "Usado para descrever o que está funcionando melhor no momento.", category: "gaming", riskLevel: "green", safeExample: "Usar essa estratégia é a meta agora, todo mundo tá usando.", contextNotes: "Termo versátil do gaming que migrou para o dia a dia. Positivo e construtivo.", origin: "Cultura gaming, 'meta' como metanálise da melhor estratégia.", variations: ["meta game", "na meta", "off meta"], popularityStatus: "ativo", region: "internacional" },

  // 45. buff
  { term: "buff (gaming)", meaning: "Melhoria, fortalecimento de algo ou alguém. Deixar mais forte.", adultTranslation: "Melhoria / Fortalecimento / Impulso.", context: "Usado quando algo é melhorado ou quando alguém está em boa forma física.", category: "gaming", riskLevel: "green", safeExample: "Esse personagem recebeu um buff na última atualização.", contextNotes: "Termo positivo do gaming. Inofensivo.", origin: "Cultura gaming de RPGs e jogos online.", variations: ["buffado", "dar buff", "receber buff"], popularityStatus: "ativo", region: "internacional" },

  // 46. nerf
  { term: "nerf", meaning: "Enfraquecer, reduzir o poder de algo ou alguém.", adultTranslation: "Enfraquecer / Reduzir / Diminuir poder.", context: "Usado quando algo é tornado mais fraco ou menos eficaz.", category: "gaming", riskLevel: "green", safeExample: "A prova foi nerfada, ficou mais fácil que o esperado.", contextNotes: "Metáfora do gaming. Inofensivo e criativo.", origin: "Da marca Nerf (armas de espuma), cultura gaming.", variations: ["nerfado", "nerfar", "foi nerfado"], popularityStatus: "ativo", region: "internacional" },

  // 47. drop
  { term: "drop", meaning: "Lançamento de produto, música ou conteúdo novo. Item raro que aparece em jogo.", adultTranslation: "Lançamento / Novidade / Item raro.", context: "Usado para falar sobre lançamentos ou itens novos em jogos.", category: "gaming", riskLevel: "green", safeExample: "O novo drop do artista foi insano!", contextNotes: "Termo positivo para lançamentos. Totalmente inofensivo.", origin: "Cultura streetwear e gaming, popularizado por marcas e jogos.", variations: ["new drop", "drop date", "rare drop"], popularityStatus: "ativo", region: "internacional" },

  // 48. pvp
  { term: "pvp", meaning: "Player versus Player, combate direto entre jogadores.", adultTranslation: "Jogador contra jogador / Combate direto.", context: "Usado para descrever modos de jogo onde se luta contra outros jogadores.", category: "gaming", riskLevel: "green", safeExample: "Vamos jogar pvp que é mais emocionante.", contextNotes: "Sigla comum do gaming. Inofensivo.", origin: "Sigla de 'Player Versus Player', cultura gaming global.", variations: ["PvP mode", "pvp arena"], popularityStatus: "ativo", region: "internacional" },

  // 49. pve
  { term: "pve", meaning: "Player versus Environment, combate contra inimigos controlados pelo jogo.", adultTranslation: "Jogador contra o jogo / Combate contra IA.", context: "Usado para descrever modos de jogo cooperativos contra o computador.", category: "gaming", riskLevel: "green", safeExample: "Hoje é dia de PVE, bora fazer dungeon com a galera.", contextNotes: "Sigla comum do gaming. Inofensivo.", origin: "Sigla de 'Player Versus Environment', cultura gaming.", variations: ["PvE content", "pve mode"], popularityStatus: "ativo", region: "internacional" },

  // 50. dps
  { term: "dps", meaning: "Damage per Second, dano por segundo. Classe focada em causar dano em jogos.", adultTranslation: "Dano por segundo / Classe de ataque / Atacante.", context: "Usado para descrever jogadores focados em causar dano ou medir eficiência.", category: "gaming", riskLevel: "green", safeExample: "Meu DPS tá alto hoje, tô causando muito dano.", contextNotes: "Sigla técnica do gaming. Inofensivo.", origin: "Sigla de 'Damage Per Second', cultura gaming RPG e MMO.", variations: ["DPS check", "DPS role", "main DPS"], popularityStatus: "ativo", region: "internacional" },

  // 51. tank
  { term: "tank", meaning: "Classe ou jogador focado em aguentar dano e proteger o time.", adultTranslation: "Tanque / Protetor / Resistente.", context: "Usado para descrever quem absorve dano ou é muito resistente em jogos.", category: "gaming", riskLevel: "green", safeExample: "Vou de tank na próxima partida pra proteger vocês.", contextNotes: "Termo positivo do gaming sobre proteção e resistência. Inofensivo.", origin: "Cultura gaming de RPGs e MOBAs.", variations: ["tanking", "main tank", "off tank"], popularityStatus: "ativo", region: "internacional" },

  // 52. ranked
  { term: "ranked", meaning: "Modo competitivo de jogo com sistema de classificação/pontos.", adultTranslation: "Modo competitivo / Ranqueada / Com pontos.", context: "Usado para descrever partidas competitivas com ranking.", category: "gaming", riskLevel: "green", safeExample: "Tô jogando ranked hoje, preciso subir de elo.", contextNotes: "Termo comum do gaming competitivo. Inofensivo.", origin: "Cultura gaming competitiva, especialmente LoL, Valorant, CS.", variations: ["ranked match", "ranked game", "jogar ranqueada"], popularityStatus: "ativo", region: "internacional" },

  // 53. gg ez
  { term: "gg ez", meaning: "Good game, easy. Vitória fácil, partirda sem esforço. Pode ser provocativo.", adultTranslation: "Jogo bom, foi fácil / Vitória fácil.", context: "Usado no final de partidas para provocar o adversário dizendo que foi fácil.", category: "gaming", riskLevel: "yellow", safeExample: "GG EZ, foi uma vitória tranquila.", contextNotes: "Pode ser considerado falta de esportividade. Muitos jogos substituem automaticamente por mensagens amigáveis. Orientar sobre fair play.", origin: "Cultura gaming competitiva, especialmente League of Legends.", variations: ["gg", "gg wp", "ez"], popularityStatus: "ativo", region: "internacional" },

  // 54. bgmi
  { term: "bgmi", meaning: "Abreviação de 'Bad Game, More Intentional' — jogo ruim com intenção.", adultTranslation: "Jogo ruim de propósito / Partida ruim.", context: "Variação de BG (bad game), usada sarcasticamente.", category: "gaming", riskLevel: "green", safeExample: "Essa partida foi bgmi, time ruim.", contextNotes: "Variação pouco comum de gírias de fim de partida. Mais humorístico que ofensivo.", origin: "Variação de 'BG' da cultura gaming, adicionando 'More Intentional'.", variations: ["bg", "gg bg"], popularityStatus: "ativo", region: "internacional" },

  // 55. sus
  { term: "sus", meaning: "Suspeito, estranho, algo que não parece confiável.", adultTranslation: "Suspeito / Estranho / Pouco confiável.", context: "Usado quando algo ou alguém parece duvidoso ou estranho.", category: "humor", riskLevel: "green", safeExample: "Essa situação tá muito sus, não confio.", contextNotes: "Abreviação de 'suspicious'. Muito popularizado por Among Us. Inofensivo.", origin: "Do inglês 'suspicious', explosão de popularidade com Among Us em 2020.", variations: ["sussy", "sussy baka", "kinda sus"], popularityStatus: "ativo", region: "internacional" },

  // 56. amogus
  { term: "amogus", meaning: "Referência ao jogo Among Us, usado como meme para coisas suspeitas ou enganosas.", adultTranslation: "Referência a Among Us / Meme de suspeita.", context: "Usado como meme quando alguém está agindo de forma suspeita.", category: "meme", riskLevel: "green", safeExample: "Esse cara tá sendo amogus, acho que tá mentindo.", contextNotes: "Variação cômica de 'Among Us'. Totalmente humorístico e inofensivo.", origin: "Deturpação cômica de 'Among Us', meme do TikTok.", variations: ["among us", "imposter", "sus amogus"], popularityStatus: "em_queda", region: "internacional" },

  // 57. yeet
  { term: "yeet", meaning: "Lançar algo com força, expressar excitação, ou se afastar rapidamente.", adultTranslation: "Jogar com força / Expressão de excitação / Sair correndo.", context: "Usado ao arremessar algo ou como interjeição de empolgação.", category: "humor", riskLevel: "green", safeExample: "Yeet! Joguei a bola longe!", contextNotes: "Expressão cômica e empolgada. Inofensivo, mas pode envolver arremesso de objetos. Orientar sobre cuidado.", origin: "Meme do Vine/Twitter, popularizado entre jovens a partir de 2014.", variations: ["yeeting", "yeeted", "yeet moment"], popularityStatus: "ativo", region: "internacional" },

  // 58. oof
  { term: "oof", meaning: "Interjeição de dor, surpresa ou empatia por algo ruim que aconteceu.", adultTranslation: "Ai / Nossa / Que dor / Puxa.", context: "Reação a algo ruim, doloroso ou constrangedor.", category: "humor", riskLevel: "green", safeExample: "Oof, caiu feio! Tá bem?", contextNotes: "Expressão de empatia ou surpresa. Totalmente inofensivo.", origin: "Som do Roblox quando o personagem morre, popularizado como meme.", variations: ["big oof", "oof moment"], popularityStatus: "ativo", region: "internacional" },

  // 59. yikes
  { term: "yikes", meaning: "Interjeição de desconforto, espanto ou repulsa por algo estranho ou ruim.", adultTranslation: "Caramba / Nossa que estranho / Que horror.", context: "Reação a algo constrangedor, estranho ou desconfortável.", category: "humor", riskLevel: "green", safeExample: "Yikes, essa situação tá complicada.", contextNotes: "Expressão de desconforto leve. Inofensivo.", origin: "Slang americano de longa data, popularizado por memes e TikTok.", variations: ["yikes moment", "big yikes"], popularityStatus: "ativo", region: "internacional" },

  // 60. tehe
  { term: "tehe", meaning: "Risada fofa, geralmente associada a comportamento engraçado ou coquete.", adultTranslation: "Risada fofa / Hehe.", context: "Usado como risada em texto, especialmente de forma fofa ou provocante.", category: "humor", riskLevel: "green", safeExample: "Tehe, você é muito engraçado.", contextNotes: "Risada escrita usada em mensagens. Totalmente inofensivo.", origin: "Onomatopeia de risada popularizada em mensagens de texto e redes sociais.", variations: ["tehehe", "hehe"], popularityStatus: "ativo", region: "internacional" },

  // 61. poggers
  { term: "poggers", meaning: "Interjeição de empolgação e excitação, expressão de alegria intensa.", adultTranslation: "Nossa! / Que incrível! / Muito bom!", context: "Usado para expressar empolgação com algo incrível que aconteceu.", category: "elogio", riskLevel: "green", safeExample: "Poggers! Essa jogada foi insana!", contextNotes: "Termo de streams e gaming. Empolgação positiva. Totalmente inofensivo.", origin: "Do emote PogChamp da Twitch, 'poggers' é a versão emote animado.", variations: ["pog", "pogchamp", "pog moment"], popularityStatus: "ativo", region: "internacional" },

  // 62. pogchamp
  { term: "pogchamp", meaning: "Interjeição máxima de empolgação, equivalente a 'mente soprada'.", adultTranslation: "Incrível! / Mente soprada! / Surpreendente!", context: "Usado para reagir a algo impressionante ou inesperado.", category: "elogio", riskLevel: "green", safeExample: "Pogchamp! Não acredito que ele fez isso!", contextNotes: "Emote clássico da Twitch. Expressão pura de empolgação. Inofensivo.", origin: "Emote da Twitch baseado no rosto do streamer Gootecks, usado desde 2012.", variations: ["pog", "poggers", "poggers moment"], popularityStatus: "ativo", region: "internacional" },

  // 63. Kappa
  { term: "Kappa", meaning: "Indica sarcasmo, ironia ou que algo é brincadeira. Emote clássico da Twitch.", adultTranslation: "Sarcasmo / Brincadeira / Ironia.", context: "Usado para indicar que se está sendo sarcástico ou irônico.", category: "humor", riskLevel: "green", safeExample: "Claro que eu vou estudar hoje Kappa.", contextNotes: "Emote de sarcasmo da Twitch. Inofensivo, mas pode confundir quem não conhece.", origin: "Emote da Twitch com o rosto de Josh DeSeno, usado desde 2012 como sarcasmo.", variations: ["KappaPride", "MiniK"], popularityStatus: "ativo", region: "internacional" },

  // 64. based
  { term: "based", meaning: "Autêntico, corajoso, que fala o que pensa sem se importar com opinião alheia.", adultTranslation: "Autêntico / Corajoso / Verdadeiro / Sem filtro.", context: "Elogio para alguém que expressa sua opinião sem medo de julgamento.", category: "elogio", riskLevel: "yellow", safeExample: "Ele falou o que todo mundo pensava, tá very based.", contextNotes: "Originalmente termo positivo de autenticidade. Pode ser cooptado por grupos extremistas. Contextualizar como ser verdadeiro consigo mesmo.", origin: "Do rapper Lil B, 'based' = ser você mesmo. Popularizado em memes.", variations: ["very based", "based af", "based god"], popularityStatus: "ativo", region: "internacional" },

  // 65. cope
  { term: "cope", meaning: "Justificativa, desculpa para lidar com algo ruim, ou lidar com frustração.", adultTranslation: "Justificativa / Lidar com frustração / Desculpa esfarrapada.", context: "Usado para descrever tentativas de lidar com perda ou frustração, geralmente de forma irônica.", category: "ironia", riskLevel: "yellow", safeExample: "Ele tá fazendo cope porque perdeu o jogo.", contextNotes: "Pode ser usado para invalidar sentimentos legítimos. Orientar sobre empatia e validação emocional.", origin: "Do inglês 'cope' (lidar com), popularizado como meme no Twitter e Reddit.", variations: ["coping", "cope harder", "cope and seethe"], popularityStatus: "ativo", region: "internacional" },

  // 66. seethe
  { term: "seethe", meaning: "Estar com muita raiva, indignado, fervendo de raiva.", adultTranslation: "Com muita raiva / Indignado / Fervendo.", context: "Usado de forma irônica para zombar de quem está irritado.", category: "ironia", riskLevel: "yellow", safeExample: "Continue seething, não vai mudar nada.", contextNotes: "Pode ser usado de forma desrespeitosa para ignorar sentimentos alheios. Orientar sobre empatia.", origin: "Do inglês 'seethe' (ferver), popularizado como meme junto com 'cope'.", variations: ["seethe harder", "cope and seethe", "seething"], popularityStatus: "ativo", region: "internacional" },

  // 67. touch grass
  { term: "touch grass", meaning: "Sair de casa, ter contato com o mundo real, desconectar da internet.", adultTranslation: "Sair de casa / Ter vida real / Desconectar.", context: "Usado para sugerir que alguém passa tempo demais online e precisa viver a vida real.", category: "humor", riskLevel: "green", safeExample: "Você tá online há 10 horas, vai touch grass!", contextNotes: "Conselho bem-humorado sobre equilíbrio entre vida digital e real. Pode soar condescendente. Orientar de forma positiva.", origin: "Meme do Twitter/TikTok sobre pessoas muito online.", variations: ["go touch grass", "touched grass"], popularityStatus: "ativo", region: "internacional" },

  // 68. NPC energy
  { term: "NPC energy", meaning: "Vibração de pessoa sem personalidade, que age de forma robótica e previsível.", adultTranslation: "Sem personalidade / Comportamento robótico / Genérico.", context: "Usado para descrever comportamentos genéricos e sem autenticidade.", category: "ironia", riskLevel: "yellow", safeExample: "Toda essa gente com o mesmo TikTok dance tem NPC energy.", contextNotes: "Pode ser julgamento de comportamentos alheios. Orientar sobre respeito à individualidade.", origin: "Extensão do meme NPC para descrever energia/comportamento.", variations: ["NPC vibes", "giving NPC"], popularityStatus: "ativo", region: "internacional" },

  // 69. rawdog
  { term: "rawdog", meaning: "Fazer algo sem proteção, preparo ou assistência, ir direto ao ponto.", adultTranslation: "Fazer sem proteção / Sem preparo / Direto.", context: "Usado para descrever fazer algo sem recursos auxiliares, como assistir aula sem anotações.", category: "humor", riskLevel: "yellow", safeExample: "Rawdogging essa prova sem estudar.", contextNotes: "Originalmente termo sexual, entre jovens passou a significar fazer algo 'cru' sem preparo. Pode ter duplo sentido. Investigar contexto.", origin: "Slang americano, adaptado como meme pelo TikTok.", variations: ["rawdogging", "rawdog it"], popularityStatus: "ativo", region: "internacional" },

  // 70. sold
  { term: "sold", meaning: "Passar vergonha, ser exposto, ser humilhado publicamente.", adultTranslation: "Passar vergonha / Ser exposto / Humilhado.", context: "Usado quando alguém é pego em mentira ou passa por situação vergonhosa.", category: "ironia", riskLevel: "yellow", safeExample: "Ele mandou mensagem errada pra pessoa errada, sold!", contextNotes: "Pode ser usado para cyberbullying. Orientar sobre privacidade e respeito.", origin: "Slang de comunidades online, especialmente Twitter e TikTok.", variations: ["got sold", "selling", "sell"], popularityStatus: "ativo", region: "internacional" },

  // 71. cappin
  { term: "cappin", meaning: "Mentindo, inventando, exagerando. Oposto de 'no cap'.", adultTranslation: "Mentindo / Inventando / Fingindo.", context: "Usado para acusar alguém de mentir ou exagerar.", category: "ironia", riskLevel: "green", safeExample: "Tá cappin, não aconteceu isso não.", contextNotes: "Termo comum para chamar atenção sobre mentiras. Pode ser usado de forma justa ou injusta. Inofensivo no geral.", origin: "Do inglês 'cap' (menteira), inverso de 'no cap'.", variations: ["cap", "capping", "that's cap"], popularityStatus: "ativo", region: "internacional" },

  // 72. drip
  { term: "drip (gen alpha)", meaning: "Estilo visual impecável, roupas e acessórios de bom gosto.", adultTranslation: "Estilo impecável / Visual marcante / Bem vestido.", context: "Elogio máximo ao estilo visual de alguém.", category: "elogio", riskLevel: "green", safeExample: "O drip de hoje tá absurdo, que look!", contextNotes: "Elogio à moda e estilo pessoal. Totalmente positivo.", origin: "Cultura hip-hop e streetwear, popularizado pelo Gen Z e Alpha.", variations: ["drip check", "drip hard", "drip god"], popularityStatus: "ativo", region: "internacional" },

  // 73. hype
  { term: "hype", meaning: "Empolgação intensa, muito animado, empolgado com algo.", adultTranslation: "Empolgação / Entusiasmo / Animado.", context: "Usado para descrever muita empolgação com algo que vai acontecer.", category: "elogio", riskLevel: "green", safeExample: "Tô muito hype pro show de sábado!", contextNotes: "Expressão de empolgação positiva. Inofensivo.", origin: "Cultura hip-hop americana, popularizado globalmente.", variations: ["hyped", "super hype", "hype train"], popularityStatus: "ativo", region: "internacional" },

  // 74. flex
  { term: "flex", meaning: "Exibir, ostentar algo que se tem de bom, mostrar superiority.", adultTranslation: "Ostentar / Exibir / Mostrar algo com orgulho.", context: "Usado quando alguém mostra algo de que tem orgulho.", category: "elogio", riskLevel: "yellow", safeExample: "Só fazendo um flex do meu novo boné.", contextNotes: "Pode ser saudável (orgulho) ou arrogante (ostentação). Contextualizar sobre equilíbrio.", origin: "Cultura hip-hop americana, 'flex' = mostrar poder/posses.", variations: ["flexing", "flex hard", "weird flex"], popularityStatus: "ativo", region: "internacional" },

  // 75. stunting
  { term: "stunting", meaning: "Ostentando, exibindo sucesso ou posses de forma intensa.", adultTranslation: "Ostentando / Exibindo sucesso / Mostrando superiority.", context: "Usado quando alguém está exibindo algo de forma exagerada.", category: "elogio", riskLevel: "yellow", safeExample: "Ele tá stunting com o carro novo no Instagram.", contextNotes: "Relacionado a ostentação. Pode gerar comparações e inveja. Discutir valores.", origin: "Cultura hip-hop, 'stunt' = ostentar riqueza.", variations: ["stunt", "stunting on them", "stunt life"], popularityStatus: "ativo", region: "internacional" },

  // 76. clout
  { term: "clout", meaning: "Influência, poder nas redes sociais, popularidade online.", adultTranslation: "Influência / Popularidade / Poder online.", context: "Usado para descrever o nível de influência de alguém na internet.", category: "outros", riskLevel: "green", safeExample: "Ela tem muito clout, qualquer post viraliza.", contextNotes: "Termo neutro sobre influência online. Inofensivo.", origin: "Do inglês 'clout', cultura hip-hop e redes sociais.", variations: ["clout chaser", "clout hungry", "famous for clout"], popularityStatus: "ativo", region: "internacional" },

  // 77. clout chaser
  { term: "clout chaser", meaning: "Pessoa que faz qualquer coisa para ganhar popularidade online.", adultTranslation: "Caçador de fama / Que busca popularidade a qualquer custo.", context: "Crítica a quem faz conteúdo só para likes e seguidores.", category: "ironia", riskLevel: "yellow", safeExample: "Ele só gravou aquele vídeo porque é clout chaser.", contextNotes: "Termo crítico que pode ser usado para desqualificar conteúdo alheio. Orientar sobre respeito.", origin: "Cultura de redes sociais, crítica à busca por popularidade.", variations: ["clout chasing", "clout hunter"], popularityStatus: "ativo", region: "internacional" },

  // 78. ghost
  { term: "ghost", meaning: "Sumir sem explicação, ignorar mensagens e cortar contato abruptamente.", adultTranslation: "Sumir sem avisar / Ignorar / Cortar contato.", context: "Usado quando alguém para de responder mensagens sem explicação.", category: "outros", riskLevel: "yellow", safeExample: "Ela me ghostou, não responde mais minhas mensagens.", contextNotes: "Comportamento que pode machucar sentimentos. Orientar sobre comunicação saudável e empatia.", origin: "Termo de relacionamentos online, popularizado por apps de namoro.", variations: ["ghosting", "ghosted", "ghost someone"], popularityStatus: "ativo", region: "internacional" },

  // 79. toast
  { term: "toast", meaning: "Brindar, celebrar, ou referência cômica a situações engraçadas.", adultTranslation: "Brinde / Celebração / Meme de humor.", context: "Usado como brinde cômico ou reação a situações.", category: "humor", riskLevel: "green", safeExample: "Toast pra gente que passou na prova!", contextNotes: "Termo leve e humorístico. Inofensivo.", origin: "Do inglês 'toast' (brinde), popularizado como meme.", variations: ["let's toast", "toast to that"], popularityStatus: "ativo", region: "internacional" },

  // 80. simp
  { term: "simp", meaning: "Pessoa que faz demais por alguém que não corresponde, geralmente romanticamente.", adultTranslation: "Puxa-saco romântico / Que faz demais por quem não corresponde.", context: "Usado para criticar quem exagera em atenção não correspondida.", category: "ironia", riskLevel: "yellow", safeExample: "Ele tá simpando por ela há meses e ela nem olha.", contextNotes: "Pode ser usado para envergonhar sentimentos genuínos. Orientar sobre respeitar os sentimentos dos outros e expressar afeto de forma saudável.", origin: "Internet culture, popularizado por streamers como Twitch.", variations: ["simping", "simped", "simp behavior"], popularityStatus: "ativo", region: "internacional" },

  // 81. white knight
  { term: "white knight", meaning: "Pessoa que defende outra (geralmente mulher) excessivamente na internet por motivações românticas.", adultTranslation: "Defensor excessivo / Puxa-saco online.", context: "Crítica a quem defende alguém de forma exagerada na internet.", category: "ironia", riskLevel: "yellow", safeExample: "Lá vem o white knight defender ela de novo.", contextNotes: "Pode desqualificar defesas legítimas. Orientar sobre defender o que é certo independentemente das motivações.", origin: "Fóruns de internet, crítica ao comportamento de defender mulheres online.", variations: ["white knighting", "white knight behavior"], popularityStatus: "ativo", region: "internacional" },

  // 82. pick me
  { term: "pick me", meaning: "Pessoa que busca aprovação rejeitando seu próprio grupo ou tentando ser diferente.", adultTranslation: "Buscador de aprovação / Que tenta se destacar rejeitando o grupo.", context: "Usado para descrever quem faz de tudo para ser escolhido ou aprovado.", category: "ironia", riskLevel: "yellow", safeExample: "Ela disse que não gosta de maquiagem, que pick me.", contextNotes: "Pode ser sexista dependendo do contexto. Geralmente direcionado a mulheres. Orientar sobre respeito e evitar rótulos.", origin: "Cultura do TikTok e Twitter, 'pick me girl' tornou-se meme.", variations: ["pick me girl", "pick me boy", "pick me behavior"], popularityStatus: "ativo", region: "internacional" },

  // 83. green flag
  { term: "green flag", meaning: "Sinal positivo em relacionamento ou pessoa, indicando qualidades boas.", adultTranslation: "Sinal positivo / Qualidade boa / Indicador saudável.", context: "Usado para apontar coisas boas sobre alguém ou um relacionamento.", category: "elogio", riskLevel: "green", safeExample: "Ele respeita seus limites, isso é green flag.", contextNotes: "Termo positivo sobre relações saudáveis. Construtivo e positivo.", origin: "Cultura de relacionamentos no TikTok, analogia com bandeiras de sinalização.", variations: ["green flags", "major green flag"], popularityStatus: "ativo", region: "internacional" },

  // 84. red flag
  { term: "red flag", meaning: "Sinal de alerta em relacionamento ou pessoa, indicando comportamento problemático.", adultTranslation: "Sinal de alerta / Comportamento problemático / Indicador ruim.", context: "Usado para alertar sobre comportamentos negativos em relacionamentos.", category: "outros", riskLevel: "green", safeExample: "Ele não apresenta os amigos, isso é red flag.", contextNotes: "Ferramenta positiva para identificar relações prejudiciais. Usar de forma construtiva, não como fofoca.", origin: "Cultura de relacionamentos no TikTok, analogia com bandeiras de alerta.", variations: ["red flags", "major red flag", "walking red flag"], popularityStatus: "ativo", region: "internacional" },

  // 85. ick
  { term: "ick", meaning: "Sensação repentina de nojo ou desinteresse romântico por algo específico que alguém faz.", adultTranslation: "Nojo repentino / Desinteresse súbito / Turn-off.", context: "Usado para descrever algo que mata a atração instantaneamente.", category: "outros", riskLevel: "green", safeExample: "Meu ick é quando ele mastiga de boca aberta.", contextNotes: "Termo de preferências pessoais. Normal e inofensivo quando usado de forma leve. Pode ser superficial em excesso.", origin: "Cultura do TikTok, 'the ick' virou trend de compartilhar preferências.", variations: ["the ick", "give me the ick", "ick list"], popularityStatus: "ativo", region: "internacional" },

  // 86. ick list
  { term: "ick list", meaning: "Lista de coisas que causam 'ick', comportamentos que matam a atração.", adultTranslation: "Lista de turn-offs / Coisas que causam nojo.", context: "Usado para compartilhar preferências e coisas que desagradam em potenciais parceiros.", category: "humor", riskLevel: "green", safeExample: "Ele chewing gum com a boca aberta tá na minha ick list.", contextNotes: "Conversa leve sobre preferências. Normal entre adolescentes. Inofensivo.", origin: "Extensão do meme 'ick' no TikTok.", variations: ["my icks", "ick list check"], popularityStatus: "ativo", region: "internacional" },

  // 87. dealbreaker
  { term: "dealbreaker", meaning: "Algo inegociável, qualidade ou característica que impossibilita um relacionamento.", adultTranslation: "Inegociável / Impedimento definitivo / Sem volta.", context: "Usado para descrever algo que é motivo para não ficar com alguém.", category: "outros", riskLevel: "green", safeExample: "Fumar é meu dealbreaker, não rola.", contextNotes: "Termo saudável sobre limites pessoais. Positivo quando usado para autoconhecimento.", origin: "Cultura de relacionamentos americanos, popularizado pelo TikTok.", variations: ["absolute dealbreaker", "dealbreaker for me"], popularityStatus: "ativo", region: "internacional" },

  // 88. chemistry
  { term: "chemistry", meaning: "Conexão natural entre duas pessoas, boa sintonia e compatibilidade.", adultTranslation: "Conexão / Sintonia / Compatibilidade / Química.", context: "Usado para descrever quando duas pessoas combinam naturalmente.", category: "elogio", riskLevel: "green", safeExample: "Tem muita chemistry entre eles dois, percebe?", contextNotes: "Termo positivo sobre relações interpessoais. Inofensivo.", origin: "Do inglês 'chemistry', popularizado em conversas sobre relacionamentos.", variations: ["tem chemistry", "good chemistry"], popularityStatus: "ativo", region: "internacional" },

  // 89. vibe check
  { term: "vibe check", meaning: "Avaliar a energia/atmosfera de uma pessoa, lugar ou situação.", adultTranslation: "Checar a energia / Avaliar o clima / Testar a vibe.", context: "Usado para avaliar se uma pessoa ou situação está alinhada com o grupo.", category: "outros", riskLevel: "green", safeExample: "Ele passou no vibe check, pode entrar no grupo.", contextNotes: "Avaliação informal de compatibilidade social. Pode ser excludente se usado para excluir pessoas. Orientar sobre inclusão.", origin: "Meme do TikTok/Twitter, 'vibe check' como avaliação social.", variations: ["failed vibe check", "vibe check passed"], popularityStatus: "ativo", region: "internacional" },

  // 90. mood
  { term: "mood", meaning: "Expressão de identificação com algo, 'esse sou eu', representa como me sinto.", adultTranslation: "Esse sou eu / Representa meu estado / Identificação.", context: "Usado como reação a algo que reflete exatamente como a pessoa se sente.", category: "outros", riskLevel: "green", safeExample: "Essa foto de sexta à noite é mood.", contextNotes: "Expressão de identificação e humor. Totalmente inofensivo.", origin: "Cultura de memes e Tumblr, popularizado pelo TikTok.", variations: ["big mood", "mood af", "mood energy"], popularityStatus: "ativo", region: "internacional" },

  // 91. era
  { term: "era", meaning: "Fase da vida, período definido por um estilo ou comportamento específico.", adultTranslation: "Fase / Período / Época da vida.", context: "Usado para classificar diferentes fases que se está vivendo.", category: "outros", riskLevel: "green", safeExample: "Tô na minha era de estudar, sem festas por enquanto.", contextNotes: "Termo positivo de autoconhecimento e fases da vida. Inofensivo.", origin: "Cultura do TikTok, 'era' para definir capítulos da vida.", variations: ["my era", "villain era", "main character era"], popularityStatus: "ativo", region: "internacional" },

  // 92. core
  { term: "core", meaning: "Sufixo estético para definir um estilo ou subcultura visual (ex: normcore, gorpcore).", adultTranslation: "Estilo visual / Subcultura estética / Tendência.", context: "Usado para classificar estilos visuais e estéticas.", category: "outros", riskLevel: "green", safeExample: "Meu estilo hoje é normcore, só roupas básicas.", contextNotes: "Termo de classificação estética. Inofensivo e criativo.", origin: "Cultura Tumblr e Pinterest, popularizado pelo TikTok.", variations: ["normcore", "gorpcore", "cottagecore", "y2k core"], popularityStatus: "ativo", region: "internacional" },

  // 93. aesthetic
  { term: "aesthetic", meaning: "Estilo visual, vibe geral de algo, aparência artisticamente agradável.", adultTranslation: "Estilo visual / Beleza / Aparência estética.", context: "Usado para descrever algo visualmente bonito ou um estilo específico.", category: "elogio", riskLevel: "green", safeExample: "O feed dela é muito aesthetic, fotos lindas.", contextNotes: "Elogio visual positivo. Inofensivo.", origin: "Cultura Tumblr/TikTok, filosofia do belo aplicada a estilos.", variations: ["aesthetic vibe", "aesthetic feed", "dark aesthetic"], popularityStatus: "ativo", region: "internacional" },

  // 94. it's giving
  { term: "it's giving", meaning: "Transmite uma vibe, tem uma energia específica, remete a algo.", adultTranslation: "Transmite essa vibe / Tem essa energia / Remete a.", context: "Usado para descrever a impressão que algo ou alguém transmite.", category: "elogio", riskLevel: "green", safeExample: "Esse look tá giving boss energy.", contextNotes: "Expressão criativa para descrever impressões. Totalmente inofensiva.", origin: "Cultura do ballroom e drag, popularizado pelo TikTok.", variations: ["it's giving xyz", "giving vibes"], popularityStatus: "ativo", region: "internacional" },

  // 95. serving
  { term: "serving", meaning: "Apresentar algo com excelência, entregar um visual ou performance impressionante.", adultTranslation: "Entregar com excelência / Apresentar muito bem / Arrasar.", context: "Elogio para quem está se apresentando ou se vestindo muito bem.", category: "elogio", riskLevel: "green", safeExample: "Ela tá serving looks nessa festa!", contextNotes: "Elogio intenso da cultura drag e ballroom. Totalmente positivo.", origin: "Cultura ballroom e drag, 'serving' = apresentar excelência.", variations: ["serving looks", "serving cunt", "serving face"], popularityStatus: "ativo", region: "internacional" },

  // 96. snatched
  { term: "snatched", meaning: "Visual incrível, corpo ou roupa que ficou perfeito, arrasou.", adultTranslation: "Arrasador / Visual perfeito / Incrível.", context: "Elogio para aparência, especialmente corpo e roupa.", category: "elogio", riskLevel: "green", safeExample: "Seu cabelo tá snatched hoje, ficou perfeito!", contextNotes: "Elogio intenso da cultura drag e pop. Positivo.", origin: "Cultura drag e ballroom, 'snatched' = arrancado/perfeito.", variations: ["snatched waist", "face snatched", "looking snatched"], popularityStatus: "ativo", region: "internacional" },

  // 97. ate
  { term: "ate", meaning: "Arrasou, fez algo perfeitamente, superou expectativas.", adultTranslation: "Arrasou / Superei expectativas / Fez perfeitamente.", context: "Elogio para performance ou aparência excepcional.", category: "elogio", riskLevel: "green", safeExample: "Ela ate that performance, ficou perfeita!", contextNotes: "Elogio da cultura drag e pop. Totalmente positivo.", origin: "Cultura drag, 'ate' = 'devorou' algo de bom.", variations: ["ate and left no crumbs", "she ate"], popularityStatus: "ativo", region: "internacional" },

  // 98. understood the assignment
  { term: "understood the assignment", meaning: "Entendeu perfeitamente o que era esperado e entregou além do esperado.", adultTranslation: "Entregou o esperado / Fez exatamente certo / Superei.", context: "Elogio para quem acerta em cheio o que se propõe a fazer.", category: "elogio", riskLevel: "green", safeExample: "Esse artista understood the assignment nessa música.", contextNotes: "Elogio criativo para quem entrega excelência. Totalmente positivo.", origin: "Cultura pop e TikTok, metáfora escolar adaptada.", variations: ["she understood the assignment", "they understood the assignment"], popularityStatus: "ativo", region: "internacional" },

  // 99. slay
  { term: "slay", meaning: "Arrasar, fazer algo incrível, impressionar. Elogio máximo.", adultTranslation: "Arrasar / Ser incrível / Impressione / Destruir (positivo).", context: "Elogio intenso para qualquer coisa que alguém faz muito bem.", category: "elogio", riskLevel: "green", safeExample: "Slay! Você arrasou na apresentação!", contextNotes: "Elogio extremamente positivo e comum. Totalmente inofensivo.", origin: "Cultura drag e ballroom, 'slay' = matar/arrasar.", variations: ["slay queen", "slay king", "slaying"], popularityStatus: "ativo", region: "internacional" },

  // 100. periodt
  { term: "periodt", meaning: "Ponto final, fim de discussão, afirmou com convicção total.", adultTranslation: "Ponto final / Fim de discussão / Assunto encerrado.", context: "Usado para encerrar uma discussão com afirmação categórica.", category: "outros", riskLevel: "green", safeExample: "Ela é a melhor da turma, periodt.", contextNotes: "Expressão de ênfase e convicção. Versão estilizada de 'period'. Inofensivo.", origin: "AAVE e cultura drag, 'periodt' com 't' para ênfase.", variations: ["period", "periodt."], popularityStatus: "ativo", region: "internacional" },

  // 101. valid
  { term: "valid", meaning: "Válido, legítimo, aceitável. Usado para validar sentimentos ou ações alheias.", adultTranslation: "Válido / Legítimo / Aceitável / Compreensível.", context: "Usado para mostrar que entende e aceita os sentimentos ou ações de alguém.", category: "elogio", riskLevel: "green", safeExample: "Seus sentimentos são valid, não precisa se sentir mal.", contextNotes: "Expressão de empatia e validação emocional. Muito positivo.", origin: "Cultura de redes sociais e terapia online, popularizado pelo Gen Z.", variations: ["that's valid", "valid point", "very valid"], popularityStatus: "ativo", region: "internacional" },

  // 102. literally
  { term: "literally", meaning: "Literalmente, usado como ênfase exagerada mesmo quando não é literal.", adultTranslation: "Literalmente / De verdade / Sério mesmo.", context: "Usado como intensificador, muitas vezes de forma exagerada.", category: "outros", riskLevel: "green", safeExample: "Eu literalmente morri de rir com aquele vídeo.", contextNotes: "Uso exagerado como intensificador. Gramaticalmente incorreto mas culturalmente aceito. Inofensivo.", origin: "Do inglês 'literally', uso intensificador popularizado pelo Gen Z e Alpha.", variations: ["literally dying", "literally crying"], popularityStatus: "ativo", region: "internacional" },

  // 103. unspoken rizz
  { term: "unspoken rizz", meaning: "Carisma natural sem precisar falar, capacidade de atrair só com presença.", adultTranslation: "Carisma natural / Atração silenciosa / Presença magnética.", context: "Habilidade de ser carismático sem usar palavras.", category: "elogio", riskLevel: "green", safeExample: "Ele tem unspoken rizz, só de olhar já conquista.", contextNotes: "Elogio sobre carisma natural. Positivo e inofensivo.", origin: "Extensão do meme 'rizz', cultura TikTok.", variations: ["unspoken rizz energy", "natural rizz"], popularityStatus: "ativo", region: "internacional" },

  // 104. rizz god
  { term: "rizz god", meaning: "Mestre absoluto do carisma e da sedução, nível máximo de rizz.", adultTranslation: "Mestre da sedução / Carisma máximo / Sedutor supremo.", context: "Elogio máximo para a capacidade de conquistar.", category: "elogio", riskLevel: "green", safeExample: "Ele é rizz god, qualquer pessoa se apaixona.", contextNotes: "Elogio exagerado sobre carisma. Inofensivo.", origin: "Extensão do meme 'rizz' do streamer Kai Cenat.", variations: ["rizzlord", "rizzler", "rizz king"], popularityStatus: "ativo", region: "internacional" },

  // 105. rizzler
  { term: "rizzler (alt)", meaning: "Versão do rizz god, alguém com carisma natural excepcional.", adultTranslation: "Carismático / Sedutor nato / Encantador.", context: "Variante de rizz god para elogiar carisma.", category: "elogio", riskLevel: "green", safeExample: "Ele é o rizzler da escola, todo mundo gosta dele.", contextNotes: "Variante cômica do meme rizz. Inofensivo.", origin: "Combinação de 'rizz' com 'The Riddler' (Charada), meme do TikTok.", variations: ["the rizzler"], popularityStatus: "ativo", region: "internacional" },

  // 106. looksmaxxing tutorial
  { term: "looksmaxxing tutorial", meaning: "Vídeo ou guia com dicas para melhorar a aparência física.", adultTranslation: "Tutorial de beleza / Guia de aparência / Dicas de visual.", context: "Vídeos populares no TikTok com dicas de skincare, fitness e estilo.", category: "gaming", riskLevel: "green", safeExample: "Vi um looksmaxxing tutorial bom de skincare no TikTok.", contextNotes: "Conteúdo sobre autocuidado e aparência. Pode ser positivo (autocuidado) ou negativo (obsessão). Acompanhar.", origin: "Comunidade looksmaxxing no TikTok, adaptado como conteúdo.", variations: ["looksmax tutorial", "glow up tutorial"], popularityStatus: "ativo", region: "internacional" },

  // 107. mewing streak
  { term: "mewing streak", meaning: "Sequência de dias praticando mewing (postura de língua para definição facial).", adultTranslation: "Sequência de mewing / Dias seguidos praticando mewing.", context: "Desafio pessoal de manter a técnica de mewing por dias consecutivos.", category: "gaming", riskLevel: "green", safeExample: "Tô no meu mewing streak de 30 dias!", contextNotes: "Desafio pessoal positivo quando focado em autocuidado. Inofensivo.", origin: "Comunidade mewing/looksmaxxing no TikTok.", variations: ["mewing challenge", "mewing journey"], popularityStatus: "ativo", region: "internacional" },

  // 108. gigachad
  { term: "gigachad", meaning: "Homem idealizado, extremamente musculoso e confiante, ícone de masculinidade.", adultTranslation: "Super musculoso / Ideal masculino / Homem confiante.", context: "Meme usado ironicamente ou como ideal de masculinidade.", category: "meme", riskLevel: "green", safeExample: "Ele vai na academia todo dia, tá ficando gigachad.", contextNotes: "Meme exagerado de masculinidade. Pode criar expectativas irreais. Orientar sobre corpo saudável.", origin: "Ilustração de Ernest Khalimov, meme do Reddit/TikTok.", variations: ["chad", "gigachad meme", "average fan vs gigachad"], popularityStatus: "ativo", region: "internacional" },

  // 109. sigma grindset
  { term: "sigma grindset", meaning: "Mentalidade de trabalho duro e sucesso individual, sem depender dos outros.", adultTranslation: "Mentalidade de sucesso / Foco no trabalho / Independência.", context: "Filosofia motivacional sobre dedicação extrema aos objetivos.", category: "elogio", riskLevel: "green", safeExample: "Tô na sigma grindset, acordando 5h pra estudar.", contextNotes: "Pode ser motivacional, mas versões extremas promovem isolamento. Equilibrar com vida social.", origin: "Combinação de 'sigma male' com 'grindset', meme motivacional do TikTok.", variations: ["grindset", "sigma mindset", "grindset mentality"], popularityStatus: "ativo", region: "internacional" },

  // 110. grindset
  { term: "grindset", meaning: "Mentalidade de grind, foco total em trabalhar duro e alcançar objetivos.", adultTranslation: "Mentalidade de trabalho / Foco nos objetivos / Dedicação.", context: "Usado para descrever estado de motivação intensa para atingir metas.", category: "elogio", riskLevel: "green", safeExample: "Entrando no grindset pra passar no vestibular.", contextNotes: "Motivacional quando equilibrado. Pode ser nocivo se levar a burnout. Orientar sobre equilíbrio.", origin: "Do inglês 'grind' (trabalhar duro), cultura de autoajuda no TikTok.", variations: ["grind mode", "grind season"], popularityStatus: "ativo", region: "internacional" },

  // 111. hustle culture
  { term: "hustle culture", meaning: "Cultura que valoriza trabalhar sem parar, produtivo acima de tudo.", adultTranslation: "Cultura do trabalho excessivo / Produtividade extrema.", context: "Crítica ou elogio à mentalidade de trabalhar sem limites.", category: "outros", riskLevel: "yellow", safeExample: "Esse influencer vive de hustle culture, só fala em trabalhar.", contextNotes: "Pode promover burnout e esgotamento. Discutir importância de descanso e saúde mental.", origin: "Cultura empresarial americana, criticada e satirizada no TikTok.", variations: ["hustle harder", "hustle life"], popularityStatus: "ativo", region: "internacional" },

  // 112. mog or be mogged
  { term: "mog or be mogged", meaning: "Frase motivacional sobre competição: supere ou seja superado.", adultTranslation: "Supere ou seja superado / Competir ou perder.", context: "Meme competitivo sobre aparência e sucesso.", category: "meme", riskLevel: "yellow", safeExample: "Mog or be mogged é a regra do jogo.", contextNotes: "Pode promover comparação tóxica e competição insalubre. Orientar sobre valor individual.", origin: "Comunidades de fóruns masculinos, meme do TikTok.", variations: ["mog or be mogged", "mogging culture"], popularityStatus: "ativo", region: "internacional" },

  // 113. empire building
  { term: "empire building", meaning: "Construir algo grande e duradouro, geralmente relacionado a carreira ou negócios.", adultTranslation: "Construir um império / Criar algo grande / Projeto ambicioso.", context: "Usado para descrever projetos ambiciosos de longo prazo.", category: "elogio", riskLevel: "green", safeExample: "Tô no mode empire building, montando meu negócio.", contextNotes: "Metáfora motivacional positiva. Inofensivo.", origin: "Cultura empresarial adaptada pelo TikTok como mentalidade jovem.", variations: ["build your empire", "empire mindset"], popularityStatus: "ativo", region: "internacional" },

  // 114. loyalty test
  { term: "loyalty test", meaning: "Teste de lealdade, verificar se alguém é fiel em amizade ou relacionamento.", adultTranslation: "Teste de lealdade / Verificar fidelidade / Testar confiança.", context: "Prática comum em relacionamentos e amizades entre jovens.", category: "outros", riskLevel: "yellow", safeExample: "Fiz uma loyalty test mandando fake pra ver se ele responde.", contextNotes: "Pode ser manipulatório e destruir confiança. Orientar sobre comunicação honesta em vez de testes.", origin: "Cultura do TikTok, vídeos de loyalty test se tornaram trend.", variations: ["loyalty test prank", "fidelidade test"], popularityStatus: "ativo", region: "internacional" },

  // 115. loyalty
  { term: "loyalty", meaning: "Lealdade, ser fiel a amigos, parceiros ou princípios.", adultTranslation: "Lealdade / Fidelidade / Ser fiel.", context: "Valor muito importante entre jovens em amizades e relacionamentos.", category: "elogio", riskLevel: "green", safeExample: "Loyalty é tudo, sem confiança não tem amizade.", contextNotes: "Valor positivo e construtivo. Inofensivo.", origin: "Cultura hip-hop e das ruas, popularizado entre jovens globalmente.", variations: ["loyal", "loyalty over everything"], popularityStatus: "ativo", region: "internacional" },

  // 116. trust issues
  { term: "trust issues", meaning: "Problemas de confiança, dificuldade em confiar nas pessoas.", adultTranslation: "Problemas de confiança / Dificuldade em confiar / Desconfiança.", context: "Usado para descrever trauma ou medo de confiar após decepções.", category: "outros", riskLevel: "green", safeExample: "Depois daquilo, desenvolvi trust issues.", contextNotes: "Expressão genuína sobre saúde emocional. Pode indicar necessidade de apoio psicológico se intenso.", origin: "Cultura de memes e terapia online, popularizado pelo TikTok.", variations: ["trust issue", "trust issues meme"], popularityStatus: "ativo", region: "internacional" },

  // 117. betrayal arc
  { term: "betrayal arc", meaning: "Momento de traição em uma história ou situação real, quando alguém trai a confiança.", adultTranslation: "Arco de traição / Momento de traição / Plot twist de traição.", context: "Usado para descrever situações de traição como se fossem enredo de filme.", category: "humor", riskLevel: "green", safeExample: "Quando o melhor amigo ficou com minha ex, betrayal arc.", contextNotes: "Forma dramatizada e humorística de processar decepções. Pode mascarar dor real. Oferecer apoio emocional.", origin: "Termo de narrativa/filmes adaptado para vida real no TikTok.", variations: ["villain arc", "betrayal"], popularityStatus: "ativo", region: "internacional" },

  // 118. villain arc
  { term: "villain arc", meaning: "Fase em que alguém se torna o 'vilão', geralmente depois de ser bom por muito tempo.", adultTranslation: "Fase de vilão / Período de ser o mau da história.", context: "Usado quando alguém decide parar de ser bonzinho e ser mais assertivo ou frio.", category: "humor", riskLevel: "green", safeExample: "Depois de tanto ajudar, agora é minha villain arc.", contextNotes: "Metáfora dramática para mudança de comportamento. Geralmente humorística. Pode indicar cansaço de ser 'bonzinho'.", origin: "Termo de narrativa adaptado para vida real no TikTok.", variations: ["entering villain era", "villain era"], popularityStatus: "ativo", region: "internacional" },

  // 119. main character energy
  { term: "main character energy", meaning: "Energia de protagonista, se sentir o personagem principal da própria vida.", adultTranslation: "Energia de protagonista / Ser o dono da própria história.", context: "Usado quando alguém está vivendo um momento épico ou se sentindo especial.", category: "elogio", riskLevel: "green", safeExample: "Hoje acordei com main character energy.", contextNotes: "Autoestima positiva e criatividade. Motivador e inofensivo.", origin: "Cultura do TikTok, referência a ser o personagem principal de um filme.", variations: ["main character syndrome", "main character moment", "protagonista energy"], popularityStatus: "ativo", region: "internacional" },

  // 120. villain era
  { term: "villain era", meaning: "Fase da vida onde se assume um papel mais frio, calculista ou sem filtro.", adultTranslation: "Fase de vilão / Período sem filtro / Fase assertiva.", context: "Quando alguém decide parar de agradar e ser mais direto.", category: "humor", riskLevel: "green", safeExample: "Cheguei na minha villain era, não vou mais agradar ninguém.", contextNotes: "Forma dramatizada de lidar com limites. Geralmente saudável quando significa assertividade. Pode ser justificativa para mau comportamento.", origin: "Extensão do meme 'main character' e 'villain arc' no TikTok.", variations: ["villain mode", "villain era activated"], popularityStatus: "ativo", region: "internacional" },

  // 121. flop era
  { term: "flop era", meaning: "Fase de fracassos, quando nada dá certo ou os resultados são ruins.", adultTranslation: "Fase de fracasso / Período ruim / Maré de azar.", context: "Usado de forma autodeprecatoria para momentos de pouca sorte.", category: "humor", riskLevel: "green", safeExample: "Tô na minha flop era, tudo que faço dá errado.", contextNotes: "Auto-humor saudável quando leve. Pode indicar baixa autoestima se excessivo. Acompanhar.", origin: "Cultura do TikTok, 'flop' = fracasso comercial ou pessoal.", variations: ["flop", "flop moment"], popularityStatus: "ativo", region: "internacional" },

  // 122. flop
  { term: "flop", meaning: "Fracasso, algo que não deu certo, desempenho ruim.", adultTranslation: "Fracasso / Decepção / Algo que não funcionou.", context: "Usado para descrever algo que não teve sucesso.", category: "ironia", riskLevel: "yellow", safeExample: "A festa foi um flop, quase ninguém foi.", contextNotes: "Pode ser cruel se usado para criticar trabalho alheio. Orientar sobre construtividade.", origin: "Indústria do entretenimento, 'flop' = fracasso de bilheteria.", variations: ["flop hard", "massive flop", "total flop"], popularityStatus: "ativo", region: "internacional" },

  // 123. hit different
  { term: "hit different", meaning: "Sentir diferente, ter um impacto especial que transcende o normal.", adultTranslation: "Sentir diferente / Ter efeito especial / Impactar de forma única.", context: "Usado para descrever algo que causou impressão especial.", category: "elogio", riskLevel: "green", safeExample: "Essa música hit different quando tá chovendo.", contextNotes: "Elogio poético para experiências especiais. Inofensivo.", origin: "Cultura hip-hop, popularizado pelo TikTok.", variations: ["hits different", "it just hits different"], popularityStatus: "ativo", region: "internacional" },

  // 124. missed the mark
  { term: "missed the mark", meaning: "Errou o alvo, não alcançou o objetivo, tentou mas não conseguiu.", adultTranslation: "Errou o alvo / Não alcançou o objetivo / Falhou.", context: "Usado quando alguém tentou algo mas não obteve o resultado esperado.", category: "ironia", riskLevel: "green", safeExample: "A piada dele missed the mark, ninguém riu.", contextNotes: "Expressão leve de crítica. Pode ser construtivo quando dado com empatia.", origin: "Expressão inglesa de longa data, popularizada no TikTok.", variations: ["missed the mark completely", "way off mark"], popularityStatus: "ativo", region: "internacional" },

  // 125. tried it
  { term: "tried it", meaning: "Tentou, mas não deu certo. Usado como resposta curta e fria.", adultTranslation: "Tentou, mas não rolou / Quase / Falhou.", context: "Resposta curta quando alguém tentou algo e não funcionou.", category: "ironia", riskLevel: "green", safeExample: "Aquele look novo? Tried it. Não ficou bom.", contextNotes: "Expressão cínica e curta. Pode soar desdenhosa. Orientar sobre gentileza.", origin: "Cultura de crítica de moda e redes sociais.", variations: ["she tried it", "tried but failed"], popularityStatus: "ativo", region: "internacional" },

  // 126. didn't age well
  { term: "didn't age well", meaning: "Envelheceu mal, algo que não se sustentou com o tempo, ficou desatualizado.", adultTranslation: "Envelheceu mal / Não envelheceu bem / Desatualizado.", context: "Usado para coisas que pareciam boas no passado mas hoje são ruins ou constrangedoras.", category: "humor", riskLevel: "green", safeExample: "Aquele vídeo dele não aged well, hoje seria cancelado.", contextNotes: "Humor sobre mudança de padrões com o tempo. Inofensivo.", origin: "Cultura de memes e nostalgia no TikTok.", variations: ["aging like milk", "didn't age well meme"], popularityStatus: "ativo", region: "internacional" },

  // 127. babygirl
  { term: "babygirl", meaning: "Termo carinhoso para pessoa querida, ou ironicamente para homens vulneráveis.", adultTranslation: "Querido / Amor / Fofinho.", context: "Termo afetuoso ou irônico para descrever alguém carinhoso ou vulnerável.", category: "elogio", riskLevel: "green", safeExample: "Meu babygirl é o melhor, amo muito.", contextNotes: "Pode ser usado afetuosamente ou ironicamente para homens. Contextualizar.", origin: "Cultura do Twitter e TikTok, apropriação irônica do termo.", variations: ["babygirl moment", "him babygirl"], popularityStatus: "ativo", region: "internacional" },

  // 128. pookie
  { term: "pookie", meaning: "Termo carinhoso extremo para pessoa muito querida, equivalente a 'amorzinho'.", adultTranslation: "Amorzinho / Queridinho / Fofo.", context: "Termo de carinho usado entre amigos e casais.", category: "elogio", riskLevel: "green", safeExample: "Obrigado pookie, você é o melhor!", contextNotes: "Termo extremamente carinhoso. Inofensivo.", origin: "Cultura do TikTok e WhatsApp entre adolescentes americanos.", variations: ["pookie bear", "my pookie"], popularityStatus: "ativo", region: "internacional" },

  // 129. bestie
  { term: "bestie", meaning: "Melhor amiga/o, pessoa muito próxima e querida.", adultTranslation: "Melhor amiga/o / Amigo íntimo / Parceira/o.", context: "Termo de carinho para amigos próximos ou usado ironicamente.", category: "elogio", riskLevel: "green", safeExample: "E aí bestie, tudo bem com você?", contextNotes: "Termo afetuoso comum entre adolescentes. Inofensivo.", origin: "Diminutivo de 'best friend', popularizado globalmente.", variations: ["bestieee", "bestie forever"], popularityStatus: "ativo", region: "internacional" },

  // 130. blorbo
  { term: "blorbo", meaning: "Personagem favorito de ficção/filme/série que se é obcecado.", adultTranslation: "Personagem favorito / Favorito de fandom / Obsessão fictional.", context: "Usado por fãs para falar de seus personagens favoritos com carinho.", category: "outros", riskLevel: "green", safeExample: "Meu blorbo da série é esse personagem aí, amo ele.", contextNotes: "Termo de fandom, totalmente inofensivo e demonstra criatividade.", origin: "Cultura de Tumblr/fandoms, 'blorbo' como nome cômico para favorito.", variations: ["my blorbo", "blorbo from my shows"], popularityStatus: "ativo", region: "internacional" },

  // 131. comfort character
  { term: "comfort character", meaning: "Personagem de ficção que traz conforto emocional e segurança.", adultTranslation: "Personagem de conforto / Personagem reconfortante.", context: "Personagem que se usa para se sentir melhor emocionalmente.", category: "outros", riskLevel: "green", safeExample: "Esse é meu comfort character, sempre que tô triste assisto.", contextNotes: "Mecanismo saudável de regulação emocional. Inofensivo.", origin: "Cultura de fandoms e Tumblr, termo de saúde mental informal.", variations: ["comfort media", "comfort show"], popularityStatus: "ativo", region: "internacional" },

  // 132. parasocial
  { term: "parasocial", meaning: "Relação unidirecional com celebridade/influencer, onde o fã sente proximidade que não existe.", adultTranslation: "Relação unidirecional / Ilusão de proximidade com celebridade.", context: "Usado para descrever conexão emocional com alguém que não conhece o fã.", category: "outros", riskLevel: "green", safeExample: "Cuidado pra não criar vínculo parasocial com influencer.", contextNotes: "Conceito importante sobre relações com celebridades. Discutir limites saudáveis.", origin: "Termo acadêmico de comunicação, popularizado no TikTok.", variations: ["parasocial relationship", "parasocial bond"], popularityStatus: "ativo", region: "internacional" },

  // 133. DNI
  { term: "DNI", meaning: "Do Not Interact, aviso para que certas pessoas não interajam com seu perfil.", adultTranslation: "Não interaja / Mantenha distância / Restrição de contato.", context: "Usado em bios de redes sociais para definir limites de interação.", category: "outros", riskLevel: "green", safeExample: "DNI: homofóbicos, racistas, tóxicos.", contextNotes: "Ferramenta de limites saudáveis. Pode ser usado de forma inclusiva ou excludente. Contextualizar.", origin: "Cultura de bios no Twitter/TikTok/Instagram.", variations: ["DNI list", "DNI criteria"], popularityStatus: "ativo", region: "internacional" },

  // 134. moots
  { term: "moots", meaning: "Mutuals, seguidores mútuos em redes sociais, pessoas que se seguem reciprocamente.", adultTranslation: "Seguidores mútuos / Amigos online / Contatos recíprocos.", context: "Termo para amigos virtuais que se seguem no Twitter/TikTok/Instagram.", category: "saudacao", riskLevel: "green", safeExample: "Meus moots são as pessoas mais legais da internet.", contextNotes: "Termo de amizade online. Totalmente inofensivo.", origin: "Do inglês 'mutuals', cultura do Twitter/X.", variations: ["mutuals", "mooties"], popularityStatus: "ativo", region: "internacional" },

  // 135. keyboard warrior
  { term: "keyboard warrior", meaning: "Pessoa que é corajosa e agressiva apenas pela internet, atrás do teclado.", adultTranslation: "Corajoso só na internet / Guerreiro de teclado / Toug online.", context: "Crítica a quem se comporta de forma diferente online e offline.", category: "ironia", riskLevel: "green", safeExample: "Ele só fala mal porque é keyboard warrior, pessoalmente é tímido.", contextNotes: "Crítica justa sobre coragem digital. Discutir responsabilidade online.", origin: "Termo de internet de longa data, popularizado entre jovens.", variations: ["keyboard warrior energy", "internet tough guy"], popularityStatus: "ativo", region: "internacional" },

  // 136. armchair expert
  { term: "armchair expert", meaning: "Pessoa que fala com autoridade sobre algo sem conhecimento real, sem experiência.", adultTranslation: "Especialista de sofá / Fala sem conhecimento / Autoproclamado especialista.", context: "Crítica a quem dá opinião sem base ou experiência.", category: "ironia", riskLevel: "yellow", safeExample: "Ele tá sendo armchair expert sobre um assunto que não conhece.", contextNotes: "Pode ser uma crítica válida a desinformação. Orientar sobre buscar conhecimento real.", origin: "Expressão inglesa, 'armchair' = de sofá, sem prática.", variations: ["armchair psychologist", "armchair quarterback"], popularityStatus: "ativo", region: "internacional" },

  // 137. backseat gamer
  { term: "backseat gamer", meaning: "Pessoa que diz o que fazer enquanto assiste alguém jogar, sem estar jogando.", adultTranslation: "Quem manda sem jogar / Ditador de joystick / Jogador de sofá.", context: "Quem fica dando instruções enquanto assiste outro jogar.", category: "gaming", riskLevel: "green", safeExample: "Para de ser backseat gamer, deixa eu jogar do meu jeito!", contextNotes: "Comum entre amigos que jogam juntos. Pode gerar irritação. Humorístico.", origin: "Cultura gaming, analogia a 'backseat driver' (motorista de banco de trás).", variations: ["backseat gaming", "stop backseat gaming"], popularityStatus: "ativo", region: "internacional" },

  // 138. monday morning quarterback
  { term: "monday morning quarterback", meaning: "Pessoa que critica depois que já aconteceu, com o benefício do hindsight.", adultTranslation: "Crítico de segunda-feira / Sábio depois do fato.", context: "Quem critica ações passadas com a visão que não se tinha na hora.", category: "ironia", riskLevel: "green", safeExample: "Todo mundo é monday morning quarterback depois do jogo.", contextNotes: "Expressão sobre crítica retrospective. Inofensiva.", origin: "Esporte americano, 'quarterback' que analisa o jogo depois de acabado.", variations: ["monday morning qb"], popularityStatus: "ativo", region: "internacional" },

  // 139. couch gamer
  { term: "couch gamer", meaning: "Jogador casual que joga do sofá, sem comprometimento competitivo.", adultTranslation: "Jogador casual / Jogador de sofá / Gamer relaxado.", context: "Pessoa que joga videogame de forma casual e relaxada.", category: "gaming", riskLevel: "green", safeExample: "Sou mais couch gamer, jogo pra relaxar no sofá.", contextNotes: "Termo neutro sobre estilo de jogo. Inofensivo.", origin: "Cultura gaming, oposição ao gamer competitivo.", variations: ["casual gamer", "sofa gamer"], popularityStatus: "ativo", region: "internacional" },

  // 140. casual
  { term: "casual", meaning: "Jogador informal, que joga por diversão sem levar a sério.", adultTranslation: "Jogador informal / Descontraído / Por hobby.", context: "Alguém que joga sem comprometimento competitivo.", category: "gaming", riskLevel: "green", safeExample: "Sou casual no jogo, não ligo pra ranking.", contextNotes: "Termo neutro sobre estilo de jogo. Inofensivo.", origin: "Cultura gaming, termo para distinguir de jogadores competitivos.", variations: ["casual player", "playing casually"], popularityStatus: "ativo", region: "internacional" },

  // 141. sweaty
  { term: "sweaty (gaming)", meaning: "Jogador que sua (literalmente ou não) por jogar com muita intensidade e seriedade.", adultTranslation: "Jogador intenso / Excessivamente competitivo.", context: "Quem joga com muita seriedade em modos casuais.", category: "gaming", riskLevel: "green", safeExample: "Esse cara é sweaty demais pra um modo casual.", contextNotes: "Pode ser elogio (dedicação) ou crítica (excesso). Humorístico.", origin: "Cultura gaming de Fortnite e Call of Duty.", variations: ["sweaty tryhard", "sweat", "sweatlord"], popularityStatus: "ativo", region: "internacional" },

  // 142. sweaty tryhard
  { term: "sweaty tryhard", meaning: "Jogador extremamente intenso e competitivo em contextos casuais.", adultTranslation: "Ultra competitivo / Intenso demais / Exagerado.", context: "Combinação de sweaty e tryhard, máximo de intensidade.", category: "gaming", riskLevel: "green", safeExample: "Esse sweaty tryhard arruinou a diversão do lobby.", contextNotes: "Termo cômico do gaming. Pode gerar conflito entre jogadores. Contextualizar.", origin: "Combinação de termos gaming (sweaty + tryhard).", variations: ["sweaty player", "tryhard sweaty"], popularityStatus: "ativo", region: "internacional" },

  // 143. fun police
  { term: "fun police", meaning: "Pessoa que estraga a diversão dos outros, que é contra tudo que é divertido.", adultTranslation: "Estraga-prazeres / Chato de plantão / Anti-diversão.", context: "Crítica a quem critica os outros por se divertirem.", category: "ironia", riskLevel: "yellow", safeExample: "Lá vem a fun police falar que a brincadeira é perigosa.", contextNotes: "Pode ser crítica justa a excesso de cuidado, ou ser usado para zoar quem tem preocupações legítimas. Equilibrar.", origin: "Expressão inglesa, 'fun police' = polícia da diversão.", variations: ["fun police energy", "buzzkill"], popularityStatus: "ativo", region: "internacional" },

  // 144. delulu
  { term: "delulu", meaning: "Delirante, pessoa que vive em fantasia, tem expectativas irreais sobre relacionamentos.", adultTranslation: "Delirante / Vivendo em fantasia / Com expectativas irreais.", context: "Usado para descrever quem tem ilusões sobre relacionamentos ou situações.", category: "humor", riskLevel: "green", safeExample: "Ela acha que ele vai voltar, tá muito delulu.", contextNotes: "Termo cômico sobre ilusões. Pode ser cruel se usado para invalidar sentimentos. Usar com empatia.", origin: "Do inglês 'delusional', popularizado no TikTok como 'delulu'.", variations: ["delulu is the solulu", "delulu behavior", "being delulu"], popularityStatus: "ativo", region: "internacional" },

  // 145. gaslight
  { term: "gaslight", meaning: "Manipular someone psicologicamente para duvidar da própria memória ou percepção.", adultTranslation: "Manipulação psicológica / Fazer alguém duvidar de si mesmo.", context: "Termo sério sobre manipulação emocional em relacionamentos.", category: "outros", riskLevel: "red", safeExample: "Ele tentou gaslightar dizendo que eu lembrava errado.", contextNotes: "Termo IMPORTANTE sobre abuso psicológico. Se o jovem usa frequentemente, pode estar em situação de abuso. Investigar.", origin: "Do filme 'Gas Light' (1944), popularizado como termo psicológico nas redes.", variations: ["gaslighting", "gaslit", "emotional manipulation"], popularityStatus: "ativo", region: "internacional" },

  // 146. red flag energy
  { term: "red flag energy", meaning: "Vibração de pessoa problemática, que emite sinais de alerta.", adultTranslation: "Energia de alerta / Vibe problemática / Sinais negativos.", context: "Quando alguém transmite sinais de que pode ser problemático.", category: "outros", riskLevel: "green", safeExample: "Ele dá red flag energy, cuidado.", contextNotes: "Extensão de 'red flag'. Ferramenta de autoconhecimento sobre relações. Positivo.", origin: "Extensão do meme 'red flag' no TikTok.", variations: ["red flag vibes", "walking red flag energy"], popularityStatus: "ativo", region: "internacional" },

  // 147. canon event
  { term: "canon event", meaning: "Evento inevitável e importante na vida, algo que precisava acontecer.", adultTranslation: "Evento inevitável / Momento crucial / Destino.", context: "Usado para justificar algo ruim que aconteceu como necessário para o crescimento.", category: "meme", riskLevel: "green", safeExample: "Rodar naquele teste foi meu canon event, me fez estudar mais.", contextNotes: "Metáfora positiva de crescimento pessoal. Referência ao filme Spider-Verse. Inofensivo e construtivo.", origin: "Referência ao filme 'Spider-Man: Across the Spider-Verse' (2023), popularizado no TikTok.", variations: ["canon", "mandatory canon event"], popularityStatus: "ativo", region: "internacional" },

  // 148. brainrot
  { term: "brainrot", meaning: "Conteúdo de internet bizarro e viciante que deteriora o cérebro, usado ironicamente.", adultTranslation: "Conteúdo viciante bizarro / Lixo de internet / Absurdo.", context: "Usado para descrever conteúdo estranho e viciante do TikTok e internet.", category: "meme", riskLevel: "green", safeExample: "Essa playlist é pura brainrot, mas não consigo parar de assistir.", contextNotes: "Termo irônico sobre consumo de conteúdo. Pode indicar autoconsciência sobre hábitos digitais. Inofensivo.", origin: "Meme do TikTok, autocrítica irônica sobre consumo de conteúdo bizarro.", variations: ["brainrot content", "brainrot tiktok", "terminal brainrot"], popularityStatus: "ativo", region: "internacional" },

  // 149. sigma facial
  { term: "sigma facial", meaning: "Expressão facial de quem pratica mewing, associada ao 'sigma male'.", adultTranslation: "Expressão de mewing / Cara de sigma / Postura facial.", context: "Expressão facial associada a mewing e postura de 'sigma'.", category: "meme", riskLevel: "green", safeExample: "Ele fez uma sigma facial na foto de formatura.", contextNotes: "Meme sobre postura facial. Inofensivo, mas pode indicar preocupação com aparência.", origin: "Combinação de 'sigma' com 'facial' (mewing), meme do TikTok.", variations: ["sigma face", "sigma look"], popularityStatus: "ativo", region: "internacional" },

  // 150. beta
  { term: "beta", meaning: "Homem considerado fraco, submisso ou sem autoridade. Oposto de sigma/alpha.", adultTranslation: "Submisso / Fraco / Sem autoridade.", context: "Insulto usado para questionar a masculinidade de alguém.", category: "ironia", riskLevel: "orange", safeExample: "Ele não defendeu a namorada, que beta.", contextNotes: "Termo MACHISTA que reforça estereótipos tóxicos de gênero. CRÍTICO: discutir sobre respeitar formas diferentes de ser homem e evitar rótulos de masculinidade.", origin: "Comunidades de fóruns masculinos (Red Pill/Alpha/Beta hierarchy), popularizado no TikTok.", variations: ["beta male", "beta energy", "beta behavior"], popularityStatus: "ativo", region: "internacional" },
];
