// =============================================================================
// Brazilian Teen Slang Dictionary — Extra Set 14 (150 terms)
// Diverse Brazilian terms — traditional, regional, party, school, money, sports, values
// =============================================================================

import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_14: SlangTerm[] = [
  // 1. saudade
  { term: "saudade", meaning: "Sentimento profundo de falta de alguém ou algo que se amou ou viveu.", adultTranslation: "Saudade / Falta / Sentimento de ausência.", context: "Sentimento único português de nostalgia misturada com carinho por algo ausente.", category: "emoção", riskLevel: "green", safeExample: "Senti uma saudade da casa da avó.", contextNotes: "Sentimento profundamente brasileiro e português. Não tem tradução exata para outras línguas. Totalmente positivo e humano.", origin: "Língua portuguesa, conceito cultural brasileiro milenar.", variations: ["com saudade", "saudades"], popularityStatus: "ativo", region: "Brasil" },
  // 2. nostalgia
  { term: "nostalgia", meaning: "Sentimento de lembrança afetuosa do passado, saudade de tempos que já passaram.", adultTranslation: "Nostalgia / Lembrança boa do passado / Saudosismo.", context: "Quando alguém lembra com carinho de momentos, épocas ou pessoas do passado.", category: "emoção", riskLevel: "green", safeExample: "Ouvi aquela música e bateu uma nostalgia dos anos 2000.", contextNotes: "Sentimento universal muito presente na cultura jovem. Trend de nostalgia nas redes sociais. Inofensivo e positivo.", origin: "Do grego 'nostos' (retorno) + 'algos' (dor), conceito médico antigo adaptado para cultura.", variations: ["nostálgico", "nostalgic"], popularityStatus: "ativo", region: "internacional" },
  // 3. de repente
  { term: "de repente", meaning: "De repente, subitamente; ou como 'talvez' em alguns contextos informais.", adultTranslation: "Subitamente / De repente / Talvez / Quem sabe.", context: "Pode indicar algo que acontece de surpresa ou como expressão de possibilidade.", category: "expressão", riskLevel: "green", safeExample: "De repente a gente vai no cinema hoje.", contextNotes: "Expressão muito versátil no português brasileiro. Pode significar tanto surpresa quanto incerteza. Inofensivo.", origin: "Expressão popular brasileira de uso cotidiano.", variations: ["dum repente", "repente"], popularityStatus: "ativo", region: "Brasil" },
  // 4. tosco
  { term: "tosco", meaning: "Feio, mal feito, sem graça, de qualidade ruim ou aparência ruim.", adultTranslation: "Feio / Mal feito / Sem graça / Rústico.", context: "Usado para descrever algo ou alguém com aparência ou qualidade ruim.", category: "insulto_leve", riskLevel: "yellow", safeExample: "Esse desenho ficou tosco, preciso refazer.", contextNotes: "Pode ser usado de forma leve (autocrítica) ou ofensiva (para descrever alguém). Orientar sobre usar palavras mais construtivas.", origin: "Do latim 'toscus' (áspero), popularizado na linguagem informal brasileira.", variations: ["tosqueira", "toscão"], popularityStatus: "ativo", region: "Brasil" },
  // 5. moleque
  { term: "moleque", meaning: "Menino, garoto, jovem; ou pessoa travessa e bagunceira.", adultTranslation: "Menino / Garoto / Rapaz / Travesso.", context: "Termo para menino ou garoto, geralmente com conotação de travessura ou energia.", category: "saudacao", riskLevel: "green", safeExample: "Esse moleque não para quieto!", contextNotes: "Termo carinhoso e informal muito usado no Brasil. Pode ter conotação de bagunceiro. Inofensivo quando usado com carinho.", origin: "Termo popular brasileiro de origem incerta, possivelmente do quimbundo.", variations: ["moleca", "molequinho"], popularityStatus: "ativo", region: "Brasil" },
  // 6. galera
  { term: "galera", meaning: "Grupo de amigos, turma, pessoal, coletivo de pessoas.", adultTranslation: "Turma / Grupo de amigos / Pessoal / Galera.", context: "Usado para se referir a um grupo de amigos ou pessoas em geral.", category: "saudacao", riskLevel: "green", safeExample: "E aí galera, bora pra festa?", contextNotes: "Termo extremamente comum e versátil. Pode referir-se a amigos, público de evento ou qualquer grupo. Totalmente inofensivo.", origin: "Expressão popular brasileira, possivelmente do galego 'galeira' (multidão).", variations: ["a galera", "galera do mal"], popularityStatus: "ativo", region: "Brasil" },
  // 7. rapaziada
  { term: "rapaziada", meaning: "Grupo de rapazes, turma de amigos, pessoal masculino.", adultTranslation: "Turma de rapazes / Grupo de amigos / Garotada.", context: "Usado para se referir a um grupo de amigos ou rapazes.", category: "saudacao", riskLevel: "green", safeExample: "Chama a rapaziada pra jogar bola sábado.", contextNotes: "Termo muito comum no Brasil para grupos de amigos. Pode incluir mulheres dependendo do contexto. Inofensivo.", origin: "Derivação de 'rapaz' com sufixo coletivo '-iada', muito usado informalmente.", variations: ["rapaz", "rapaziada firmeza"], popularityStatus: "ativo", region: "Brasil" },
  // 8. patota
  { term: "patota", meaning: "Grupo de amigos, turma que sempre faz coisas juntos.", adultTranslation: "Grupo de amigos / Turma / Panelinha de amigos.", context: "Grupo fechado de amigos que fazem programas juntos.", category: "saudacao", riskLevel: "green", safeExample: "A patota toda vai no show do Anitta.", contextNotes: "Semelhante a galera e rapaziada. Refere-se a grupo de amigos próximos. Inofensivo e afetuoso.", origin: "Gíria popular brasileira, possivelmente origem no futebol ou vida escolar.", variations: ["patotinha", "patota do bem"], popularityStatus: "ativo", region: "SP, RJ" },
  // 9. cabra macho
  { term: "cabra macho", meaning: "Homem corajoso, destemido, que não tem medo de nada.", adultTranslation: "Homem corajoso / Destemido / Valente.", context: "Expressão para descrever alguém muito corajoso e determinado.", category: "elogio", riskLevel: "green", safeExample: "Esse atleta é um cabra macho, joga machucado.", contextNotes: "Expressão popular nordestina que elogia coragem e determinação. Muito usada no esporte. Totalmente positivo.", origin: "Cultura nordestina brasileira, possivelmente de origem na figura do vaqueiro.", variations: ["cabra", "cabra da peste"], popularityStatus: "ativo", region: "Nordeste" },
  // 10. patricinha
  { term: "patricinha", meaning: "Moça de classe alta, que se veste bem e tem atitude de superioridade.", adultTranslation: "Mimada / Garota rica / Snob.", context: "Estereótipo de garota de classe alta com visual marcante e atitude elitista.", category: "estereótipo", riskLevel: "yellow", safeExample: "Ela arruma como patricinha, mas é gente como a gente.", contextNotes: "Pode ser usado como estereótipo ou de forma pejorativa. Reflete julgamento de classe. Orientar sobre não julgar pela aparência.", origin: "Gíria paulista dos anos 2000, derivada de nomes de elite ( Patrícia).", variations: ["patricinhas", "mauá", "miranha"], popularityStatus: "em_queda", region: "SP" },
  // 11. cidadão
  { term: "cidadão", meaning: "Pessoa honesta, trabalhadora, correto; ou termo para se referir a alguém respeitosamente.", adultTranslation: "Pessoa honesta / Cidadão / Homem de bem.", context: "Usado para descrever alguém correto e honesto, ou como vocativo informal.", category: "elogio", riskLevel: "green", safeExample: "Esse cara é cidadão, trabalha honestamente.", contextNotes: "Termo que valoriza honestidade e trabalho. Pode ser usado de forma irônica. Totalmente positivo quando genuíno.", origin: "Do latim 'civitas', adaptado na cultura popular brasileira como elogio moral.", variations: ["cidadã", "cidadão de bem"], popularityStatus: "ativo", region: "Brasil" },
  // 12. genuíno
  { term: "genuíno", meaning: "Verdadeiro, autêntico, que não é falso nem forçado.", adultTranslation: "Autêntico / Verdadeiro / Real / Sincero.", context: "Quando algo ou alguém é verdadeiro e sincero, sem fingimento.", category: "elogio", riskLevel: "green", safeExample: "O abraço dela foi genuíno, senti que era de verdade.", contextNotes: "Elogio que valoriza sinceridade e autenticidade. Muito usado para descrever sentimentos e atitudes. Totalmente positivo.", origin: "Do latim 'genuinus', palavra formal adaptada para uso informal entre jovens.", variations: ["genuine", "autêntico"], popularityStatus: "ativo", region: "Brasil" },
  // 13. farsante
  { term: "farsante", meaning: "Pessoa falsa, que finge ser algo que não é, hipócrita.", adultTranslation: "Falso / Hipócrita / Fingido / Embustei ro.", context: "Alguém que mente ou finge ter qualidades que não tem.", category: "insulto_leve", riskLevel: "yellow", safeExample: "Aquele farsante prometeu e não cumpriu.", contextNotes: "Termo que pode machucar se usado de forma pública. Deve ser usado com cuidado. Orientar sobre comunicação direta.", origin: "Do italiano 'farsante', popularizado na linguagem informal brasileira.", variations: ["farsa", "farsante de marca maior"], popularityStatus: "ativo", region: "Brasil" },
  // 14. enrolação
  { term: "enrolação", meaning: "Ato de enrolar, enrolar a pessoa, dar desculpas em vez de responder ou agir.", adultTranslation: "Enrolação / Desculpa / Evasiva / Bater papo furado.", context: "Quando alguém dá voltas em vez de ser direto ou cumprir o prometido.", category: "expressão", riskLevel: "green", safeExample: "Para de enrolação e vai logo fazer o trabalho!", contextNotes: "Expressão comum no dia a dia. Pode ser brincadeira entre amigos ou frustração com atrasos. Inofensivo.", origin: "Cultura popular brasileira, do verbo 'enrolar'.", variations: ["enrolou", "enrolado", "enrolador"], popularityStatus: "ativo", region: "Brasil" },
  // 15. lero lero
  { term: "lero lero", meaning: "Fala longa e sem sentido, conversa fiada, papo que não leva a nada.", adultTranslation: "Conversa fiada / Papo furado / Palavrório vazio.", context: "Quando alguém fala muito sem dizer nada de útil ou interessante.", category: "expressão", riskLevel: "green", safeExample: "O discurso dele foi puro lero lero, não falou de nada.", contextNotes: "Expressão divertida para descrever fala vazia. Pode ser usada de forma engraçada ou crítica. Inofensivo.", origin: "Expressão popular brasileira de origem incerta, possivelmente onomatopeica.", variations: ["lero-lero", "papo furado"], popularityStatus: "ativo", region: "Brasil" },
  // 16. foi mal
  { term: "foi mal", meaning: "Desculpa, erro meu, me desculpe — expressão informal de pedido de desculpas.", adultTranslation: "Desculpa / Me perdoe / Foi sem querer.", context: "Expressão informal para pedir desculpas por algo que fez de errado.", category: "expressão", riskLevel: "green", safeExample: "Foi mal chegar atrasado, o trânsito tava péssimo.", contextNotes: "Expressão muito comum e natural entre jovens. Forma casual de pedir desculpas. Totalmente inofensivo.", origin: "Expressão popular brasileira, forma contraída de 'foi mau (por minha parte)'.", variations: ["malzão", "desculpa aí"], popularityStatus: "ativo", region: "Brasil" },
  // 17. esquece
  { term: "esquece", meaning: "Não faz mal, deixa pra lá, não se preocupa com isso.", adultTranslation: "Deixa pra lá / Não se preocupa / Não importa.", context: "Expressão para dizer que algo não tem importância ou para perdoar um erro.", category: "expressão", riskLevel: "green", safeExample: "Atrasei a entrega? Esquece, sem problema.", contextNotes: "Expressão de desapego e perdão. Muito saudável em relações. Totalmente positivo.", origin: "Expressão popular brasileira usada como atenuante em situações cotidianas.", variations: ["esquece isso", "deixa pra lá"], popularityStatus: "ativo", region: "Brasil" },
  // 18. zoeira
  { term: "zoeira", meaning: "Bagunça, brincadeira, diversão barulhenta, confusão alegre.", adultTranslation: "Brincadeira / Bagunça / Diversão / Confusão alegre.", context: "Situação de brincadeira e diversão entre amigos, geralmente com barulho e risada.", category: "humor", riskLevel: "green", safeExample: "A aula de educação física foi pura zoeira.", contextNotes: "Termo muito positivo que representa diversão e amizade. Pode virar bagunça excessiva em sala de aula. Contexto define.", origin: "Expressão popular brasileira, possivelmente do tupi ou origem africana.", variations: ["zoeiro", "zuar", "zoeira de leve"], popularityStatus: "ativo", region: "Brasil" },
  // 19. memes
  { term: "memes", meaning: "Imagens, vídeos ou textos cômicos que se espalham pela internet de forma viral.", adultTranslation: "Meme / Conteúdo viral cômico / Piada da internet.", context: "Conteúdo humorístico que se espalha rapidamente pela internet e é adaptado.", category: "humor", riskLevel: "green", safeExample: "Os memes de segunda-feira são sempre precisos.", contextNotes: "Linguagem universal da internet entre jovens. Pode ser usado para humor ou comentário social. Inofensivo na maioria das vezes.", origin: "Do grego 'mimeme', popularizado por Richard Dawkins e adaptado pela internet.", variations: ["meme", "memagem"], popularityStatus: "ativo", region: "internacional" },
  // 20. tiktok
  { term: "tiktok", meaning: "Rede social de vídeos curtos que domina a cultura jovem atual.", adultTranslation: "TikTok / App de vídeos curtos / Plataforma de conteúdo.", context: "Principal rede social entre adolescentes, onde trends, músicas e memes nascem.", category: "redes_sociais", riskLevel: "green", safeExample: "Aprendi isso no TikTok ontem.", contextNotes: "Plataforma central na vida de adolescentes. Pode ter conteúdo positivo e negativo. Orientar sobre uso consciente e tempo de tela.", origin: "App chinês lançado em 2016 (Douyin/TikTok), tornou-se a principal rede social jovem.", variations: ["TikTok", "TK"], popularityStatus: "ativo", region: "internacional" },
  // 21. instagram
  { term: "instagram", meaning: "Rede social de fotos e vídeos, principal plataforma de identidade visual dos jovens.", adultTranslation: "Instagram / Redes sociais / Plataforma de fotos.", context: "Rede social usada para compartilhar fotos, stories e reels.", category: "redes_sociais", riskLevel: "green", safeExample: "Postei uma foto nova no Instagram.", contextNotes: "Plataforma que afeta autoestima de muitos jovens. Pressão por likes e aparência. Orientar sobre comparação e uso saudável.", origin: "Rede social lançada em 2010, adquirida pelo Facebook em 2012.", variations: ["IG", "insta", "gram"], popularityStatus: "ativo", region: "internacional" },
  // 22. whatsapp
  { term: "whatsapp", meaning: "Aplicativo de mensagens mais usado no Brasil, principal forma de comunicação.", adultTranslation: "WhatsApp / App de mensagens / Zap.", context: "Aplicativo de mensagens usado para conversas pessoais, grupos e trabalho.", category: "redes_sociais", riskLevel: "green", safeExample: "Me manda no WhatsApp o endereço.", contextNotes: "Principal ferramenta de comunicação no Brasil. Pode gerar ansiedade com mensagens lidas e groups barulhentos. Orientar sobre desapego digital.", origin: "App lançado em 2009, adquirido pelo Facebook em 2014, dominante no Brasil.", variations: ["zap", "whats", "wpp", "zapzap"], popularityStatus: "ativo", region: "Brasil" },
  // 23. twitter
  { term: "twitter", meaning: "Rede social de mensagens curtas, espaço de debate e opinião.", adultTranslation: "Twitter/X / Rede social de microblog / Plataforma de opinião.", context: "Rede social onde pessoas compartilham opiniões curtas e participam de debates.", category: "redes_sociais", riskLevel: "yellow", safeExample: "Vi uma thread boa demais no Twitter.", contextNotes: "Pode ser espaço de debate saudável ou toxicidade. Polarização é problema. Orientar sobre pensamento crítico e respeito nas discussões.", origin: "Rede social lançada em 2006, rebatizada como X em 2023.", variations: ["X", "tweet", "thread"], popularityStatus: "ativo", region: "internacional" },
  // 24. discord
  { term: "discord", meaning: "Plataforma de comunicação por voz e texto, muito usada por gamers e comunidades.", adultTranslation: "Discord / Plataforma de chat / Comunicação gamer.", context: "App de chat por voz e texto muito usado por comunidades de jogos e amigos.", category: "gaming", riskLevel: "green", safeExample: "Bora pro Discord jogar com a galera?", contextNotes: "Principal ferramenta de comunicação gamer. Pode ter salas com conteúdo inadequado. Orientar sobre segurança online.", origin: "App lançado em 2015, popularizado entre comunidades de jogos.", variations: ["disc", "server do discord"], popularityStatus: "ativo", region: "internacional" },
  // 25. twitch
  { term: "twitch", meaning: "Plataforma de transmissões ao vivo, especialmente de jogos eletrônicos.", adultTranslation: "Twitch / Plataforma de streams / Transmissão ao vivo gamer.", context: "Plataforma onde streamers transmitem jogos, talk shows e entretenimento ao vivo.", category: "gaming", riskLevel: "green", safeExample: "Assisti o stream dele na Twitch ontem.", contextNotes: "Principal plataforma de streaming. Pode ter conteúdo inadequado em lives. Orientar sobre escolher canais seguros.", origin: "Plataforma de streaming lançada em 2011, adquirida pela Amazon em 2014.", variations: ["Twitch.tv", "live na Twitch"], popularityStatus: "ativo", region: "internacional" },
  // 26. youtube
  { term: "youtube", meaning: "Plataforma de vídeos, principal fonte de entretenimento e aprendizado online.", adultTranslation: "YouTube / Plataforma de vídeos / Canal de conteúdo.", context: "Site de vídeos onde se assiste de tudo: tutoriais, música, vlogs, games.", category: "redes_sociais", riskLevel: "green", safeExample: "Aprendi a tocar violino no YouTube.", contextNotes: "Plataforma versátil que pode educar e entreter. Conteúdo inadequado existe. Orientar sobre uso consciente e seleção de canais.", origin: "Plataforma de vídeos lançada em 2005, maior biblioteca de vídeos do mundo.", variations: ["YT", "YouTube"], popularityStatus: "ativo", region: "internacional" },
  // 27. spotify
  { term: "spotify", meaning: "Serviço de streaming de música mais usado no mundo.", adultTranslation: "Spotify / Streaming de música / App de música.", context: "Aplicativo para ouvir música online, criar playlists e descobrir novos artistas.", category: "entretenimento", riskLevel: "green", safeExample: "Minha playlist do Spotify tá perfeita.", contextNotes: "Ferramenta positiva para descoberta musical. Pode gerar ansiedade por wrapped (estatísticas anuais). Inofensivo.", origin: "Serviço sueco de streaming lançado em 2008, dominante globalmente.", variations: ["Spotify Premium", "playlist do Spotify"], popularityStatus: "ativo", region: "internacional" },
  // 28. netflix
  { term: "netflix", meaning: "Serviço de streaming de filmes e séries, principal plataforma de entretenimento.", adultTranslation: "Netflix / Streaming de séries / Plataforma de filmes.", context: "Serviço de streaming usado para assistir filmes, séries e documentários.", category: "entretenimento", riskLevel: "green", safeExample: "Vamos maratonar Netflix no fim de semana.", contextNotes: "Entretenimento popular entre jovens. Binge watching pode afetar sono e rotina. Orientar sobre equilíbrio.", origin: "Serviço americano de streaming lançado em 2007, popularizado globalmente.", variations: ["Netflix and chill", "maratona Netflix"], popularityStatus: "ativo", region: "internacional" },
  // 29. crunchyroll
  { term: "crunchyroll", meaning: "Plataforma de streaming especializada em animes e mangás.", adultTranslation: "Crunchyroll / Streaming de anime / Plataforma de animação japonesa.", context: "Serviço para assistir animes com legendas ou dublagem.", category: "entretenimento", riskLevel: "green", safeExample: "O novo episódio do anime já tá no Crunchyroll.", contextNotes: "Principal plataforma para fãs de anime. Comunidade apaixonada e criativa. Inofensivo.", origin: "Serviço americano de streaming de anime, popularizado entre jovens fãs de cultura japonesa.", variations: ["Crunchy", "CR"], popularityStatus: "ativo", region: "internacional" },
  // 30. wi-fi
  { term: "wi-fi", meaning: "Conexão sem fio à internet, essencial para a vida digital dos jovens.", adultTranslation: "Wi-Fi / Internet sem fio / Conexão wireless.", context: "Rede de internet sem fio que permite conectar dispositivos.", category: "tecnologia", riskLevel: "green", safeExample: "A wi-fi da escola caiu de novo.", contextNotes: "Essencial para a vida digital. Dependência de wi-fi pode gerar ansiedade quando indisponível. Inofensivo.", origin: "Tecnologia wireless padrão IEEE 802.11, popularizada a partir dos anos 2000.", variations: ["wifi", "internet", "rede"], popularityStatus: "ativo", region: "internacional" },
  // 31. slow
  { term: "slow", meaning: "Lento, demorado, internet ou pessoa que demora muito para fazer algo.", adultTranslation: "Lento / Demorado / Que leva tempo.", context: "Quando internet, computador ou pessoa está funcionando com lentidão.", category: "tecnologia", riskLevel: "green", safeExample: "O Wi-Fi tá slow demais, não carrega nada.", contextNotes: "Termo do inglês usado em português. Pode referir-se a tecnologia ou pessoas. Quando aplicado a pessoas, pode ser julgamento.", origin: "Do inglês 'slow', popularizado na cultura digital e entre jovens.", variations: ["lento", "demorando"], popularityStatus: "ativo", region: "Brasil" },
  // 32. lag
  { term: "lag", meaning: "Atraso ou lentidão em jogos online, quando a conexão não acompanha em tempo real.", adultTranslation: "Lentidão / Atraso / Travamento temporário.", context: "Quando há atraso entre ação e resposta em jogos online ou sistemas.", category: "gaming", riskLevel: "green", safeExample: "Perdi a partida por causa do lag.", contextNotes: "Problema técnico comum em jogos online. Pode causar frustração mas é apenas técnico. Inofensivo.", origin: "Termo técnico de computação e gaming, do escandinavo 'lagga' (atrasar).", variations: ["lagando", "laggy", "tps"], popularityStatus: "ativo", region: "internacional" },
  // 33. bug
  { term: "bug", meaning: "Erro ou defeito em software, app ou jogo que causa funcionamento incorreto.", adultTranslation: "Erro / Defeito / Falha de sistema.", context: "Quando um programa, app ou jogo apresenta comportamento incorreto ou inesperado.", category: "tecnologia", riskLevel: "green", safeExample: "O app tá com bug, não abre.", contextNotes: "Termo técnico de informática popularizado. Usado no dia a dia para qualquer problema digital. Inofensivo.", origin: "Termo técnico de computação, popularizado por Grace Hopper ao encontrar um inseto literal no computador.", variations: ["bugado", "bugando", "debug"], popularityStatus: "ativo", region: "internacional" },
  // 34. crash
  { term: "crash", meaning: "Falha grave que faz um app ou sistema fechar abruptamente.", adultTranslation: "Travamento total / Fechamento abrupto / Pane no sistema.", context: "Quando um aplicativo ou sistema para de funcionar de repente e fecha sozinho.", category: "tecnologia", riskLevel: "green", safeExample: "Meu celular deu crash no meio do jogo.", contextNotes: "Problema técnico frustrante mas sem consequências graves. Muito comum em jogos e apps. Inofensivo.", origin: "Do inglês 'crash', termo técnico de informática.", variations: ["crashou", "crashar"], popularityStatus: "ativo", region: "internacional" },
  // 35. brabo
  { term: "brabo", meaning: "Muito bom, incrível, impressionante; ou pessoa irritada.", adultTranslation: "Muito bom / Incrível / Irritado (contexto).", context: "Pode significar algo excelente ou alguém zangado, dependendo do contexto.", category: "elogio", riskLevel: "green", safeExample: "O som novo do MC tá brabo!", contextNotes: "Termo muito popular que pode ser elogio ou indicação de raiva. Contexto é fundamental. Na maioria das vezes é positivo.", origin: "Do espanhol 'bravo', adaptado na cultura popular brasileira, especialmente no funk.", variations: ["braba", "tá brabo", "brabíssimo"], popularityStatus: "ativo", region: "RJ, SP" },
  // 36. loco
  { term: "loco", meaning: "Louco, maluco, algo impressionante ou alguém que age de forma inesperada.", adultTranslation: "Louco / Maluco / Impressionante / Inesperado.", context: "Do espanhol, usado no Brasil para descrever algo louco ou impressionante.", category: "elogio", riskLevel: "green", safeExample: "Essa festança foi loca demais!", contextNotes: "Empréstimo do espanhol muito usado no Brasil. Pode ser elogio ou descrição de algo caótico. Inofensivo.", origin: "Do espanhol 'loco', popularizado na fronteira Brasil-Uruguai e na cultura reggaeton.", variations: ["loca", "loquinho"], popularityStatus: "ativo", region: "RS, Sul" },
  // 37. maluco
  { term: "maluco", meaning: "Louco, pessoa que faz coisas diferentes; ou algo impressionante e surpreendente.", adultTranslation: "Louco / Diferente / Surpreendente / Inesperado.", context: "Pode ser carinhoso (amigo maluco) ou impressionante (show maluco).", category: "elogio", riskLevel: "green", safeExample: "Esse maluco fez um gol de bicicleta!", contextNotes: "Termo muito versátil e positivo na maioria dos usos. Pode ser carinhoso entre amigos. Inofensivo.", origin: "Expressão popular brasileira, de origem na cultura afro-brasileira.", variations: ["maluca", "maluquice"], popularityStatus: "ativo", region: "Brasil" },
  // 38. pirada
  { term: "pirada", meaning: "Louca, maluca, exagerada; pessoa que age de forma intensa ou incomum.", adultTranslation: "Louca / Exagerada / Intensa / Incomum.", context: "Usado para descrever pessoa ou situação intensa, exagerada ou surpreendente.", category: "elogio", riskLevel: "green", safeExample: "Essa menina é pirada de tão engraçada.", contextNotes: "Pode ser elogio (pessoa divertida) ou crítica (pessoa excessiva). Depende do tom. Geralmente leve entre amigos.", origin: "Expressão popular brasileira, possivelmente derivada de 'pirar' (perder o eixo).", variations: ["pirado", "piração"], popularityStatus: "ativo", region: "Brasil" },
  // 39. insana
  { term: "insana", meaning: "Coisa muito boa, impressionante, absurda de tão boa.", adultTranslation: "Impressionante / Absurda / Muito boa / Inacreditável.", context: "Usado para descrever algo extremamente bom ou surpreendente.", category: "elogio", riskLevel: "green", safeExample: "A festa foi insana, melhor da vida!", contextNotes: "Termo que generalizou o significado de 'insano' para 'muito bom'. Muito comum entre jovens. Totalmente positivo.", origin: "Do latim 'insanus', ganhou conotação positiva na gíria jovem brasileira.", variations: ["insano", "insanidade"], popularityStatus: "ativo", region: "Brasil" },
  // 40. ousadia
  { term: "ousadia", meaning: "Coragem de fazer algo diferente, arriscado ou inesperado.", adultTranslation: "Ousadia / Coragem / Atitude arrojada / Audácia.", context: "Quando alguém faz algo que exige coragem e quebra o padrão.", category: "elogio", riskLevel: "green", safeExample: "Ousadia dela de cortar todo o cabelo ficou incrível!", contextNotes: "Qualidade muito valorizada entre jovens. Incentiva criatividade e autoconfiança. Totalmente positivo.", origin: "Do latim 'audacia', conceito valorizado na cultura jovem e funk.", variations: ["ousado", "ousadia de sobra"], popularityStatus: "ativo", region: "Brasil" },
  // 41. presença
  { term: "presença", meaning: "Capacidade de se fazer notar, carisma natural que impacta um ambiente.", adultTranslation: "Presença / Carisma / Impacto pessoal / Imponência.", context: "Quando alguém tem uma energia natural que chama atenção onde quer que vá.", category: "elogio", riskLevel: "green", safeExample: "A presença dele na sala é absurda, todos olham.", contextNotes: "Elogio a carisma e energia pessoal. Pode ser desenvolvida com confiança. Totalmente positivo.", origin: "Cultura popular brasileira, especialmente no funk e na música.", variations: ["presença de palco", "tem presença"], popularityStatus: "ativo", region: "Brasil" },
  // 42. influência
  { term: "influência", meaning: "Poder de afetar as ações e opiniões dos outros, especialmente nas redes sociais.", adultTranslation: "Influência / Impacto / Poder de convencimento.", context: "Capacidade de uma pessoa de afetar comportamentos e opiniões, especialmente online.", category: "redes_sociais", riskLevel: "green", safeExample: "O influenciador tem muita influência sobre os seguidores.", contextNotes: "Conceito central na cultura digital. Pode ser positivo (influenciadores educativos) ou negativo. Orientar sobre pensamento crítico.", origin: "Marketing e redes sociais, conceito amplificado pela economia de criadores.", variations: ["influencer", "influenciar"], popularityStatus: "ativo", region: "internacional" },
  // 43. referência
  { term: "referência", meaning: "Pessoa ou coisa que serve de exemplo, modelo ou inspiração.", adultTranslation: "Referência / Modelo / Exemplo / Inspiração.", context: "Alguém que é exemplo a ser seguido em determinada área.", category: "elogio", riskLevel: "green", safeExample: "O Craque é referência pra qualquer jogador.", contextNotes: "Elogio que reconhece excelência. Pode ser em qualquer área: esporte, arte, estudos. Totalmente positivo.", origin: "Cultura esportiva e artística brasileira.", variations: ["referência em...", "é referência"], popularityStatus: "ativo", region: "Brasil" },
  // 44. coach
  { term: "coach", meaning: "Orientador, mentor, pessoa que guia e motiva outros a alcançarem objetivos.", adultTranslation: "Orientador / Mentor / Treinador pessoal / Guia.", context: "Pessoa que ajuda outros a alcançarem metas, seja nos estudos, esportes ou vida pessoal.", category: "profissão", riskLevel: "green", safeExample: "Meu coach me ajudou a organizar os estudos.", contextNotes: "Profissão emergente entre jovens. Pode ser motivacional ou técnico. Orientar sobre verificar credenciais.", origin: "Do inglês, originally esportivo, expandido para todas as áreas da vida.", variations: ["coaching", "mentor"], popularityStatus: "ativo", region: "internacional" },
  // 45. escola
  { term: "escola", meaning: "Instituição de ensino, ambiente de convivência e aprendizagem.", adultTranslation: "Escola / Colégio / Instituição de ensino.", context: "Lugar de estudo e convivência social, central na vida de adolescentes.", category: "educacao", riskLevel: "green", safeExample: "A escola hoje teve dia de prova.", contextNotes: "Ambiente que pode ser positivo ou estressante. Relações sociais são centrais. Orientar sobre convivência saudável e buscar ajuda em caso de bullying.", origin: "Do latim 'schola', instituição fundamental na sociedade.", variations: ["colégio", "escolinha", "aula"], popularityStatus: "ativo", region: "Brasil" },
  // 46. faculdade
  { term: "faculdade", meaning: "Ensino superior, universidade, curso de graduação.", adultTranslation: "Faculdade / Universidade / Ensino superior.", context: "Instituição de ensino superior onde se faz graduação.", category: "educacao", riskLevel: "green", safeExample: "Quero entrar em faculdade de medicina.", contextNotes: "Meta importante para muitos adolescentes. Pode gerar ansiedade. Orientar sobre diferentes caminhos e que não há apenas um rumo certo.", origin: "Do latim 'facultas', sistema educacional brasileiro.", variations: ["facul", "uni", "universidade"], popularityStatus: "ativo", region: "Brasil" },
  // 47. enem
  { term: "enem", meaning: "Exame Nacional do Ensino Médio, principal prova de acesso ao ensino superior no Brasil.", adultTranslation: "ENEM / Exame nacional / Prova de vestibular.", context: "Prova aplicada pelo MEC usada para acesso a universidades e programas do governo.", category: "educacao", riskLevel: "green", safeExample: "Tô estudando muito pro ENEM desse ano.", contextNotes: "Central na vida de estudantes brasileiros. Pode gerar muita ansiedade. Orientar sobre gerenciar estresse e que não define o futuro.", origin: "Criado em 1998, tornou-se principal porta de entrada para universidades públicas.", variations: ["prova do ENEM", "ENEM 2024"], popularityStatus: "ativo", region: "Brasil" },
  // 48. redação
  { term: "redação", meaning: "Texto dissertativo argumentativo, especialmente a do ENEM.", adultTranslation: "Redação / Texto dissertativo / Composição escrita.", context: "Prova de escrita do ENEM ou trabalho escrito escolar.", category: "educacao", riskLevel: "green", safeExample: "Preciso treinar redação todo dia pra tirar 1000.", contextNotes: "Parte crucial do ENEM. Pode ser fonte de estresse. Orientar sobre prática regular e não buscar perfeição.", origin: "Do latim 'redactione', prática educacional fundamental.", variations: ["redação do ENEM", "texto"], popularityStatus: "ativo", region: "Brasil" },
  // 49. estágio
  { term: "estágio", meaning: "Programa de trabalho para estudantes, experiência profissional prática.", adultTranslation: "Estágio / Primeiro emprego / Experiência profissional.", context: "Programa de trabalho para estudantes ganharem experiência profissional.", category: "educacao", riskLevel: "green", safeExample: "Consegui estágio na empresa dos sonhos!", contextNotes: "Primeira experiência profissional para muitos jovens. Pode ser remunerado ou não. Totalmente positivo para desenvolvimento.", origin: "Do mundo corporativo, Lei do Estagiário (Lei 11.788/2008).", variations: ["estagiário", "estagiar"], popularityStatus: "ativo", region: "Brasil" },
  // 50. freelancer
  { term: "freelancer", meaning: "Profissional autônomo que trabalha por projeto sem vínculo empregatício.", adultTranslation: "Autônomo / Profissional liberal / Trabalhador por projeto.", context: "Pessoa que trabalha de forma independente, prestando serviços por projeto.", category: "profissão", riskLevel: "green", safeExample: "Comecei como freelancer fazendo design pra small businesses.", contextNotes: "Forma de trabalho crescente entre jovens. Pode ser flexível mas inseguro. Orientar sobre gestão financeira.", origin: "Do inglês 'freelance', popularizado pela economia digital e internet.", variations: ["freelance", "autônomo", "trabalho remoto"], popularityStatus: "ativo", region: "internacional" },
  // 51. startup
  { term: "startup", meaning: "Empresa emergente e inovadora, geralmente de tecnologia.", adultTranslation: "Empresa emergente / Negócio inovador / Startup tech.", context: "Empresa jovem e inovadora que busca crescer rapidamente com uma ideia nova.", category: "profissão", riskLevel: "green", safeExample: "Meu sonho é montar uma startup de IA.", contextNotes: "Ecossistema que atrai jovens empreendedores. Pode ser excitante mas arriscado. Orientar sobre planejamento e estudo de mercado.", origin: "Do inglês, conceito de negócio inovador popularizado no Vale do Silício.", variations: ["empreendimento", "nova empresa"], popularityStatus: "ativo", region: "internacional" },
  // 52. grana
  { term: "grana", meaning: "Dinheiro, valor monetário, recursos financeiros.", adultTranslation: "Dinheiro / Nota / Valor / Recurso financeiro.", context: "Forma informal de se referir a dinheiro em geral.", category: "dinheiro", riskLevel: "green", safeExample: "Preciso arrumar uma grana pra comprar o tênis novo.", contextNotes: "Termo muito comum e inofensivo para falar de dinheiro. Pode indicar necessidade ou fartura. Normal no dia a dia.", origin: "Possivelmente do italiano 'grana' (trigo/riqueza), popularizado no Brasil.", variations: ["dinheiro", "din", "garimpo"], popularityStatus: "ativo", region: "Brasil" },
  // 53. pilas
  { term: "pilas", meaning: "Dinheiro, principalmente em grande quantidade; riqueza, recursos.", adultTranslation: "Dinheiro / Riqueza / Fortuna / Dinheiro vivo.", context: "Forma informal de falar de dinheiro, especialmente quando se tem muito.", category: "dinheiro", riskLevel: "green", safeExample: "Ele tem pilas, compra tudo que quer.", contextNotes: "Gíria brasileira para dinheiro, mais usada em alguns estados. Inofensivo.", origin: "Expressão popular brasileira, possivelmente origem no espanês 'pilas' (baterias/energia).", variations: ["pilas demais", "ter pilas"], popularityStatus: "regional", region: "RJ, SP" },
  // 54. pão duro
  { term: "pão duro", meaning: "Pessoa avarenta, que não gosta de gastar dinheiro; sovina.", adultTranslation: "Avarento / Sovina / Pão-duro / Economato.", context: "Alguém que economiza demais ou não quer gastar dinheiro.", category: "humor", riskLevel: "yellow", safeExample: "Meu amigo é pão duro, nunca paga o lanche.", contextNotes: "Pode ser brincadeira entre amigos ou crítica real. Pode machucar se usado de forma pública. Orientar sobre empatia.", origin: "Expressão popular brasileira que compara avareza a dureza do pão.", variations: ["pão-duro", "sovina", "mão-de-vaca"], popularityStatus: "ativo", region: "Brasil" },
  // 55. farpando
  { term: "farpando", meaning: "Trabalhando duro, correndo atrás do dinheiro, batalhando.", adultTranslation: "Trabalhando duro / Batalhando / Correndo atrás.", context: "Quando alguém está trabalhando muito para conseguir dinheiro ou atingir objetivo.", category: "expressão", riskLevel: "green", safeExample: "Tô farpando aqui pra conseguir comprar o presente.", contextNotes: "Termo que valoriza esforço e trabalho. Muito usado de forma positiva para reconhecer dedicação. Totalmente positivo.", origin: "Cultura popular brasileira, possivelmente de 'farpas' (espinhos, dificuldades).", variations: ["farpar", "batalhando"], popularityStatus: "regional", region: "RJ, SP" },
  // 56. ostentando
  { term: "ostentando", meaning: "Exibindo riqueza, mostrando posses de forma exagerada para impressionar.", adultTranslation: "Exibindo / Ostentando riqueza / Mostrando posse.", context: "Quando alguém mostra bens caros de forma exagerada para impressionar os outros.", category: "humor", riskLevel: "yellow", safeExample: "Ele tá ostentando o carro novo no Instagram.", contextNotes: "Pode ser visto como supérfluo ou engraçado. Depende da intenção. Orientar sobre valores além de bens materiais.", origin: "Cultura funk e hip-hop, popularizado por músicas sobre ostentação.", variations: ["ostentação", "ostentar", "flex"], popularityStatus: "ativo", region: "Brasil" },
  // 57. renda
  { term: "renda", meaning: "Dinheiro que se ganha regularmente, salário, ganho mensal.", adultTranslation: "Renda / Salário / Ganhos / Entrada de dinheiro.", context: "Dinheiro que uma pessoa recebe regularmente por trabalho ou investimentos.", category: "dinheiro", riskLevel: "green", safeExample: "Minha renda do mês deu pra pagar tudo.", contextNotes: "Conceito financeiro importante. Muito jovem já pensa em renda e finanças. Totalmente normal e positivo.", origin: "Do latim 'rendita', conceito econômico básico.", variations: ["renda mensal", "renda familiar"], popularityStatus: "ativo", region: "Brasil" },
  // 58. aplicar
  { term: "aplicar", meaning: "Investir dinheiro, usar conhecimento na prática, se dedicar a algo.", adultTranslation: "Investir / Empregar / Dedicar-se / Colocar em prática.", context: "Investir dinheiro, aplicar conhecimento ou se dedicar a um objetivo.", category: "expressão", riskLevel: "green", safeExample: "Preciso aplicar meu dinheiro em vez de gastar tudo.", contextNotes: "Conceito financeiro positivo que incentiva planejamento. Quando aplicado a estudos, também é construtivo.", origin: "Do latim 'applicare', termo formal adaptado para linguagem informal.", variations: ["aplicação", "aplicando"], popularityStatus: "ativo", region: "Brasil" },
  // 59. preguiçoso
  { term: "preguiçoso", meaning: "Pessoa que não quer fazer nada, que tem dificuldade de se movimentar ou trabalhar.", adultTranslation: "Preguiçoso / Preguiça / Indolente / Desmotivado.", context: "Alguém que evita esforço físico ou mental, prefere não fazer nada.", category: "humor", riskLevel: "green", safeExample: "Hoje tô me sentindo preguiçoso, não quero sair da cama.", contextNotes: "Pode ser crítica ou autodepreciação leve. Pode indicar falta de motivação ou até depressão. Orientar sobre importância de atividade física.", origin: "Do latim 'pigritia', conceito universal.", variations: ["preguiça", "preguiça de levar"], popularityStatus: "ativo", region: "Brasil" },
  // 60. madrugada
  { term: "madrugada", meaning: "Período da noite entre meia-noite e o amanhecer, horas avançadas da noite.", adultTranslation: "Madrugada / Altas horas / Pequenas horas.", context: "Horário noturno tardio, quando muitos adolescentes estão acordados no celular.", category: "tempo", riskLevel: "green", safeExample: "Fiquei até a madrugada vendo TikTok.", contextNotes: "Período que pode afetar sono e saúde. Muitos jovens dormem tarde por hábito digital. Orientar sobre higiene do sono.", origin: "Do latim 'maturugada', conceito temporal brasileiro.", variations: ["de madrugada", "altas horas"], popularityStatus: "ativo", region: "Brasil" },
  // 61. confia
  { term: "confia", meaning: "Confiar, acreditar, expressão de confiança e crença.", adultTranslation: "Confia / Acredita / Tem fé.", context: "Expressão para demonstrar confiança em alguém ou em uma situação.", category: "elogio", riskLevel: "green", safeExample: "Confia em mim, vai dar tudo certo.", contextNotes: "Expressão positiva que transmite confiança e apoio. Pode ser usado como lema motivacional. Totalmente positivo.", origin: "Do verbo 'confiar', popularizado como expressão afirmativa entre jovens.", variations: ["confia!", "trust"], popularityStatus: "ativo", region: "Brasil" },
  // 62. no cap
  { term: "no cap", meaning: "Sem mentira, sem exagero, falando sério, é a verdade.", adultTranslation: "Sem mentira / Falando sério / É verdade / Juro.", context: "Expressão usada para enfatizar que se está dizendo a verdade, sem exagero.", category: "expressão", riskLevel: "green", safeExample: "Esse filme é bom demais, no cap.", contextNotes: "Termo do rap americano adaptado globalmente. Equivalente a 'juro' ou 'falando sério'. Totalmente inofensivo.", origin: "Cultura hip-hop americana, 'cap' significa mentira, 'no cap' é sem mentira.", variations: ["cap", "no cap fr fr"], popularityStatus: "ativo", region: "internacional" },
  // 63. fr fr
  { term: "fr fr", meaning: "For real for real, verdadeiramente, de verdade, sem dúvida.", adultTranslation: "De verdade / Sem dúvida / Realmente / Com certeza.", context: "Expressão para enfatizar concordância ou que algo é verdadeiro.", category: "expressão", riskLevel: "green", safeExample: "A prova foi difícil, fr fr.", contextNotes: "Abreviação de 'for real for real'. Muito comum entre adolescentes. Totalmente inofensivo.", origin: "Cultura hip-hop e internet americana, popularizado globalmente pelo TikTok.", variations: ["for real", "real"], popularityStatus: "ativo", region: "internacional" },
  // 64. literally
  { term: "literally", meaning: "Literalmente, exatamente como dito, sem exagero.", adultTranslation: "Literalmente / Exatamente / De verdade.", context: "Usado para enfatizar que algo é exato ou real, às vezes de forma exagerada.", category: "expressão", riskLevel: "green", safeExample: "Eu literally chorei assistindo esse filme.", contextNotes: "Termo inglês muito usado por jovens brasileiros. Pode ser exagerado para dar ênfase. Inofensivo.", origin: "Do inglês 'literally', popularizado entre jovens bilíngues e pela internet.", variations: ["literal", "literalmente"], popularityStatus: "ativo", region: "internacional" },
  // 65. deadass
  { term: "deadass", meaning: "Sério, falando sério, sem brincadeira, de verdade.", adultTranslation: "Sério / Falando sério / Sem brincadeira / Honestamente.", context: "Expressão para enfatizar seriedade, equivalente a 'tô falando sério'.", category: "expressão", riskLevel: "green", safeExample: "Ele deadass disse isso na aula?", contextNotes: "Termo do slang americano popularizado pelo TikTok. Pode soar estranho para adultos mas é inofensivo.", origin: "Slang afro-americano de Nova York, popularizado globalmente.", variations: ["dead serious", "sério mesmo"], popularityStatus: "ativo", region: "internacional" },
  // 66. lowkey
  { term: "lowkey", meaning: "Discretamente, de forma sutil, sem muita atenção; ou secretamente.", adultTranslation: "Discretamente / De baixo / Secretamente / Sutilmente.", context: "Expressão para dizer que algo é sutil, secreto ou que se sente algo moderadamente.", category: "expressão", riskLevel: "green", safeExample: "Lowkey tô gostando dessa música que todo mundo odeia.", contextNotes: "Extremamente popular entre adolescentes. Permite expressar sentimentos sem comprometimento. Inofensivo.", origin: "Cultura hip-hop americana, popularizado globalmente pelo TikTok.", variations: ["low key", "lowkey", "de leve"], popularityStatus: "ativo", region: "internacional" },
  // 67. highkey
  { term: "highkey", meaning: "Abertamente, de forma clara e óbvia, sem esconder.", adultTranslation: "Abertamente / Claramente / De forma óbvia / Sem disfarce.", context: "Antônimo de lowkey, usado para expressar algo de forma clara e direta.", category: "expressão", riskLevel: "green", safeExample: "Highkey quero ir nesse show, tô falando sério.", contextNotes: "Menos usado que lowkey mas igualmente popular. Expressa convicção e clareza. Inofensivo.", origin: "Cultura hip-hop e internet americana.", variations: ["high key", "alto"], popularityStatus: "ativo", region: "internacional" },
  // 68. valid
  { term: "valid", meaning: "Válido, aceitável, legítimo, que faz sentido.", adultTranslation: "Válido / Legítimo / Aceitável / Compreensível.", context: "Expressão para validar a opinião ou sentimento de alguém.", category: "elogio", riskLevel: "green", safeExample: "Sua opinião é super valid.", contextNotes: "Uso empático e construtivo do inglês 'valid'. Mostra respeito pela perspectiva do outro. Totalmente positivo.", origin: "Cultura da internet e psicologia pop, popularizado como expressão de empatia.", variations: ["valid point", "valid"], popularityStatus: "ativo", region: "internacional" },
  // 69. period
  { term: "period", meaning: "Ponto final, fim de discussão, está decidido, não tem mais o que falar.", adultTranslation: "Ponto final / Fim de discussão / Acabou / Pronto.", context: "Expressão usada para encerrar uma discussão ou afirmação de forma definitiva.", category: "expressão", riskLevel: "green", safeExample: "Ela é a melhor cantora, period.", contextNotes: "Expressão assertiva que marca firmeza na opinião. Pode ser vista como arrogante se usada em excesso. No geral, inofensivo.", origin: "Cultura pop americana, especialmente discurso feminista negro.", variations: ["period.", "periodt"], popularityStatus: "ativo", region: "internacional" },
  // 70. periodt
  { term: "periodt", meaning: "Versão enfatizada de period, com ainda mais ênfase e firmeza.", adultTranslation: "Ponto final definitivo / Fim absoluto / Sem discussão.", context: "Versão intensificada de period, usada com ainda mais convicção.", category: "expressão", riskLevel: "green", safeExample: "Isso é racismo, periodt.", contextNotes: "Versão com 't' que enfatiza a firmeza. Muito usada em debates sobre justiça social. Totalmente inofensivo.", origin: "Cultura AAVE (African American Vernacular English), popularizado no TikTok.", variations: ["period", "periodtt"], popularityStatus: "ativo", region: "internacional" },
  // 71. tá rodando
  { term: "tá rodando", meaning: "Tá funcionando, tá dando certo, está tudo bem.", adultTranslation: "Tá funcionando / Tá dando certo / Tá sob controle.", context: "Expressão para dizer que algo está funcionando ou indo bem.", category: "expressão", riskLevel: "green", safeExample: "O projeto tá rodando bem, deve ficar pronto na semana.", contextNotes: "Expressão informal positiva muito comum no dia a dia. Totalmente inofensivo.", origin: "Cultura popular brasileira, possivelmente de origem no funk ou trabalho informal.", variations: ["tá rolando", "rodando"], popularityStatus: "ativo", region: "Brasil" },
  // 72. tá osso
  { term: "tá osso", meaning: "Tá difícil, tá complicado, situação está ruim.", adultTranslation: "Tá difícil / Tá complicado / Situação ruim / Pesado.", context: "Expressão para descrever uma situação difícil ou desafiadora.", category: "expressão", riskLevel: "green", safeExample: "O conteúdo da prova tá osso demais.", contextNotes: "Expressão muito comum entre estudantes para descrever dificuldades. Inofensivo e natural.", origin: "Cultura popular brasileira, metáfora com osso (difícil de roer).", variations: ["tá osso mesmo", "osso"], popularityStatus: "ativo", region: "Brasil" },
  // 73. tá brabo
  { term: "tá brabo", meaning: "Tá muito bom, impressionante; ou está irritado.", adultTranslation: "Tá muito bom / Tá forte / Tá irritado (contexto).", context: "Pode significar que algo está excelente ou que alguém está bravo.", category: "elogio", riskLevel: "green", safeExample: "O lanche novo da cantina tá brabo!", contextNotes: "Na maioria das vezes é elogio (muito bom). Contexto de raiva é menos comum entre jovens. Inofensivo.", origin: "Expressão popular brasileira, possivelmente do espanhol 'bravo'.", variations: ["brabo", "tá braba"], popularityStatus: "ativo", region: "Brasil" },
  // 74. tá foda
  { term: "tá foda", meaning: "Tá muito bom, excelente; ou tá muito difícil.", adultTranslation: "Tá incrível / Tá difícil / Situação intensa.", context: "Pode ser positivo (muito bom) ou negativo (muito difícil), dependendo do contexto.", category: "expressão", riskLevel: "yellow", safeExample: "Esse jogo novo tá foda, gráficos são insanos.", contextNotes: "Contém palavrão na origem mas é usado como intensificador. Normal entre adolescentes. Orientar sobre uso de palavras mais adequadas em contextos formais.", origin: "Cultura popular brasileira, intensificador coloquial.", variations: ["foda", "fodástico"], popularityStatus: "ativo", region: "Brasil" },
  // 75. tá top
  { term: "tá top", meaning: "Tá ótimo, excelente, perfeito.", adultTranslation: "Tá ótimo / Excelente / Perfeito / Muito bom.", context: "Expressão para dizer que algo está muito bom ou excelente.", category: "elogio", riskLevel: "green", safeExample: "A festinha tá top, bora!", contextNotes: "Expressão extremamente comum e positiva. Totalmente inofensivo e construtiva.", origin: "Do inglês 'top', adaptado na gíria brasileira como elogio.", variations: ["top demais", "muito top"], popularityStatus: "ativo", region: "Brasil" },
  // 76. tá slay
  { term: "tá slay", meaning: "Tá incrível, tá matando, está arrasando, look ou performance perfeita.", adultTranslation: "Tá arrasando / Tá perfeito / Tá incrível.", context: "Expressão para elogiar alguém que está se saindo muito bem em algo.", category: "elogio", riskLevel: "green", safeExample: "Seu look hoje tá slay, demais!", contextNotes: "Termo de elogio muito popular entre adolescentes. Totalmente positivo e construtivo. Celebra excelência.", origin: "Do inglês 'slay' (matar, arrasar), popularizado pelo TikTok e cultura pop.", variations: ["slay", "slaying", "slay queen"], popularityStatus: "ativo", region: "internacional" },
  // 77. tá lit
  { term: "tá lit", meaning: "Tá muito bom, animado, emocionante, incrível.", adultTranslation: "Tá animado / Tá bom demais / Tá muito legal.", context: "Expressão para descrever algo que está muito bom ou animado.", category: "elogio", riskLevel: "green", safeExample: "A festa tá lit, música tá ótima!", contextNotes: "Termo do inglês 'lit' (aceso, emocionante). Muito comum entre jovens. Totalmente inofensivo.", origin: "Cultura hip-hop americana, popularizado globalmente.", variations: ["lit", "lit af", "tá lit demais"], popularityStatus: "ativo", region: "internacional" },
  // 78. tá bussin
  { term: "tá bussin", meaning: "Tá muito bom, excelente, saboroso (especialmente comida) ou impressionante.", adultTranslation: "Tá muito bom / Excelente / Saboroso / Impressionante.", context: "Expressão para dizer que algo é extremamente bom, especialmente comida.", category: "elogio", riskLevel: "green", safeExample: "Essa pizza tá bussin, melhor que já comi!", contextNotes: "Termo do TikTok americano adaptado globalmente. Inofensivo e divertido.", origin: "AAVE, do inglês 'bussin' (delicioso), popularizado no TikTok.", variations: ["bussin", "bussin bussin"], popularityStatus: "ativo", region: "internacional" },
  // 79. tá sigma
  { term: "tá sigma", meaning: "Tá muito bom, demonstrate atitude de independência e confiança.", adultTranslation: "Tá confiante / Tá independente / Atitude de líder.", context: "Expressão para descrever alguém com atitude de liderança e independência.", category: "elogio", riskLevel: "green", safeExample: "Ele entrou na sala sem falar com ninguém, tá sigma.", contextNotes: "Refere-se ao arquétipo 'sigma male' — independente, confiante, que não segue a multidão. Pode reforçar expectativas de gênero.", origin: "TikTok, arquétipo 'sigma male' da hierarquia social inventada na internet.", variations: ["sigma", "sigma male"], popularityStatus: "ativo", region: "internacional" },
  // 80. tá aura
  { term: "tá aura", meaning: "Tá com muita energia positiva, carisma e presença notável.", adultTranslation: "Tá com energia boa / Tem presença / Carisma elevado.", context: "Expressão para descrever alguém com energia magnética e positiva.", category: "elogio", riskLevel: "green", safeExample: "Esse tênis novo é puro aura.", contextNotes: "Trend recente do TikTok. 'Aura' como qualidade pessoal magnética. Totalmente positivo e divertido.", origin: "TikTok 2024, trend de 'aura points' para medir carisma.", variations: ["aura", "aura points", "negative aura"], popularityStatus: "ativo", region: "internacional" },
  // 81. tá farmar
  { term: "tá farmar", meaning: "Tá cultivando, está acumulando, está construindo algo aos poucos.", adultTranslation: "Tá cultivando / Acumulando / Construindo aos poucos.", context: "Expressão usada especialmente no gaming para dizer que está ganhando experiência ou itens.", category: "gaming", riskLevel: "green", safeExample: "Tô farmando XP pra subir de nível.", contextNotes: "Termo de gaming que passou para o dia a dia. Refere-se a acumular recursos ou experiência. Inofensivo.", origin: "Cultura gamer, do inglês 'farming' (cultivar).", variations: ["farmar", "farm", "farming"], popularityStatus: "ativo", region: "internacional" },
  // 82. tá crack
  { term: "tá crack", meaning: "Tá muito bom, excelente, nível profissional, impecável.", adultTranslation: "Tá excelente / Nível profissional / Impecável.", context: "Elogio máximo para algo ou alguém que está em nível muito alto.", category: "elogio", riskLevel: "green", safeExample: "Esse jogador é crack, joga melhor que profissional.", contextNotes: "Originalmente do futebol (craque). Significa excelência. Pode referir-se a qualquer área. Totalmente positivo.", origin: "Futebol brasileiro, 'craque' como jogador excepcional, adaptado para gíria geral.", variations: ["craque", "crack", "crackzinho"], popularityStatus: "ativo", region: "Brasil" },
  // 83. tá brutal
  { term: "tá brutal", meaning: "Tá absurdo, muito bom, impressionante demais.", adultTranslation: "Absurdo de bom / Impressionante / Muito forte.", context: "Intensificador para algo extremamente bom ou surpreendente.", category: "elogio", riskLevel: "green", safeExample: "O show de ontem foi brutal!", contextNotes: "Termo muito comum como elogio entre jovens. Intensifica qualquer descrição positiva. Inofensivo.", origin: "Do inglês 'brutal', adaptado na gíria brasileira com conotação positiva.", variations: ["brutal", "brutal demais"], popularityStatus: "ativo", region: "Brasil" },
  // 84. tá nice
  { term: "tá nice", meaning: "Tá legal, tá bom, agradável, bacana.", adultTranslation: "Tá legal / Bacana / Agradável / Bonito.", context: "Expressão de aprovação leve, quando algo está bom mas não extraordinário.", category: "elogio", riskLevel: "green", safeExample: "O lugar é nice, nada demais mas é agradável.", contextNotes: "Elogio moderado, menos intenso que 'tá top' ou 'tá brabo'. Pode ser honesto ou desinteressado. Inofensivo.", origin: "Do inglês 'nice', adaptado na gíria brasileira informal.", variations: ["nice", "muito nice"], popularityStatus: "ativo", region: "Brasil" },
  // 85. tá de boa
  { term: "tá de boa", meaning: "Tá tranquilo, tudo bem, sem problemas, relaxado.", adultTranslation: "Tá tranquilo / Tudo bem / Sem stress / Relaxado.", context: "Expressão para dizer que está tudo bem ou que está sem preocupações.", category: "saudacao", riskLevel: "green", safeExample: "Tá de boa, pode contar comigo.", contextNotes: "Uma das expressões mais comuns entre jovens brasileiros. Transmite tranquilidade e confiança. Totalmente positivo.", origin: "Cultura popular brasileira, expressão de descontração.", variations: ["de boa", "tá suave", "tá sussa"], popularityStatus: "ativo", region: "Brasil" },
  // 86. tá sussa
  { term: "tá sussa", meaning: "Tá tranquilo, tá calmo, sem stress, tudo resolvido.", adultTranslation: "Tá tranquilo / Sem stress / Calmo / Resolvido.", context: "Versão descontraída de 'tá de boa', mais relaxada ainda.", category: "saudacao", riskLevel: "green", safeExample: "Não se preocupa, tá sussa.", contextNotes: "Expressão muito comum e descontraída. Transmite calma e segurança. Totalmente inofensivo.", origin: "Cultura jovem paulista, possivelmente variação de 'sussegado'.", variations: ["sussa", "sussado", "sussência"], popularityStatus: "ativo", region: "SP, RJ" },
  // 87. mega
  { term: "mega", meaning: "Muito, extremamente, super, intensificador de algo.", adultTranslation: "Muito / Super / Extremamente / Hiper.", context: "Intensificador usado para enfatizar qualquer adjetivo ou situação.", category: "expressão", riskLevel: "green", safeExample: "A festa foi mega divertida!", contextNotes: "Intensificador leve e inofensivo. Equivalente a 'super' ou 'muito'. Totalmente normal.", origin: "Do grego 'megas' (grande), adaptado como intensificador na linguagem informal.", variations: ["mega mesmo", "mega chato"], popularityStatus: "ativo", region: "Brasil" },
  // 88. hiper
  { term: "hiper", meaning: "Muito, extremamente, exageradamente, além do normal.", adultTranslation: "Hiper / Exagerado / Muito intenso / Além do normal.", context: "Intensificador para enfatizar algo que está acima do normal.", category: "expressão", riskLevel: "green", safeExample: "Ela ficou hiper animada com o convite.", contextNotes: "Pode indicar entusiasmo excessivo. Normal entre jovens. Quando aplicado a comportamento, pode indicar TDAH. Contexto importa.", origin: "Do grego 'hyper' (acima de), usado como prefixo e intensificador.", variations: ["hiperativo", "hiper mesmo"], popularityStatus: "ativo", region: "Brasil" },
  // 89. super
  { term: "super", meaning: "Muito, extremamente, excelente, intensificador universal.", adultTranslation: "Muito / Super / Excelente / Acima do normal.", context: "Intensificador muito versátil, pode reforçar positivamente qualquer coisa.", category: "elogio", riskLevel: "green", safeExample: "Ficou super bonita com esse vestido!", contextNotes: "Intensificador mais comum e inofensivo da língua portuguesa. Totalmente normal e positivo.", origin: "Do latim 'super', intensificador universal.", variations: ["super legal", "super bom"], popularityStatus: "ativo", region: "Brasil" },
  // 90. pra caramba
  { term: "pra caramba", meaning: "Muito, demais, exageradamente, intensificador forte.", adultTranslation: "Muito / Demais / Bastante / Extremamente.", context: "Intensificador para enfatizar algo de forma forte e expressiva.", category: "expressão", riskLevel: "green", safeExample: "Estava cansado pra caramba depois do treino.", contextNotes: "Expressão popular inofensiva que substitui palavrões. Eufemismo criativo e positivo.", origin: "Expressão popular brasileira, eufemismo que substitui expressões mais fortes.", variations: ["pra burro", "pra dedéu"], popularityStatus: "ativo", region: "Brasil" },
  // 91. demais
  { term: "demais", meaning: "Muito, excessivo, excelente (dependendo do contexto).", adultTranslation: "Demais / Excessivo / Muito bom / Muito intenso.", context: "Intensificador que pode ser positivo (ótimo) ou negativo (excessivo).", category: "elogio", riskLevel: "green", safeExample: "O filme foi demais, recomendo demais!", contextNotes: "Muito versátil e positivo na maioria dos usos. Pode indicar exagero quando negativo. Inofensivo.", origin: "Expressão portuguesa padrão adaptada como intensificador na gíria.", variations: ["muito demais", "demais pra caramba"], popularityStatus: "ativo", region: "Brasil" },
  // 92. né
  { term: "né", meaning: "Não é?, expressão para concordar ou confirmar algo.", adultTranslation: "Não é? / Concorda? / Certo?", context: "Usado no final de frases para buscar confirmação ou concordância.", category: "expressão", riskLevel: "green", safeExample: "Hoje tá quente, né?", contextNotes: "Expressão mais comum do português brasileiro informal. Marca de identidade linguística brasileira. Totalmente inofensivo.", origin: "Contração de 'não é', marca registrada da língua portuguesa brasileira.", variations: ["né?", "né mano", "né véi"], popularityStatus: "ativo", region: "Brasil" },
  // 93. mano
  { term: "mano", meaning: "Irmão, amigo, cara — vocativo afetuoso entre amigos.", adultTranslation: "Irmão / Amigo / Cara / Irmão.", context: "Vocativo carinhoso usado entre amigos, especialmente do sexo masculino.", category: "saudacao", riskLevel: "green", safeExample: "E aí mano, tudo beleza?", contextNotes: "Um dos termos mais usados entre jovens brasileiros. Pode ser usado para qualquer amigo. Totalmente inofensivo.", origin: "Diminutivo de 'irmão', popularizado na cultura jovem brasileira.", variations: ["mermão", "irmão", "mano"], popularityStatus: "ativo", region: "Brasil" },
  // 94. bro
  { term: "bro", meaning: "Irmão, amigo, companheiro — do inglês brother.", adultTranslation: "Irmão / Amigo / Cara / Companheiro.", context: "Versão em inglês de mano, usada entre amigos.", category: "saudacao", riskLevel: "green", safeExample: "Bro, você acreditou nisso?", contextNotes: "Empréstimo do inglês muito usado no Brasil. Mostra influência da cultura global. Totalmente inofensivo.", origin: "Do inglês 'brother', popularizado por cultura americana e games.", variations: ["brother", "bruh"], popularityStatus: "ativo", region: "internacional" },
  // 95. mermão
  { term: "mermão", meaning: "Meu irmão, expressão muito usada entre amigos como vocativo afetuoso.", adultTranslation: "Meu irmão / Meu amigo / Meu parceiro.", context: "Versão mais afetuosa de mano, enfatiza a amizade.", category: "saudacao", riskLevel: "green", safeExample: "E aí mermão, bora jogar?", contextNotes: "Expressão carinhosa muito popular. Mostra proximidade entre amigos. Totalmente inofensivo.", origin: "Contração de 'meu irmão', popularizado na cultura jovem brasileira.", variations: ["mano", "irmão", "parceiro"], popularityStatus: "ativo", region: "Brasil" },
  // 96. família
  { term: "família", meaning: "Grupo familiar, ou grupo de amigos muito próximos como família.", adultTranslation: "Família / Grupo próximo / Pessoas queridas.", context: "Pode ser família biológica ou grupo de amigos que se tratam como família.", category: "valores", riskLevel: "green", safeExample: "Essa galera é minha segunda família.", contextNotes: "Conceito de família expandido para incluir amigos. Muito presente na cultura jovem. Totalmente positivo.", origin: "Do latim 'familia', conceito fundamental da sociedade brasileira.", variations: ["fam", "família de coração"], popularityStatus: "ativo", region: "Brasil" },
  // 97. eita
  { term: "eita", meaning: "Interjeição de surpresa, espanto ou admiração, marca da cultura brasileira.", adultTranslation: "Nossa! / Caramba! / Expressão de espanto.", context: "Interjeição usada para expressar surpresa, espanto ou emoção.", category: "expressão", riskLevel: "green", safeExample: "Eita, que golpe bonito!", contextNotes: "Uma das interjeições mais brasileiras. Inofensiva e culturalmente rica. Pode ser imitada de forma estereotipada.", origin: "Expressão popular brasileira de origem incerta, possivelmente de origem religiosa (Eita!).", variations: ["eita!, eita mãe", "e mephis"], popularityStatus: "ativo", region: "Brasil" },
  // 98. vixi
  { term: "vixi", meaning: "Interjeição de preocupação, susto ou alerta.", adultTranslation: "Ah não! / Cuidado! / Puxa! / Expressão de alerta.", context: "Interjeição usada quando algo ruim ou preocupante acontece.", category: "expressão", riskLevel: "green", safeExample: "Vixi, esqueci a mochila em casa!", contextNotes: "Expressão leve e humorística de preocupação. Muito comum e inofensiva. Pode indicar ansiedade leve.", origin: "Expressão popular brasileira, eufemismo de expressões mais fortes.", variations: ["vixi maria", "vixe"], popularityStatus: "ativo", region: "Brasil" },
  // 99. nossa
  { term: "nossa", meaning: "Interjeição de espanto, admiração ou surpresa.", adultTranslation: "Nossa! / Caramba! / Nossa Senhora!", context: "Interjeição muito usada para expressar qualquer emoção forte.", category: "expressão", riskLevel: "green", safeExample: "Nossa, que dia bonito!", contextNotes: "Abreviação de 'Nossa Senhora'. Interjeição universal brasileira. Inofensivo.", origin: "Abreviação de 'Nossa Senhora', expressão religiosa adaptada como interjeição.", variations: ["nossa senhora", "nossa!), nossinha"], popularityStatus: "ativo", region: "Brasil" },
  // 100. caramba
  { term: "caramba", meaning: "Interjeição de espanto ou ênfase, eufemismo para palavrões.", adultTranslation: "Caramba! / Nossa! / Expressão de espanto.", context: "Interjeição usada como eufemismo para expressões mais fortes.", category: "expressão", riskLevel: "green", safeExample: "Caramba, esqueci da prova!", contextNotes: "Eufemismo positivo que substitui palavrões. Expressão culturalmente aceitável em qualquer contexto. Totalmente inofensivo.", origin: "Eufemismo brasileiro de origem incerta, possivelmente relacionado ao mar.", variations: ["caramba!, caramba mesmo"], popularityStatus: "ativo", region: "Brasil" },
  // 101. ops
  { term: "ops", meaning: "Interjeição usada quando se comete um erro ou algo inesperado acontece.", adultTranslation: "Ops! / Opa! / Desculpe! / Foi sem querer.", context: "Usado quando se faz algo errado ou acidentalmente.", category: "expressão", riskLevel: "green", safeExample: "Ops, apaguei a mensagem errada.", contextNotes: "Interjeção leve e universal. Reconhece erro de forma simpática. Inofensivo.", origin: "Do inglês 'oops', universalizado na língua portuguesa.", variations: ["oops", "opa"], popularityStatus: "ativo", region: "internacional" },
  // 102. ué
  { term: "ué", meaning: "Interjeição de estranheza, confusão ou questionamento.", adultTranslation: "Como assim? / Por quê? / Estranho.", context: "Usado quando algo não faz sentido ou quando se está confuso.", category: "expressão", riskLevel: "green", safeExample: "ué, mas você não tinha dito que vinha?", contextNotes: "Interjeição muito brasileira que expressa confusão. Pode soar ríspida dependendo do tom. No geral, inofensiva.", origin: "Expressão popular brasileira de origem incerta.", variations: ["ué?", "ué mano"], popularityStatus: "ativo", region: "Brasil" },
  // 103. oba
  { term: "oba", meaning: "Interjeição de alegria, satisfação ou comemoração.", adultTranslation: "Oba! / Legal! / Que bom! / Yay!", context: "Usado para expressar alegria quando algo bom acontece.", category: "expressão", riskLevel: "green", safeExample: "Oba, não tem prova hoje!", contextNotes: "Interjeição muito positiva e infantil que jovens usam de forma irônica ou genuína. Inofensivo.", origin: "Expressão popular brasileira, possivelmente onomatopeica.", variations: ["oba!", "oba oba"], popularityStatus: "ativo", region: "Brasil" },
  // 104. bairro
  { term: "bairro", meaning: "Região onde se mora, comunidade local, referência de pertencimento.", adultTranslation: "Bairro / Vizinhança / Comunidade local.", context: "Área residencial onde a pessoa mora, referência de identidade local.", category: "cultura", riskLevel: "green", safeExample: "Vou jogar bola lá no bairro.", contextNotes: "Espaço de convivência fundamental na vida de adolescentes. Pode influenciar identidade e cultura. Totalmente positivo.", origin: "Do árabe 'barri', conceito urbanístico e cultural.", variations: ["meu bairro", "bairro bom"], popularityStatus: "ativo", region: "Brasil" },
  // 105. internet
  { term: "internet", meaning: "Rede global de computadores, principal fonte de informação e entretenimento.", adultTranslation: "Internet / Rede mundial / Web.", context: "Sistema global de comunicação digital que conecta o mundo.", category: "tecnologia", riskLevel: "green", safeExample: "A internet caiu, não consigo fazer a pesquisa.", contextNotes: "Essencial na vida dos jovens. Pode ser ferramenta incrível ou fonte de problemas. Orientar sobre uso seguro e consciente.", origin: "Rede global criada nos anos 1960, popularizada nos anos 1990.", variations: ["net", "web", "online"], popularityStatus: "ativo", region: "internacional" },
  // 106. online
  { term: "online", meaning: "Conectado à internet, disponível digitalmente.", adultTranslation: "Online / Conectado / Na rede / Disponível.", context: "Estado de estar conectado à internet ou disponível em plataformas digitais.", category: "tecnologia", riskLevel: "green", safeExample: "Tô online no WhatsApp, manda mensagem.", contextNotes: "Conceito básico da vida digital. Pode gerar pressão por estar sempre disponível. Orientar sobre limites.", origin: "Do inglês, conceito da era digital.", variations: ["on", "conectado"], popularityStatus: "ativo", region: "internacional" },
  // 107. propósito
  { term: "propósito", meaning: "Razão de ser, objetivo de vida, missão pessoal.", adultTranslation: "Propósito / Missão / Razão de viver / Objetivo de vida.", context: "Sentido ou direção que alguém dá à própria vida.", category: "valores", riskLevel: "green", safeExample: "Encontrei meu propósito na música.", contextNotes: "Conceito profundo muito discutido entre jovens. Pode gerar ansiedade em quem ainda não encontrou. Orientar que é normal não saber.", origin: "Conceito filosófico, popularizado por autoajuda e redes sociais.", variations: ["propósito de vida", "missão"], popularityStatus: "ativo", region: "internacional" },
  // 108. meta
  { term: "meta", meaning: "Objetivo, alvo, resultado que se quer alcançar.", adultTranslation: "Objetivo / Alvo / Meta / Resultado desejado.", context: "Objetivo específico que alguém quer alcançar em um prazo determinado.", category: "valores", riskLevel: "green", safeExample: "Minha meta é passar no ENEM.", contextNotes: "Conceito motivacional importante. Ajuda a organizar esforços. Pode gerar pressão se irrealista. Orientar sobre metas alcançáveis.", origin: "Do inglês e do latim, conceito de planejamento e gestão.", variations: ["objetivo", "goal", "meta do ano"], popularityStatus: "ativo", region: "internacional" },
  // 109. criatividade
  { term: "criatividade", meaning: "Capacidade de criar, inventar, pensar de forma original e inovadora.", adultTranslation: "Criatividade / Inventividade / Pensamento original.", context: "Habilidade de criar coisas novas e originais, resolver problemas de forma diferente.", category: "valores", riskLevel: "green", safeExample: "A criatividade dela nos projetos é incrível.", contextNotes: "Qualidade fundamental para o desenvolvimento juvenil. Pode ser aplicada em qualquer área. Totalmente positiva.", origin: "Do latim 'creatio', conceito valorizado em educação e cultura.", variations: ["criativo", "ser criativo"], popularityStatus: "ativo", region: "internacional" },
  // 110. inovação
  { term: "inovação", meaning: "Criação de algo novo e diferente que traz melhoria ou solução.", adultTranslation: "Inovação / Novidade / Criação inovadora / Mudança positiva.", context: "Processo de criar algo novo que melhora o que já existe.", category: "valores", riskLevel: "green", safeExample: "A inovação na medicina salvou muitas vidas.", contextNotes: "Conceito positivo que incentiva progresso. Muito valorizado em tecnologia e educação. Totalmente construtivo.", origin: "Do latim 'innovatio', conceito central na cultura tecnológica.", variations: ["inovar", "inovador"], popularityStatus: "ativo", region: "internacional" },
  // 111. tecnologia
  { term: "tecnologia", meaning: "Conjunto de ferramentas e técnicas criadas pelo ser humano para resolver problemas.", adultTranslation: "Tecnologia / Tech / Ciência aplicada / Ferramentas digitais.", context: "Ferramentas, apps, dispositivos e sistemas que fazem parte do dia a dia.", category: "tecnologia", riskLevel: "green", safeExample: "A tecnologia mudou a forma como a gente estuda.", contextNotes: "Presente em todas as áreas da vida juvenil. Pode ser positiva ou gerar dependência. Orientar sobre uso equilibrado.", origin: "Do grego 'techne' (arte, técnica), conceito fundamental da modernidade.", variations: ["tech", "tecnológica"], popularityStatus: "ativo", region: "internacional" },
  // 112. música
  { term: "música", meaning: "Arte dos sons, forma de expressão cultural fundamental na vida dos jovens.", adultTranslation: "Música / Arte sonora / Expressão musical.", context: "Forma de arte e expressão presente no dia a dia de todos os adolescentes.", category: "cultura", riskLevel: "green", safeExample: "A música é minha terapia.", contextNotes: "Fundamental na identidade juvenil. Pode influenciar humor, comportamento e identidade. Totalmente positiva.", origin: "Arte milenar, central em todas as culturas humanas.", variations: ["som", "playlist", "música boa"], popularityStatus: "ativo", region: "internacional" },
  // 113. sociedade
  { term: "sociedade", meaning: "Conjunto de pessoas que vivem em comunidade, organizadas socialmente.", adultTranslation: "Sociedade / Comunidade / Mundo social.", context: "O mundo social em que vivemos, com suas regras e dinâmicas.", category: "valores", riskLevel: "green", safeExample: "A sociedade precisa ser mais justa.", contextNotes: "Conceito que jovens começam a questionar na adolescência. Desenvolve pensamento crítico. Totalmente positivo quando discutido com profundidade.", origin: "Do latim 'societas', conceito sociológico fundamental.", variations: ["social", "questão social"], popularityStatus: "ativo", region: "internacional" },
  // 114. educação
  { term: "educação", meaning: "Processo de ensino e aprendizagem, tanto formal quanto informal.", adultTranslation: "Educação / Ensino / Aprendizado / Formação.", context: "Processo de adquirir conhecimento e valores, na escola ou na vida.", category: "educacao", riskLevel: "green", safeExample: "A educação transforma vidas.", contextNotes: "Valor fundamental que jovens reconhecem como importante. Pode ser formal ou informal. Totalmente positivo.", origin: "Do latim 'educatio', conceito central da civilização.", variations: ["educar", "educado", "boa educação"], popularityStatus: "ativo", region: "internacional" },
  // 115. esporte
  { term: "esporte", meaning: "Atividade física competitiva ou recreativa, importante para saúde e socialização.", adultTranslation: "Esporte / Atividade física / Prática esportiva.", context: "Qualquer prática esportiva, do futebol ao skate, fundamental na vida juvenil.", category: "esporte", riskLevel: "green", safeExample: "O esporte me ajudou a fazer amigos e ficar saudável.", contextNotes: "Fundamental para saúde física, mental e socialização. Pode gerar pressão competitiva. Orientar sobre esporte como prazer.", origin: "Atividade humana milenar, central na cultura juvenil brasileira.", variations: ["esportivo", "praticar esporte"], popularityStatus: "ativo", region: "internacional" },
  // 116. lazer
  { term: "lazer", meaning: "Tempo livre dedicado a atividades prazerosas e descanso.", adultTranslation: "Lazer / Tempo livre / Diversão / Descanso.", context: "Período de tempo dedicado a atividades que dão prazer e relaxamento.", category: "lifestyle", riskLevel: "green", safeExample: "Final de semana é dia de lazer.", contextNotes: "Fundamental para saúde mental e qualidade de vida. Muitos adolescentes têm pouco lazer. Orientar sobre equilíbrio.", origin: "Do inglês 'leisure', conceito de qualidade de vida.", variations: ["lazer e diversão", "tempo livre"], popularityStatus: "ativo", region: "internacional" },
  // 117. felicidade
  { term: "felicidade", meaning: "Estado de satisfação e alegria, bem-estar emocional profundo.", adultTranslation: "Felicidade / Alegria / Bem-estar / Satisfação.", context: "Sentimento de contentamento e realização pessoal.", category: "valores", riskLevel: "green", safeExample: "A felicidade tá nas coisas simples da vida.", contextNotes: "Valor universal que todos buscam. Pode ser efêmera ou duradoura. Orientar que felicidade não é constante e está ok.", origin: "Conceito filosófico e psicológico universal.", variations: ["feliz", "ser feliz"], popularityStatus: "ativo", region: "internacional" },
  // 118. paz
  { term: "paz", meaning: "Estado de harmonia, tranquilidade, ausência de conflito.", adultTranslation: "Paz / Harmonia / Tranquilidade / Ausência de conflito.", context: "Estado de calma e harmonia pessoal ou coletiva.", category: "valores", riskLevel: "green", safeExample: "Quero paz na minha vida.", contextNotes: "Valor fundamental para saúde mental e relações. Pode ser pessoal ou global. Totalmente positivo.", origin: "Conceito universal, valor em todas as culturas e religiões.", variations: ["paz interior", "paz mundial"], popularityStatus: "ativo", region: "internacional" },
  // 119. amor
  { term: "amor", meaning: "Sentimento profundo de afeição, carinho e conexão com outra pessoa.", adultTranslation: "Amor / Afeto / Carinho / Sentimento profundo.", context: "Sentimento mais profundo de conexão emocional entre pessoas.", category: "valores", riskLevel: "green", safeExample: "O amor é o que move o mundo.", contextNotes: "Sentimento universal e fundamental. Muito discutido entre adolescentes. Pode referir-se a romance, família ou amizade.", origin: "Do latim 'amor', conceito universal humano.", variations: ["amor próprio", "amor de verdade"], popularityStatus: "ativo", region: "internacional" },
  // 120. amizade
  { term: "amizade", meaning: "Relação de afeto e confiança entre amigos.", adultTranslation: "Amizade / Relação de amizade / Vínculo afetivo.", context: "Laço de afeto mútuo entre pessoas que se gostam e se apoiam.", category: "valores", riskLevel: "green", safeExample: "A amizade de verdade é rara, valoriza quem está ai.", contextNotes: "Fundamental na adolescência. Amigos são principal rede de apoio. Orientar sobre amizades saudáveis.", origin: "Conceito universal, central na vida social adolescente.", variations: ["amigo", "friendship", "best friend"], popularityStatus: "ativo", region: "internacional" },
  // 121. lealdade
  { term: "lealdade", meaning: "Qualidade de ser fiel, honesto e verdadeiro com amigos e princípios.", adultTranslation: "Lealdade / Fidelidade / Honestidade / Constância.", context: "Qualidade de manter-se fiel a amigos, princípios e compromissos.", category: "valores", riskLevel: "green", safeExample: "A lealdade é a base de qualquer amizade.", contextNotes: "Valor muito importante entre jovens. Pode ser testada em situações difíceis. Totalmente positivo.", origin: "Conceito de cavalaria medieval, adaptado para relações modernas.", variations: ["leal", "ser leal"], popularityStatus: "ativo", region: "internacional" },
  // 122. respeito
  { term: "respeito", meaning: "Consideração pelos direitos, sentimentos e diferenças dos outros.", adultTranslation: "Respeito / Consideração / Reconhecimento do outro.", context: "Valor fundamental de tratar os outros com dignidade e consideração.", category: "valores", riskLevel: "green", safeExample: "Respeito é a base da convivência.", contextNotes: "Valor essencial para sociedade justa. Precisa ser praticado diariamente. Orientar sobre respeito em todas as relações.", origin: "Conceito universal, fundamental para ética e moral.", variations: ["respeitar", "ser respeitado", "respeito mútuo"], popularityStatus: "ativo", region: "internacional" },
  // 123. gratidão
  { term: "gratidão", meaning: "Sentimento de reconhecimento e agradecimento por algo bom recebido.", adultTranslation: "Gratidão / Agradecimento / Reconhecimento.", context: "Sentimento de agradecer pelas coisas boas da vida.", category: "valores", riskLevel: "green", safeExample: "Praticar gratidão melhora a saúde mental.", contextNotes: "Prática muito positiva recomendada por psicólogos. Pode melhorar humor e perspectiva de vida. Totalmente construtivo.", origin: "Conceito filosófico e psicológico, popularizado por autoajuda.", variations: ["grato", "ser grato", "gratidão diária"], popularityStatus: "ativo", region: "internacional" },
  // 124. verdade
  { term: "verdade", meaning: "Aquilo que é real, correto e fiel à realidade dos fatos.", adultTranslation: "Verdade / Realidade / Fato / Honestidade.", context: "Conceito de honestidade e fidelidade aos fatos.", category: "valores", riskLevel: "green", safeExample: "Sempre buscar a verdade é importante.", contextNotes: "Valor fundamental para relações saudáveis e sociedade justa. Pode ser subjetiva em alguns contextos.", origin: "Conceito filosófico fundamental, debatido desde a antiguidade.", variations: ["verdadeiro", "falar a verdade"], popularityStatus: "ativo", region: "internacional" },
  // 125. liberdade
  { term: "liberdade", meaning: "Direito de fazer escolhas, expressar-se e agir sem opressão.", adultTranslation: "Liberdade / Autonomia / Independência / Livre-arbítrio.", context: "Capacidade de fazer próprias escolhas e expressar-se livremente.", category: "valores", riskLevel: "green", safeExample: "A liberdade de expressão é um direito de todos.", contextNotes: "Valor fundamental especialmente na adolescência, quando se busca independência. Totalmente positivo quando exercida com responsabilidade.", origin: "Conceito político e filosófico, central em democracias.", variations: ["livre", "ser livre", "liberdade de expressão"], popularityStatus: "ativo", region: "internacional" },
  // 126. igualdade
  { term: "igualdade", meaning: "Princípio de que todas as pessoas devem ter os mesmos direitos e oportunidades.", adultTranslation: "Igualdade / Paridade / Mesmos direitos.", context: "Princípio de que todos merecem tratamento justo, independente de diferenças.", category: "valores", riskLevel: "green", safeExample: "Lutar por igualdade é dever de todos.", contextNotes: "Valor fundamental para sociedade justa. Muito discutido nas redes sociais. Pode gerar debates produtivos.", origin: "Conceito político e social, central em direitos humanos.", variations: ["igualdade de direitos", "igualdade social"], popularityStatus: "ativo", region: "internacional" },
  // 127. justiça
  { term: "justiça", meaning: "Princípio moral que garante que cada pessoa receba o que é justo e correto.", adultTranslation: "Justiça / Equidade / Imparcialidade / Direito.", context: "Valor que busca garantir tratamento justo para todas as pessoas.", category: "valores", riskLevel: "green", safeExample: "Queremos justiça para todos.", contextNotes: "Conceito complexo mas essencial. Jovens são muito sensíveis a injustiças. Orientar sobre formas de agir pela justiça.", origin: "Conceito filosófico e jurídico, fundamental para sociedade.", variations: ["justo", "ser justo", "justiça social"], popularityStatus: "ativo", region: "internacional" },
  // 128. bondade
  { term: "bondade", meaning: "Qualidade de ser bom, gentil e compassivo com os outros.", adultTranslation: "Bondade / Gentileza / Compaixão / Benevolência.", context: "Atitude de ser gentil e bom com as pessoas ao redor.", category: "valores", riskLevel: "green", safeExample: "A bondade custa nada e vale tudo.", contextNotes: "Valor simples mas poderoso. Pequenos atos de bondade podem transformar o dia de alguém. Totalmente positivo.", origin: "Conceito moral universal, valorizado em todas as culturas.", variations: ["bom", "gentil", "bondoso"], popularityStatus: "ativo", region: "internacional" },
  // 129. compaixão
  { term: "compaixão", meaning: "Sentimento de empatia misturado com desejo de ajudar quem sofre.", adultTranslation: "Compaixão / Piedade / Misericórdia / Desejo de ajudar.", context: "Sentimento que leva a se importar com o sofrimento alheio e querer ajudar.", category: "valores", riskLevel: "green", safeExample: "A compaixão é o que nos torna humanos.", contextNotes: "Valor profundo que conecta pessoas. Diferente de pena, compaixão move à ação. Totalmente positivo.", origin: "Conceito filosófico e religioso universal.", variations: ["compassivo", "ter compaixão"], popularityStatus: "ativo", region: "internacional" },
  // 130. periferia
  { term: "periferia", meaning: "Região periférica das cidades, geralmente com menos infraestrutura e recursos.", adultTranslation: "Periferia / Subúrbio / Região menos privilegiada.", context: "Bairros afastados dos centros urbanos, geralmente com menos investimento público.", category: "cultura", riskLevel: "green", safeExample: "A cultura da periferia é rica e resistente.", contextNotes: "Realidade de muitos jovens brasileiros. Produz cultura incrível (funk, rap, arte). Pode envolver vulnerabilidade social. Orientar sobre valorização cultural e acesso a direitos.", origin: "Conceito urbanístico e social brasileiro.", variations: ["periférica", "subúrbio", "quebrada"], popularityStatus: "ativo", region: "Brasil" },
  // 131. cultura negra
  { term: "cultura negra", meaning: "Conjunto de manifestações culturais, tradições e contribuições da população negra.", adultTranslation: "Cultura afro-brasileira / Herança africana / Tradições negras.", context: "Expressões culturais de origem africana: música, dança, culinária, religião.", category: "cultura", riskLevel: "green", safeExample: "A cultura negra é fundamental pra identidade brasileira.", contextNotes: "Riquíssima e essencial para a identidade nacional. Deve ser valorizada e respeitada. Fundamental na educação.", origin: "Herança africana no Brasil, resistência cultural através dos séculos.", variations: ["afro-brasileiro", "cultura afro"], popularityStatus: "ativo", region: "Brasil" },
  // 132. resiliência
  { term: "resiliência urbana", meaning: "Capacidade de superar desafios da vida urbana, especialmente em comunidades periféricas.", adultTranslation: "Resistência / Força urbana / Capacidade de superar.", context: "Habilidade de enfrentar e superar dificuldades da vida na cidade, especialmente na periferia.", category: "cultura", riskLevel: "green", safeExample: "A resiliência do povo da quebrada é inspiradora.", contextNotes: "Qualidade muito presente na cultura periférica. Muito admirada e celebrada. Orientar sobre que ninguém deveria precisar ser tão resiliente.", origin: "Conceito de psicologia adaptado para contexto urbano brasileiro.", variations: ["resistência", "guerreiro"], popularityStatus: "ativo", region: "Brasil" },
  // 133. forró
  { term: "forró", meaning: "Gênero musical nordestino, ritmo animado para dançar em pares.", adultTranslation: "Forró / Música nordestina / Ritmo de dança a dois.", context: "Música tradicional do Nordeste, celebrada em festas juninas e o ano todo.", category: "cultura", riskLevel: "green", safeExample: "No forró a gente dança bem juntinho!", contextNotes: "Patrimônio cultural brasileiro. Pode envolver proximidade física na dança que deve ser consensual. Totalmente cultural e positivo.", origin: "Nordeste brasileiro, do inglês 'for all' ou do termo 'forrobodó'.", variations: ["forró universitário", "forró pé de serra"], popularityStatus: "ativo", region: "Nordeste, Brasil" },
  // 134. pagode
  { term: "pagode", meaning: "Gênero musical brasileiro derivado do samba, com ritmos animados e românticos.", adultTranslation: "Pagode / Samba / Música brasileira animada.", context: "Estilo musical popular brasileiro, muito tocado em festas e rodas de amigos.", category: "cultura", riskLevel: "green", safeExample: "A festinha de pagode ontem foi demais.", contextNotes: "Gênero genuinamente brasileiro que traz alegria e romance. Pode ter letras problemáticas. Contexto importa. Totalmente cultural.", origin: "Rio de Janeiro, derivado do samba, popularizado por grupos como Fundo de Quintal.", variations: ["pagodinho", "roda de pagode"], popularityStatus: "ativo", region: "RJ, SP" },
  // 135. funk
  { term: "funk", meaning: "Gênero musical brasileiro que nasceu nas favelas cariocas, ritmo mais ouvido no país.", adultTranslation: "Funk carioca / Funk brasileiro / Música eletrônica brasileira.", context: "Estilo musical que domina as paradas brasileiras, expressão cultural da periferia.", category: "cultura", riskLevel: "yellow", safeExample: "O funk é a maior expressão cultural da juventude brasileira.", contextNotes: "Patrimônio cultural que merece respeito. Pode ter letras com conteúdo adulto. Diferenciar funk como gênero musical de letras específicas. Muito valorizado pelos jovens.", origin: "Favelas cariocas, anos 1980, influência do funk americano e Miami bass.", variations: ["funk carioca", "funk paulista", "funk ostentação"], popularityStatus: "ativo", region: "Brasil" },
  // 136. samba
  { term: "samba", meaning: "Gênero musical brasileiro patrimônio cultural, símbolo da identidade nacional.", adultTranslation: "Samba / Música brasileira / Patrimônio cultural.", context: "Gênero musical icônico brasileiro, presente no carnaval e na cultura nacional.", category: "cultura", riskLevel: "green", safeExample: "O samba é a alma do Brasil.", contextNotes: "Patrimônio cultural imaterial da humanidade (UNESCO). Totalmente positivo e culturalmente enriquecedor.", origin: "Herança africana no Rio de Janeiro, século XX, patrimônio cultural brasileiro.", variations: ["samba de enredo", "samba de roda", "pagode samba"], popularityStatus: "ativo", region: "Brasil" },
  // 137. carnaval
  { term: "carnaval", meaning: "Festa popular brasileira, maior celebração cultural do país.", adultTranslation: "Carnaval / Festa popular / Celebração cultural.", context: "Maior festa do Brasil, com desfiles, blocos, alegria e música.", category: "cultura", riskLevel: "green", safeExample: "O carnaval desse ano foi incrível!", contextNotes: "Patrimônio cultural brasileiro. Pode envolver excessos. Orientar sobre segurança e respeito. Celebração cultural que merece valorização.", origin: "Tradição brasileira de origem europeia e africana, símbolo cultural nacional.", variations: ["carnaval de rua"], popularityStatus: "ativo", region: "Brasil" },
  // 138. futebol
  { term: "futebol", meaning: "Esporte mais popular do Brasil, paixão nacional.", adultTranslation: "Futebol / Soccer / Esporte nacional.", context: "Esporte que une o Brasil, paixão de todas as idades e classes sociais.", category: "esporte", riskLevel: "green", safeExample: "O jogo do Brasil hoje é de morrer!", contextNotes: "Identidade cultural brasileira. Pode gerar rivalidades saudáveis. Orientar sobre fair play e respeito nas discussões esportivas.", origin: "Esporte inglês adaptado como paixão nacional brasileira desde o século XX.", variations: ["fute", "pelada", "bolão"], popularityStatus: "ativo", region: "Brasil" },
  // 139. pelada
  { term: "pelada", meaning: "Jogo de futebol informal, sem arbitro, entre amigos.", adultTranslation: "Futebol informal / Racha / Jogo de amigos.", context: "Partida de futebol informal entre amigos, geralmente em campo improvisado.", category: "esporte", riskLevel: "green", safeExample: "Vamos fazer uma pelada no campinho?", contextNotes: "Tradição brasileira que promove socialização e saúde. Totalmente positivo e saudável.", origin: "Tradição brasileira de futebol informal em ruas e campinhos.", variations: ["racha", "futebol de areia", "peladão"], popularityStatus: "ativo", region: "Brasil" },
  // 140. quadra
  { term: "quadra", meaning: "Campo de esporte, geralmente de futebol, na escola ou no bairro.", adultTranslation: "Quadra esportiva / Campo / Área de jogo.", context: "Espaço para prática esportiva, geralmente na escola ou comunidade.", category: "esporte", riskLevel: "green", safeExample: "Encontra todo mundo na quadra do colégio.", contextNotes: "Espaço de convivência fundamental na vida escolar. Centro de socialização e esporte. Totalmente positivo.", origin: "Do latim 'quadra', espaço esportivo comum em escolas brasileiras.", variations: ["quadra de esporte", "quadra poliesportiva"], popularityStatus: "ativo", region: "Brasil" },
  // 141. gol
  { term: "gol", meaning: "Gol em jogo de futebol, momento de alegria e celebração.", adultTranslation: "Gol / Ponto / Marcação / Golaço.", context: "Quando a bola entra no gol no futebol, momento de grande emoção.", category: "esporte", riskLevel: "green", safeExample: "Que golaço! Melhor gol que já vi!", contextNotes: "Momento mais emocionante do futebol. Pode gerar celebrações intensas. Totalmente cultural e positivo.", origin: "Do inglês 'goal', central no futebol brasileiro.", variations: ["golaço", "gol contra", "gol de placa"], popularityStatus: "ativo", region: "Brasil" },
  // 142. craque
  { term: "craque", meaning: "Jogador excepcional de futebol, pessoa muito boa em alguma área.", adultTranslation: "Jogador excepcional / Expert / Melhor na área.", context: "Atleta de futebol de altíssimo nível, ou alguém muito bom em algo.", category: "elogio", riskLevel: "green", safeExample: "O Neymar é craque, joga muito.", contextNotes: "Elogio que reconhece excelência. Pode ser aplicado a qualquer área além do esporte. Totalmente positivo.", origin: "Futebol brasileiro, termo para jogador excepcional.", variations: ["crack", "craquinho", "craque do time"], popularityStatus: "ativo", region: "Brasil" },
  // 143. seleção
  { term: "seleção", meaning: "Seleção brasileira de futebol, time nacional que representa o país.", adultTranslation: "Seleção brasileira / Time nacional / Brasil.", context: "Time nacional de futebol que representa o Brasil em competições internacionais.", category: "esporte", riskLevel: "green", safeExample: "A seleção brasileira jogou bem na Copa!", contextNotes: "Símbolo de identidade nacional. Pode gerar emoções fortes. Orientar sobre patriotismo saudável.", origin: "Seleções esportivas nacionais, a de futebol é a mais seguida.", variations: ["seleção brasileira", "Canarinho", "amarelinha"], popularityStatus: "ativo", region: "Brasil" },
  // 144. copa
  { term: "copa", meaning: "Copa do Mundo de Futebol, maior evento esportivo do planeta.", adultTranslation: "Copa do Mundo / Mundial / Torneio de futebol.", context: "Maior evento de futebol, acontece a cada 4 anos e mobiliza o mundo.", category: "esporte", riskLevel: "green", safeExample: "Na Copa o Brasil inteiro para pra torcer.", contextNotes: "Evento que une o país. Pode gerar emoções coletivas intensas. Momento cultural importante.", origin: "FIFA World Cup, evento criado em 1930, paixão nacional brasileira.", variations: ["Copa do Mundo", "Mundial", "Copa"], popularityStatus: "ativo", region: "internacional" },
  // 145. bagunça
  { term: "bagunça", meaning: "Desordem, confusão, sujeira; ou brincadeira barulhenta entre amigos.", adultTranslation: "Bagunça / Desordem / Confusão / Sujeira.", context: "Quando algo está desorganizado ou quando há brincadeira barulhenta.", category: "humor", riskLevel: "green", safeExample: "O quarto tá uma bagunça, preciso arrumar.", contextNotes: "Pode ser brincadeira saudável entre amigos ou desordem física. Contexto define. Normal na adolescência.", origin: "Expressão popular brasileira, possivelmente origem no tupi.", variations: ["bagunceiro", "fazer bagunça"], popularityStatus: "ativo", region: "Brasil" },
  // 146. aventura
  { term: "aventura", meaning: "Experiência emocionante e diferente, algo novo e empolgante.", adultTranslation: "Aventura / Experiência emocionante / Novidade.", context: "Atividade ou experiência que traz emoção, novidade e adrenalina.", category: "lifestyle", riskLevel: "green", safeExample: "A viagem foi uma aventura incrível!", contextNotes: "Conceito positivo que incentiva experimentar coisas novas. Fundamental para desenvolvimento juvenil. Totalmente construtivo.", origin: "Do latim 'adventura', conceito que remete a explorar o desconhecido.", variations: ["aventureiro", "aventurar"], popularityStatus: "ativo", region: "internacional" },
  // 147. natureza
  { term: "natureza", meaning: "Conjunto de tudo que existe naturalmente no planeta: plantas, animais, paisagens.", adultTranslation: "Natureza / Meio ambiente / Mundo natural.", context: "O mundo natural ao redor: florestas, rios, montanhas, animais.", category: "valores", riskLevel: "green", safeExample: "Passar o dia na natureza faz bem pra saúde mental.", contextNotes: "Conexão com a natureza é essencial para bem-estar. Muitos jovens estão desconectados. Orientar sobre preservação ambiental.", origin: "Do latim 'natura', conceito fundamental de ecologia e sustentabilidade.", variations: ["meio ambiente", "natureza selvagem"], popularityStatus: "ativo", region: "internacional" },
  // 148. viagem
  { term: "viagem", meaning: "Jornada a um lugar diferente, ou alucinação/experiência surreal (gíria).", adultTranslation: "Viagem / Jornada / Passeio / Alucinação (gíria).", context: "Pode ser uma viagem literal ou uma experiência surreal e estranha.", category: "lifestyle", riskLevel: "green", safeExample: "Esse filme é uma viagem, não entendi nada.", contextNotes: "No sentido literal, é muito positivo. No sentido figurado, significa algo estranho ou surreal. Inofensivo em ambos os sentidos.", origin: "Do latim 'viaticum', conceito de deslocamento e experiência.", variations: ["viajar", "viagem mesmo", "viajem"], popularityStatus: "ativo", region: "Brasil" },
  // 149. talento
  { term: "talento", meaning: "Habilidade natural, dom, aptidão especial para algo.", adultTranslation: "Talento / Dom / Habilidade natural / Aptidão.", context: "Capacidade natural ou desenvolvida que alguém tem em uma área específica.", category: "elogio", riskLevel: "green", safeExample: "Ela tem talento pra dançar, é impressionante.", contextNotes: "Elogio que reconhece habilidades. Pode ser natural ou desenvolvido com prática. Totalmente positivo.", origin: "Do latim 'talentum', conceito de habilidade e dom natural.", variations: ["talentoso", "cheio de talento", "dom"], popularityStatus: "ativo", region: "internacional" },
  // 150. superação
  { term: "superação", meaning: "Ato de superar dificuldades, limites ou desafios, crescer com adversidades.", adultTranslation: "Superação / Crescimento pessoal / Vencer obstáculos.", context: "Processo de superar problemas e sair mais forte deles.", category: "valores", riskLevel: "green", safeExample: "A superação dela após a lesão é inspiradora.", contextNotes: "Conceito muito positivo que reconhece crescimento pessoal. Inspirador quando genuíno. Importante não romantizar sofrimento.", origin: "Do latim 'superatio', conceito de desenvolvimento pessoal e resiliência.", variations: ["superar", "superação pessoal"], popularityStatus: "ativo", region: "internacional" },
];
