import type { SlangTerm } from "./slang-data";

export const REGIONAL_SLANG_DATA: SlangTerm[] = [
  {
    term: "tri massa",
    meaning: "Muito legal, ótimo, excelente.",
    adultTranslation: "Muito bom / Excelente.",
    context: "Expressão de elogio bastante comum no Sul do Brasil.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Esse show foi tri!",
    contextNotes: "Uso positivo e inofensivo, geralmente no Rio Grande do Sul.",
    origin: "Uso popular da região Sul, especialmente no RS.",
    variations: ["tri legal", "tri bom", "tri"],
    popularityStatus: "regional",
    region: "Sul (RS)",
  },
  {
    term: "bah guri",
    meaning: "Interjeição de surpresa ou intensidade.",
    adultTranslation: "Nossa! / Caramba!",
    context: "Muito usada no Sul em conversa casual.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Bah guri, que frio hoje!",
    contextNotes: "Tom informal e amistoso.",
    origin: "Fala popular gaúcha.",
    variations: ["bah", "guri", "guria"],
    popularityStatus: "regional",
    region: "Sul",
  },
  {
    term: "oxi mainha",
    meaning: "Interjeição de surpresa, espanto ou dúvida.",
    adultTranslation: "Ué / Nossa / Como assim?",
    context: "Interjeição típica em contextos informais no Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Oxi mainha, já acabou a aula?",
    contextNotes: "Expressão tradicional e sem conotação ofensiva.",
    origin: "Expressão histórica da cultura nordestina.",
    variations: ["oxente", "o xente"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "visse",
    meaning: "Partícula para reforçar ou pedir confirmação.",
    adultTranslation: "Entendeu? / Viu? / Certo?",
    context: "Usado no fim da frase em conversas informais no Nordeste.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Chega cedo amanhã, visse?",
    contextNotes: "Uso coloquial regional, geralmente amigável.",
    origin: "Variação oral de 'viste/viu' na fala regional.",
    variations: ["vixe", "viu"],
    popularityStatus: "regional",
    region: "Nordeste",
  },
  {
    term: "papo reto",
    meaning: "Falar a verdade de forma direta.",
    adultTranslation: "Sem enrolação / Sinceridade.",
    context: "Muito presente em funk e periferias do Sudeste.",
    category: "funk",
    riskLevel: "green",
    safeExample: "Papo reto, esse som tá brabo.",
    contextNotes: "Pode aparecer em música e redes sociais.",
    origin: "Cultura urbana RJ/SP.",
    variations: ["reta", "na real"],
    popularityStatus: "trending",
    region: "Rio/São Paulo",
  },
  {
    term: "amassou",
    meaning: "Foi muito bem em algo.",
    adultTranslation: "Arrasou / Mandou muito.",
    context: "Linguagem de adolescentes em escola, jogos e TikTok.",
    category: "internet",
    riskLevel: "green",
    safeExample: "Ele amassou na apresentação.",
    contextNotes: "Uso positivo e comum em vídeo curto.",
    origin: "Internet/TikTok.",
    variations: ["amassando", "amasso"],
    popularityStatus: "trending",
    region: "Brasil",
  },
  {
    term: "pai tá on",
    meaning: "Expressa animação e confiança.",
    adultTranslation: "Estou no clima / Estou pronto.",
    context: "Gíria de memes e música, muito usada em redes sociais.",
    category: "internet",
    riskLevel: "green",
    safeExample: "Sextou, pai tá on!",
    contextNotes: "Tom brincalhão, bastante popular.",
    origin: "Memes e funk nacional.",
    variations: ["tá on", "on demais"],
    popularityStatus: "trending",
    region: "Brasil",
  },
  {
    term: "pequiado",
    meaning: "Pessoa com forte identidade do Centro-Oeste.",
    adultTranslation: "Bem regional / Raiz.",
    context: "Uso descontraído em Goiás e entorno.",
    category: "regional",
    riskLevel: "green",
    safeExample: "Ele é pequiado, conhece tudo de Goiânia.",
    contextNotes: "Referência cultural ao pequi.",
    origin: "Centro-Oeste.",
    variations: ["raiz do pequi"],
    popularityStatus: "regional",
    region: "Centro-Oeste",
  },
];
