import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_19: SlangTerm[] = [
  {
    term: 'amassou',
    meaning: 'Mandou muito bem, arrasou ou venceu com folga.',
    adultTranslation: 'Fez muito bem / Teve ótimo desempenho.',
    context: 'Aparece em comentários de vídeos, apresentações, jogos e provas quando alguém impressiona.',
    category: 'elogio',
    riskLevel: 'green',
    safeExample: 'Ela apresentou o trabalho e amassou.',
    contextNotes: 'Normalmente é elogio e sinal de aprovação. Só vira provocação se for usado para comparar ou humilhar outra pessoa.',
    origin: 'Uso popular em redes sociais e cultura gamer, associado à ideia de dominar uma situação.',
    variations: ['amassar', 'amassou demais', 'amassou muito'],
    popularityStatus: 'trending',
    region: 'Brasil',
  },
  {
    term: 'de milhões',
    meaning: 'Algo excelente, valioso, bonito ou digno de muita aprovação.',
    adultTranslation: 'Muito bom / Excelente / De alto valor.',
    context: 'Usado para elogiar roupa, atitude, resposta, comida, foto ou conquista.',
    category: 'elogio',
    riskLevel: 'green',
    safeExample: 'Esse look ficou de milhões.',
    contextNotes: 'Expressão positiva e inofensiva na maioria dos casos.',
    origin: 'Popularizada em memes e comentários de redes sociais no Brasil.',
    variations: ['milhões', 'coisa de milhões', 'milhões demais'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'fofoca premium',
    meaning: 'Informação curiosa, detalhada ou muito interessante sobre alguém ou alguma situação.',
    adultTranslation: 'Uma fofoca muito boa / Informação cheia de detalhes.',
    context: 'Usado quando alguém promete contar uma história com detalhes ou bastidores.',
    category: 'humor',
    riskLevel: 'yellow',
    safeExample: 'Depois eu te conto a fofoca premium da sala.',
    contextNotes: 'Pode ser só brincadeira, mas vale observar se envolve exposição, boato ou constrangimento de terceiros.',
    origin: 'Mistura de linguagem de assinatura premium com cultura de fofoca em redes sociais.',
    variations: ['fofoca de milhões', 'fofoca boa', 'chá premium'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'plot twist',
    meaning: 'Virada inesperada em uma história ou situação.',
    adultTranslation: 'Reviravolta / Acontecimento inesperado.',
    context: 'Usado quando algo muda de forma surpreendente, como em filmes, séries ou situações da escola.',
    category: 'meme',
    riskLevel: 'green',
    safeExample: 'Plot twist: a professora adiou a prova.',
    contextNotes: 'Termo comum e geralmente neutro, importado do vocabulário de entretenimento.',
    origin: 'Expressão em inglês do cinema e da literatura, adotada por comunidades online.',
    variations: ['plot', 'plotão', 'virada de roteiro'],
    popularityStatus: 'internacional',
    region: 'Global',
  },
  {
    term: 'divou',
    meaning: 'Arrasou, brilhou ou chamou atenção de forma positiva.',
    adultTranslation: 'Se destacou / Ficou muito bem.',
    context: 'Muito usado para elogiar visual, apresentação, dança ou atitude confiante.',
    category: 'elogio',
    riskLevel: 'green',
    safeExample: 'Ela divou na festa junina.',
    contextNotes: 'Elogio informal e positivo, sem sinal de alerta por si só.',
    origin: 'Derivado de “diva”, popular em cultura pop e redes sociais.',
    variations: ['divar', 'divando', 'divou muito'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'lapada seca',
    meaning: 'Resposta ou acontecimento muito forte, direto ou impactante.',
    adultTranslation: 'Resposta contundente / Golpe verbal forte.',
    context: 'Pode aparecer em discussões, memes, esportes ou comentários sobre uma resposta atravessada.',
    category: 'provocacao',
    riskLevel: 'yellow',
    safeExample: 'A resposta dele foi uma lapada seca.',
    contextNotes: 'Geralmente é humor, mas pode indicar provocação ou conflito se estiver direcionada a alguém.',
    origin: 'Expressão popular nordestina ampliada por memes e vídeos curtos.',
    variations: ['lapada', 'lapada grande', 'lapada forte'],
    popularityStatus: 'regional',
    region: 'Nordeste / Brasil',
  },
  {
    term: 'ficou pequeno',
    meaning: 'Algo não deu conta, foi superado ou pareceu insuficiente diante da situação.',
    adultTranslation: 'Foi superado / Não foi suficiente.',
    context: 'Usado em brincadeiras quando alguém manda muito bem ou quando um lugar/evento não comporta a empolgação.',
    category: 'zoeira',
    riskLevel: 'yellow',
    safeExample: 'Depois desse golaço, o campo ficou pequeno.',
    contextNotes: 'Pode ser elogio exagerado ou provocação leve. O tom da conversa define o sentido.',
    origin: 'Expressão coloquial brasileira adaptada para memes esportivos e escolares.',
    variations: ['o lugar ficou pequeno', 'ficou minúsculo'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'qual foi',
    meaning: 'Pode significar “o que aconteceu?”, “olá” ou “qual é o problema?”, dependendo do tom.',
    adultTranslation: 'O que houve? / Tudo bem? / Qual é a questão?',
    context: 'Usado como saudação entre amigos ou como reação a algo estranho ou irritante.',
    category: 'saudacao',
    riskLevel: 'yellow',
    safeExample: 'Qual foi, tudo certo por aí?',
    contextNotes: 'É comum e pode ser neutro, mas em tom agressivo pode abrir uma discussão.',
    origin: 'Expressão urbana brasileira presente em conversas informais.',
    variations: ['q foi', 'qual é', 'qual foi mesmo'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
];
