import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_2: SlangTerm[] = [
  // =========================================================================
  // 1. Modern 2024-2025 Internet Culture (9 terms)
  // =========================================================================
  {
    term: "brainrot",
    meaning: "Deterioração mental causada por excesso de consumo de conteúdo viral e memes sem sentido",
    adultTranslation: "Mindless internet overconsumption rotting your brain",
    context: "Usado para descrever quando alguém está vendo tanto conteúdo absurdo que perde noção da realidade",
    category: "meme",
    riskLevel: "green",
    safeExample: "Tava vendo TikTok até as 5h, brainrot total",
    contextNotes: "Termo global que pegou forte no Brasil em 2024-2025, geralmente usado de forma autodepreciativa",
    origin: "Internet anglofona, popularizado no TikTok em 2023-2024",
    variations: ["brain rot", "brainrotado"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "demure",
    meaning: "Comportamento modesto, elegante e contido, usado ironicamente para elogiar atitudes simples do dia a dia",
    adultTranslation: "Being classy and mindful about it",
    context: "Viralizou como forma de elogiar qualquer atitude cotidiana com ironia sofisticada",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Arrumei o cabelo pra ir pra aula, muito demure, muito cutesy",
    contextNotes: "Explodiu no TikTok em meados de 2024, a pessoa original dizia 'very demure, very mindful'",
    origin: "TikTok, viralizado pela criadora Jools Lebron em 2024",
    variations: ["very demure", "demure and mindful"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "brat summer",
    meaning: "Estética e atitude de verão baseada no álbum Brat de Charli XCX: caótica, verde limão, sem frescura",
    adultTranslation: "Embracing a messy, unapologetic party girl aesthetic",
    context: "Descreve um estilo de vida despreocupado e festivo, oposto ao 'clean girl'",
    category: "meme",
    riskLevel: "green",
    safeExample: "Esse look verde é muito brat summer, amo",
    contextNotes: "Fenômeno cultural global de meados de 2024, a cor verde limão virou símbolo",
    origin: "Álbum Brat de Charli XCX, lançado em junho de 2024",
    variations: ["brat", "brat girl"],
    popularityStatus: "em_queda",
    region: "Internacional"
  },
  {
    term: "very mindful",
    meaning: "Expressão irônica usada para descrever atitudes comuns como se fossem profundas e conscientes",
    adultTranslation: "Being intentionally aware and classy about mundane things",
    context: "Sempre acompanhado de 'very demure', usado para descrever qualquer ação cotidiana",
    category: "meme",
    riskLevel: "green",
    safeExample: "Vou entrar na sala de aula assim, very mindful, very demure",
    contextNotes: "Parte do meme do 'very demure very mindful', usado com humor irônico",
    origin: "TikTok, mesma origem do demure, 2024",
    variations: ["mindful", "very cutesy very mindful"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "cutesy",
    meaning: "Fofo, bonitinho, com apelo estético delicado e kawaii",
    adultTranslation: "Adorable and aesthetically pleasing in a dainty way",
    context: "Usado para descrever looks, atitudes ou coisas que são fofas de propósito",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Essa fita no cabelo ficou muito cutesy",
    contextNotes: "Frequentemente junto com 'very demure', pegou no Brasil via TikTok",
    origin: "Inglês, popularizado na internet global e adaptado pelo TikTok brasileiro em 2024",
    variations: ["very cutesy", "cutie"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "locked in",
    meaning: "Totalmente focado e concentrado em um objetivo, sem distrações",
    adultTranslation: "Hyper-focused and fully committed to something",
    context: "Usado quando alguém está estudando, treinando ou trabalhando com máxima dedicação",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Prova amanhã, tô locked in, nem olho pro celular",
    contextNotes: "Muito usado em contexto de estudos e esportes, transmite determinação",
    origin: "Internet anglofona, popularizado no TikTok em 2023-2024",
    variations: ["locked", "lock in"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "hawk tuah",
    meaning: "Meme viral de um vídeo onde uma mulher faz um som de cuspir, virou símbolo de humor absurdo",
    adultTranslation: "Viral meme about an unexpected sound/gag reaction",
    context: "Usado como piada em situações inesperadas ou como meme de humor bizarro",
    category: "meme",
    riskLevel: "orange",
    safeExample: "Aquela resposta do professor foi tipo hawk tuah, ninguém esperava",
    contextNotes: "Meme muito viral com conotação suggestive, usado com cautela",
    origin: "Viral de uma entrevista de rua nos EUA em meados de 2024",
    variations: ["hawk tuah girl", "tuah"],
    popularityStatus: "em_queda",
    region: "Internacional"
  },
  {
    term: "barelylegal",
    meaning: "Meme usado ironicamente para descrever situações ou pessoas que mal cumpriram um requisito mínimo",
    adultTranslation: "Barely meeting the minimum requirement, sketchy territory",
    context: "Usado em memes para descrever algo que está no limite, geralmente de forma humorística",
    category: "meme",
    riskLevel: "orange",
    safeExample: "Meu álbum de figurinha tá barelylegal, quase completo",
    contextNotes: "Importante: usado apenas como meme de internet, NÃO deve ser interpretado literalmente. O meme ironiza a expressão original que tem conotação problemática",
    origin: "Meme de internet que ironiza a expressão anglofona, reaproveitado no humor brasileiro em 2024",
    variations: ["barely legal"],
    popularityStatus: "regional",
    region: "Nacional"
  },
  {
    term: "only in miami",
    meaning: "Expressão usada para descrever situações surreais, absuradas ou únicas que só poderiam acontecer em um lugar específico",
    adultTranslation: "Something so wild and unique it could only happen there",
    context: "Meme usado quando acontece algo muito bizarro ou inesperado",
    category: "meme",
    riskLevel: "green",
    safeExample: "A professora dançou funk na sala, only in miami",
    contextNotes: "Meme adaptado do contexto americano, no Brasil é usado pra qualquer situação absurda",
    origin: "TikTok americano, adaptado pela comunidade brasileira em 2024",
    variations: ["only in miami vibes", "so miami"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 2. Funk / Trap Music (12 terms)
  // =========================================================================
  {
    term: "novinha",
    meaning: "Garota jovem, geralmente adolescente, muito usada nas letras de funk",
    adultTranslation: "Young girl / teenage girl",
    context: "Termo extremamente comum no funk carioca e nos podcasts de humor teen",
    category: "outros",
    riskLevel: "orange",
    safeExample: "A novinha do 2º ano é muito engraçada",
    contextNotes: "Cuidado: no funk tem conotação sexualizada, mas entre teens é usado de forma neutra. Depende muito do contexto",
    origin: "Funk carioca, década de 2010, massificado em 2020+",
    variations: ["novie", "novin"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "escuta essa",
    meaning: "Expressão usada para pedir que alguém ouça uma música ou um beat que é muito bom",
    adultTranslation: "Listen to this, check this out",
    context: "Usado ao compartilhar músicas, beats ou trechos de funk/trap",
    category: "outros",
    riskLevel: "green",
    safeExample: "Escuta essa produção que o DJ mandou, tá foda",
    contextNotes: "Expressão muito comum na cultura musical juvenil, especialmente funk e trap",
    origin: "Cultura funk/trap brasileira",
    variations: ["escuta isso", "dá uma escutada"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "solta o som",
    meaning: "Manda tocar, liga a música, expressão para iniciar uma festa ou animação",
    adultTranslation: "Turn up the music, let's go",
    context: "Usado em festas, no carro com amigos, ou quando quer animar a galera",
    category: "outros",
    riskLevel: "green",
    safeExample: "Chegou a galera, solta o som!",
    contextNotes: "Expressão clássica do funk que continua muito viva entre adolescentes",
    origin: "Funk carioca, popularizado na década de 2010",
    variations: ["solta a batida", "bota pra tocar"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "dj",
    meaning: "Aquele que mixa e produz músicas, especialmente funk e trap",
    adultTranslation: "DJ / disc jockey / music producer",
    context: "Usado para se referir a produtores musicais, tanto profissionais quanto amadores que fazem beats",
    category: "outros",
    riskLevel: "green",
    safeExample: "Esse DJ novo tá mandando muito nas produções",
    contextNotes: "No cenário funk/trap teen, qualquer pessoa que faz beat no celular se chama de DJ",
    origin: "Cultura musical global, adaptada ao funk brasileiro",
    variations: ["DJ", "deejay"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "soundcloud",
    meaning: "Referência à plataforma SoundCloud, associada a artistas independentes e上升 stars do rap/trap",
    adultTranslation: "Underground music platform, indie artist scene",
    context: "Usado para descrever artistas que estão começando ou têm som mais alternativo",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Esse rapper é tipo soundcloud, mas tem potencial",
    contextNotes: "Ser 'soundcloud' pode ser elogio (autêntico) ou crítica (amador), depende do contexto",
    origin: "Plataforma SoundCloud, popularizada na cultura rap/trap desde 2016",
    variations: ["soundcloud rapper", "som de soundcloud"],
    popularityStatus: "regional",
    region: "Nacional"
  },
  {
    term: "produção",
    meaning: "Beat, instrumental ou o trabalho de produção musical por trás de uma música",
    adultTranslation: "Beat / instrumental track / music production",
    context: "Usado para elogiar ou comentar sobre a qualidade musical de um funk/trap",
    category: "outros",
    riskLevel: "green",
    safeExample: "A letra é média mas a produção tá insana",
    contextNotes: "Entre teens que fazem música, 'produção' é o termo mais usado para falar do beat",
    origin: "Cultura funk/trap brasileira",
    variations: ["produçãozinha", "prod"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "beatmaker",
    meaning: "Pessoa que cria beats e instrumentais para funk, trap ou rap",
    adultTranslation: "Beat producer / instrumental maker",
    context: "Usado para descrever quem faz as bases musicais das músicas",
    category: "outros",
    riskLevel: "green",
    safeExample: "Meu amigo é beatmaker, já fez som pra MC famoso",
    contextNotes: "Muitos teens começam como beatmakers usando programas grátis no celular",
    origin: "Cultura hip-hop/trap, adaptado ao funk brasileiro",
    variations: ["produtor", "maker"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "flow",
    meaning: "Ritmo e estilo de um rapper/MC ao cantar, a forma como solta as rimas",
    adultTranslation: "Rapping style, rhythm and delivery of lyrics",
    context: "Usado para elogiar ou criticar como alguém canta rap/funk",
    category: "elogio",
    riskLevel: "green",
    safeExample: "O flow desse MC é muito bom, rima bem rápido",
    contextNotes: "Ter 'flow' é o maior elogio na cena rap/funk teen",
    origin: "Hip-hop americano, incorporado ao funk e trap brasileiros",
    variations: ["flowzin", "tá no flow"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "rima",
    meaning: "Letra rimada, verso de rap/funk, ou a habilidade de criar rimas",
    adultTranslation: "Rhyme / verse / lyrics",
    context: "Usado em batalhas de rap ou ao falar sobre letras de funk",
    category: "outros",
    riskLevel: "green",
    safeExample: "Essa rima que ele soltou na batalha foi braba",
    contextNotes: "Central na cultura rap/funk, ter 'bom rima' é sinal de habilidade",
    origin: "Cultura hip-hop, fundamental no funk e rap brasileiros",
    variations: ["rimador", "bom de rima"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "freestyle",
    meaning: "Improvisação de rimas e flow ao vivo, sem letra preparada",
    adultTranslation: "Off-the-top rap improvisation",
    context: "Usado em batalhas, circle de amigos, ou quando alguém improvisa versos",
    category: "outros",
    riskLevel: "green",
    safeExample: "Deixa eu soltar um freestyle aqui, confia",
    contextNotes: "O freestyle é uma habilidade muito valorizada entre teens que curtem rap/funk",
    origin: "Hip-hop americano, popularizado no Brasil pelo rap nacional",
    variations: ["free", "improviso"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "batalha",
    meaning: "Competição de rap onde MCs se enfrentam com rimas improvisadas ou preparadas",
    adultTranslation: "Rap battle / MC competition",
    context: "Eventos ou vídeos onde rappers se enfrentam com rimas",
    category: "outros",
    riskLevel: "green",
    safeExample: "Vi a batalha no YouTube, o cara destruiu o outro",
    contextNotes: "Batalhas de rap são extremamente populares entre teens brasileiros",
    origin: "Hip-hop americano, com forte tradição no Brasil (Batalha do SIM, Entrelinhas)",
    variations: ["battle", "batalha de rimas"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "cipher",
    meaning: "Roda de rap onde os participantes vão um por vez soltando seus versos e flows",
    adultTranslation: "Rap circle where everyone takes turns spitting bars",
    context: "Momento social entre amigos que gostam de rap/funk",
    category: "outros",
    riskLevel: "green",
    safeExample: "Montou um cipher no recreio, cada um soltou uma rima",
    contextNotes: "Termo importado do hip-hop americano, muito usado em comunidades rap teen",
    origin: "Hip-hop americano, cipher significa círculo",
    variations: ["círculo", "roda de rap"],
    popularityStatus: "regional",
    region: "Nacional"
  },

  // =========================================================================
  // 3. Money / Status (10 terms)
  // =========================================================================
  {
    term: "grana",
    meaning: "Dinheiro, em especial de forma informal",
    adultTranslation: "Cash, money, bucks",
    context: "Usado no dia a dia para falar de dinheiro de forma descontraída",
    category: "outros",
    riskLevel: "green",
    safeExample: "Preciso de mais grana pra comprar o tênis novo",
    contextNotes: "Termo clássico que nunca sai de moda entre adolescentes",
    origin: "Português brasileiro informal, décadas de uso",
    variations: ["graninha", "grana extra"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "dim dim",
    meaning: "Dinheiro, expressão onomatopaica e divertida para falar de cash",
    adultTranslation: "Money, cash, dough",
    context: "Forma divertida de falar sobre dinheiro, muito usada em memes",
    category: "outros",
    riskLevel: "green",
    safeExample: "Preciso arrumar um dim dim pra ir no show",
    contextNotes: "Mais lúdico que 'grana', geralmente usado com humor",
    origin: "Internet brasileira, meme popularizado em 2020+",
    variations: ["dim", "din din"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "couve",
    meaning: "Dinheiro, vem de 'couve flor' que rima com 'dinheiro'",
    adultTranslation: "Money, cash",
    context: "Gíria para dinheiro especialmente na cultura funk e periferia",
    category: "outros",
    riskLevel: "green",
    safeExample: "Tô sem couve esse mês, quebrado",
    contextNotes: "Muito usado em letras de funk e no dia a dia de teens de periferia",
    origin: "Rima de 'couve-flor' com 'dinheiro', popularizada pelo funk",
    variations: ["couve-flor"],
    popularityStatus: "regional",
    region: "Nacional"
  },
  {
    term: "ostentação",
    meaning: "Exibicionismo de riqueza, mostrar que tem dinheiro ou status",
    adultTranslation: "Flexing, showing off wealth and status",
    context: "Usado para descrever quem gosta de exibir suas coisas caras",
    category: "outros",
    riskLevel: "yellow",
    safeExample: "Esse tênis é pura ostentação, custou uma fortuna",
    contextNotes: "Pode ser elogio ou crítica dependendo do tom de voz",
    origin: "Cultura funk/rap brasileira, massificado nas redes sociais",
    variations: ["ostentando", "ostentar"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "riq",
    meaning: "Abreviação de 'rico', usado para descrever quem tem dinheiro ou algo de qualidade premium",
    adultTranslation: "Rich, wealthy, high-quality",
    context: "Usado como adjetivo para coisas caras ou pessoas com dinheiro",
    category: "outros",
    riskLevel: "green",
    safeExample: "Esse celular é riq demais, custou 5 mil",
    contextNotes: "Abreviação comum entre teens, sempre com conotação positiva",
    origin: "Internet brasileira, abreviação de 'rico' popularizada em redes sociais",
    variations: ["riqui", "ricão"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "flexar",
    meaning: "Mostrar, exibir algo com orgulho, geralmente algo caro ou de achievement",
    adultTranslation: "To show off, to flex something",
    context: "Usado quando alguém quer demonstrar conquista, roupa nova, nota alta, etc.",
    category: "outros",
    riskLevel: "green",
    safeExample: "Flexou o iPhone novo no grupo, agora todo mundo quer",
    contextNotes: "Verbo derivado do inglês 'flex', muito incorporado ao vocabulário teen",
    origin: "Inglês 'flex', popularizado pelo rap americano e adaptado no Brasil",
    variations: ["flex", "flexou"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "chapado",
    meaning: "Ter muito dinheiro, estar rico momentaneamente, ou estar chapado de tanto gastar",
    adultTranslation: "Stacked with cash, having a lot of money at the moment",
    context: "Usado quando alguém recebeu dinheiro ou está podendo gastar",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Recebi o salário, tô chapado hoje",
    contextNotes: "Uso mais associado a ter dinheiro no momento do que ser rico",
    origin: "Cultura funk/periferia, década de 2010+",
    variations: ["chapadíssimo"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "quebrado",
    meaning: "Sem dinheiro, zerado, na lona financeiramente",
    adultTranslation: "Broke, having no money",
    context: "Usado para descrever situação de falta de dinheiro",
    category: "outros",
    riskLevel: "green",
    safeExample: "Não posso sair hoje, tô quebrado",
    contextNotes: "Muito comum entre teens que dependem da mesada dos pais",
    origin: "Português brasileiro informal, uso antigo mas muito vivo entre jovens",
    variations: ["liso", "na lona", "zerado"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "farpando",
    meaning: "Ganhando dinheiro, arrumando uma graninha, geralmente de forma criativa ou paralela",
    adultTranslation: "Making money, hustling on the side",
    context: "Usado quando alguém está conseguindo dinheiro extra",
    category: "outros",
    riskLevel: "green",
    safeExample: "Tô farpando vendendo adesivo, já fiz 200 reais",
    contextNotes: "Termo popular na cultura teen de empreendedorismo informal",
    origin: "Gíria de internet brasileira, popularizada em 2023-2024",
    variations: ["farpa", "farpou"],
    popularityStatus: "regional",
    region: "Nacional"
  },
  {
    term: "gastando",
    meaning: "Gastando dinheiro sem pensar, gastando à vontade",
    adultTranslation: "Spending money freely, balling out",
    context: "Usado para descrever alguém que está gastando bastante",
    category: "outros",
    riskLevel: "green",
    safeExample: "Passei o fim de semana gastando, agora tô na fase quebrado",
    contextNotes: "Geralmente seguido de arrependimento ou humor",
    origin: "Internet brasileira, uso popular entre teens em 2024",
    variations: ["gastação", "gastador"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 4. Teen Relationships (13 terms)
  // =========================================================================
  {
    term: "ficante",
    meaning: "Pessoa com quem se fica (namoro informal), sem compromisso oficial",
    adultTranslation: "Someone you're casually seeing / hooking up with",
    context: "Status entre solteiro e namorado, muito comum entre adolescentes",
    category: "outros",
    riskLevel: "yellow",
    safeExample: "Meu ficante me mandou mensagem agora",
    contextNotes: "Conceito central dos relacionamentos teen brasileiros, é mais que crush mas menos que namoro",
    origin: "Cultura juvenil brasileira, existe há décadas mas continua essencial",
    variations: ["ficantinho", "ficagem"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "ex",
    meaning: "Ex-namorado(a), pessoa com quem se teve relacionamento no passado",
    adultTranslation: "Ex-boyfriend / ex-girlfriend",
    context: "Usado para falar de relacionamentos passados",
    category: "outros",
    riskLevel: "yellow",
    safeExample: "Vi meu ex na feira, aí fiquei estranho",
    contextNotes: "Termo universal mas cheio de nuances entre teens, geralmente carrega drama",
    origin: "Universal, adaptado à cultura teen brasileira",
    variations: ["ex-namorada", "ex-boy"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "amorzinho",
    meaning: "Forma carinhosa de se referir ao crush ou ficante, diminutivo de amor",
    adultTranslation: "Sweetheart, little love (for crush/partner)",
    context: "Usado para se referir afetuosamente a alguém que se gosta",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Meu amorzinho mandou bom dia hoje, morri",
    contextNotes: "Muito usado entre meninas para falar de crush, especialmente em áudios e stories",
    origin: "Português brasileiro, popularizado nas redes sociais entre teens",
    variations: ["amor", "mozinho"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "casal",
    meaning: "Par romântico, duas pessoas que estão namorando ou são reconhecidas como um par",
    adultTranslation: "Couple, pair",
    context: "Usado para confirmar que duas pessoas estão juntas",
    category: "outros",
    riskLevel: "green",
    safeExample: "Todo mundo já sabe que eles são casal",
    contextNotes: "No mundo teen, ser 'casal' é uma declaração pública de relacionamento",
    origin: "Português, uso comum e atemporal",
    variations: ["casalzinho", "ship"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "conversa",
    meaning: "Fase de conversar com alguém antes de ficar, o período de flerte por mensagens",
    adultTranslation: "Talking stage, early flirting phase",
    context: "A fase entre conhecer alguém e começar a ficar, muito baseada em DMs e WhatsApp",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Tô em conversa com uma pessoa agora, phodasse",
    contextNotes: "Etapas teen: conversa → ficante → namoro. A 'conversa' é a primeira fase",
    origin: "Cultura juvenil brasileira contemporânea",
    variations: ["talking stage", "fase de conversa"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "avanzar",
    meaning: "Dar um passo à frente no relacionamento, progredir do flerte para algo mais",
    adultTranslation: "To make a move, to advance the relationship",
    context: "Usado quando alguém decide tomar atitude com o crush",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Vou avanzar hoje, vou pedir o número dela",
    contextNotes: "Vem do espanhol 'avanzar', muito usado no Sul do Brasil",
    origin: "Influência espanhola, popularizado no Sul e Sudeste do Brasil",
    variations: ["avançar"],
    popularityStatus: "regional",
    region: "Sul e Sudeste"
  },
  {
    term: "dar sinal",
    meaning: "Demonstrar interesse em alguém de forma sutil, dar indícios que gosta",
    adultTranslation: "To show interest, give hints that you like someone",
    context: "Quando alguém manda sinais de que está interessado",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Ela tá dando sinal, já curtiu todas as fotos",
    contextNotes: "Analisa-se muito os 'sinais' nas redes sociais: curtidas, stories, mensagens",
    origin: "Cultura juvenil brasileira de relacionamentos",
    variations: ["sinal", "dar bola"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "ficar de olho",
    meaning: "Demonstrar interesse em alguém, observar com intenção romântica",
    adultTranslation: "To keep an eye on someone (romantically interested)",
    context: "Quando alguém está de olho em outra pessoa como potencial crush",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Tô ficando de olho na menina do outro 3º ano",
    contextNotes: "Mais sutil que 'dar sinal', é o estágio de observação antes da ação",
    origin: "Expressão brasileira comum, incorporada ao vocabulário teen",
    variations: ["de olho"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "ciumeira",
    meaning: "Crise de ciúmes, sensação de inveja por alguém que está com a pessoa que você gosta",
    adultTranslation: "Jealousy fit, being jealous over someone",
    context: "Reação emocional comum em relacionamentos teen ou situações de crush",
    category: "alerta_emocional",
    riskLevel: "yellow",
    safeExample: "Dei uma ciumeira quando vi ele conversando com outra",
    contextNotes: "A ciumeira é vista como normal entre teens mas pode ser prejudicial se exagerada",
    origin: "Cultura juvenil brasileira",
    variations: ["ciúme", "ciumento"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "paquerar",
    meaning: "Cortejar, flertar com alguém, demonstrar interesse romântico",
    adultTranslation: "To flirt, to hit on someone",
    context: "Ato de tentar conquistar alguém, geralmente com elogios e atenção",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Ele vive paquerando todo mundo na escola",
    contextNotes: "Termo clássico que segue sendo usado pelas novas gerações",
    origin: "Português brasileiro, uso antigo mas vivo entre teens",
    variations: ["paquera", "paquerador"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "cantada",
    meaning: "Frase usada para flertar ou tentar conquistar alguém",
    adultTranslation: "Pickup line, flirting attempt",
    context: "Pode ser romântica, engraçada ou bizarra dependendo de quem usa",
    category: "flerte",
    riskLevel: "green",
    safeExample: "A cantada dele foi tão ruim que a gente ri até hoje",
    contextNotes: "Cantadas ruins viram memes entre grupos de amigos",
    origin: "Cultura brasileira, uso antigo e popular",
    variations: ["cantada de tiro", "cantada top"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "abordagem",
    meaning: "Ato de chegar em alguém para puxar conversa com intenção romântica",
    adultTranslation: "Approaching someone to start a romantic conversation",
    context: "Momento crucial na conquista, pode dar certo ou ser constrangedor",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Fiz uma abordagem hoje, não deu muito certo",
    contextNotes: "A abordagem é tema constante de discussão entre teens",
    origin: "Cultura de paquera brasileira, popularizada em vídeos de dating",
    variations: ["abordar"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "rejeitado",
    meaning: "Pessoa que foi recusada romanticamente, levou um não",
    adultTranslation: "Rejected, turned down",
    context: "Estado de ter sido rejeitado por um crush ou ficante",
    category: "outros",
    riskLevel: "yellow",
    safeExample: "Fui rejeitado, mas vida que segue",
    contextNotes: "Entre teens, a rejeição é fonte de memes e piadas entre amigos",
    origin: "Universal, incorporado ao vocabulário teen",
    variations: ["rejeitada", "tomou um não"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 5. Daily Teen Actions (10 terms)
  // =========================================================================
  {
    term: "bater papo",
    meaning: "Conversar, trocar ideias, ter uma conversa informal",
    adultTranslation: "To chat, to have a conversation",
    context: "Usado tanto para conversa presencial quanto por mensagem",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Fomos bater papo no parque depois da aula",
    contextNotes: "Expressão neutra e versátil, serve para qualquer tipo de conversa",
    origin: "Português brasileiro, uso popular e antigo",
    variations: ["papo", "bate-papo"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "soltar a voz",
    meaning: "Cantar alto, gritar de empolgação, se expressar livremente e com energia",
    adultTranslation: "To belt out, to sing/shout with energy and enthusiasm",
    context: "Usado em karaokês, festas, ou quando alguém expressa opinião com firmeza",
    category: "outros",
    riskLevel: "green",
    safeExample: "Aí soltou a voz no karaokê, impressionou todo mundo",
    contextNotes: "Pode ser literal (cantar) ou figurado (falar o que pensa)",
    origin: "Cultura musical brasileira, funk e samba",
    variations: ["soltou a voz"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "correr pra lá",
    meaning: "Ir rapidamente a algum lugar, se mover com urgência",
    adultTranslation: "To rush over there, to hurry somewhere",
    context: "Usado quando precisa ir a algum lugar depressa",
    category: "outros",
    riskLevel: "green",
    safeExample: "O ônibus tá chegando, corre pra lá!",
    contextNotes: "Expressão muito comum no dia a dia, com tom de urgência",
    origin: "Português brasileiro coloquial",
    variations: ["corre pra cá"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "virar a noite",
    meaning: "Ficar acordado a noite toda, não dormir, geralmente por diversão",
    adultTranslation: "To stay up all night, to pull an all-nighter",
    context: "Usado para descrever noites de jogos, festas ou maratonas de série",
    category: "outros",
    riskLevel: "green",
    safeExample: "Viramos a noite jogando com a galera",
    contextNotes: "Muito comum em finais de semana e férias entre teens",
    origin: "Português brasileiro, uso comum em todas as idades",
    variations: ["virada", "maratona"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "marcar bobeira",
    meaning: "Fazer algo sem sentido, cometer erro bobo, agir de forma tola",
    adultTranslation: "To act foolishly, to make a silly mistake",
    context: "Usado quando alguém faz algo engraçado ou sem propósito",
    category: "ironia",
    riskLevel: "green",
    safeExample: "Marquei bobeira e mandei mensagem na sala errada",
    contextNotes: "Geralmente dito com humor, sem malícia",
    origin: "Português brasileiro coloquial",
    variations: ["bobagem", "bobeira"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "cair na real",
    meaning: "Perceber a verdade, aceitar a realidade, parar de viver em ilusão",
    adultTranslation: "To face reality, to come back to earth",
    context: "Usado quando alguém precisa acordar para a realidade de uma situação",
    category: "outros",
    riskLevel: "green",
    safeExample: "Preciso cair na real e começar a estudar pra prova",
    contextNotes: "Pode ser conselho ou autocrítica, geralmente com tom construtivo",
    origin: "Português brasileiro, uso popular e antigo",
    variations: ["cai na real"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "passar raiva",
    meaning: "Ficar com raiva, se frustrar com uma situação",
    adultTranslation: "To be pissed off, to be frustrated",
    context: "Expressão de frustração no dia a dia, geralmente por coisas pequenas",
    category: "outros",
    riskLevel: "green",
    safeExample: "Passei raiva quando o professor passou trabalho de última hora",
    contextNotes: "Expressão muito comum, geralmente seguida de desabafo",
    origin: "Português brasileiro coloquial",
    variations: ["raiva", "puto"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "dar risada",
    meaning: "Rir, rir muito, achar algo engraçado",
    adultTranslation: "To laugh, to crack up",
    context: "Usado ao compartilhar memes, piadas ou situações engraçadas",
    category: "outros",
    riskLevel: "green",
    safeExample: "Dei risada sozinho na sala vendo meme no Instagram",
    contextNotes: "No mundo teen, 'dar risada' geralmente envolve vídeos e memes no celular",
    origin: "Português, uso universal",
    variations: ["risada", "morrendo de rir"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "chorar",
    meaning: "Chorar, desabafar emocionalmente",
    adultTranslation: "To cry, to break down emotionally",
    context: "Usado de forma literal ou exagerada para descrever tristeza",
    category: "alerta_emocional",
    riskLevel: "green",
    safeExample: "Quase chorei no final do filme, era tão triste",
    contextNotes: "Entre teens, falar sobre chorar é mais normalizado que antes",
    origin: "Português, uso universal",
    variations: ["choramingo", "choradeira"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "pensar",
    meaning: "Refletir sobre algo, ficar pensando demais (overthinking)",
    adultTranslation: "To think deeply, to overthink something",
    context: "Usado quando alguém está reflexivo ou preocupado demais",
    category: "alerta_emocional",
    riskLevel: "green",
    safeExample: "Fico pensando muito nas coisas, preciso relaxar",
    contextNotes: "O excesso de 'pensar' é comum entre teens e ligado à ansiedade",
    origin: "Português, uso universal mas com nuances entre teens",
    variations: ["pensamento", "overthinkar"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 6. Food / Fitness (8 terms)
  // =========================================================================
  {
    term: "whey",
    meaning: "Suplemento protéico (whey protein), muito associado à cultura de academia entre jovens",
    adultTranslation: "Whey protein supplement",
    context: "Usado por teens que treinam na academia e querem ganhar massa muscular",
    category: "outros",
    riskLevel: "green",
    safeExample: "Tomo whey depois do treino todo dia",
    contextNotes: "Entre teens da academia, tomar whey é praticamente obrigatório",
    origin: "Cultura fitness global, adaptada ao público adolescente brasileiro",
    variations: ["whey protein", "protein"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "academia",
    meaning: "Local de treino, mas também o lifestyle de quem treina regularmente",
    adultTranslation: "Gym / fitness lifestyle",
    context: "Ir para a academia é um status symbol entre teens, especialmente meninos",
    category: "outros",
    riskLevel: "green",
    safeExample: "Vou pra academia depois da aula, treino de peito hoje",
    contextNotes: "A academia se tornou centro social para muitos adolescentes",
    origin: "Cultura fitness, popularizada entre teens em 2020+",
    variations: ["aca", "malhar"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "treinar",
    meaning: "Fazer exercício físico, especialmente musculação",
    adultTranslation: "To work out, to train",
    context: "Usado para descrever a rotina de exercícios",
    category: "outros",
    riskLevel: "green",
    safeExample: "Preciso treinar hoje, não posso perder o dia",
    contextNotes: "Entre teens fitness, 'treinar' é sagrado e não pode ser pulado",
    origin: "Cultura fitness, uso universal entre praticantes",
    variations: ["treino", "training"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "shape",
    meaning: "Forma física, corpo definido e musculoso, estar em boa forma",
    adultTranslation: "Being in good physical shape, having a fit body",
    context: "Ter shape é um dos maiores objetivos estéticos entre teens",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Esse cara tá com shape absurdo, quanto tempo de treino?",
    contextNotes: "Shape é o padrão estético aspiracional para teens que frequentam academia",
    origin: "Inglês 'shape', popularizado pela cultura fitness brasileira",
    variations: ["shapeado", "em shape"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "maromba",
    meaning: "Pessoa que é obcecada por academia e musculação, geralmente de forma exagerada",
    adultTranslation: "Gym rat, someone obsessed with working out and getting big",
    context: "Pode ser elogio (dedicação) ou crítica (obsessão)",
    category: "outros",
    riskLevel: "green",
    safeExample: "Meu amigo virou maromba, só fala de treino e dieta",
    contextNotes: "Termo carinhoso ou irônico dependendo do contexto",
    origin: "Gíria brasileira da cultura fitness",
    variations: ["marombinha", "maromba full"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "fitness",
    meaning: "Estilo de vida focado em saúde e exercícios físicos",
    adultTranslation: "Fitness lifestyle, health-conscious living",
    context: "Usado para descrever roupas, hábitos ou pessoas ligadas a academia",
    category: "outros",
    riskLevel: "green",
    safeExample: "Comprei uma roupa fitness nova pra academia",
    contextNotes: "Ser 'fitness' é um lifestyle completo que inclui treino, dieta e estética",
    origin: "Cultura fitness global",
    variations: ["fit", "fitness lifestyle"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "dieta",
    meaning: "Regime alimentar restritivo, geralmente com foco em resultados estéticos",
    adultTranslation: "Diet, eating plan for fitness goals",
    context: "Usado por teens que querem perder peso ou definir o corpo",
    category: "outros",
    riskLevel: "yellow",
    safeExample: "Tô em dieta seca pra ficar em shape pro verão",
    contextNotes: "Atenção: dietas restritivas entre teens podem ser prejudiciais à saúde mental e física",
    origin: "Cultura fitness, uso universal",
    variations: ["cutting", "seca"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "gado",
    meaning: "Pessoa que não pensa por si, que segue a massa sem questionar, clueless",
    adultTranslation: "Sheep, someone clueless who follows the crowd blindly",
    context: "Usado para descrever quem não tem opinião própria ou cai em qualquer coisa",
    category: "ironia",
    riskLevel: "yellow",
    safeExample: "Caiu no golpe do WhatsApp de novo? Que gado",
    contextNotes: "Muito usado como meme na internet brasileira para descrever comportamentos ingênuos",
    origin: "Internet brasileira, meme que se tornou gíria corrente em 2023-2024",
    variations: ["gado demência", "boi"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 7. School (8 terms)
  // =========================================================================
  {
    term: "rabisco",
    meaning: "Desenho ou escrita feita de forma descuidada, geralmente nas margens do caderno durante a aula",
    adultTranslation: "Doodle, scribble",
    context: "Desenhos feitos no caderno enquanto o professor dá aula",
    category: "escola",
    riskLevel: "green",
    safeExample: "Fiz tanto rabisco na prova que o professor reclamou",
    contextNotes: "Todo teen rabiscou no caderno pelo menos uma vez, é um ritual escolar",
    origin: "Português brasileiro, uso comum em contexto escolar",
    variations: ["rabiscar", "doodle"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "colar",
    meaning: "Copiar a resposta de alguém em uma prova ou trabalho escolar",
    adultTranslation: "To cheat on a test, to copy answers",
    context: "Prática comum (mas proibida) em escolas brasileiras",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "Quase que eu colava na prova de matemática",
    contextNotes: "Embora seja comum, colar é visto com humor entre teens e não como algo sério",
    origin: "Cultura escolar brasileira, existe há gerações",
    variations: ["cola", "colinha"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "xerox",
    meaning: "Cópia de documento ou atividade escolar (mesmo que seja impressão digital hoje)",
    adultTranslation: "Photocopy / printout of school materials",
    context: "Usado para pedir cópias de atividades ou materiais de estudo",
    category: "escola",
    riskLevel: "green",
    safeExample: "Alguém fez xerox da lista de exercícios?",
    contextNotes: "O termo sobreviveu à era digital e é usado mesmo para impressões",
    origin: "Marca Xerox, virou nome comum em português",
    variations: ["xérox", "cópia"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "fichário",
    meaning: "Organizador de folhas soltas usado na escola, geralmente cheio de fichas e anotações",
    adultTranslation: "Binder / folder for school papers",
    context: "Item essencial do material escolar teen",
    category: "escola",
    riskLevel: "green",
    safeExample: "Meu fichário tá uma bagunça, não acho a ficha de português",
    contextNotes: "O estado do fichário é indicador de organização (ou falta dela) do aluno",
    origin: "Cultura escolar brasileira",
    variations: ["ficha", "fichário organizado"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "nota vermelha",
    meaning: "Nota abaixo da média em uma prova ou disciplina, geralmente abaixo de 5",
    adultTranslation: "Failing grade, red mark on a test",
    context: "Situação temida por todo aluno, geralmente gera bronca dos pais",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "Tirei nota vermelha em física, minha mãe vai me matar",
    contextNotes: "A 'nota vermelha' é fonte de ansiedade entre teens e motivo de conversa entre amigos",
    origin: "Sistema educacional brasileiro, notas vermelhas indicam reprovação",
    variations: ["reprovado", "rodou"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "conselho de classe",
    meaning: "Reunião de professores para decidir sobre aprovação ou reprovação dos alunos",
    adultTranslation: "Teacher council meeting to decide student pass/fail status",
    context: "Momento de tensão para alunos com notas baixas",
    category: "escola",
    riskLevel: "green",
    safeExample: "Conselho de classe amanhã, torcendo pra passar de ano",
    contextNotes: "O conselho de classe é um evento estressante no calendário escolar teen",
    origin: "Sistema educacional brasileiro",
    variations: ["conselho"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "recuperação",
    meaning: "Prova ou período extra para tentar recuperar uma nota baixa e não reprovar",
    adultTranslation: "Make-up test / remedial exam to save your grade",
    context: "Última chance para alunos que estão em risco de reprovação",
    category: "escola",
    riskLevel: "green",
    safeExample: "Preciso estudar pra recuperação de história, senão reprovo",
    contextNotes: "A recuperação é vista como salvação ou como evidência de que não estudou o suficiente",
    origin: "Sistema educacional brasileiro",
    variations: ["recupera", "recupe"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "recesso",
    meaning: "Pausa entre as aulas, intervalo escolar",
    adultTranslation: "School break, recess time between classes",
    context: "Momento sagrado do dia escolar, quando os teens socializam",
    category: "escola",
    riskLevel: "green",
    safeExample: "No recesso a gente jogava bola no pátio",
    contextNotes: "O recesso é o melhor momento do dia letivo para a maioria dos teens",
    origin: "Cultura escolar, uso universal",
    variations: ["intervalo", "recreio"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 8. Emotional / Mental Health (5 terms)
  // =========================================================================
  {
    term: "crise",
    meaning: "Momento de desespero emocional, ansiedade ou estresse agudo",
    adultTranslation: "Emotional breakdown, crisis moment",
    context: "Usado para descrever momentos de pico de estresse ou ansiedade",
    category: "alerta_emocional",
    riskLevel: "yellow",
    safeExample: "Tive uma crise antes da apresentação, mas consegui me controlar",
    contextNotes: "Os teens falam mais abertamente sobre crises emocionais hoje, o que é positivo para saúde mental",
    origin: "Termo clínico adaptado ao vocabulário adolescente",
    variations: ["crise de ansiedade", "crise de pânico"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "burnout",
    meaning: "Esgotamento mental e físico por excesso de atividades, estudos ou trabalho",
    adultTranslation: "Mental and physical exhaustion from overwork",
    context: "Usado quando alguém está sobrecarregado com escola, estudos e atividades",
    category: "alerta_emocional",
    riskLevel: "yellow",
    safeExample: "Semana de provas me deixou em burnout total",
    contextNotes: "Termo originalmente corporativo, agora muito usado por teens sob pressão escolar",
    origin: "Psicologia corporativa, popularizado na internet e adaptado por teens",
    variations: ["burnoutado", "esgotado"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "sobrevivendo",
    meaning: "Estado de apenas conseguir lidar com o dia a dia, sem energia extra",
    adultTranslation: "Barely getting by, surviving day to day",
    context: "Usado de forma humorística para descrever o estado mental durante períodos difíceis",
    category: "alerta_emocional",
    riskLevel: "yellow",
    safeExample: "Como tô? Sobrevivendo. É o que posso dizer",
    contextNotes: "Muitos teens usam com humor para lidar com estresse real",
    origin: "Internet brasileira, meme de autoestima",
    variations: ["sobrevivência", "no survival mode"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "cansado",
    meaning: "Esgotado, sem energia, tanto física quanto mentalmente",
    adultTranslation: "Tired, exhausted, drained",
    context: "Expressão constante entre teens que lidam com escola, redes e expectativas",
    category: "alerta_emocional",
    riskLevel: "green",
    safeExample: "Tô cansado de tudo, preciso de férias",
    contextNotes: "Quando um teen diz 'tô cansado' pode significar cansaço físico, mental ou emocional",
    origin: "Português, uso universal mas com peso emocional entre teens",
    variations: ["cansadíssimo", "morto"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "exausto",
    meaning: "Extremamente cansado, esgotado até o limite",
    adultTranslation: "Extremely exhausted, completely drained",
    context: "Versão intensificada de 'cansado', geralmente após período de muito esforço",
    category: "alerta_emocional",
    riskLevel: "green",
    safeExample: "Depois da semana de provas, tô exausto",
    contextNotes: "Usado para enfatizar que o cansaço é real e profundo",
    origin: "Português, uso formal adaptado ao vocabulário teen",
    variations: ["exaustão", "fisicamente exausto"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 9. Verbs (3 terms)
  // =========================================================================
  {
    term: "meter o pé",
    meaning: "Agir com pressa, se apressar, fazer algo rapidamente sem pensar muito",
    adultTranslation: "To rush, to hurry up, to act fast",
    context: "Usado quando alguém precisa fazer algo depressa",
    category: "outros",
    riskLevel: "green",
    safeExample: "Mete o pé que o ônibus tá passando!",
    contextNotes: "Expressão muito comum no dia a dia, com tom de urgência",
    origin: "Português brasileiro coloquial",
    variations: ["mete o pé", "meteram o pé"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "levantar",
    meaning: "Acordar, sair da cama, geralmente com dificuldade cedo pela manhã",
    adultTranslation: "To wake up, to get out of bed",
    context: "Usado na rotina matinal, geralmente reclamando sobre acordar cedo",
    category: "outros",
    riskLevel: "green",
    safeExample: "Preciso levantar 6h pra escola, que sofrimento",
    contextNotes: "Para teens, 'levantar' é sinônimo de sofrimento matinal",
    origin: "Português, uso universal",
    variations: ["acordar", "levantar cedo"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "deitar",
    meaning: "Deitar na cama, ir dormir ou descansar",
    adultTranslation: "To lie down, to go to bed",
    context: "Usado quando someone vai descansar ou dormir",
    category: "outros",
    riskLevel: "green",
    safeExample: "Cheguei da escola e já fui deitar, tava morto",
    contextNotes: "Depois de um longo dia, 'deitar' é tudo que um teen quer fazer",
    origin: "Português, uso universal",
    variations: ["deitar cedo", "ir pra cama"],
    popularityStatus: "ativo",
    region: "Nacional"
  },

  // =========================================================================
  // 10. Misc / Daily Life (2 terms)
  // =========================================================================
  {
    term: "combo",
    meaning: "Conjunto de itens comprados juntos com desconto, especialmente comida em fast food",
    adultTranslation: "Combo meal, bundle deal",
    context: "Usado ao pedir comida em lanchonetes ou para descrever conjuntos",
    category: "outros",
    riskLevel: "green",
    safeExample: "Pediu o combo do McDonald's que é mais em conta",
    contextNotes: "Termo comum no dia a dia, muito usado em fast food e delivery",
    origin: "Inglês 'combo', incorporado ao vocabulário brasileiro",
    variations: ["combozinho", "combinação"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "pix",
    meaning: "Transferência bancária instantânea brasileira, usada para qualquer pagamento entre pessoas",
    adultTranslation: "Instant money transfer (Brazil's instant payment system)",
    context: "Forma principal de pagamento entre teens, desde dividir conta até pagar ficante",
    category: "outros",
    riskLevel: "green",
    safeExample: "Me manda o pix do lanche, esqueci a carteira",
    contextNotes: "O PIX revolucionou como teens lidam com dinheiro, tudo é pago por PIX",
    origin: "Sistema PIX do Banco Central do Brasil, lançado em 2020, tornou-se ubiquitous",
    variations: ["pixar", "faz um pix"],
    popularityStatus: "ativo",
    region: "Nacional"
  }
];
