import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_3: SlangTerm[] = [
  // =========================================================================
  // 1. Modern TikTok/Memes 2024-2025 (10 terms)
  // =========================================================================
  {
    term: "serving cunt",
    meaning: "Elogio máximo a alguém que está arrasando na aparência, atitude ou performance; expressão de aprovação absoluta no TikTok",
    adultTranslation: "Looking absolutely stunning / delivering an impeccable look or moment",
    context: "Usado para elogiar fashion, performance ou confiança. Apesar da palavra forte, no contexto do TikTok virou elogio fashion neutro e celebratório, sem conotação sexual",
    category: "elogio",
    riskLevel: "orange",
    safeExample: "O look dela no show tava serving cunt demais",
    contextNotes: "Termo de drag culture popularizado no TikTok. No Brasil, adolescentes usam como elogio fashion. O tom é celebratório, não vulgar. Precisa de explicação cuidadosa para pais",
    origin: "Drag culture / Ballroom, popularizado no TikTok a partir de 2023",
    variations: ["serving", "served cunt"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "eating it up",
    meaning: "Entregando algo com excelência, dominando uma situação, fazendo algo perfeitamente",
    adultTranslation: "Absolutely killing it / doing something amazingly well",
    context: "Usado quando alguém tira de letra uma situação, performance ou tarefa",
    category: "elogio",
    riskLevel: "green",
    safeExample: "A apresentação dela tava eating it up, demais",
    contextNotes: "Muito usado em performances de dança, canto ou moda. Comum no TikTok desde 2023",
    origin: "Internet anglofona, popularizado no TikTok",
    variations: ["ate that up", "ate and left no crumbs"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "hits different",
    meaning: "Algo que parece especial, diferente de tudo, uma experiência única que não se compara",
    adultTranslation: "Something that feels uniquely good / a special kind of vibe",
    context: "Usado para descrever sensações, músicas, comidas ou momentos que são especiais",
    category: "meme",
    riskLevel: "green",
    safeExample: "Ouvir essa música à noite hits different",
    contextNotes: "Termo global que jovens brasileiros usam misturado com português. Muito comum em legends de story e TikTok",
    origin: "Internet anglofona, Tumblr/Twitter, popularizado 2020-2022",
    variations: ["hits diff"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "no thoughts head empty",
    meaning: "Estado de relaxamento total sem pensar em nada; desconectar completamente",
    adultTranslation: "Total zen mode / brain off, chilling",
    context: "Usado de forma engraçada quando alguém está completamente relaxado ou distraído",
    category: "meme",
    riskLevel: "green",
    safeExample: "Domingo sem compromisso, no thoughts head empty",
    contextNotes: "Meme clássico de internet que continua muito usado. Geralmente acompanha memes de gatos ou personagens olhando pro nada",
    origin: "Meme clássico de internet / Tumblr, 2018+",
    variations: ["head empty", "brain empty"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "me when",
    meaning: "Formato de meme onde alguém se identifica com uma situação absurda ou específica",
    adultTranslation: "Literally me / my exact reaction when...",
    context: "Usado no início de memes e stories para se identificar com algo",
    category: "meme",
    riskLevel: "green",
    safeExample: "Me when a professora fala que tem prova amanhã",
    contextNotes: "Formato de meme onipresente no TikTok e Twitter. Pode ser usado com qualquer situação",
    origin: "Internet meme culture, Tumblr/Twitter 2019+",
    variations: ["literally me when"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "i'm just a girl",
    meaning: "Expressão irônica usada para justificar algo bobo, esquecimento ou comportamento estereotipado",
    adultTranslation: "I'm just a girl (as an excuse for silly behavior)",
    context: "Usado de forma humorística para justificar atitudes. Virou meme massivo no TikTok",
    category: "meme",
    riskLevel: "green",
    safeExample: "Esqueci a senha de novo... i'm just a girl",
    contextNotes: "Vem do meme da Margot Robbie em Barbie mas a frase já existia. Usado de forma cômica e autodepreciativa",
    origin: "Meme clássico de internet / popularizado pelo filme Barbie (2023)",
    variations: ["i'm just a girl living in a world"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "roman empire",
    meaning: "Algo que você pensa constantemente sem motivo óbvio; uma obsessão secreta do dia a dia",
    adultTranslation: "Something you think about randomly all the time",
    context: "Vem do meme 'What's something you think about more than you should? The Roman Empire'",
    category: "meme",
    riskLevel: "green",
    safeExample: "Fico pensando naquele episódio de anime, é meu roman empire",
    contextNotes: "Meme viral de 2023 que continua popular. Usado quando alguém menciona algo que pensa demais",
    origin: "Meme viral TikTok/Twitter, setembro 2023",
    variations: ["meu roman empire"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "girl dinner",
    meaning: "Refeição improvisada e aleatória feita de snacks e sobras; jantar improvisado e sem regra",
    adultTranslation: "A random assortment of snacks as a meal",
    context: "Usado de forma humorística para descrever uma refeição montada com o que tem pela casa",
    category: "meme",
    riskLevel: "green",
    safeExample: "Hoje girl dinner: biscoito, queijo e suco",
    contextNotes: "Meme muito popular entre adolescentes de todos os gêneros. Normaliza refeições improvisadas",
    origin: "TikTok, viralizado em meados de 2023",
    variations: ["boy dinner"],
    popularityStatus: "em_queda",
    region: "Internacional"
  },
  {
    term: "girl math",
    meaning: "Lógica matemática distorcida para justificar gastos; racionalização cômica de compras",
    adultTranslation: "Funny twisted logic to justify spending money",
    context: "Usado de forma irônica quando alguém inventa uma lógica para dizer que uma compra 'na verdade saiu de graça'",
    category: "meme",
    riskLevel: "green",
    safeExample: "Se eu pago em dinheiro, na verdade é de graça. Girl math",
    contextNotes: "Meme que explodiu em 2023. Exemplos: 'comprei de promoção, na verdade ganhei dinheiro'",
    origin: "TikTok, meados de 2023",
    variations: ["boy math"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "mother",
    meaning: "Elogio supremo para alguém que está arrasando, inspirando ou dominando; uma diva, referência absoluta",
    adultTranslation: "Absolute icon / queen / someone who is dominating",
    context: "Usado para celebrar alguém que é inspiração, geralmente mulheres na moda, música ou atitude",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Ela é mother, sempre arrasando",
    contextNotes: "Termo de stan culture e drag culture que pegou no mainstream. Usado para ídolos e referências",
    origin: "Drag culture / Stan culture / TikTok",
    variations: ["mothering", "is mother"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  // =========================================================================
  // 2. More TikTok/Memes 2024-2025 (8 terms)
  // =========================================================================
  {
    term: "i fear",
    meaning: "Expressão usada para admitir algo preocupante ou constrangedor sobre si mesmo; 'tenho medo de que seja verdade'",
    adultTranslation: "I'm scared to admit it but... / I have a feeling that...",
    context: "Usado no início de uma confissão autodepreciativa ou observação cômica",
    category: "meme",
    riskLevel: "green",
    safeExample: "I fear que eu não vou conseguir dormir hoje",
    contextNotes: "Formato de tweet/TikTok muito popular. Geralmente seguido de uma constatação engraçada",
    origin: "Twitter/X meme culture, 2023-2024",
    variations: ["i fear that"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "canon event",
    meaning: "Evento necessário e inevitável que todo mundo passa; algo que faz parte da 'história' da sua vida",
    adultTranslation: "An inevitable life event everyone goes through / a necessary plot point",
    context: "Referência ao filme Homem-Aranha: Através do Aranhaverso, usado para normalizar situações difíceis",
    category: "meme",
    riskLevel: "green",
    safeExample: "Levar um fora na adolescência é um canon event",
    contextNotes: "Muito usado para normalizar experiencias comuns da vida adolescente como sofrer, errar, etc",
    origin: "Spider-Verse movies, popularizado no TikTok 2023-2024",
    variations: ["canon"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "rare achievement",
    meaning: "Conquista cômica e inútil que alguém conseguiu; feito raro e sem importância celebrado como troféu",
    adultTranslation: "A silly, rare accomplishment celebrated as a big deal",
    context: "Usado de forma irônica para comemorar algo bizarro ou específico que aconteceu",
    category: "meme",
    riskLevel: "green",
    safeExample: "Dormir 12 horas seguidas: rare achievement desbloqueado",
    contextNotes: "Formato de meme com estética de notificação de jogo. Muito usado no Twitter e TikTok",
    origin: "Gaming culture + internet meme format, 2023+",
    variations: ["achievement unlocked", "rare achievement unlocked"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "boymom",
    meaning: "Mãe de menino; usado como identidade e orgulho, geralmente em conteúdo de redes sociais",
    adultTranslation: "Boy mom / mother of sons, used as a lifestyle identity",
    context: "Usado por mães para se identificar e também zombado por adolescentes que acham o termo exagerado",
    category: "meme",
    riskLevel: "green",
    safeExample: "Minha mãe é total boymom, tem camiseta e tudo",
    contextNotes: "No Brasil, adolescentes frequentemente usam o termo de forma cômica para caracterizar mães que só falam dos filhos",
    origin: "Instagram/TikTok parenting culture",
    variations: ["girlmom"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "it's over",
    meaning: "Expressão dramática de que algo acabou definitivamente ou que uma situação é irrecuperável",
    adultTranslation: "It's completely done / there's no coming back from this",
    context: "Usado de forma exagerada e cômica para situações cotidianas ruins",
    category: "meme",
    riskLevel: "green",
    safeExample: "Prova amanhã e eu não estudei nada... it's over",
    contextNotes: "Meme clássico que continua forte. Geralmente seguido de imagem dramática ou meme de pepe",
    origin: "Meme clássico / Pepe the Frog, 2018+",
    variations: ["it's so over"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "we're back",
    meaning: "Expressão de retorno triunfal; usada quando algo bom volta a acontecer ou quando se retoma uma vibe",
    adultTranslation: "We're officially back / the vibe has returned",
    context: "Usado em contraste com 'it's over', geralmente seguido de algo positivo",
    category: "meme",
    riskLevel: "green",
    safeExample: "Depois de uma semana de prova, we're back baby",
    contextNotes: "Sempre usado junto com 'it's over'. Ciclo: it's over → we're back → it's over...",
    origin: "Twitter/X meme culture, 2023+",
    variations: ["we're so back"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "lol",
    meaning: "Riso; abreviação de 'laughing out loud', usada para indicar algo engraçado ou como reação genérica",
    adultTranslation: "LOL / laughing out loud / that's funny",
    context: "Uma das abreviações mais usadas da internet. Pode ser reação genuína ou sarcástica",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "O vídeo que você mandou, lol demais",
    contextNotes: "Tão comum que virou parte da linguagem natural. Usado em qualquer plataforma de mensagem",
    origin: "Internet primordial / IRC / AOL, anos 90",
    variations: ["lolz", "lols"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "lmao",
    meaning: "Riso intenso; abreviação de 'laughing my ass off', usada quando algo é muito engraçado",
    adultTranslation: "LMFAO / laughing my ass off / that's hilarious",
    context: "Versão mais forte de 'lol'. Usada para reações mais intensas a algo engraçado",
    category: "abreviação",
    riskLevel: "yellow",
    safeExample: "A cara dele caindo na escada, lmao",
    contextNotes: "Contém 'ass' na sigla original, mas adolescentes usam como reação casual sem pensar no significado literal",
    origin: "Internet / AIM, anos 90-2000",
    variations: ["lmfao"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  // =========================================================================
  // 3. Gaming (8 terms)
  // =========================================================================
  {
    term: "fortnite",
    meaning: "Referência ao jogo Fortnite Battle Royale; usado como referência cultural e meme entre jovens",
    adultTranslation: "Fortnite reference / gaming culture shorthand",
    context: "Usado para referenciar o jogo diretamente ou como metáfora de algo que é muito popular entre jovens",
    category: "games",
    riskLevel: "green",
    safeExample: "Tava jogando Fortnite ontem até tarde",
    contextNotes: "Um dos jogos mais influentes da cultura jovem atual. Danças e skins do jogo viraram referência cultural",
    origin: "Epic Games, lançado em 2017",
    variations: ["fort", "fn"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "valorant",
    meaning: "Referência ao jogo Valorant da Riot Games; usado como referência cultural e gíria gamer",
    adultTranslation: "Valorant reference / competitive shooter gaming culture",
    context: "Usado para falar do jogo ou como referência de cultura gamer competitiva no Brasil",
    category: "games",
    riskLevel: "green",
    safeExample: "Meu brother subiu de ranked no Valorant",
    contextNotes: "Jogo extremamente popular entre adolescentes brasileiros. Muita gíria nasceu da comunidade Valorant BR",
    origin: "Riot Games, lançado em 2020",
    variations: ["valo", "val"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "minecraft",
    meaning: "Referência ao jogo Minecraft; pode ser elogio (nostálgico) ou piada (jogo de criança)",
    adultTranslation: "Minecraft reference / nostalgia gaming",
    context: "Adolescentes têm relação ambígua com Minecraft: alguns jogam orgulhosamente, outros usam como piada",
    category: "games",
    riskLevel: "green",
    safeExample: "Hoje o mood é Minecraft e playlist lofi",
    contextNotes: "Jogo atravessa gerações. Voltou a ser trendy com vídeos de speedrun e memes",
    origin: "Mojang, lançado em 2011",
    variations: ["mine", "mc"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "vava",
    meaning: "Vovo/Vavá; gíria gamer para dizer que alguém está jogando mal, sendo fraco ou fazendo algo errado",
    adultTranslation: "Playing like a grandma / noob / weak play",
    context: "Usado em jogos para zoar quem está jogando mal. Comparação com vovô/vovó",
    category: "games",
    riskLevel: "yellow",
    safeExample: "Para de jogar igual vava, bora focar",
    contextNotes: "Gíria comum em comunidades de Valorant e Fortnite no Brasil. Pode ser interpretada como ageísmo leve",
    origin: "Comunidade gamer brasileira, 2022+",
    variations: ["vovó", "vô"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "apex",
    meaning: "Referência ao jogo Apex Legends; gíria gamer e referência cultural",
    adultTranslation: "Apex Legends reference / battle royale gaming culture",
    context: "Usado para falar do jogo ou como parte de conversas sobre games entre adolescentes",
    category: "games",
    riskLevel: "green",
    safeExample: "Aquele_movement do Apex é insano",
    contextNotes: "Jogo popular no Brasil pela sua mecânica de movimento (movement). Comunidade muito ativa",
    origin: "Respawn Entertainment / EA, lançado em 2019",
    variations: ["apex legends", "apexinho"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "roblox",
    meaning: "Referência à plataforma de jogos Roblox; pode ser elogio ou piada dependendo do contexto",
    adultTranslation: "Roblox reference / user-generated gaming platform",
    context: "Usado para falar de jogos na plataforma ou como piada entre adolescentes mais velhos",
    category: "games",
    riskLevel: "green",
    safeExample: "Meu irmão mais novo só fica no Roblox",
    contextNotes: "Divisão geracional: crianças e jovens jogam, adolescentes mais velhos às vezes zoam de quem joga",
    origin: "Roblox Corporation, lançado em 2006",
    variations: ["robloxiano"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "hitbox",
    meaning: "Área de colisão de um personagem no jogo; usado fora dos games para dizer que alguém acertou o alvo em algo",
    adultTranslation: "Hitbox / collision area / accuracy reference",
    context: "Dentro de jogos: área que registra acertos. Fora: forma de dizer que alguém foi preciso em algo",
    category: "games",
    riskLevel: "green",
    safeExample: "A hitbox desse personagem é absurda de grande",
    contextNotes: "Termo técnico que virou gíria. Muito comum em discussões sobre balanceamento de jogos",
    origin: "Gaming terminology, anos 2000+",
    variations: ["hitboxada", "hitboxar"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "hitmarker",
    meaning: "Indicador visual de acerto em jogos de tiro; som/marca que aparece quando você acerta um tiro",
    adultTranslation: "Hitmarker / visual hit indicator in shooter games",
    context: "Usado para celebrar acertos precisos ou como referência cômica de jogos FPS",
    category: "games",
    riskLevel: "green",
    safeExample: "Aquele hitmarker na cabeça foi satisfatório demais",
    contextNotes: "O som de hitmarker virou meme. Geralmente acompanhado de 'pew pew' de forma cômica",
    origin: "FPS gaming culture, popularizado pelo Call of Duty",
    variations: ["headshot marker"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  // =========================================================================
  // 4. More Gaming Terms (7 terms)
  // =========================================================================
  {
    term: "lootar",
    meaning: "Coletar itens/espólio em um jogo; saquear recursos ou equipamentos",
    adultTranslation: "To loot / scavenge for items and resources in games",
    context: "Verbalização brasileira de 'loot'. Usado em jogos de battle royale e RPG",
    category: "games",
    riskLevel: "green",
    safeExample: "Vem lootar essa área comigo que tem arma boa",
    contextNotes: "Adaptação brasileira do inglês 'loot' com sufixo '-ar'. Muito natural na fala gamer",
    origin: "Anglicismo adaptado pela comunidade gamer BR",
    variations: ["loot", "lootagem"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "xp",
    meaning: "Experiência ou pontos ganhos; pode ser usado literalmente em jogos ou metaforicamente para aprender algo",
    adultTranslation: "XP / experience points / leveling up in real life",
    context: "Dentro de jogos: pontos de experiência. Fora: usado como 'ganhar experiência de vida'",
    category: "games",
    riskLevel: "green",
    safeExample: "Levar um fora é xp de vida",
    contextNotes: "Migração do termo de jogos para a vida real. Muito usado em contexto de autoajuda irônica entre adolescentes",
    origin: "RPG gaming terminology",
    variations: ["exp"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "level up",
    meaning: "Evoluir, melhorar, subir de nível; usado para descrever progresso pessoal ou em jogos",
    adultTranslation: "Level up / improve / upgrade yourself",
    context: "Pode ser usado literalmente em jogos ou metaforicamente para crescimento pessoal",
    category: "games",
    riskLevel: "green",
    safeExample: "Depois da academia, to level up",
    contextNotes: "Outro termo de games que migrou para a vida real. Muito comum em contexto de evolução pessoal",
    origin: "RPG/gaming terminology",
    variations: ["levelou", "lvl up"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "game over",
    meaning: "Fim de jogo; usado metaforicamente para dizer que algo acabou ou que alguém perdeu definitivamente",
    adultTranslation: "Game over / it's done / you lost",
    context: "Usado fora dos jogos quando alguém falha ou quando uma situação acaba",
    category: "games",
    riskLevel: "green",
    safeExample: "Esqueci a mochala... game over pra mim",
    contextNotes: "Expressão universal que atravessa gerações. Usado de forma dramática e cômica",
    origin: "Gaming, universal",
    variations: ["game overzado"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "respawn",
    meaning: "Renascer em um jogo; usado metaforicamente para quando alguém volta a agir depois de um erro",
    adultTranslation: "Respawn / come back / regenerate after a failure",
    context: "Em jogos: reaparecer após morrer. Na vida: voltar à ativa depois de um fracasso",
    category: "games",
    riskLevel: "green",
    safeExample: "Depois daquele erro, respawn e tentou de novo",
    contextNotes: "Metáfora gamer para resiliência. Muito usado de forma positiva",
    origin: "Gaming terminology, multiplayer games",
    variations: ["respawnar", "respawnou"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "gg go next",
    meaning: "Boa partida, vamos para a próxima; atitude de seguir em frente após uma derrota",
    adultTranslation: "Good game, let's move on / shake it off and keep going",
    context: "Usado em jogos e na vida real como mantra de resiliência após derrota",
    category: "games",
    riskLevel: "green",
    safeExample: "Reprovou? GG go next, estuda mais na próxima",
    contextNotes: "Muito mais que um termo gamer - virou filosofia de vida entre jovens. Encoraja seguir em frente",
    origin: "Competitive gaming / esports culture",
    variations: ["gg wp go next", "go next"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "call of duty",
    meaning: "Referência à franquia de jogos Call of Duty; usado culturalmente como sinônimo de jogos de tiro realistas",
    adultTranslation: "Call of Duty reference / military shooter gaming culture",
    context: "Pode ser usado para falar do jogo ou como referência a cultura FPS/guerra",
    category: "games",
    riskLevel: "green",
    safeExample: "Meu tio só joga Call of Duty desde 2009",
    contextNotes: "Franquia icônica que atravessa gerações. Adolescentes conhecem mesmo que não joguem",
    origin: "Activision, primeiro jogo em 2003",
    variations: ["cod", "co_d"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  // =========================================================================
  // 5. Internet Abbreviations (7 terms)
  // =========================================================================
  {
    term: "irl",
    meaning: "Na vida real; usado para distinguir interações online do mundo real",
    adultTranslation: "In real life / offline / face to face",
    context: "Usado quando algo acontece fora da internet ou para confirmar que algo é verdade na vida real",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vimos esse meme tanto que já acontece irl",
    contextNotes: "Uma das abreviações mais antigas e ainda essenciais. Usado em qualquer plataforma",
    origin: "Internet / IRC, anos 90",
    variations: ["in real life"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "afk",
    meaning: "Longe do teclado; usado para avisar que alguém vai ficar ausente temporariamente",
    adultTranslation: "Away from keyboard / stepping away temporarily",
    context: "Usado em jogos e grupos de mensagem quando alguém precisa se ausentar",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Vou comer, afk 10 minutos",
    contextNotes: "Abreviação clássica de jogos online. Ainda muito usada em grupos de WhatsApp e Discord",
    origin: "Gaming / IRC, anos 90",
    variations: [],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "ttyl",
    meaning: "Até mais tarde; abreviação para encerrar uma conversa online temporariamente",
    adultTranslation: "Talk to you later / see you later",
    context: "Usado no fim de conversas para dizer que vai falar depois",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Tenho que ir, ttyl",
    contextNotes: "Abreviação clássica que continua sendo usada em mensagens de texto entre adolescentes",
    origin: "Internet / SMS culture, anos 90-2000",
    variations: ["talk to you later"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "brb",
    meaning: "Volto já; abreviação para avisar ausência breve",
    adultTranslation: "Be right back / I'll be back in a sec",
    context: "Usado em conversas online para dizer que vai voltar rapidamente",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "BRB, to pegando água",
    contextNotes: "Abreviação universal e atemporal. Usado em jogos, WhatsApp, Discord, etc",
    origin: "Internet / IRC / SMS, anos 90",
    variations: ["be right back"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "thx",
    meaning: "Obrigado; forma abreviada de 'thanks'",
    adultTranslation: "Thanks / thank you (abbreviated)",
    context: "Usado para agradecer de forma rápida em mensagens e jogos",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Valeu pela carona, thx",
    contextNotes: "Forma rápida e casual de agradecer. Mais comum em jogos e mensagens rápidas",
    origin: "Internet / SMS culture",
    variations: ["thanks"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "omg",
    meaning: "Meu Deus; expressão de surpresa, choque ou espanto (abreviação de 'oh my god')",
    adultTranslation: "Oh my god / OMG / expression of shock or surprise",
    context: "Usado para reagir a algo surpreendente, bom ou ruim",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "OMG, não acredito que passou na prova",
    contextNotes: "Uma das abreviações mais universais da internet. Usado por todas as idades, mas especialmente por adolescentes",
    origin: "Internet / SMS culture, anos 90",
    variations: ["oh my god", "oh my gosh"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "smh",
    meaning: "Balancando a cabeça; expressão de desaprovação ou decepção (abreviação de 'shaking my head')",
    adultTranslation: "SMH / shaking my head / disappointed disapproval",
    context: "Usado para demonstrar decepção, incredulidade ou julgamento silencioso",
    category: "abreviação",
    riskLevel: "green",
    safeExample: "Ele mandou mensagem pra ex de novo... smh",
    contextNotes: "Sempre acompanhado de um tom de julgamento. Muito usado em comentários e stories",
    origin: "Internet / Twitter culture, 2010+",
    variations: ["shaking my head"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  // =========================================================================
  // 6. Regional Slang (5 terms)
  // =========================================================================
  {
    term: "oxente",
    meaning: "Expressão de surpresa típica do Nordeste, especialmente Bahia; equivalente a 'eita' ou 'nossa'",
    adultTranslation: "Oh my / well well well / expression of surprise",
    context: "Usado por nordestinos e popularizado nacionalmente. Expressa espanto, alegria ou surpresa",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Oxente, que Surpresa te ver aqui!",
    contextNotes: "Termo nordestino que virou patrimônio cultural. Muito usado em memes e conteúdo humorístico",
    origin: "Bahia / Nordeste brasileiro",
    variations: ["oxi", "oxente mesmo"],
    popularityStatus: "ativo",
    region: "Bahia"
  },
  {
    term: "ehh tchê",
    meaning: "Expressão gaúcha de ênfase, surpresa ou acordo; marca da identidade cultural do Rio Grande do Sul",
    adultTranslation: "Hey there / well well / expression of emphasis (gaucho style)",
    context: "Usado no final de frases ou como interjeição. Marca registrada do gaúcho",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Ehh tchê, hoje o dia tá bonito pra churras",
    contextNotes: "Tão característico que virou meme nacional. Gaúchos usam naturalmente, outros usam de forma cômica",
    origin: "Rio Grande do Sul / cultura gaúcha",
    variations: ["tchê", "bah tchê"],
    popularityStatus: "ativo",
    region: "Rio Grande do Sul"
  },
  {
    term: "ué",
    meaning: "Expressão paulista de espanto, indignação ou questionamento; equivalente a 'como assim?'",
    adultTranslation: "Wait what? / well excuse me / expression of bewilderment",
    context: "Usado quando algo inesperado acontece ou quando alguém discorda",
    category: "saudacao",
    riskLevel: "green",
    safeExample: "Ué, eu não disse pra trazer o livro?",
    contextNotes: "Palavra curta mas carregada de significado. Pode ser amigável ou indiciativo dependendo do tom",
    origin: "São Paulo / Sudeste brasileiro",
    variations: ["ué poxa", "ué mano"],
    popularityStatus: "ativo",
    region: "São Paulo"
  },
  // =========================================================================
  // 7. Random Teen Expressions (8 terms)
  // =========================================================================
  {
    term: "deus do céu",
    meaning: "Expressão de desespero, surpresa ou exasperação; usada quando algo é muito intenso",
    adultTranslation: "Oh my god / good heavens / expression of despair or shock",
    context: "Usado de forma dramática e cômica, geralmente com tom exagerado de sofrimento",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Deus do céu, mais uma prova surpresa",
    contextNotes: "Expressão dramática que adolescentes usam com humor exagerado. Funciona como meme",
    origin: "Expressão popular brasileira",
    variations: ["deus do céu meu", "meu deus do céu"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "já era",
    meaning: "Já acabou, já deu; expressão de que algo está perdido ou terminou",
    adultTranslation: "It's already over / no chance / that's done",
    context: "Usado quando uma situação está irremediavelmente perdida ou quando algo acabou",
    category: "expressão",
    riskLevel: "green",
    safeExample: "O prazo passou, já era",
    contextNotes: "Expressão muito natural e cotidiana. Pode ser usada de forma séria ou cômica",
    origin: "Expressão popular brasileira, ganhou força com internet",
    variations: ["ja era mano", "ja era geração"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "nem vem",
    meaning: "Não tenta nem / desista; expressão de rejeição ou aviso de que algo não vai funcionar",
    adultTranslation: "Don't even try / not happening / back off",
    context: "Usado para impedir que alguém tente algo ou para negar categoricamente",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Quer copiar minha resposta? Nem vem",
    contextNotes: "Expressão muito comum entre adolescentes. Tem tom firme mas pode ser amigável",
    origin: "Gíria popular brasileira",
    variations: ["nem vem cumpadi"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "caraio",
    meaning: "Expressão de ênfase, surpresa ou irritação; variante suave de uma palavra de baixo calão",
    adultTranslation: "Damn / holy crap / expression of emphasis or surprise",
    context: "Usado como intensificador. Equivale a 'caralho' mas é versão mais leve e socialmente aceitável",
    category: "expressão",
    riskLevel: "yellow",
    safeExample: "Caraio, que calor absurdo",
    contextNotes: "Versão 'civilizada' de um palavrão. Adolescentes usam como alternativa aceitável em qualquer ambiente",
    origin: "Adaptação popular de palavrão brasileiro",
    variations: ["carai", "caramba"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  // =========================================================================
  // 8. Body/Looks (4 terms)
  // =========================================================================
  {
    term: "tá liso",
    meaning: "Estar careca; piada sobre calvície usada de forma cômica entre amigos",
    adultTranslation: "Going bald / shiny head / bald joke",
    context: "Piada sobre calvície, geralmente entre amigos homens. Pode ser sensível para quem está perdendo cabelo",
    category: "zoeira",
    riskLevel: "yellow",
    safeExample: "Meu irmão tá liso aos 20, já era a cabeleira",
    contextNotes: "Piada comum entre adolescentes masculinos. Pode machucar dependendo de quem recebe, apesar de ser 'zoeira'",
    origin: "Gíria popular brasileira",
    variations: ["ficou liso", "liso mesmo"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "pedrada",
    meaning: "Algo muito feio, ruim ou de qualidade péssima; também pode ser soco/pedrada literal",
    adultTranslation: "Ugly as hell / terrible looking / can also mean a punch",
    context: "Usado para descrever algo muito feio ou ruim. Contexto duplo: aparência ou qualidade",
    category: "zoeira",
    riskLevel: "yellow",
    safeExample: "Esse corte de cabelo ficou pedrada",
    contextNotes: "Pode ser ofensivo se dirigido a alguém diretamente. Normalmente usado para coisas ou em zoeira entre amigos",
    origin: "Gíria popular brasileira",
    variations: ["pedrado", "parece pedrada"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "disgrama",
    meaning: "Pessoa com dislexia; usado como piada sobre dificuldade de leitura ou escrita",
    adultTranslation: "Dyslexic person / someone who struggles with reading/spelling",
    context: "Pode ser usado de forma preconceituosa ou como piada sobre erros de digitação e leitura",
    category: "zoeira",
    riskLevel: "orange",
    safeExample: "Errei todas as palavras do ditado, sou disgrama",
    contextNotes: "ATENÇÃO: Este termo pode ser ofensivo e preconceituoso. Refere-se a uma condição real (dislexia). Uso como piada desrespeita pessoas com dislexia",
    origin: "Gíria popular, combinação de 'disléxico' + 'grama'",
    variations: ["disgrâmico"],
    popularityStatus: "em_queda",
    region: "Nacional"
  },
  {
    term: "four eyes",
    meaning: "Quatro olhos; apelido preconceituoso para quem usa óculos",
    adultTranslation: "Four eyes / glasses-wearer (mocking nickname)",
    context: "Apelido usado para quem usa óculos. Geralmente entre crianças e adolescentes, pode ser ofensivo",
    category: "zoeira",
    riskLevel: "orange",
    safeExample: "Me chamaram de four eyes por causa do óculos novo",
    contextNotes: "Bullying clássico em escolas. Com óculos se tornando acessório de moda, o termo perdeu força mas ainda existe",
    origin: "Expressão inglesa adaptada ao português, bullying clássico",
    variations: ["four-eyes", "quatro olhos"],
    popularityStatus: "em_queda",
    region: "Internacional"
  },
  // =========================================================================
  // 9. Fashion/Brands (6 terms)
  // =========================================================================
  {
    term: "balenciaga",
    meaning: "Marca de luxo que virou meme; usada como referência de ostentação ou como piada sobre moda absurda",
    adultTranslation: "Balenciaga / luxury fashion brand turned meme / absurdly expensive fashion",
    context: "Referência à marca de moda de luxo. Pode ser elogio (ostentação) ou piada (designs estranhos)",
    category: "moda",
    riskLevel: "green",
    safeExample: "Essa mochila custou quanto? Tá achando que é Balenciaga?",
    contextNotes: "Balenciaga virou meme por seus designs absurdos e preços exorbitantes. Adolescentes usam como referência de ostentação",
    origin: "Marca Balenciaga / cultura de memes de moda",
    variations: ["balen"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "nike",
    meaning: "Marca de esportes e streetwear; referência cultural de tênis e moda esportiva entre jovens",
    adultTranslation: "Nike / sneaker culture reference / sportswear brand",
    context: "Usado para falar de tênis, roupa esportiva ou como referência de status na cultura sneakerhead",
    category: "moda",
    riskLevel: "green",
    safeExample: "Comprei um Nike novo, ficou muito top",
    contextNotes: "Marca onipresente na cultura jovem. Certos modelos (Air Force, Dunk, Jordan) são símbolos de status",
    origin: "Nike Inc. / cultura sneakerhead global",
    variations: ["swoosh", "nikita"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "jordan",
    meaning: "Referência aos tênis Air Jordan da Nike; símbolo de status e cultura streetwear",
    adultTranslation: "Air Jordans / status sneakers / basketball shoe culture",
    context: "Tênis Jordan são objetos de desejo. Ter um Jordan é símbolo de status entre adolescentes",
    category: "moda",
    riskLevel: "green",
    safeExample: "Consegui um Jordan do desconto, tá voando",
    contextNotes: "Jordan transcendeu o basquete e virou ícone cultural. Diferentes modelos têm valores simbólicos diferentes",
    origin: "Nike / Michael Jordan, linha criada em 1985",
    variations: ["aj", "air jordan", "jordans"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "crocs",
    meaning: "Sapato Crocs; pode ser elogiado (confortável) ou zoado (feio) dependendo do contexto",
    adultTranslation: "Crocs footwear / polarizing fashion item / love it or hate it shoes",
    context: "Crocs divide opiniões: uns amam o conforto, outros zoam a aparência. Com Jibbitz virou fashion",
    category: "moda",
    riskLevel: "green",
    safeExample: "Crocs com meia, o melhor dos mundos",
    contextNotes: "Crocs saiu de 'sapato feio' para item de moda. Adolescentes misturam com meias, Jibbitz, etc",
    origin: "Crocs Inc., lançado em 2002",
    variations: ["crocsinho"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "chinelão",
    meaning: "Chinelo grande e confortável; geralmente Havaianas. Usado como referência de conforto e estar em casa",
    adultTranslation: "Flip flops / comfortable slides / home chill vibes",
    context: "Usado para descrever chinelo favorito ou estado de relaxamento total (estar de chinelão em casa)",
    category: "moda",
    riskLevel: "green",
    safeExample: "Final de semana é pra ficar de chinelão no sofá",
    contextNotes: "Chinelão é quase patrimônio cultural brasileiro. Havaianas são o símbolo máximo",
    origin: "Cultura popular brasileira",
    variations: ["chinelão da Havaianas"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  // =========================================================================
  // 10. Transport/Places (5 terms)
  // =========================================================================
  {
    term: "99",
    meaning: "Referência ao aplicativo de transporte 99; usado como sinônimo de chamar carro ou ir a algum lugar de app",
    adultTranslation: "99 ride app / getting an Uber-like ride",
    context: "No Brasil, '99' e 'Uber' são usados como verbos: 'vamos chamar um 99'",
    category: "lugar",
    riskLevel: "green",
    safeExample: "Chama o 99 que a gente tá atrasado",
    contextNotes: "Junto com Uber, transformou a forma como adolescentes se locomovem. Muitos nem sabem pegar ônibus",
    origin: "App 99 (ex-99Taxis), brasileiro, fundado em 2012",
    variations: ["99app"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "shopping",
    meaning: "Centro comercial; referência a lugar de encontro social para adolescentes",
    adultTranslation: "Shopping mall / mall / social hangout spot",
    context: "Shopping é o principal ponto de encontro de adolescentes. Ir ao shopping é evento social, não só compras",
    category: "lugar",
    riskLevel: "green",
    safeExample: "Encontramos no shopping sábado pra comer e passear",
    contextNotes: "Shopping funciona como 'praça' moderna para adolescentes. Ponto de encontro, comida, cinema, lojas",
    origin: "Cultura urbana brasileira",
    variations: ["shopp", "mall"],
    popularityStatus: "ativo",
    region: "Nacional"
  },
  {
    term: "uber",
    meaning: "Referência ao app de transporte Uber; usado como verbo para pedir transporte por aplicativo",
    adultTranslation: "Uber ride / getting a ride-hailing car",
    context: "Usado como verbo ('chamar o Uber') ou referência ao transporte. Transformou a mobilidade urbana juvenil",
    category: "lugar",
    riskLevel: "green",
    safeExample: "Pede um Uber pra gente ir pro shopping",
    contextNotes: "Uber e 99 são praticamente sinônimos de 'carro' para adolescentes de classe média urbana",
    origin: "Uber Technologies, lançado em 2009",
    variations: ["ubizinho"],
    popularityStatus: "ativo",
    region: "Internacional"
  },
  {
    term: "praça",
    meaning: "Praça pública; ponto de encontro gratuito para adolescentes que não querem gastar",
    adultTranslation: "Public square / park / free hangout spot",
    context: "Praça é alternativa ao shopping para quem não tem dinheiro. Local de encontro, skatismo, pique",
    category: "lugar",
    riskLevel: "green",
    safeExample: "Bora pra praça jogar bola?",
    contextNotes: "Espaço democrático de convivência. Praça é cena de esportes, encontros, paquera e cultura urbana",
    origin: "Cultura urbana brasileira",
    variations: ["praçinha", "praça do bairro"],
    popularityStatus: "ativo",
    region: "Nacional"
  }
];
