import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_8: SlangTerm[] = [
  // ── Dating / Relacionamentos (50 terms) ──
  {
    term: "red flag",
    meaning: "Sinal de alerta em um relacionamento; comportamento preocupante.",
    adultTranslation: "Sinal de alerta; alguém com comportamento tóxico ou perigoso.",
    context: "Quando alguém nota algo estranho ou ruim sobre a pessoa com quem está saindo.",
    category: "alerta_emocional",
    riskLevel: "yellow",
    safeExample: "Ele falou mal de todos os ex, enorme red flag.",
    contextNotes: "Importante sinalizar comportamentos abusivos ou manipuladores.",
    origin: "Cultura pop e redes sociais ocidentais, popularizado no TikTok.",
    variations: ["bandeira vermelha", "sinal vermelho"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "green flag",
    meaning: "Sinal positivo em um relacionamento; comportamento saudável.",
    adultTranslation: "Alguém com atitudes boas e saudáveis em um relacionamento.",
    context: "Quando alguém percebe qualidades positivas em um pretendente.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "Ele respeita meus limites, total green flag.",
    contextNotes: "Usado para valorizar atitudes saudáveis e maduras.",
    origin: "TikTok e Twitter, como contraposição ao red flag.",
    variations: ["bandeira verde", "sinal verde"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "beige flag",
    meaning: "Sinal de mediocridade; algo sem graça mas não necessariamente ruim.",
    adultTranslation: "Pessoa ou comportamento sem graça, sem brilho, mediano.",
    context: "Quando alguém nota algo chato ou sem graça em uma pessoa.",
    category: "ironia",
    riskLevel: "green",
    safeExample: "Ele só assiste Netflix e não tem opinião sobre nada, beige flag.",
    contextNotes: "Mais leve que red flag, indica falta de personalidade.",
    origin: "TikTok, expansão da metáfora das bandeiras de relacionamento.",
    variations: ["bandeira bege", "medíocre"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ick",
    meaning: "Sensação repentina de nojo ou desinteresse por alguém.",
    adultTranslation: "Algo que a pessoa faz que te afasta instantaneamente, te dá nojo.",
    context: "Quando algo específico faz alguém perder totalmente o interesse em outra pessoa.",
    category: "flerte",
    riskLevel: "yellow",
    safeExample: "Ele riu com a boca aberta e eu senti o ick mais rápido da minha vida.",
    contextNotes: "Pode ser sobre algo banal, mas o sentimento é genuíno e intenso.",
    origin: "Cultura anglo-saxônica, popularizado por programas como Love Island.",
    variations: ["ick moment", "the ick"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "love bombing",
    meaning: "Estratégia manipuladora de demonstrar afeto excessivo no início do relacionamento.",
    adultTranslation: "Bombardeio de amor; encher alguém de atenção e mimos para controlar.",
    context: "Quando alguém é excessivamente carinhoso logo no início, antes de mostrar comportamento controlador.",
    category: "alerta_emocional",
    riskLevel: "red",
    safeExample: "Nos primeiros dias mandou 50 mensagens e mil flores, era love bombing.",
    contextNotes: "Comportamento tóxico e perigoso, frequentemente associado a narcisistas.",
    origin: "Psicologia popular, ganhou força nas redes sociais.",
    variations: ["bombardeio de amor", "lovebomb"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ghosting",
    meaning: "Sumir de repente sem explicação, cortar contato abruptamente.",
    adultTranslation: "Desaparecer sem dar satisfação; ignorar totalmente a pessoa.",
    context: "Quando alguém para de responder mensagens e some sem explicação.",
    category: "provocacao",
    riskLevel: "orange",
    safeExample: "Saímos três vezes e depois ele me deu ghosting.",
    contextNotes: "Causa frustração e confusão em quem é alvo.",
    origin: "Cultura de relacionamentos online, popularizado na década de 2010.",
    variations: ["dar bolo virtual", "sumir do mapa", "dar ghost"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "breadcrumbing",
    meaning: "Dar pequenos sinais de interesse para manter a pessoa engajada, sem compromisso.",
    adultTranslation: "Soltar migalhas; manter alguém interessado com o mínimo de esforço.",
    context: "Quando alguém manda mensagens esporádicas só para manter a outra pessoa por perto.",
    category: "ironia",
    riskLevel: "orange",
    safeExample: "Ele manda um story por mês, é puré breadcrumbing.",
    contextNotes: "Forma sutil de manipulação emocional.",
    origin: "Termo em inglês popularizado em blogs de relacionamento.",
    variations: ["dar migalhas", "migalhas"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "situationship",
    meaning: "Relação que não é oficial, mas tem características de namoro.",
    adultTranslation: "Ficante com exclusividade não declarada; algo entre amizade e namoro.",
    context: "Quando duas pessoas ficam juntas como namorados mas sem formalizar.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "A gente tá há um ano junto, mas tá tudo no situationship.",
    contextNotes: "Muito comum na gen Z, reflete resistência a rótulos.",
    origin: "Cultura juvenil americana, viralizou no TikTok.",
    variations: ["situation", "ficância"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "talking stage",
    meaning: "Fase de conversas antes de algo oficializar; período de conhecimento.",
    adultTranslation: "Fase de conversa; quando dois estão se conhecendo antes de qualquer compromisso.",
    context: "Quando duas pessoas estão trocando mensagens e se conhecendo, antes de ficar.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "A gente tá no talking stage, ainda conversando pra ver se rola.",
    contextNotes: "Fase crucial onde se define se há interesse mútuo.",
    origin: "Cultura de namoro online nos EUA.",
    variations: ["fase das conversas", "pré-ficante"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "orbitar",
    meaning: "Ficar de olho nas redes sociais de um ex sem interagir diretamente.",
    adultTranslation: "Vigiar as redes sociais de alguém sem dar Like ou comentar.",
    context: "Quando alguém vê stories e posts de um ex constantemente sem interagir.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Ele não manda mensagem, mas orbita todos os meus stories.",
    contextNotes: "Comum após término, mistura de curiosidade e saudade.",
    origin: "Cultura digital contemporânea.",
    variations: ["orbiting", "orbitador"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "hard launch",
    meaning: "Apresentar publicamente um relacionamento de forma oficial nas redes sociais.",
    adultTranslation: "Lançar o namoro com foto oficial nas redes, sem papinho.",
    context: "Quando alguém posta foto do casal declarando o relacionamento.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Fiz o hard launch com ele no Instagram, foto de casal e tudo.",
    contextNotes: "Marcante e definidor em um relacionamento moderno.",
    origin: "Cultura de influenciadores e redes sociais.",
    variations: ["lançamento oficial", "declarar nas redes"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "soft launch",
    meaning: "Dar indiretas sutis sobre um relacionamento sem se declarar oficialmente.",
    adultTranslation: "Soltar pistas sobre estar namorando, sem postar foto de casal.",
    context: "Quando alguém posta uma mão, uma sombra, ou detalhes que sugerem namoro.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Ela postou a mão dele no story, foi um soft launch.",
    contextNotes: "Estratégia comum para testar reações antes de se assumir.",
    origin: "Cultura de influenciadores de redes sociais.",
    variations: ["lançamento sutil", "indireta de namoro"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cuffing season",
    meaning: "Época do ano (inverno) em que as pessoas buscam relacionamentos por solidão.",
    adultTranslation: "Tempo de prender; época em que as pessoas querem alguém pra ficar em casa.",
    context: "Nos meses mais frios, quando as pessoas buscam companhia para não ficarem sozinhas.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "É cuffing season, tá na hora de arrumar alguém pra assistir série.",
    contextNotes: "Mais comum em lugares com inverno rigoroso, adaptado ao Brasil.",
    origin: "Cultura afro-americana e redes sociais americanas.",
    variations: ["temporada de casar", "época do cuffing"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "roaching",
    meaning: "Estar saindo com várias pessoas ao mesmo tempo sem que saibam umas das outras.",
    adultTranslation: "Ficar com várias pessoas escondido, como baratas que se multiplicam.",
    context: "Quando alguém descobre que seu pretendente está saindo com outras pessoas.",
    category: "alerta_emocional",
    riskLevel: "orange",
    safeExample: "Descobri que ele tava saindo com mais três, puro roaching.",
    contextNotes: "Metáfora com baratas que se escondem e se multiplicam.",
    origin: "Termo de dating apps e blogs de relacionamento.",
    variations: ["cafetão emocional", "ficante múltiplo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "benching",
    meaning: "Manter alguém no banco de reservas; deixar como opção sem compromisso.",
    adultTranslation: "Deixar alguém na reserva; dar atenção só quando convém.",
    context: "Quando alguém não investe mas também não descarta completamente a pessoa.",
    category: "ironia",
    riskLevel: "yellow",
    safeExample: "Ela sempre manda mensagem quando tá sem nada, tá me fazendo benching.",
    contextNotes: "Como no esporte, o jogador fica no banco e só entra quando precisa.",
    origin: "Analogia esportiva adaptada para relacionamentos.",
    variations: ["banco de reservas", "reserva afetiva"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pocketing",
    meaning: "Esconder o parceiro de amigos e família, não apresentar a ninguém.",
    adultTranslation: "Esconder o relacionamento; manter a pessoa no bolso, longe de todos.",
    context: "Quando alguém namora ou fica mas nunca apresenta a pessoa ao seu círculo social.",
    category: "alerta_emocional",
    riskLevel: "orange",
    safeExample: "Ficamos seis meses juntos e ele nunca me apresentou aos amigos, era pocketing.",
    contextNotes: "Pode indicar falta de compromisso ou que a pessoa está escondendo algo.",
    origin: "Termo de cultura de relacionamentos digitais.",
    variations: ["esconder o relacionamento", "manter no bolso"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "crush",
    meaning: "Pessoa por quem se tem uma paixão intensa, geralmente em segredo.",
    adultTranslation: "Paixão platônica; pessoa que você acha incrível e não consegue parar de pensar.",
    context: "Quando alguém gostar muito de outra pessoa e ficar shy por perto.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Meu crush passou por mim no corredor e eu quase morri.",
    contextNotes: "Sentimento intenso e comum na adolescência, mas também em adultos.",
    origin: "Cultura pop americana, massificado por filmes e séries.",
    variations: ["paixão", "ansonite"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "paixonite",
    meaning: "Paixão repentina, intensa e passageira, como uma doença temporária.",
    adultTranslation: "Enamoramento rápido e forte que passa rápido; crush temporário.",
    context: "Quando alguém se apaixona perdidamente por alguém em poucos dias e depois esquece.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Achei que era amor, mas era só paixonite de fim de semana.",
    contextNotes: "Combinação de paixão + amigdalite, algo que vem e vai.",
    origin: "Neologismo brasileiro criado na internet.",
    variations: ["paixonite passageira", "crush temporário"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ficante",
    meaning: "Pessoa com quem se fica sem compromisso formal de namoro.",
    adultTranslation: "Parceiro(a) casual; alguém com quem se tem intimidade sem rótulo.",
    context: "Quando duas pessoas ficam juntas mas não são namorados oficiais.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "A gente é ficante há dois meses, nada oficial.",
    contextNotes: "Termo muito usado por jovens brasileiros desde os anos 2000.",
    origin: "Cultura jovem brasileira, derivação de 'ficar'.",
    variations: ["ficância", "ficagem"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dar bola",
    meaning: "Demonstrar interesse por alguém; prestar atenção às investidas de alguém.",
    adultTranslation: "Dar atenção a alguém que está flertando; demonstrar interesse.",
    context: "Quando alguém está sendo flertado e retribui a atenção.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Tentei flertar com ela, mas não deu bola nenhuma.",
    contextNotes: "Expressão clássica do português brasileiro, muito antiga.",
    origin: "Gíria brasileira tradicional, possivelmente ligada ao futebol.",
    variations: ["dar atenção", "retribuir"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ficar com",
    meaning: "Beijar ou ter intimidade casual com alguém, sem compromisso.",
    adultTranslation: "Beijar alguém sem formalizar relacionamento; pegar, transar casualmente.",
    context: "Em festas, baladas ou encontros casuais.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Fiquei com ele na festa ontem, foi muito legal.",
    contextNotes: "Um dos termos mais usados entre jovens brasileiros.",
    origin: "Cultura jovem brasileira das décadas de 90 e 2000.",
    variations: ["ficar", "dar uns amassos"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pombinha",
    meaning: "Ajudar alguém a conquistar outra pessoa, atuar como cupido.",
    adultTranslation: "Facilitar um flerte; intermediar um encontro entre duas pessoas.",
    context: "Quando um amigo ajuda outro a chegar em alguém que gosta.",
    category: "zoeira",
    riskLevel: "green",
    safeExample: "O João foi minha pombinha e apresentou a gente.",
    contextNotes: "Antigamente associado a casamenteiros, hoje é entre amigos.",
    origin: "Cultura popular brasileira, metáfora com o pombo mensageiro.",
    variations: ["cupido", "pombo-correio"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "namorico",
    meaning: "Namoro casual ou temporário; relacionamento leve e sem formalidade.",
    adultTranslation: "Ficar periodicamente com a mesma pessoa sem ser namorado(a) oficial.",
    context: "Quando duas pessoas têm um envolvimento que parece namoro mas não é formal.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "A gente tem um namorico, todo fim de semana a gente sai junto.",
    contextNotes: "Mais comprometido que ficante, menos que namoro.",
    origin: "Expressão popular brasileira antiga.",
    variations: ["ficante fixo", "namoro informal"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "cair para",
    meaning: "Se apaixonar perdidamente por alguém, se encantar completamente.",
    adultTranslation: "Perder a cabeça por alguém; se apaixonar de repente.",
    context: "Quando alguém percebe que está se apaixonando por alguém que antes era só amigo.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Comecei a conversar com ele e cai pra ele duro.",
    contextNotes: "O termo 'cair' indica perda de controle emocional involuntária.",
    origin: "Cultura popular brasileira, antigo mas ainda muito usado.",
    variations: ["cair de amores", "se entregar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "match",
    meaning: "Dois perfis que combinaram interesse mútuo em um app de relacionamento.",
    adultTranslation: "Interesse mútuo em app de namoro; ambos deram like um no outro.",
    context: "Quando dois usuários de Tinder ou similar têm interesse recíproco.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Deu match com ela no Tinder, agora é conversar.",
    contextNotes: "Momento emocionante do uso de apps de relacionamento.",
    origin: "Aplicativos de relacionamento tipo Tinder.",
    variations: ["dar match", "combinação"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tinder",
    meaning: "Referência ao app de relacionamentos; sinônimo de buscar encontros online.",
    adultTranslation: "Usar app de namoro para conhecer pessoas; procurar parceiros online.",
    context: "Quando alguém está usando apps de relacionamento para conhecer gente.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "To no tinder de novo, vamos ver se acho alguém legal.",
    contextNotes: "Tornou-se sinônimo genérico para qualquer app de namoro.",
    origin: "Aplicativo Tinder, lançado em 2012.",
    variations: ["tinderar", "app de namoro"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bumble",
    meaning: "App de namoro onde as mulheres iniciam a conversa; dinâmica invertida.",
    adultTranslation: "App onde a mulher manda mensagem primeiro; namoro com iniciativa feminina.",
    context: "Quando mulheres preferem apps onde elas têm o controle da primeira abordagem.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Prefiro o Bumble porque eu que escolho quem mandar mensagem.",
    contextNotes: "Popular entre mulheres que querem mais controle nas interações.",
    origin: "App Bumble, criado por ex-fundadora do Tinder em 2014.",
    variations: ["bumblar", "app da mulher"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dar chance",
    meaning: "Aceitar sair com alguém ou dar oportunidade a um pretendente.",
    adultTranslation: "Aceitar um encontro; permitir que alguém tente conquistá-lo(a).",
    context: "Quando alguém decide dar uma oportunidade a quem está demonstrando interesse.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Ele insistiu tanto que resolvi dar uma chance.",
    contextNotes: "Pode indicar relutância inicial que se transforma em interesse.",
    origin: "Expressão comum do português brasileiro.",
    variations: ["dar uma chance", "dar oportunidade"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "recusar",
    meaning: "Rejeitar uma investida ou pedido de namoro de alguém.",
    adultTranslation: "Dizer não a um convite romântico; não aceitar as investidas.",
    context: "Quando alguém não quer sair ou ficar com um pretendente.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Ela me pediu em namoro mas eu tive que recusar.",
    contextNotes: "Parte natural dos relacionamentos; é importante saber recusar com respeito.",
    origin: "Vocabulário comum da língua portuguesa.",
    variations: ["negar", "dar o cano"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ex",
    meaning: "Pessoa com quem se teve relacionamento no passado.",
    adultTranslation: "Ex-namorado(a) ou ex-parceiro(a); pessoa do passado amoroso.",
    context: "Ao falar sobre relacionamentos anteriores.",
    category: "expressão",
    riskLevel: "yellow",
    safeExample: "Meu ex me mandou mensagem hoje, ignorei.",
    contextNotes: "Tema delicado; falar de ex pode causar ciúmes ou desconforto.",
    origin: "Abreviação de 'ex-namorado/ex-namorada', uso universal.",
    variations: ["ex-namorado", "ex-parceiro", "ex"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "flertar",
    meaning: "Demonstrar interesse romântico de forma leve e brincalhona.",
    adultTranslation: "Paquerar; jogar charme; demonstrar atração de forma sutil.",
    context: "Em interações sociais onde há interesse mútuo ou unilateral.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Ele passou a tarde toda flertando comigo no trabalho.",
    contextNotes: "Pode ser verbal ou por linguagem corporal.",
    origin: "Do francês 'flirter', incorporado ao português.",
    variations: ["paquerar", "dar mole", "cantar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "casar",
    meaning: "Unir-se legalmente ou religiosamente com alguém.",
    adultTranslation: "Contrair matrimônio; formalizar união conjugal.",
    context: "Quando um casal decide formalizar a união.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Vamos casar no ano que vem, já tá tudo planejado.",
    contextNotes: "Milestone importante na vida de um casal.",
    origin: "Do latim 'casa', tradição milenar.",
    variations: ["dar o sim", "casamento", "amarrar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "noivar",
    meaning: "Prometer casamento formalmente; trocar alianças de noivado.",
    adultTranslation: "Comprometer-se a se casar; fase entre namoro e casamento.",
    context: "Quando o casal decide oficializar o compromisso de casamento.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Eles noivaram no final de semana, que lindo!",
    contextNotes: "Ritual importante em muitas culturas, incluindo a brasileira.",
    origin: "Tradição cultural ocidental, do latim 'novus'.",
    variations: ["pedir em casamento", "compromisso", "aliança"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pedir em namoro",
    meaning: "Formalizar um pedido para começar um relacionamento oficial.",
    adultTranslation: "Convidar alguém para ser seu/sua namorado(a) de forma oficial.",
    context: "Quando alguém quer transformar ficância em namoro.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Ele me pediu em namoro com serenata e tudo.",
    contextNotes: "Tradição romântica brasileira, embora cada vez menos formal.",
    origin: "Cultura romântica brasileira, tradição histórica.",
    variations: ["pedir em relação", "formalizar"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "sneaky link",
    meaning: "Encontro secreto e casual, geralmente para intimidade.",
    adultTranslation: "Rolê secreto; encontro escondido para ficar sem ninguém saber.",
    context: "Quando duas pessoas se encontram às escondidas para ficarem juntas.",
    category: "expressão",
    riskLevel: "orange",
    safeExample: "O sneaky link dela chegou às 2 da manhã, todo mundo desconfiou.",
    contextNotes: "Popular na cultura rap e trap, comum na gen Z.",
    origin: "Cultura hip-hop e trap americana, viralizou no TikTok.",
    variations: ["rolê secreto", "encontro escondido"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "rizz",
    meaning: "Habilidade natural de seduzir e encantar alguém; carisma.",
    adultTranslation: "Poder de sedução; capacidade de encantar e conquistar com facilidade.",
    context: "Quando alguém consegue conquistar quem quer com charme e jeito.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "O menino tem muito rizz, conquistou ela só de olhar.",
    contextNotes: "Palavra do ano 2023 nos EUA, adotada mundialmente.",
    origin: "Abreviação de 'charisma', popularizada pelo streamer Kai Cenat.",
    variations: ["charisma", "game", "poder de conquista"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "simp",
    meaning: "Pessoa que faz de tudo por alguém que não corresponde; submisso afetivo.",
    adultTranslation: "Quem se humilha por amor não correspondido; adorador exagerado.",
    context: "Quando alguém faz de tudo para agradar um crush que nem dá bola.",
    category: "ironia",
    riskLevel: "yellow",
    safeExample: "Ele mandou presente todo dia e ela nem respondeu, puro simp.",
    contextNotes: "Usado tanto de forma humorística quanto pejorativa.",
    origin: "Cultura gamer e Reddit, popularizado no final dos anos 2010.",
    variations: ["simpático", "massa de manobra", "pena de amor"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "friendzone",
    meaning: "Ser tratado apenas como amigo por alguém que se gosta romanticamente.",
    adultTranslation: "Zona de amizade; quando a pessoa que você ama te vê só como amigo.",
    context: "Quando alguém tenta conquistar alguém mas é colocado na zona de amigos.",
    category: "ironia",
    riskLevel: "green",
    safeExample: "Tentei conquistar ela por um ano e acabei na friendzone.",
    contextNotes: "Um dos conceitos mais conhecidos sobre relacionamentos na internet.",
    origin: "Popularizado pela série Friends nos anos 90.",
    variations: ["zona de amigos", "friendzonado"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dump",
    meaning: "Terminar um relacionamento de forma abrupta e sem considerar sentimentos.",
    adultTranslation: "Dedurar; terminar o relacionamento de forma fria e direta.",
    context: "Quando alguém é terminado sem muita explicação ou consideração.",
    category: "provocacao",
    riskLevel: "orange",
    safeExample: "Ele me dumpou por mensagem, nem teve a coragem de falar ao vivo.",
    contextNotes: "Termo forte que indica falta de consideração.",
    origin: "Gíria inglesa adotada na cultura digital.",
    variations: ["dar um fora", "terminar de forma fria"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "choveu namoro",
    meaning: "Expressão humorística para quando duas pessoas formam um casal de forma inesperada.",
    adultTranslation: "Quando surge um casal do nada, surpreendendo a todos.",
    context: "Quando amigos descobrem que dois conhecidos começaram a namorar.",
    category: "zoeira",
    riskLevel: "green",
    safeExample: "Os dois estavam só conversando e de repente choveu namoro.",
    contextNotes: "Metáfora divertida que indica surpresa com o novo casal.",
    origin: "Gíria popular brasileira das redes sociais.",
    variations: ["choveu casamento", "choveu par"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tbt do ex",
    meaning: "Postar foto antiga com o ex nas redes, geralmente causando fofoca.",
    adultTranslation: "Nostalgia de ex; postar recordação de relacionamento passado.",
    context: "Quando alguém posta Throwback Thursday com foto de relacionamento antigo.",
    category: "redes_sociais",
    riskLevel: "yellow",
    safeExample: "Ela postou tbt do ex, agora todo mundo tá comentando.",
    contextNotes: "Pode indicar saudade, provocação ou simplesmente nostalgia.",
    origin: "Combinação de TBT (Throwback Thursday) com cultura de relacionamentos.",
    variations: ["tbt antigo", "nostalgia de ex"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "tipo de cara que",
    meaning: "Expressão para descrever padrões de comportamento em relacionamentos.",
    adultTranslation: "Tipo de pessoa que faz X; classificar alguém por hábitos amorosos.",
    context: "Quando alguém descreve um padrão de comportamento que desgosta ou gosta.",
    category: "ironia",
    riskLevel: "yellow",
    safeExample: "Ele é o tipo de cara que some depois do primeiro encontro.",
    contextNotes: "Muito usado em memes e Tweets sobre relacionamentos.",
    origin: "Redes sociais brasileiras, formato de tweet viral.",
    variations: ["tipo de pessoa que", "aquele cara que"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "superar",
    meaning: "Seguir em frente após um término; superar um amor.",
    adultTranslation: "Esquecer um ex; se recuperar de um término doloroso.",
    context: "Após o fim de um relacionamento, quando a pessoa tenta seguir adiante.",
    category: "alerta_emocional",
    riskLevel: "green",
    safeExample: "Levei seis meses pra superar meu último término.",
    contextNotes: "Processo emocional importante e muitas vezes longo.",
    origin: "Termo comum em português aplicado ao contexto de relacionamentos.",
    variations: ["superar o ex", "seguir em frente", "dar a volta"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "saber das coisas",
    meaning: "Ficar sabendo de fofocas ou informações sobre a vida amorosa de alguém.",
    adultTranslation: "Descobrir fofocas; ficar sabendo de coisas que não devia.",
    context: "Quando alguém descobre informações sobre o relacionamento de outrem.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Fui saber das coisas e ele tá saindo com minha amiga.",
    contextNotes: "Expressão comum em conversas de fofoca entre amigos.",
    origin: "Cultura popular brasileira de fofoca.",
    variations: ["ficar sabendo", "fofocar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dê o prossimo passo",
    meaning: "Ter coragem de formalizar um relacionamento ou avançar no flerte.",
    adultTranslation: "Ter atitude de formalizar; parar de enrolar e se declarar.",
    context: "Quando alguém incentiva outro a assumir um relacionamento.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "Já conversam há meses, precisa dar o próximo passo logo.",
    contextNotes: "Usado por amigos que querem que o amigo formalize o namoro.",
    origin: "Expressão motivacional adaptada para contexto amoroso.",
    variations: ["se declarar", "assumir", "avançar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mimimi",
    meaning: "Reclamação exagerada sobre relacionamento, geralmente vista como imatura.",
    adultTranslation: "Choro de quenga; reclamação excessiva sobre coisas amorosas banais.",
    context: "Quando alguém reclama demais sobre namoro, ex, ou ficante.",
    category: "ironia",
    riskLevel: "yellow",
    safeExample: "Todo dia é um mimimi novo sobre o ex dela.",
    contextNotes: "Pode ser desrespeitoso se usado para invalidar sentimentos reais.",
    origin: "Onomatopeia de choro, viralizou na internet brasileira.",
    variations: ["mimimi da vida", "chororô"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "entregar o ouro",
    meaning: "Dar indiretas claras sobre um relacionamento nas redes sociais.",
    adultTranslation: "Soltar pistas óbvias de que está namorando ou ficando com alguém.",
    context: "Quando alguém posta fotos ou stories que deixam claro que tem alguém.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Ela postou a caneca dele, já entregou o ouro.",
    contextNotes: "Expressão brasileira antiga adaptada para a era digital.",
    origin: "Cultura popular, possivelmente ligada a jogos e trapaças.",
    variations: ["entregar", "dar a cara", "mostrar a cara"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "dar o fora",
    meaning: "Terminar um relacionamento ou rejeitar alguém de forma direta.",
    adultTranslation: "Dedurar; terminar com alguém; dizer que não está mais interessado.",
    context: "Quando alguém decide terminar ou rejeitar uma pessoa.",
    category: "expressão",
    riskLevel: "green",
    safeExample: "Ela me deu o fora depois de três meses de namoro.",
    contextNotes: "Expressão clássica do português brasileiro.",
    origin: "Expressão popular brasileira antiga.",
    variations: ["terminar", "dar o pé", "mandar embora"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tiroteio",
    meaning: "Flerte intenso, troca de indiretas provocativas entre duas pessoas.",
    adultTranslation: "Flerte pesado; troca de mensagens provocantes e sedutoras.",
    context: "Quando duas pessoas estão flertando intensamente por mensagens ou pessoalmente.",
    category: "flerte",
    riskLevel: "green",
    safeExample: "O tiroteio de story entre os dois tá insano.",
    contextNotes: "Metáfora bélica aplicada ao flerte digital.",
    origin: "Cultura funk e rede sociais brasileiras.",
    variations: ["tiro", "tiroteio de story", "tiro certeiro"],
    popularityStatus: "ativo",
    region: "Brasil",
  },

  // ── Moda / Fashion (50 terms) ──
  {
    term: "drip",
    meaning: "Estilo impecável; aparência muito estilosa e bem montada.",
    adultTranslation: "Ter muito estilo; estar bem vestido com roupas de grife e acessórios.",
    context: "Quando alguém aparece muito bem vestido e estiloso.",
    category: "elogio",
    riskLevel: "green",
    safeExample: "O drip dele hoje tá absurdo, Jordan nova e tudo.",
    contextNotes: "Termo central da cultura streetwear e hip-hop.",
    origin: "Cultura hip-hop americana, popularizado por rappers.",
    variations: ["drip pesado", "drip insano"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "hypebeast",
    meaning: "Pessoa obcecada por marcas de streetwear e lançamentos exclusivos.",
    adultTranslation: "Fã compulsivo de moda streetwear; compra tudo que é hype.",
    context: "Para descrever alguém que vive de lançamentos de tênis e roupas de marca.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Ele é hypebeast, tem todos os lançamentos de Jordan.",
    contextNotes: "Pode ser elogio ou crítica, dependendo do tom.",
    origin: "Subcultura hip-hop e streetwear americana dos anos 2000.",
    variations: ["hype", "hypeado"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "streetwear",
    meaning: "Estilo de moda urbana inspirada na cultura hip-hop e skate.",
    adultTranslation: "Moda de rua; roupas urbanas, casuais e estilosas.",
    context: "Ao descrever o estilo de vestir de alguém ou uma coleção de roupas.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O look dele é 100% streetwear, moletom e tênis limitado.",
    contextNotes: "Um dos estilos mais influentes na moda contemporânea.",
    origin: "Cultura surf/skate da Califórnia dos anos 70 e 80.",
    variations: ["moda urbana", "casual estilo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "drop",
    meaning: "Lançamento de uma coleção ou produto de forma limitada.",
    adultTranslation: "Data de lançamento de produto exclusivo; nova coleção que vai vender rápido.",
    context: "Quando uma marca lança uma coleção limitada ou produto exclusivo.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O novo drop da Nike sai sexta-feira, vou tentar comprar.",
    contextNotes: "Eventos aguardados por colecionadores e fãs de moda.",
    origin: "Cultura streetwear e sneakerhead americana.",
    variations: ["lançamento", "release", "nova coleção"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "release",
    meaning: "Lançamento de um produto, especialmente tênis ou roupas de marca.",
    adultTranslation: "Data de lançamento; momento em que um produto fica disponível.",
    context: "Quando se fala sobre o dia em que um tênis ou roupa vai ser vendido.",
    category: "moda",
    riskLevel: "green",
    safeExample: "A release do Jordan 4 Retro é amanhã, site vai cair.",
    contextNotes: "Sinônimo de drop, usado especialmente para tênis.",
    origin: "Cultura sneakerhead e streetwear.",
    variations: ["lançamento", "drop"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "collab",
    meaning: "Colaboração entre duas marcas ou artista e marca para criar produto exclusivo.",
    adultTranslation: "Parceria entre marcas para lançar coleção especial.",
    context: "Quando duas marcas ou celebridades se unem para criar algo único.",
    category: "moda",
    riskLevel: "green",
    safeExample: "A collab entre Adidas e Bad Bunny foi incrível, já esgotou.",
    contextNotes: "As collabs costumam esgotar rapidamente e se tornar items colecionáveis.",
    origin: "Cultura streetwear, popularizada por parcerias como Nike x Off-White.",
    variations: ["colaboração", "parceria"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "grail",
    meaning: "Item dos sonhos de um colecionador; a peça mais desejada de uma coleção.",
    adultTranslation: "Peça sagrada; item de moda que alguém sonha em ter na coleção.",
    context: "Quando alguém fala da peça mais rara ou desejada de sua coleção.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O Jordan 1 Chicago é o meu grail, um dia vou ter.",
    contextNotes: "Do Santo Graal, símbolo de algo supremamente desejado.",
    origin: "Cultura sneakerhead, analogia ao Santo Graal.",
    variations: ["grail piece", "peça sagrada", "santo graal"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cop",
    meaning: "Comprar; adquirir um item de moda ou tênis.",
    adultTranslation: "Comprar algo; adquirir uma peça de roupa ou tênis desejado.",
    context: "Quando alguém diz que vai comprar determinado item de moda.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Vou cop esse moletom do Travis Scott.",
    contextNotes: "Verbo muito usado na cultura streetwear e hip-hop.",
    origin: "Gíria americana, abreviação de 'cop' (policial) como pegar/pegar algo.",
    variations: ["copar", "comprar", "garantir"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pass",
    meaning: "Não comprar; deixar passar um item de moda por não gostar ou por preço alto.",
    adultTranslation: "Deixar de comprar; não se interessar por um lançamento.",
    context: "Quando alguém decide não comprar um item que era esperado.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Vou dar pass nesse tênis, preço tá absurdo.",
    contextNotes: "Oposto de cop; também origem do basquete (passar a bola).",
    origin: "Cultura streetwear americana.",
    variations: ["dar pass", "deixar pra lá", "skip"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "heat",
    meaning: "Coleção ou peças muito desejadas e difíceis de encontrar.",
    adultTranslation: "Roupas ou tênis raros e muito valorizados; produtos quentes.",
    context: "Quando alguém se refere a itens de moda que são raros e cobiçados.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Esse look tá com heat demais, tênis limitado e blazer de couro.",
    contextNotes: "Heat remete a algo quente, disputado e valioso.",
    origin: "Cultura sneakerhead americana.",
    variations: ["fogo", "heat demais"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ootd",
    meaning: "Abreviação de 'Outfit of the Day'; look do dia.",
    adultTranslation: "Look do dia; roupa que alguém está vestindo no dia.",
    context: "Quando alguém posta foto com a roupa que está usando no Instagram.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O ootd de hoje é streetwear, vou postar no IG.",
    contextNotes: "Hashtag muito popular no Instagram e TikTok.",
    origin: "Cultura de influenciadores de moda no Instagram.",
    variations: ["look do dia", "outfit do dia"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fit check",
    meaning: "Verificação do look; momento de mostrar a roupa que está usando.",
    adultTranslation: "Avaliação do look; mostrar a roupa e pedir opinião.",
    context: "Quando alguém tira foto no espelho para mostrar o outfit.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Fiz fit check antes de sair, o look tá certinho.",
    contextNotes: "Trend muito comum no TikTok e Instagram.",
    origin: "Cultura digital de moda e redes sociais.",
    variations: ["avaliação de look", "check de roupa"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "jordan",
    meaning: "Tênis da marca Jordan (Nike), símbolo de status na cultura streetwear.",
    adultTranslation: "Tênis Michael Jordan; item de status e desejo na cultura urbana.",
    context: "Ao falar de tênis, especialmente modelos icônicos como o Air Jordan 1.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Consegui comprar o Jordan 1 no drop, felicidade total.",
    contextNotes: "Os Jordans são os tênis mais cobiçados da cultura streetwear.",
    origin: "Linha de tênis da Nike criada para Michael Jordan em 1985.",
    variations: ["AJ", "Air Jordan", "Jordan 1"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "supreme",
    meaning: "Marca de streetwear americana conhecida por lançamentos limitados.",
    adultTranslation: "Grife de moda urbana; símbolo máximo de hype na cultura street.",
    context: "Ao mencionar a marca ou produtos com o logo vermelho icônico.",
    category: "moda",
    riskLevel: "green",
    safeExample: "A camiseta do Supreme com logo vermelho tá dificílima de achar.",
    contextNotes: "Marca cult com comunidades de colecionadores em todo o mundo.",
    origin: "Marca fundada por James Jebbia em Nova York, 1994.",
    variations: ["SupNY", "logo vermelho"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "stüssy",
    meaning: "Marca de streetwear californiana, pioneira na cultura surf e skate.",
    adultTranslation: "Grife clássica de streetwear surf/skate; referência cultural.",
    context: "Ao falar de roupas streetwear com a estética surf californiana.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Comprei uma camiseta do Stüssy, estética de surf absurda.",
    contextNotes: "Uma das marcas mais respeitadas da cultura streetwear.",
    origin: "Marca fundada por Shawn Stussy na Califórnia em 1980.",
    variations: ["Stussy", "surf streetwear"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "balenciaga",
    meaning: "Marca de luxo espanhola famosa por peças ousadas e exageradas.",
    adultTranslation: "Grife de luxo; marca de moda de alta-costura com estilo urbano.",
    context: "Ao falar de roupas ou acessórios de grife de alto valor.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O tênis Balenciaga Track é o mais comentado do momento.",
    contextNotes: "Marca muito comentada na cultura pop e trap.",
    origin: "Casa de moda fundada por Cristóbal Balenciaga na Espanha, 1919.",
    variations: ["Balen", "balenziaga"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "off-white",
    meaning: "Marca de streetwear de luxo fundada por Virgil Abloh.",
    adultTranslation: "Grife de alta moda street; mistura de luxo e cultura urbana.",
    context: "Ao mencionar a marca ou seus produtos icônicos com aspas e zíperes.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O tênis Off-White com a flecha é um dos mais estilosos.",
    contextNotes: "Virgil Abloh revolucionou a moda ao misturar streetwear com alta costura.",
    origin: "Marca fundada por Virgil Abloh em 2012, em Milão.",
    variations: ["OW", "Virgil Abloh"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "yeezy",
    meaning: "Linha de roupas e tênis de Kanye West em parceria com Adidas.",
    adultTranslation: "Marca de moda de Kanye West; tênis com design futurista.",
    context: "Ao falar dos tênis icônicos ou roupas da linha Yeezy.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O Yeezy 350 V2 é o tênis mais confortável que já tive.",
    contextNotes: "Após controvérsias com Kanye, o futuro da marca ficou incerto.",
    origin: "Linha criada por Kanye West em parceria com Adidas em 2015.",
    variations: ["YZY", "Yeezys", "Kanye"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "aesthetic",
    meaning: "Estética visual específica; conjunto de elementos que define um estilo.",
    adultTranslation: "Estilo visual; conjunto de cores, roupas e acessórios que formam uma vibe.",
    context: "Quando alguém descreve o estilo visual de um look, quarto ou perfil.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O aesthetic dessa foto é dark academia, muito elegante.",
    contextNotes: "Virou trend gigante no TikTok com dezenas de aesthetics.",
    origin: "TikTok e Pinterest, conceito de identidade visual.",
    variations: ["estética", "vibe visual"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "minimalista",
    meaning: "Estilo de moda com poucas peças, cores neutras e design simples.",
    adultTranslation: "Moda simples e clean; roupas sem estampas com cores básicas.",
    context: "Quando alguém prefere looks simples, elegantes e sem exageros.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O estilo dela é minimalista, só usa preto, branco e bege.",
    contextNotes: "Tendência forte na moda contemporânea.",
    origin: "Movimento minimalista na arte e design, adaptado à moda.",
    variations: ["clean", "basicão", "minimal"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "oversized",
    meaning: "Roupas maiores que o tamanho normal; estilo folgado e confortável.",
    adultTranslation: "Tamanho grande de propósito; roupas exageradamente largas.",
    context: "Ao descrever peças de roupa que são propositalmente maiores.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Comprei esse moletom oversized, fica super confortável.",
    contextNotes: "Um dos estilos mais populares na cultura streetwear.",
    origin: "Cultura hip-hop dos anos 90 e moda streetwear contemporânea.",
    variations: ["baggy", "oversize", "XXL"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "crop top",
    meaning: "Blusa ou camiseta cortada na barriga, deixando o umbigo de fora.",
    adultTranslation: "Top curto; blusa que deixa a barriga à mostra.",
    context: "Ao falar de roupas femininas que deixam o abdômen exposto.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Comprei um crop top preto pra usar com calça cargo.",
    contextNotes: "Peça icônica da moda feminina, especialmente no verão.",
    origin: "Cultura pop e moda dos anos 80/90, ressurgiu nos anos 2010.",
    variations: ["top curtinho", "blusa curta"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cargo",
    meaning: "Calça com bolsos laterais grandes, estilo militar adaptado para o dia a dia.",
    adultTranslation: "Calça estilo militar com bolsos amplos; peça streetwear popular.",
    context: "Ao falar de calças cargo, muito usadas no estilo streetwear.",
    category: "moda",
    riskLevel: "green",
    safeExample: "A calça cargo verde é a peça mais versátil do meu guarda-roupa.",
    contextNotes: "Voltou com força na moda urbana nos últimos anos.",
    origin: "Roupas militares, adaptadas para a moda civil.",
    variations: ["calça cargo", "cargo pants"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "moletom",
    meaning: "Blusa de tecido grosso e felpudo, confortável e casual.",
    adultTranslation: "Suéter de algodão; blusa quente e confortável para o dia a dia.",
    context: "Ao falar de roupas casuais para dias frios.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Vou usar meu moletom do Chicago Bulls hoje.",
    contextNotes: "Peça essencial no guarda-roupa de quem curte streetwear.",
    origin: "Do francês 'molleton', tecido felpudo.",
    variations: ["sweatshirt", "blusa de moletom", "suéter"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "chino",
    meaning: "Calça social casual de algodão, mais elegante que jeans.",
    adultTranslation: "Calça social casual; meio termo entre calça jeans e social.",
    context: "Ao falar de calças versáteis que servem para diversas ocasiões.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Usei uma calça chino com camisa para o evento, ficou perfeito.",
    contextNotes: "Peça curinga que combina casualidade com elegância.",
    origin: "Calças de algodão originárias da China, adaptadas ao estilo ocidental.",
    variations: ["calça chino", "chinos"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bucket hat",
    meaning: "Chapéu de aba larga, estilo balde, popular na cultura streetwear.",
    adultTranslation: "Chapéu de aba redonda; acessório icônico da moda urbana.",
    context: "Ao falar de acessórios de cabeça no estilo streetwear.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Comprei um bucket hat do Stüssy, ficou demais no look.",
    contextNotes: "Acessório que voltou à moda nos anos 2010 com força.",
    origin: "Chapéus usados por pescadores e irlandeses, popularizados pelo hip-hop.",
    variations: ["chapéu de balde", "boné abas largas"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "corrente",
    meaning: "Colar de metal grosso usado como acessório de estilo.",
    adultTranslation: "Colar de metal pesado; acessório símbolo de poder e estilo.",
    context: "Ao falar de acessórios masculinos na cultura streetwear e hip-hop.",
    category: "moda",
    riskLevel: "green",
    safeExample: "A corrente de prata complementa o look perfeitamente.",
    contextNotes: "Acessório icônico do hip-hop desde os anos 80.",
    origin: "Cultura hip-hop americana dos anos 80.",
    variations: ["chain", "colar de corrente"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "piercings",
    meaning: "Adornos metálicos colocados em várias partes do corpo.",
    adultTranslation: "Piercings; brincos e adereços no corpo como forma de expressão.",
    context: "Ao falar de modificações corporais estéticas.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Ela tem piercings no nariz e na orelha, estilo insano.",
    contextNotes: "Forma de expressão pessoal e estilo muito popular.",
    origin: "Culturas antigas de modificação corporal, popularizadas na cultura punk.",
    variations: ["piercing", "brinco", "adereço"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tattoo",
    meaning: "Tatuagem; desenho permanente na pele como expressão de estilo.",
    adultTranslation: "Tatuagem; arte corporal permanente como forma de identidade.",
    context: "Ao falar de tatuagens como parte do estilo pessoal.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Fiz uma tattoo no braço que combina com meu estilo.",
    contextNotes: "Tatuagens se tornaram muito mais aceitas socialmente.",
    origin: "Práticas ancestrais de diversas culturas ao redor do mundo.",
    variations: ["tatuagem", "tatto", "tinta"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "sneaker",
    meaning: "Tênis esportivo e estiloso, frequentemente de coleções limitadas.",
    adultTranslation: "Tênis estiloso; calçado esportivo usado como peça de moda.",
    context: "Ao falar de tênis de marcas como Nike, Adidas, Jordan, etc.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Sou sneakerhead, tenho mais de 30 pares de sneakers.",
    contextNotes: "Os sneakers se tornaram peça central da moda contemporânea.",
    origin: "Termo inglês para tênis esportivo, da cultura streetwear.",
    variations: ["tênis", "tenis", "kick"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "boné",
    meaning: "Chapéu com aba frontal, acessório essencial do estilo streetwear.",
    adultTranslation: "Chapéu de aba; acessório de cabeça usado para estilo e proteção solar.",
    context: "Ao falar de acessórios casuais no dia a dia.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O boné do Yankees é curinga, combina com qualquer look.",
    contextNotes: "Um dos acessórios mais icônicos e usados mundialmente.",
    origin: "Acessório de beisebol americano, popularizado globalmente.",
    variations: ["cap", "boné aba reta", "snapback"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cap",
    meaning: "Boné, especialmente de aba reta e ajustável.",
    adultTranslation: "Boné estilo americano; acessório urbano indispensável.",
    context: "Ao falar do boné como parte essencial do look.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Coloquei meu cap preto pra completar o fit.",
    contextNotes: "Termo em inglês amplamente usado no Brasil.",
    origin: "Inglês 'cap', do original boné de baseball.",
    variations: ["boné", "cap aberto", "dad hat"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "tênis",
    meaning: "Calçado esportivo, usado tanto para atividade física quanto como item de moda.",
    adultTranslation: "Sapato esportivo; calçado versátil que serve para esporte e estilo.",
    context: "Ao falar de calçados casuais e esportivos no dia a dia.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Comprei um tênis novo branco, combina com tudo.",
    contextNotes: "No Brasil, tênis branco é item básico do guarda-roupa.",
    origin: "Do inglês 'tennis shoe', popularizado mundialmente.",
    variations: ["sneaker", "tenis", "calcado"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "hype",
    meaning: "Excitação exagerada em torno de um lançamento ou produto de moda.",
    adultTranslation: "Expectativa alta; alvoroço em torno de algo que vai ser lançado.",
    context: "Quando há muita ansiedade e expectativa antes de um lançamento de moda.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O hype do novo iPhone da Apple é absurdo esse ano.",
    contextNotes: "O hype move bilhões na indústria da moda.",
    origin: "Palavra inglesa para excitação, popularizada na cultura pop.",
    variations: ["hypeado", "hype demais"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "unboxing",
    meaning: "Vídeo ou momento de abrir uma caixa de produto de moda novo.",
    adultTranslation: "Desembalar; registro em vídeo de abrir uma compra nova.",
    context: "Quando alguém grava vídeo abrendo tênis, roupas ou acessórios novos.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Fiz o unboxing do meu novo Jordan no YouTube.",
    contextNotes: "Gênero de conteúdo gigante no YouTube e TikTok.",
    origin: "Cultura de YouTubers e reviewers de produtos.",
    variations: ["desembalar", "abrir a caixa"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "limited edition",
    meaning: "Edição limitada; produto lançado em quantidade restrita.",
    adultTranslation: "Lançamento exclusivo com poucas unidades; item raro de colecionar.",
    context: "Ao falar de produtos de moda com produção limitada.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Consegui um Nike Dunk limited edition, tinha só 500 pares.",
    contextNotes: "Itens de edição limitada valorizam com o tempo.",
    origin: "Indústria da moda e colecionismo.",
    variations: ["edição limitada", "ed. limitada", "LE"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "resell",
    meaning: "Revenda de produtos de moda acima do preço original.",
    adultTranslation: "Revender item de moda com lucro; mercado de revenda de tênis e roupas.",
    context: "Quando alguém compra um item limitado para vender mais caro.",
    category: "moda",
    riskLevel: "yellow",
    safeExample: "O resell do Jordan 1 está custando o triplo do preço original.",
    contextNotes: "Mercado bilionário que surgiu da cultura streetwear.",
    origin: "Mercado de revenda de tênis, plataformas como StockX.",
    variations: ["revenda", "revender", "revendedor"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "grife",
    meaning: "Marca de moda de alto padrão; etiqueta de designer famoso.",
    adultTranslation: "Marca de luxo; designer de moda reconhecido e valorizado.",
    context: "Ao falar de marcas caras e prestigiadas de moda.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O look dela é tudo de grife, Gucci e Louis Vuitton.",
    contextNotes: "No Brasil, 'grife' é sinônimo de marca de luxo.",
    origin: "Do francês 'griffe', marca de identidade de designers.",
    variations: ["marca de luxo", "designer", "brand"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "look",
    meaning: "Conjunto de roupas e acessórios montados para uma ocasião.",
    adultTranslation: "Visual; conjunto completo de roupas, calçados e acessórios.",
    context: "Ao falar da aparência de alguém ou de uma montagem de roupas.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O look de hoje está incrível, combinou tudo certinho.",
    contextNotes: "Termo onipresente em conversas sobre moda.",
    origin: "Inglês 'look', popularizado na cultura da moda.",
    variations: ["visual", "outfit", "fit"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fit",
    meaning: "Abreviação de outfit; conjunto de roupas usado em uma ocasião.",
    adultTranslation: "Look; conjunto de roupas montado para sair ou postar.",
    context: "Ao falar de looks no dia a dia, especialmente em redes sociais.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Montei um fit de streetwear pra ir no show.",
    contextNotes: "Versão curta e informal de outfit.",
    origin: "Abreviação de 'outfit' na cultura digital.",
    variations: ["outfit", "look", "montagem"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "necklace",
    meaning: "Colar; acessório usado no pescoço como adorno.",
    adultTranslation: "Colar; peça de joalheria ou acessório de moda usado no pescoço.",
    context: "Ao falar de acessórios de pescoço como parte do look.",
    category: "moda",
    riskLevel: "green",
    safeExample: "A necklace de prata combina perfeitamente com a camiseta preta.",
    contextNotes: "Acessório versátil que pode elevar qualquer look simples.",
    origin: "Inglês para colar, usado em contextos de moda.",
    variations: ["colar", "pingente"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "baggy",
    meaning: "Estilo de roupas largas e folgadas, originário da cultura hip-hop.",
    adultTranslation: "Roupas bem largas e soltas; estilo oversized dos anos 90.",
    context: "Ao falar de calças, camisetas e moletom no estilo largo.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O estilo baggy voltou com tudo, calça larga e camiseta enorme.",
    contextNotes: "Estilo que teve origem na cultura hip-hop e voltou à moda.",
    origin: "Cultura hip-hop dos anos 90, associado a skatistas.",
    variations: ["largadão", "folgado", "wide fit"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "pegar emprestado",
    meaning: "Usar roupa emprestada de amigo ou parente para um evento.",
    adultTranslation: "Pedir roupa emprestada; usar algo de alguém sem comprar.",
    context: "Quando alguém precisa de uma roupa boa e pede emprestado.",
    category: "zoeira",
    riskLevel: "green",
    safeExample: "Peguei o terno emprestado do meu irmão pro formatura.",
    contextNotes: "Muito comum entre amigos e familiares jovens.",
    origin: "Cultura popular, prática antiga de compartilhar roupas.",
    variations: ["tomar emprestado", "roubar do guarda-roupa"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: " thrift store",
    meaning: "Loja de roupas usadas; brechó.",
    adultTranslation: "Brechó; loja que vende roupas de segunda mão com estilo.",
    context: "Ao falar de compras em brechós como forma sustentável e estilosa.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Encontrei uma jaqueta vintage incrível numa thrift store.",
    contextNotes: "Thrifting virou tendência sustentável entre jovens.",
    origin: "Cultura americana de lojas de usados com seleção curada.",
    variations: ["brechó", "sebo de roupas", "usados"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vintage",
    meaning: "Roupas ou acessórios antigos que se tornaram estilosos novamente.",
    adultTranslation: "Peças antigas com valor estético; estilo retrô que voltou à moda.",
    context: "Ao falar de roupas com estilo de décadas passadas.",
    category: "moda",
    riskLevel: "green",
    safeExample: "Essa camiseta vintage dos anos 80 é um achado raríssimo.",
    contextNotes: "Peças vintage são valorizadas por sua exclusividade e história.",
    origin: "Cultura de colecionismo e moda retrô.",
    variations: ["retrô", "antigo", "clássico"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "logo-mania",
    meaning: "Obsessão por usar roupas com logos de marcas visíveis.",
    adultTranslation: "Usar roupas com logos grandes de grife; ostentação de marca.",
    context: "Quando alguém veste muitas peças com logos de marca expostos.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O look dele é logo-mania, Nike da cabeça aos pés.",
    contextNotes: "Tendência muito presente na cultura streetwear.",
    origin: "Cultura da moda e streetwear, especialmente nos anos 2000.",
    variations: ["logomaníaco", "ostentação de marca"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "inspo",
    meaning: "Abreviação de inspiration; referência para montar um look.",
    adultTranslation: "Inspiracao; referencia visual para criar um outfit.",
    context: "Quando alguém busca referências para montar um look ou estilo.",
    category: "redes_sociais",
    riskLevel: "green",
    safeExample: "Peguei a inspo desse look no Pinterest.",
    contextNotes: "Muito usado no Instagram e Pinterest como hashtag.",
    origin: "Cultura de redes sociais e blogs de moda.",
    variations: ["inspiração", "referência"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "styling",
    meaning: "A arte de montar looks; estilização de roupas e acessórios.",
    adultTranslation: "Montagem de look; escolher e combinar roupas com criatividade.",
    context: "Ao falar da habilidade de criar visuais interessantes com roupas.",
    category: "moda",
    riskLevel: "green",
    safeExample: "O styling desse editorial de moda é impressionante.",
    contextNotes: "Profissão de estilista ganhou muito destaque nas redes sociais.",
    origin: "Mundo da moda profissional, popularizado por influenciadores.",
    variations: ["estilização", "montar look", "estilista"],
    popularityStatus: "ativo",
    region: "Brasil",
  },

  // ── Escola / Estudo (50 terms) ──
  {
    term: "bizu",
    meaning: "Dica ou informação privilegiada sobre uma prova ou trabalho.",
    adultTranslation: "Dica; informação vazada sobre o que vai cair na prova.",
    context: "Quando alguém descobre antecipadamente o conteúdo de uma avaliação.",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "O amigo me deu o bizu de que vai cair matéria do capítulo 5.",
    contextNotes: "Prática comum entre estudantes, mas pode ser antiética em alguns contextos.",
    origin: "Gíria estudantil brasileira, possivelmente derivada de 'bispo'.",
    variations: ["dica", "puxada", "papo de corredor"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cola",
    meaning: "Material escondido para usar durante uma prova; prática de colar.",
    adultTranslation: "Material de cola; pequeno papel com respostas escondido na roupa.",
    context: "Quando alguém prepara algo para trapacear em uma prova.",
    category: "escola",
    riskLevel: "orange",
    safeExample: "Ele foi pego com cola na prova de matemática.",
    contextNotes: "Prática proibida e punível em ambiente escolar.",
    origin: "Gíria estudantil universal.",
    variations: ["cola na manga", "canga", "canequinha"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "macete",
    meaning: "Truque ou atalho para aprender ou memorizar algo mais facilmente.",
    adultTranslation: "Truque de estudo; estratégia para aprender rápido.",
    context: "Quando alguém compartilha uma técnica para facilitar o aprendizado.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Esse macete de memorizar fórmulas com música funciona demais.",
    contextNotes: "Ferramenta valiosa de estudo quando usada corretamente.",
    origin: "Do espanhol 'maqueta' ou gíria popular brasileira.",
    variations: ["truque", "atalho", "técnica"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ranger",
    meaning: "Se dar mal; ter resultado ruim em prova ou situação.",
    adultTranslation: "Ir mal em algo; reprovar; ter consequências negativas.",
    context: "Quando um aluno tira nota baixa ou tem problema na escola.",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "Rangi feio na prova de física, vou ter que estudar mais.",
    contextNotes: "Expressão comum entre estudantes brasileiros.",
    origin: "Gíria popular, possivelmente ligada a ranger os dentes de nervoso.",
    variations: ["se dar mal", "ir mal", "quebrar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "gabaritar",
    meaning: "Acertar todas as questões de uma prova; tirar nota máxima.",
    adultTranslation: "Acertar tudo na prova; tirar 10 sem nenhum erro.",
    context: "Quando um aluno tira a nota máxima em uma avaliação.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Gabaritei a prova de história, me orgulhei muito.",
    contextNotes: "Máxima conquista em uma prova, motivo de orgulho.",
    origin: "Do termo 'gabarito', que é a folha de respostas.",
    variations: ["acertar tudo", "tirar 10", "nota máxima"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bomba",
    meaning: "Prova muito difícil; algo que é impossível de resolver.",
    adultTranslation: "Prova dificílima; avaliação quase impossível de passar.",
    context: "Quando uma prova é tão difícil que ninguém consegue fazer.",
    category: "escola",
    riskLevel: "green",
    safeExample: "A prova de matemática foi uma bomba, ninguém conseguiu fazer.",
    contextNotes: "Expressão clássica que todo estudante brasileiro conhece.",
    origin: "Gíria estudantil antiga, metáfora com explosão.",
    variations: ["prova difícil", "massacre", "terror"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "prova",
    meaning: "Avaliação escrita ou oral aplicada por professor para testar conhecimento.",
    adultTranslation: "Exame; avaliação escolar para medir aprendizado.",
    context: "Em contexto escolar ou acadêmico.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Tenho prova de biologia amanhã, preciso estudar hoje.",
    contextNotes: "Momento de maior estresse para estudantes.",
    origin: "Do latim 'proba', que significa teste ou demonstração.",
    variations: ["avaliação", "exame", "teste"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "trabalho",
    meaning: "Atividade escolar para ser feita em casa ou em grupo.",
    adultTranslation: "Tarefa acadêmica; atividade avaliativa atribuída pelo professor.",
    context: "Quando o professor passa uma atividade para ser entregue em data futura.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Tenho um trabalho de português pra entregar sexta-feira.",
    contextNotes: "Pode ser individual ou em grupo, causa ansiedade quando acumula.",
    origin: "Vocabulário comum do ambiente escolar.",
    variations: ["tarefa", "atividade", "trampo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "seminário",
    meaning: "Apresentação oral sobre um tema, geralmente feita em grupo.",
    adultTranslation: "Apresentação em grupo sobre tema acadêmico; exposição oral.",
    context: "Quando alunos precisam apresentar um tema para a classe.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O seminário de geografia vai ser sobre mudanças climáticas.",
    contextNotes: "Uma das formas de avaliação mais temidas por estudantes.",
    origin: "Do latim 'seminarium', ambiente de aprendizado.",
    variations: ["apresentação", "semina", "exposição"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "grupo",
    meaning: "Equipe de alunos que trabalham juntos em uma atividade escolar.",
    adultTranslation: "Time de trabalho escolar; conjunto de alunos que fazem atividade juntos.",
    context: "Quando o professor divide a turma para fazer trabalho em equipe.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Meu grupo de trabalho tem gente demais e ninguém faz nada.",
    contextNotes: "Trabalhos em grupo são fonte de conflito e procrastinação.",
    origin: "Ambiente escolar comum.",
    variations: ["equipe", "time", "turma"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "rabiscar",
    meaning: "Escrever ou desenhar sem cuidado, encher o caderno de rabiscos.",
    adultTranslation: "Desenhar sem atenção enquanto ouve aula; rabisco.",
    context: "Quando o aluno desenha ou escreve coisas aleatórias durante a aula.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Passei a aula inteira rabiscando na margem do caderno.",
    contextNotes: "Muito comum entre alunos distraídos ou entediados.",
    origin: "Do latim 'resperare', arranhar.",
    variations: ["doodle", "rabisco", "rabiscos"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "copiar",
    meaning: "Copiar o trabalho ou prova de outro aluno; plágio.",
    adultTranslation: "Copiar o trabalho alheio; reproduzir conteúdo sem autorização.",
    context: "Quando um aluno copia o trabalho ou prova de colega.",
    category: "escola",
    riskLevel: "orange",
    safeExample: "O professor pegou ele copiando a prova do colega.",
    contextNotes: "Prática proibida com consequências sérias no ambiente escolar.",
    origin: "Termo comum no ambiente acadêmico.",
    variations: ["copiar", "plagiar", "CTRL+C CTRL+V"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "colar",
    meaning: "Copiar de alguém durante uma prova; trapacear.",
    adultTranslation: "Trapacear em prova; olhar a prova do colega.",
    context: "Quando um aluno tenta copiar as respostas do colega durante avaliação.",
    category: "escola",
    riskLevel: "orange",
    safeExample: "Tentei colar do meu amigo mas o professor viu.",
    contextNotes: "Embora comum, é prática antiética e proibida.",
    origin: "Gíria estudantil brasileira clássica.",
    variations: ["copiar", "colar", "roubar respostas"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "entregar",
    meaning: "Prazo final para submeter um trabalho ou atividade escolar.",
    adultTranslation: "Enviar ou apresentar um trabalho; data de entrega.",
    context: "Quando o prazo de um trabalho está chegando.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Preciso entregar o trabalho até sexta ou perco ponto.",
    contextNotes: "Entregas atrasadas podem afetar a nota final.",
    origin: "Vocabulário escolar comum.",
    variations: ["entrega", "data limite", "deadline"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "nota",
    meaning: "Pontuação obtida em uma prova ou trabalho; conceito de avaliação.",
    adultTranslation: "Resultado de uma avaliação; pontuação numérica ou conceitual.",
    context: "Quando alunos recebem o resultado de suas avaliações.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Tirei nota 9 na prova de química, quase gabaritei.",
    contextNotes: "As notas são a principal métrica de desempenho escolar.",
    origin: "Sistema educacional formal.",
    variations: ["pontuação", "conceito", "avaliação"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "faltou",
    meaning: "Não comparecer à aula; ausência escolar.",
    adultTranslation: "Não ir à escola; ter falta não justificada.",
    context: "Quando um aluno não vai à aula sem justificativa.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Faltou ontem e perdeu a matéria toda de revisão.",
    contextNotes: "Muitas faltas podem levar à reprovação por frequência.",
    origin: "Vocabulário escolar comum.",
    variations: ["falta", "ausência", "matar aula"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "professor",
    meaning: "Docente; pessoa que ensina em escola, faculdade ou curso.",
    adultTranslation: "Educador; pessoa responsável por transmitir conhecimento.",
    context: "Ao falar de quem ministra aulas em ambiente educacional.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O professor de história conta as aulas de um jeito muito interessante.",
    contextNotes: "Figura central no ambiente escolar, com grande influência sobre alunos.",
    origin: "Do latim 'professor', aquele que professa conhecimento.",
    variations: ["prof", "profe", "docente"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "recuperação",
    meaning: "Prova extra para quem ficou abaixo da média; chance de recuperar nota.",
    adultTranslation: "Segunda chance na prova; exame para quem reprovou na primeira tentativa.",
    context: "Quando o aluno tira nota baixa e precisa fazer outra prova.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Vou fazer recuperação de matemática, não quero reprovar.",
    contextNotes: "Momento de pressão para o aluno, última chance de passar.",
    origin: "Sistema educacional brasileiro.",
    variations: ["recup", "recupe", "segunda chance"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cantar de galo",
    meaning: "Entregar um trabalho no último minuto; fazer algo na pressa.",
    adultTranslation: "Fazer trabalho de última hora; estudar na madrugada antes da prova.",
    context: "Quando o aluno faz o trabalho ou estuda de madrugada antes da entrega.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Cantei de galo para entregar o trabalho, fiz tudo às 3 da manhã.",
    contextNotes: "Expressão clássica do estudante brasileiro procrastinador.",
    origin: "Expressão popular, possivelmente ligada ao canto do galo de madrugada.",
    variations: ["fazer de última hora", "correr atrás", "noite mal dormida"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "rango",
    meaning: "Comida; alimento, especialmente em contexto escolar.",
    adultTranslation: "Comida; refeição; algo para comer na hora do intervalo.",
    context: "Ao falar de comida na escola ou durante o intervalo.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Levei um rango pra escola porque a cantina tá cara.",
    contextNotes: "Termo muito popular entre estudantes para comida.",
    origin: "Gíria popular brasileira, possivelmente de origem indígena.",
    variations: ["comida", "lanche", "marmita"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bandejão",
    meaning: "Refeitório universitário; local onde se serve comida barata.",
    adultTranslation: "Cantina da faculdade; refeitório de universidade pública.",
    context: "Ao falar de refeições na universidade.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Almocei no bandejão hoje, o arroz tava meio duro mas tá valendo.",
    contextNotes: "Símbolo da vida universitária brasileira, famosa pela comida questionável.",
    origin: "Universidades públicas brasileiras, referência às bandejas de comida.",
    variations: ["bandex", "RU", "restaurante universitário"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "intervalo",
    meaning: "Pausa entre as aulas; momento de descanso e socialização.",
    adultTranslation: "Recreio escolar; tempo de pausa entre aulas para comer e conversar.",
    context: "Durante a pausa entre aulas na escola ou faculdade.",
    category: "escola",
    riskLevel: "green",
    safeExample: "No intervalo a gente joga futebol no campinho.",
    contextNotes: "Momento mais aguardado do dia escolar.",
    origin: "Estrutura escolar tradicional.",
    variations: ["recreio", "pausa", "break"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "recreio",
    meaning: "Pausa entre aulas na escola fundamental; tempo de brincar e comer.",
    adultTranslation: "Intervalo escolar; hora de brincar e lanchar entre aulas.",
    context: "Na escola fundamental, quando crianças brincam no pátio.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O recreio é a melhor parte do dia, brincamos de pique-pega.",
    contextNotes: "Momento icônico da infância escolar brasileira.",
    origin: "Termo escolar tradicional brasileiro.",
    variations: ["intervalo", "pausa", "hora do lanche"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "mascote",
    meaning: "Pessoa que não faz nada no trabalho em grupo; que não contribui.",
    adultTranslation: "Aproveitador de grupo; aluno que se esconde no trabalho coletivo.",
    context: "Quando alguém não faz parte do trabalho em grupo mas fica com a nota.",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "O João é sempre mascote no grupo, não faz nada e recebe a nota.",
    contextNotes: "Fonte de frustração entre alunos que trabalham.",
    origin: "Gíria estudantil, metáfora com mascote de time que só acompanha.",
    variations: ["carona", "aproveitador", "parasita"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "coordenador",
    meaning: "Responsável por coordenar turmas e resolver problemas disciplinares.",
    adultTranslation: "Gestor pedagógico; pessoa que cuida da disciplina e organização escolar.",
    context: "Quando há problemas de disciplina ou organização na escola.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O coordenador chamou os pais por causa das faltas.",
    contextNotes: "Figura de autoridade na escola,仅次于 a direção.",
    origin: "Estrutura escolar brasileira.",
    variations: ["coordenação", "coord", "pedagogo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "diretora",
    meaning: "Responsável máxima pela administração da escola.",
    adultTranslation: "Diretora escolar; líder administrativa da instituição de ensino.",
    context: "Ao falar da autoridade máxima da escola.",
    category: "escola",
    riskLevel: "green",
    safeExample: "A diretora convocou uma reunião com todos os alunos.",
    contextNotes: "Máxima autoridade na escola, pode punir ou expulsar alunos.",
    origin: "Estrutura escolar tradicional.",
    variations: ["diretor", "direção", "administração"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "conselho de classe",
    meaning: "Reunião entre professores para discutir desempenho dos alunos.",
    adultTranslation: "Reunião pedagógica para avaliar notas e comportamento dos estudantes.",
    context: "No fim do bimestre, quando professores se reúnem para decidir aprovações.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Meu nome foi discutido no conselho de classe por causa das faltas.",
    contextNotes: "Momento que define se o aluno passa ou reprova.",
    origin: "Sistema educacional brasileiro.",
    variations: ["conselho", "reunião de professores"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "EDT",
    meaning: "Ensino Médio integrado ao Técnico; curso que combina ensino médio e profissionalizante.",
    adultTranslation: "Curso integrado de ensino médio com formação técnica profissional.",
    context: "Ao falar de escolas que oferecem formação técnica junto com o ensino médio.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Estudo na ETEC no modelo EDT, já saio formado técnico.",
    contextNotes: "Opção muito procurada por alunos que querem entrar no mercado cedo.",
    origin: "Rede estadual de ensino técnico de São Paulo.",
    variations: ["ETEC", "ensino técnico", "técnico integrado"],
    popularityStatus: "regional",
    region: "Brasil",
  },
  {
    term: "matar aula",
    meaning: "Faltar à aula de propósito, sem justificativa.",
    adultTranslation: "Não ir à aula propositalmente; escapar da escola.",
    context: "Quando o aluno decide não ir à aula por preguiça ou desinteresse.",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "Matei aula de física hoje porque não tinha estudado.",
    contextNotes: "Prática comum entre adolescentes, mas com consequências.",
    origin: "Gíria estudantil brasileira clássica.",
    variations: ["falhar", "não ir", "sacanear a aula"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cursinho",
    meaning: "Curso preparatório para vestibulares e concursos.",
    adultTranslation: "Escola preparatória para provas importantes como ENEM e vestibulares.",
    context: "Quando alguém estuda em curso preparatório para ingressar na faculdade.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Entrei no cursinho pra estudar pro ENEM do ano que vem.",
    contextNotes: "Instituição fundamental na vida de estudantes brasileiros.",
    origin: "Cultura educacional brasileira pós-ditadura.",
    variations: ["pré-vestibular", "curso preparatório", "prep course"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "vestibular",
    meaning: "Exame de ingresso para universidades brasileiras.",
    adultTranslation: "Prova seletiva para entrar na faculdade; exame de admissão.",
    context: "Quando estudantes fazem provas para conseguir vaga em universidades.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O vestibular da USP é um dos mais difíceis do país.",
    contextNotes: "Um dos momentos mais importantes e estressantes da vida estudantil.",
    origin: "Sistema universitário brasileiro, inspirado no modelo francês.",
    variations: ["vesti", "processo seletivo", "admissão"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ENEM",
    meaning: "Exame Nacional do Ensino Médio; prova nacional usada para ingresso em faculdades.",
    adultTranslation: "Prova nacional padronizada; principal forma de entrar na universidade no Brasil.",
    context: "Quando estudantes se preparam e fazem a prova do ENEM.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Tô estudando pro ENEM desde janeiro, quero uma nota boa.",
    contextNotes: "Prova mais importante do sistema educacional brasileiro.",
    origin: "Criado em 1998, tornou-se principal forma de acesso ao ensino superior.",
    variations: ["enemzão", "prova nacional"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "redação",
    meaning: "Texto dissertativo-argumentativo exigido em vestibulares e ENEM.",
    adultTranslation: "Essay; texto que o aluno escreve como parte de provas importantes.",
    context: "Ao falar da parte de escrita de provas como ENEM e vestibulares.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Preciso praticar mais redação, minha nota tá baixa.",
    contextNotes: "A redação do ENEM vale muito na nota final e é o pesadelo de muitos.",
    origin: "Sistema educacional brasileiro.",
    variations: ["essay", "dissertação", "texto"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bullying escolar",
    meaning: "Prática de intimidar ou humilhar colegas na escola.",
    adultTranslation: "Assédio moral entre estudantes; humilhação sistemática de colegas.",
    context: "Quando um aluno é vítima de agressões verbais ou físicas na escola.",
    category: "bullying",
    riskLevel: "red",
    safeExample: "Ele sofria bullying escolar por causa do peso e mudou de escola.",
    contextNotes: "Problema grave com consequências duradouras na vida das vítimas.",
    origin: "Termo inglês adotado mundialmente para descrever assédio escolar.",
    variations: ["assédio escolar", "intimidação"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "passar de ano",
    meaning: "Ser aprovado para o ano escolar seguinte.",
    adultTranslation: "Conseguir aprovação escolar; avançar para a próxima série.",
    context: "Quando o aluno consegue notas e frequência suficientes para avançar.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Passei de ano com dificuldade em matemática, mas passei.",
    contextNotes: "Momento de alívio e celebração para estudantes.",
    origin: "Sistema educacional brasileiro.",
    variations: ["ser aprovado", "avançar", "subir de série"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "reprovar",
    meaning: "Não conseguir aprovação escolar; ter que repetir o ano.",
    adultTranslation: "Não passar de ano; ter que cursar a mesma série novamente.",
    context: "Quando o aluno não alcança notas ou frequência mínima para aprovação.",
    category: "escola",
    riskLevel: "yellow",
    safeExample: "Reprovei em matemática e vou ter que fazer recuperação.",
    contextNotes: "Momento difícil que pode afetar a autoestima do aluno.",
    origin: "Sistema educacional tradicional.",
    variations: ["rodar", "repetir", "ficar para trás"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "caderno",
    meaning: "Material escolar para escrever; objeto essencial de estudante.",
    adultTranslation: "Material de anotações; livro de caderno para escrever em aula.",
    context: "Ao falar de materiais escolares e anotações de aula.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Esqueci meu caderno em casa e não pude copiar a matéria.",
    contextNotes: "Item essencial de todo estudante.",
    origin: "Material escolar universal.",
    variations: ["caderno de anotações", "bloco"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "cantina",
    meaning: "Local na escola onde se vendem lanches e bebidas.",
    adultTranslation: "Lanchonete da escola; espaço onde se compra comida durante o intervalo.",
    context: "No intervalo, quando alunos vão comprar lanche.",
    category: "escola",
    riskLevel: "green",
    safeExample: "A cantina da escola vende coxinha e suco de caixinha.",
    contextNotes: "Ponto de socialização importante na escola.",
    origin: "Estrutura escolar tradicional brasileira.",
    variations: ["lanchonete", "barzinho da escola"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "quadro negro",
    meaning: "Superfície escura onde o professor escreve com giz; símbolo da escola.",
    adultTranslation: "Lousa; painel onde o professor escreve durante as aulas.",
    context: "Durante as aulas, quando o professor escreve no quadro.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O professor escreveu toda a matéria no quadro negro.",
    contextNotes: "Símbolo icônico do ambiente escolar, substituído em muitos lugares por quadro digital.",
    origin: "Sistema educacional tradicional, originário de séculos atrás.",
    variations: ["lousa", "quadro branco", "quadro digital"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "lousa digital",
    meaning: "Quadro eletrônico interativo usado em salas de aula modernas.",
    adultTranslation: "Painel touch screen para aulas; quadro eletrônico com recursos digitais.",
    context: "Em escolas modernas que adotam tecnologia nas salas de aula.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O professor usa a lousa digital para explicar geometria.",
    contextNotes: "Representa a modernização do ambiente educacional.",
    origin: "Tecnologia educacional dos anos 2000 em diante.",
    variations: ["smartboard", "quadro digital", "painel interativo"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "diário de classe",
    meaning: "Registro de frequência e notas dos alunos mantido pelo professor.",
    adultTranslation: "Livro de registros escolares; onde o professor anota frequência e notas.",
    context: "Quando o professor faz chamada ou registra notas.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O professor esqueceu o diário de classe e não pôde fazer chamada.",
    contextNotes: "Documento oficial do ambiente escolar.",
    origin: "Sistema educacional tradicional.",
    variations: ["diário", "chamada", "registro de classe"],
    popularityStatus: "em_queda",
    region: "Brasil",
  },
  {
    term: "uniforme",
    meaning: "Roupa padronizada que alunos são obrigados a usar na escola.",
    adultTranslation: "Roupa oficial da escola; vestimenta obrigatória para estudantes.",
    context: "Ao falar do código de vestimenta escolar.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O uniforme da minha escola é camisa branca e calça azul.",
    contextNotes: "Muitas escolas brasileiras exigem uniforme, mas há debate sobre isso.",
    origin: "Tradição escolar, popularizada por instituições religiosas e militares.",
    variations: ["fardamento", "roupa de escola", "jaleco"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "ENEM da vida",
    meaning: "Situação ou momento extremamente difícil e desafiador, comparado ao ENEM.",
    adultTranslation: "Provação; situação muito difícil de enfrentar na vida real.",
    context: "Quando alguém enfrenta uma situação tão difícil quanto o ENEM.",
    category: "ironia",
    riskLevel: "green",
    safeExample: "Essa entrevista de emprego foi o ENEM da minha vida.",
    contextNotes: "Metáfora humorística que compara dificuldades ao ENEM.",
    origin: "Internet brasileira, memes sobre o ENEM.",
    variations: ["prova de fogo", "momento difícil"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "feriadão",
    meaning: "Feriado que junto com finais de semana forma uma longa folga.",
    adultTranslation: "Fim de semana prolongado; feriado que cai na quinta ou segunda-feira.",
    context: "Quando há feriado e a galera aproveita para viajar ou descansar.",
    category: "escola",
    riskLevel: "green",
    safeExample: "O feriadão de Carnaval é o melhor, galera viaja tudo.",
    contextNotes: "Momento celebrado por estudantes e trabalhadores.",
    origin: "Gíria popular brasileira.",
    variations: ["férias longas", "final de semana estendido"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "aula de reforço",
    meaning: "Aula extra para alunos com dificuldade em determinada matéria.",
    adultTranslation: "Aula complementar para reforçar conteúdo; recuperação paralela.",
    context: "Quando o aluno precisa de ajuda extra em alguma disciplina.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Tenho aula de reforço de matemática às terças e quintas.",
    contextNotes: "Pode ser constrangedor para alguns alunos, mas é importante.",
    origin: "Sistema educacional complementar.",
    variations: ["reforço escolar", "aula extra", "monitoria"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "monitoria",
    meaning: "Programa onde alunos mais adiantados ajudam colegas com dificuldades.",
    adultTranslation: "Aluno auxiliar que ajuda o professor e colegas; tutoria entre alunos.",
    context: "Quando alunos avançados dão suporte a colegas em disciplinas difíceis.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Sou monitor de física, ajudo os calouros com as provas.",
    contextNotes: "Ótima oportunidade de aprendizado e fixedo na universidade.",
    origin: "Universidades brasileiras, programa de monitoria acadêmica.",
    variations: ["tutoria", "ajuda entre colegas", "monitor"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "TCC",
    meaning: "Trabalho de Conclusão de Curso; projeto final exigido para graduação.",
    adultTranslation: "Trabalho final da faculdade; projeto de conclusão do curso superior.",
    context: "Quando estudantes universitários precisam apresentar trabalho final para se formar.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Preciso começar meu TCC senão não formo no semestre que vem.",
    contextNotes: "Uma das maiores fontes de estresse na vida universitária.",
    origin: "Sistema universitário brasileiro.",
    variations: ["trabalho de conclusão", "monografia", "projeto final"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "bolsa de estudo",
    meaning: "Desconto ou isenção total nas mensalidades de uma escola ou faculdade.",
    adultTranslation: "Auxílio financeiro para estudar; benefício que cobre parte ou toda a mensalidade.",
    context: "Quando alunos de baixa renda recebem ajuda para estudar.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Consegui uma bolsa de estudo de 100% na faculdade privada.",
    contextNotes: "Programas como Prouni e FIES são essenciais para acesso ao ensino superior.",
    origin: "Políticas de inclusão educacional brasileiras.",
    variations: ["bolsa", "Prouni", "isenção"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "plantão de dúvidas",
    meaning: "Horário extra em que o professor atende alunos para tirar dúvidas.",
    adultTranslation: "Horário de atendimento para dúvidas; momento de falar com o professor individualmente.",
    context: "Quando o professor disponibiliza um horário para atender alunos individualmente.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Fui no plantão de dúvidas e finally entendi frações.",
    contextNotes: "Ótima oportunidade para alunos que têm dificuldades.",
    origin: "Sistema educacional brasileiro, comum em faculdades.",
    variations: ["plantão", "horário de dúvidas", "tira-dúvidas"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "fazer de conta",
    meaning: "Fingir que estuda ou faz o trabalho sem realmente se dedicar.",
    adultTranslation: "Simular estar estudando; fazer trabalho por fazer sem aprender.",
    context: "Quando o aluno faz trabalho sem se dedicar de verdade.",
    category: "zoeira",
    riskLevel: "green",
    safeExample: "Ele só faz de conta que estuda, na hora da prova não sabe nada.",
    contextNotes: "Comum entre alunos que procrastinam.",
    origin: "Expressão popular brasileira.",
    variations: ["simular", "fingir", "maquiar"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "xerox",
    meaning: "Cópia de material didático; reprografia feita em papelaria perto da escola.",
    adultTranslation: "Cópia xerox de material de estudo; apostila reproduzida.",
    context: "Quando alunos vão à papelaria copiar exercícios ou resumos.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Peguei o xerox da apostila de biologia na papelaria.",
    contextNotes: "Parte essencial da rotina de estudantes brasileiros.",
    origin: "Marca registrada Xerox, tornou-se sinônimo de cópia.",
    variations: ["cópia", "reprografia", "apostila"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "chamada",
    meaning: "Verificação de presença feita pelo professor no início da aula.",
    adultTranslation: "Lista de presença; momento em que o professor verifica quem está na aula.",
    context: "No início da aula, quando o professor chama os nomes dos alunos.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Cheguei atrasado e já tinham feito a chamada.",
    contextNotes: "Momento crucial para manter a frequência escolar.",
    origin: "Sistema educacional tradicional.",
    variations: ["lista de presença", "frequência", "chamada nominal"],
    popularityStatus: "ativo",
    region: "Brasil",
  },
  {
    term: "maratonar estudo",
    meaning: "Estudar por muitas horas seguidas sem parar, geralmente antes de provas.",
    adultTranslation: "Estudar intensamente por horas; sessão longa de estudo antes de prova.",
    context: "Antes de provas grandes como ENEM ou vestibulares.",
    category: "escola",
    riskLevel: "green",
    safeExample: "Vou maratonar estudo esse fim de semana para o ENEM.",
    contextNotes: "Prática comum mas que pode causar cansaço mental se não houver pausas.",
    origin: "Cultura estudantil brasileira associada a séries e filmes.",
    variations: ["maratona de estudo", "studar muito", "se afundar nos livros"],
    popularityStatus: "ativo",
    region: "Brasil",
  }
];
