import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_20: SlangTerm[] = [
  {
    term: 'foi de arrasta',
    meaning: 'Algo acabou, deu errado, foi cancelado ou “morreu” no sentido figurado.',
    adultTranslation: 'Acabou / Deu errado / Foi cancelado.',
    context: 'Usado em memes quando um plano falha, uma conta cai, um personagem perde ou alguém desiste.',
    category: 'meme',
    riskLevel: 'yellow',
    safeExample: 'O passeio foi de arrasta por causa da chuva.',
    contextNotes: 'Na maioria das vezes é meme, mas vale atenção se aparecer associado a violência real, automutilação ou ameaça.',
    origin: 'Memes brasileiros derivados de expressões sobre fim ou derrota em vídeos curtos.',
    variations: ['foi de base', 'foi de comes', 'foi de ralo'],
    popularityStatus: 'trending',
    region: 'Brasil',
  },
  {
    term: 'jantou',
    meaning: 'Respondeu muito bem, venceu uma discussão ou deixou alguém sem reação.',
    adultTranslation: 'Argumentou muito bem / Respondeu de forma certeira.',
    context: 'Comum em comentários quando alguém dá uma resposta inteligente, irônica ou muito direta.',
    category: 'ironia',
    riskLevel: 'yellow',
    safeExample: 'Ela explicou com calma e jantou no debate.',
    contextNotes: 'Pode ser elogio, mas também pode incentivar humilhação pública dependendo do tom da conversa.',
    origin: 'Linguagem de memes e comentários, com sentido de “devorar” retoricamente uma situação.',
    variations: ['jantou cedo', 'jantou demais', 'almoçou e jantou'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'passou a visão',
    meaning: 'Explicou, avisou ou deu uma orientação importante.',
    adultTranslation: 'Explicou / Orientou / Deu o aviso.',
    context: 'Usado quando alguém compartilha uma dica, alerta, conselho ou informação útil.',
    category: 'expressão',
    riskLevel: 'green',
    safeExample: 'Meu primo passou a visão sobre a prova.',
    contextNotes: 'Geralmente positivo e ligado a ajuda entre amigos.',
    origin: 'Expressão urbana brasileira associada a conselho e troca de informação.',
    variations: ['passar a visão', 'visão passada', 'deu a visão'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'sem neurose',
    meaning: 'Sem preocupação, sem estresse ou sem exagerar no problema.',
    adultTranslation: 'Fique tranquilo / Sem preocupação.',
    context: 'Usado para acalmar alguém ou dizer que uma situação não precisa virar conflito.',
    category: 'saudacao',
    riskLevel: 'green',
    safeExample: 'Sem neurose, eu levo o material amanhã.',
    contextNotes: 'Apesar da palavra “neurose”, normalmente é uma expressão informal de tranquilização.',
    origin: 'Gíria urbana difundida em conversas informais e músicas brasileiras.',
    variations: ['sem neura', 'zero neurose', 'sem neurose nenhuma'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'meter o shape',
    meaning: 'Focar em academia, cuidar do corpo ou entrar em uma fase fitness.',
    adultTranslation: 'Começar a treinar / Melhorar o físico.',
    context: 'Aparece em memes de disciplina, autoestima, treino e mudança de visual.',
    category: 'lifestyle',
    riskLevel: 'yellow',
    safeExample: 'Nas férias ele quer meter o shape com orientação.',
    contextNotes: 'Pode ser motivacional, mas vale observar cobrança corporal excessiva, comparação ou dietas sem orientação.',
    origin: 'Cultura fitness, memes de transformação corporal e redes sociais.',
    variations: ['shape', 'botar o shape', 'projeto shape'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'no sapatinho',
    meaning: 'Fazer algo discretamente, sem chamar atenção ou sem alarde.',
    adultTranslation: 'De forma discreta / Sem fazer barulho.',
    context: 'Pode ser usado para estudar, conquistar algo, resolver um problema ou sair sem chamar atenção.',
    category: 'expressão',
    riskLevel: 'green',
    safeExample: 'Ela estudou no sapatinho e passou.',
    contextNotes: 'Termo geralmente neutro; atenção só se o contexto envolver esconder algo arriscado.',
    origin: 'Expressão popular brasileira associada à ideia de agir com discrição.',
    variations: ['sapatinho', 'quietinho', 'na miúda'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
];
