import type { SlangTerm } from './slang-data';

export const EXTRA_SLANG_DATA_20: SlangTerm[] = [
  {
    term: 'six seven',
    meaning: 'Expressão-meme propositalmente sem significado fixo, repetida como piada interna, reação absurda ou referência cultural entre adolescentes.',
    adultTranslation: 'É uma piada interna sem tradução literal; o humor está justamente em dizer algo que não precisa fazer sentido.',
    context: 'Pode aparecer como “six seven”, “6 7”, “6-7” ou “67”, muitas vezes com gesto de mãos, em vídeos, escola, esportes e conversas de grupo.',
    category: 'meme',
    riskLevel: 'green',
    safeExample: 'O professor falou sessenta e sete e a sala inteira respondeu: six seven.',
    contextNotes: 'Não trate como código secreto por padrão. Em geral é humor nonsense e pertencimento ao grupo. Pergunte onde a pessoa viu a expressão antes de atribuir outro sentido.',
    origin: 'Meme viral associado à música “Doot Doot (6 7)”, a vídeos de basquete e à cultura Gen Alpha em 2025–2026.',
    variations: ['67', '6 7', '6-7', 'six-seven', 'seis sete'],
    popularityStatus: 'trending',
    region: 'Internacional / internet',
  },
  {
    term: '41',
    meaning: 'Número usado como meme nonsense e resposta absurda, na mesma lógica de outras piadas numéricas da Gen Alpha.',
    adultTranslation: 'Piada interna aleatória; normalmente não possui significado literal estável.',
    context: 'Aparece em comentários, vídeos curtos e brincadeiras escolares como resposta inesperada.',
    category: 'meme',
    riskLevel: 'green',
    safeExample: 'Perguntaram a resposta e ele soltou 41 só pela piada.',
    contextNotes: 'O principal valor é social: reconhecer quem acompanha a tendência. Não é automaticamente sinal de conteúdo impróprio.',
    origin: 'Cultura de memes numéricos Gen Alpha difundida em TikTok, Reels e ambientes escolares.',
    variations: ['forty one', 'quarenta e um'],
    popularityStatus: 'trending',
    region: 'Internacional / internet',
  },
  {
    term: 'aura farming',
    meaning: 'Agir de propósito para parecer muito confiante, estiloso, misterioso ou impressionante, geralmente fingindo naturalidade.',
    adultTranslation: 'Construir uma imagem de pessoa muito legal ou marcante.',
    context: 'Usado para elogiar uma presença forte ou ironizar alguém que está claramente tentando parecer descolado.',
    category: 'meme',
    riskLevel: 'green',
    safeExample: 'Ele entrou sem olhar para ninguém e começou o aura farming.',
    contextNotes: 'Pode ser elogio ou provocação leve. O tom e a relação entre as pessoas definem a intenção.',
    origin: 'Junção do sentido de “aura” como presença marcante com “farming” dos games, popularizada por anime, esportes e vídeos curtos.',
    variations: ['farmar aura', 'farmando aura', 'aura farmer', 'ganhar aura'],
    popularityStatus: 'trending',
    region: 'Internacional / Brasil',
  },
  {
    term: 'cooked',
    meaning: 'Estar sem saída, derrotado, muito cansado ou prestes a sofrer uma consequência ruim.',
    adultTranslation: 'Estou ferrado / não tem mais jeito / estou acabado.',
    context: 'Pode ser usado depois de uma prova difícil, erro, derrota em jogo ou situação embaraçosa.',
    category: 'meme',
    riskLevel: 'yellow',
    safeExample: 'Não estudei para a prova de amanhã, estou cooked.',
    contextNotes: 'Quase sempre é exagero cômico. Vale investigar apenas quando vier acompanhado de ameaça, desespero real ou risco concreto.',
    origin: 'Gíria inglesa de internet e gaming incorporada por jovens brasileiros.',
    variations: ['i am cooked', "i'm cooked", 'tô cooked', 'we are cooked'],
    popularityStatus: 'trending',
    region: 'Internacional / Brasil',
  },
  {
    term: 'crash out',
    meaning: 'Perder o controle emocional, explodir, agir impulsivamente ou arriscar tudo por raiva.',
    adultTranslation: 'Surtar / perder a cabeça / agir sem pensar.',
    context: 'Usado tanto como meme quanto para descrever uma reação agressiva ou impulsiva de verdade.',
    category: 'alerta_emocional',
    riskLevel: 'orange',
    safeExample: 'Respira antes de responder para não dar crash out no grupo.',
    contextNotes: 'Peça contexto. Se houver ameaça, violência, perseguição ou intenção de se machucar, trate como alerta real e não apenas como meme.',
    origin: 'Inglês afro-americano e cultura rap, difundido globalmente por TikTok e memes.',
    variations: ['crashing out', 'crashou', 'dar crash out'],
    popularityStatus: 'trending',
    region: 'Internacional / internet',
  },
  {
    term: 'locked in',
    meaning: 'Estar totalmente focado, comprometido e concentrado em uma tarefa ou objetivo.',
    adultTranslation: 'Estou concentrado / entrei em modo de foco.',
    context: 'Comum em estudos, academia, esportes, jogos e projetos pessoais.',
    category: 'lifestyle',
    riskLevel: 'green',
    safeExample: 'Essa semana estou locked in para terminar o trabalho.',
    contextNotes: 'Normalmente positivo. Pode indicar disciplina ou concentração intensa.',
    origin: 'Expressão inglesa popularizada em esportes, gaming e conteúdo de produtividade.',
    variations: ['lock in', 'tô locked', 'modo locked in'],
    popularityStatus: 'trending',
    region: 'Internacional / Brasil',
  },
  {
    term: 'unc',
    meaning: 'Forma abreviada de “uncle”, usada para chamar alguém de velho, ultrapassado ou mais velho que o grupo, geralmente em tom de brincadeira.',
    adultTranslation: 'Tiozão / você está ficando velho para isso.',
    context: 'Pode ser brincadeira carinhosa ou provocação sobre idade, aparência ou hábitos.',
    category: 'provocacao',
    riskLevel: 'yellow',
    safeExample: 'Você dormiu antes das dez? Virou unc.',
    contextNotes: 'Observe se é zoeira recíproca ou humilhação repetida. Pode incomodar quando usado para excluir alguém.',
    origin: 'Abreviação de “uncle”, difundida em comunidades online, esportes e memes.',
    variations: ['unc status', 'big unc', 'tio'],
    popularityStatus: 'trending',
    region: 'Internacional / internet',
  },
  {
    term: 'glazing',
    meaning: 'Elogiar ou defender alguém de forma exagerada, insistente ou pouco crítica.',
    adultTranslation: 'Puxar o saco / idolatrar demais.',
    context: 'Usado para acusar alguém de exagerar nos elogios a artista, jogador, influenciador ou amigo.',
    category: 'provocacao',
    riskLevel: 'yellow',
    safeExample: 'Você pode gostar do jogador sem fazer glazing o tempo inteiro.',
    contextNotes: 'Geralmente é provocação. Pode escalar para bullying se usado para constranger a pessoa repetidamente.',
    origin: 'Gíria de internet em inglês popularizada em comunidades esportivas e de streaming.',
    variations: ['glaze', 'glazer', 'glazeando'],
    popularityStatus: 'trending',
    region: 'Internacional / Brasil',
  },
  {
    term: 'delulu',
    meaning: 'Pessoa ou ideia excessivamente fantasiosa, otimista ou desconectada da realidade; abreviação brincalhona de “delusional”.',
    adultTranslation: 'Iludido / vivendo numa fantasia.',
    context: 'Usado em fandoms, relacionamentos, metas e situações em que alguém acredita muito em algo improvável.',
    category: 'meme',
    riskLevel: 'yellow',
    safeExample: 'Achar que ele vai responder hoje é meu momento delulu.',
    contextNotes: 'Normalmente é autoironia. Evite interpretar como diagnóstico de saúde mental.',
    origin: 'Fandoms de K-pop e redes sociais, depois difundido globalmente.',
    variations: ['delusional', 'delulu is the solulu', 'momento delulu'],
    popularityStatus: 'ativo',
    region: 'Internacional / Brasil',
  },
  {
    term: 'brainrot',
    meaning: 'Conteúdo repetitivo, absurdo ou viciante que domina a atenção e passa a ocupar o vocabulário e os pensamentos.',
    adultTranslation: 'Conteúdo bobo e viciante que fica preso na cabeça.',
    context: 'Pode nomear um tipo de meme ou a sensação de estar consumindo demais um assunto, fandom ou formato de vídeo.',
    category: 'meme',
    riskLevel: 'yellow',
    safeExample: 'Meu brainrot da semana é esse áudio do TikTok.',
    contextNotes: 'Geralmente é autoironia, não uma condição médica. Observe tempo de tela, sono e impacto real antes de concluir que há problema.',
    origin: 'Gíria antiga de internet que ganhou novo impulso com memes Gen Alpha e vídeos curtos.',
    variations: ['brain rot', 'brain-rotted', 'cérebro derretido'],
    popularityStatus: 'trending',
    region: 'Internacional / Brasil',
  },
  {
    term: 'mogged',
    meaning: 'Ser superado visualmente, fisicamente ou em presença por outra pessoa.',
    adultTranslation: 'Foi ofuscado / ficou em desvantagem na comparação.',
    context: 'Comum em memes de aparência, academia, moda e comparação social.',
    category: 'provocacao',
    riskLevel: 'orange',
    safeExample: 'No meme, ele disse que foi mogged pelo amigo mais alto.',
    contextNotes: 'Pode reforçar comparação corporal, humilhação e padrões irreais. Se estiver direcionado a uma pessoa, observe sinais de bullying.',
    origin: 'Fóruns de aparência e cultura fitness, posteriormente difundido em memes mainstream.',
    variations: ['mog', 'mogging', 'moggar', 'foi mogado'],
    popularityStatus: 'trending',
    region: 'Internacional / internet',
  },
  {
    term: 'rage bait',
    meaning: 'Conteúdo feito de propósito para provocar raiva, indignação e comentários, aumentando o alcance.',
    adultTranslation: 'Isca de indignação / provocação calculada para gerar engajamento.',
    context: 'Usado para identificar vídeos, opiniões ou manchetes deliberadamente irritantes.',
    category: 'redes_sociais',
    riskLevel: 'yellow',
    safeExample: 'Não responde; esse vídeo é rage bait para ganhar comentário.',
    contextNotes: 'Reconhecer o formato ajuda a evitar conflito e compartilhamento impulsivo.',
    origin: 'Cultura de redes sociais e economia de atenção.',
    variations: ['ragebait', 'bait de raiva', 'isca de ódio'],
    popularityStatus: 'trending',
    region: 'Internacional / Brasil',
  },
  {
    term: 'foi de arrasta',
    meaning: 'Algo acabou, deu errado, foi cancelado ou “morreu” no sentido figurado.',
    adultTranslation: 'Acabou / Deu errado / Foi cancelado.',
    context: 'Usado em memes quando um plano falha, uma conta cai, um personagem perde ou alguém desiste.',
    category: 'meme',
    riskLevel: 'yellow',
    safeExample: 'O passeio foi de arrasta por causa da chuva.',
    contextNotes: 'Na maioria das vezes é meme, mas vale atenção se aparecer associado a violência real, automutilação ou ameaça.',
    origin: 'Memes brasileiros derivados de expressões sobre fim ou derrota em vídeos curtos.',
    variations: ['foi de base', 'foi de comes', 'foi de ralo'],
    popularityStatus: 'trending',
    region: 'Brasil',
  },
  {
    term: 'jantou',
    meaning: 'Respondeu muito bem, venceu uma discussão ou deixou alguém sem reação.',
    adultTranslation: 'Argumentou muito bem / Respondeu de forma certeira.',
    context: 'Comum em comentários quando alguém dá uma resposta inteligente, irônica ou muito direta.',
    category: 'ironia',
    riskLevel: 'yellow',
    safeExample: 'Ela explicou com calma e jantou no debate.',
    contextNotes: 'Pode ser elogio, mas também pode incentivar humilhação pública dependendo do tom da conversa.',
    origin: 'Linguagem de memes e comentários, com sentido de “devorar” retoricamente uma situação.',
    variations: ['jantou cedo', 'jantou demais', 'almoçou e jantou'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'passou a visão',
    meaning: 'Explicou, avisou ou deu uma orientação importante.',
    adultTranslation: 'Explicou / Orientou / Deu o aviso.',
    context: 'Usado quando alguém compartilha uma dica, alerta, conselho ou informação útil.',
    category: 'expressão',
    riskLevel: 'green',
    safeExample: 'Meu primo passou a visão sobre a prova.',
    contextNotes: 'Geralmente positivo e ligado a ajuda entre amigos.',
    origin: 'Expressão urbana brasileira associada a conselho e troca de informação.',
    variations: ['passar a visão', 'visão passada', 'deu a visão'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'sem neurose',
    meaning: 'Sem preocupação, sem estresse ou sem exagerar no problema.',
    adultTranslation: 'Fique tranquilo / Sem preocupação.',
    context: 'Usado para acalmar alguém ou dizer que uma situação não precisa virar conflito.',
    category: 'saudacao',
    riskLevel: 'green',
    safeExample: 'Sem neurose, eu levo o material amanhã.',
    contextNotes: 'Apesar da palavra “neurose”, normalmente é uma expressão informal de tranquilização.',
    origin: 'Gíria urbana difundida em conversas informais e músicas brasileiras.',
    variations: ['sem neura', 'zero neurose', 'sem neurose nenhuma'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'meter o shape',
    meaning: 'Focar em academia, cuidar do corpo ou entrar em uma fase fitness.',
    adultTranslation: 'Começar a treinar / Melhorar o físico.',
    context: 'Aparece em memes de disciplina, autoestima, treino e mudança de visual.',
    category: 'lifestyle',
    riskLevel: 'yellow',
    safeExample: 'Nas férias ele quer meter o shape com orientação.',
    contextNotes: 'Pode ser motivacional, mas vale observar cobrança corporal excessiva, comparação ou dietas sem orientação.',
    origin: 'Cultura fitness, memes de transformação corporal e redes sociais.',
    variations: ['shape', 'botar o shape', 'projeto shape'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
  {
    term: 'no sapatinho',
    meaning: 'Fazer algo discretamente, sem chamar atenção ou sem alarde.',
    adultTranslation: 'De forma discreta / Sem fazer barulho.',
    context: 'Pode ser usado para estudar, conquistar algo, resolver um problema ou sair sem chamar atenção.',
    category: 'expressão',
    riskLevel: 'green',
    safeExample: 'Ela estudou no sapatinho e passou.',
    contextNotes: 'Termo geralmente neutro; atenção só se o contexto envolver esconder algo arriscado.',
    origin: 'Expressão popular brasileira associada à ideia de agir com discrição.',
    variations: ['sapatinho', 'quietinho', 'na miúda'],
    popularityStatus: 'ativo',
    region: 'Brasil',
  },
];
