"use client";

import { FormEvent, useRef, useState } from "react";
import { ArrowRight, CheckCircle2, Copy, Loader2, Search, Sparkles, ThumbsDown, ThumbsUp } from "lucide-react";

type Translation = { term?: string; meaning?: string; adultTranslation?: string; contextualMeaning?: string; context?: string; safeExample?: string; origin?: string; matchType?: "exact"|"contextual"|"approximate"|"fallback"; intelligence?: { confidence:"alta"|"media"|"baixa"; confidenceScore:number; tone:"positivo"|"neutro"|"ironico"|"provocativo"|"sensivel"; intent:string; platform?:string|null; ambiguity:boolean; clarificationQuestion?:string|null; }; };
const popularTerms=["six seven","farmar aura","brainrot","delulu","cooked"];

export default function EliteHomeLanding(){
 const [query,setQuery]=useState("");const [translation,setTranslation]=useState<Translation|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);const [copied,setCopied]=useState(false);const [feedback,setFeedback]=useState<"correct"|"incorrect"|null>(null);const resultRef=useRef<HTMLDivElement>(null);
 async function translate(event?:FormEvent,preset?:string){event?.preventDefault();const value=(preset??query).trim();if(!value||loading)return;setQuery(value);setLoading(true);setError(null);setTranslation(null);setFeedback(null);try{const response=await fetch("/api/translate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slang:value})});const data=(await response.json()) as Translation&{error?:string};if(!response.ok)throw new Error(data.error||"Não foi possível explicar agora.");setTranslation(data);requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"}));}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível explicar agora.");}finally{setLoading(false);}}
 async function copyResult(){if(!translation)return;await navigator.clipboard.writeText([translation.term,translation.contextualMeaning||translation.adultTranslation||translation.meaning,translation.context].filter(Boolean).join("\n\n"));setCopied(true);setTimeout(()=>setCopied(false),1800);}
 async function sendFeedback(verdict:"correct"|"incorrect"){if(!translation||feedback)return;setFeedback(verdict);try{await fetch("/api/feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({verdict,term:translation.term,query,matchType:translation.matchType,confidence:translation.intelligence?.confidence}),keepalive:true});}catch{setFeedback(null);}}
 const intelligence=translation?.intelligence;
 return <main className="min-h-screen bg-[#fbfbfa] text-[#111] dark:bg-slate-950 dark:text-white"><div className="mx-auto flex min-h-screen max-w-6xl flex-col px-5 pt-6 sm:px-8 lg:px-10">
  <header className="flex items-center gap-2.5 text-sm font-black tracking-tight"><span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-white dark:bg-white dark:text-slate-950"><Sparkles className="h-4 w-4"/></span><span>Gíria AI</span></header>
  <section className="mx-auto flex w-full max-w-3xl flex-1 flex-col justify-center py-14 text-center sm:py-20">
   <h1 className="mx-auto max-w-3xl text-balance text-[2.85rem] font-semibold leading-[0.98] tracking-[-0.055em] sm:text-6xl lg:text-[4.7rem]">Entenda qualquer gíria.</h1>
   <p className="mx-auto mt-5 max-w-xl text-base leading-7 text-black/55 dark:text-white/55 sm:text-lg">Cole a palavra, frase ou meme. A gente explica o que significa e o que a pessoa quis dizer.</p>
   <form onSubmit={(event)=>void translate(event)} className="mt-8 rounded-[1.5rem] border border-black/10 bg-white p-2 shadow-[0_20px_70px_rgba(15,23,42,0.10)] dark:border-white/10 dark:bg-slate-900"><div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-black/30 dark:text-white/35"/><span className="sr-only">Cole uma gíria, frase ou meme</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cole aqui o que você não entendeu" enterKeyHint="search" autoComplete="off" autoFocus className="h-16 w-full rounded-2xl border-0 bg-[#f5f6f4] pl-12 pr-4 text-base outline-none placeholder:text-black/35 focus:bg-white focus:ring-2 focus:ring-emerald-400 dark:bg-slate-950 dark:placeholder:text-white/35"/></label><button type="submit" disabled={loading||!query.trim()} className="inline-flex h-16 min-w-36 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-7 font-semibold text-white transition hover:bg-emerald-600 disabled:opacity-40 dark:bg-white dark:text-slate-950">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<ArrowRight className="h-4 w-4"/>}Explicar</button></div></form>
   <div className="mt-4 flex gap-2 overflow-x-auto pb-2 text-sm sm:flex-wrap sm:justify-center sm:overflow-visible"><span className="self-center whitespace-nowrap text-xs text-black/35 dark:text-white/35">Tente:</span>{popularTerms.map((term)=><button key={term} type="button" onClick={()=>void translate(undefined,term)} className="min-h-10 shrink-0 rounded-full border border-black/10 px-3.5 py-1.5 font-medium text-black/55 transition hover:border-emerald-300 hover:text-emerald-700 dark:border-white/10 dark:text-white/60">{term}</button>)}</div>
   <div ref={resultRef} aria-live="polite" className="text-left">{error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-semibold text-red-700">{error}</div>}{translation&&!loading&&<article className="mt-8 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-4 border-b border-slate-100 px-5 py-5 dark:border-slate-800 sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-600">{translation.matchType==="approximate"?"Pode ser isso":translation.matchType==="contextual"?"Nesse contexto":"Significa"}</p><h2 className="mt-1 text-3xl font-black">“{translation.term||query}”</h2></div><button type="button" onClick={()=>void copyResult()} className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 dark:border-slate-700" aria-label="Copiar resposta">{copied?<CheckCircle2 className="h-4 w-4 text-emerald-500"/>:<Copy className="h-4 w-4"/>}</button></div><div className="p-5 sm:p-8"><div className="rounded-3xl bg-emerald-50 p-5 dark:bg-emerald-950/30"><p className="text-lg font-bold leading-8">{translation.contextualMeaning||translation.adultTranslation||translation.meaning}</p></div>{intelligence?.clarificationQuestion?<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold leading-6 text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100">{intelligence.clarificationQuestion}</div>:null}<div className="mt-5 grid gap-3 sm:grid-cols-2"><ResultCard label="Em outras palavras" value={translation.meaning}/><ResultCard label="O que quiseram dizer" value={intelligence?.intent}/><ResultCard label="Exemplo" value={translation.safeExample}/><ResultCard label="Origem" value={translation.origin}/></div><div className="mt-5 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-5 text-sm dark:border-slate-800"><span className="mr-1 text-slate-500 dark:text-slate-400">Fez sentido?</span><button type="button" onClick={()=>void sendFeedback("correct")} disabled={Boolean(feedback)} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-slate-200 px-3.5 font-semibold hover:border-emerald-400 hover:text-emerald-700 disabled:opacity-60 dark:border-slate-700"><ThumbsUp className="h-4 w-4"/>Sim</button><button type="button" onClick={()=>void sendFeedback("incorrect")} disabled={Boolean(feedback)} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-slate-200 px-3.5 font-semibold hover:border-amber-400 hover:text-amber-700 disabled:opacity-60 dark:border-slate-700"><ThumbsDown className="h-4 w-4"/>Não</button>{feedback?<span className="ml-1 text-slate-500">Valeu.</span>:null}</div></div></article>}</div>
  </section>
  <footer className="border-t border-black/8 py-5 text-center text-[11px] leading-5 text-black/40 dark:border-white/10 dark:text-white/40"><span className="font-semibold text-black/60 dark:text-white/60">AIX8C</span> · Um site do grupo <a href="https://volponi.tech" target="_blank" rel="noopener noreferrer" className="font-semibold hover:text-emerald-700">volponi.tech</a> · <a href="https://www.instagram.com/lorenzavolponi" target="_blank" rel="noopener noreferrer" className="font-semibold hover:text-emerald-700">@lorenzavolponi</a> · #01 em tecnologia no Brasil</footer>
 </div></main>;
}
function ResultCard({label,value}:{label:string;value?:string}){if(!value)return null;return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950"><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-2 text-sm leading-6 text-slate-700 dark:text-slate-200">{value}</p></div>;}
